import "server-only";
import {randomUUID} from "node:crypto";
import type {SupabaseClient} from "@supabase/supabase-js";
import {GoogleCalendarLive} from "./google-calendar-live";
import {GoogleCalendarApiProvider} from "../provider/google-calendar-live.provider";
import {SupabaseGoogleCalendarSyncRepository} from "../repository/google-calendar-sync.repository";
import {loadGoogleWorkspaceAccessToken,loadGoogleWorkspaceConnection} from "@/features/connectors/google-workspace/application/google-workspace.repository";
import type {CalendarOperationalEventInput,CalendarOperationalEventType,GoogleCalendarSyncOperation} from "../types/google-calendar-live.types";
import {chileDateTime,resolveEventOperationalWindow} from "@/features/operations/event-operational-window";

type ProjectRecord={id:string;name:string;status:string;orbit_event_id:string;project_type:string;event_date:string;event_time:string;location:string|null;city:string|null;updated_at:string;operations:Record<string,unknown>|null;customers:unknown;project_services:Array<{service_code:string;duration_hours:number|null;extras:unknown}>;quotations:Array<{status:string}>;agreements:Array<{status:string}>;assignments:Array<{assignment_type:string;status:string;staff_call_at:string|null;staff:{first_name:string;last_name:string}|null}>};
type CalendarResult={operation:"CREATED"|"UPDATED"|"UNCHANGED"|"CANCELLED"|"RESTORED";googleEventId?:string};
const relation=<T>(value:unknown):T|undefined=>Array.isArray(value)?value[0] as T|undefined:value as T|undefined;
const line=(notes:string,label:string)=>notes.split("\n").find(value=>value.trim().startsWith(label))?.slice(label.length).trim();
const plusDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};

export async function synchronizeConfirmedReservationCalendar(input:{client:SupabaseClient;projectId:string;actorId:string;operation?:GoogleCalendarSyncOperation;requireCommercialReadiness?:boolean;onlyExisting?:boolean}):Promise<CalendarResult|null>{
  const[{data,error},{data:vehicle,error:vehicleError},{data:operational,error:operationalError}]=await Promise.all([
    input.client.from("projects").select("id,name,status,orbit_event_id,project_type,event_date,event_time,location,city,updated_at,operations,customers!inner(full_name,phone,email,metadata),project_services(service_code,duration_hours,extras),quotations(status),agreements(status),assignments(staff_id,assignment_type,status,staff_call_at,staff(first_name,last_name))").eq("id",input.projectId).single(),
    input.client.from("event_vehicle_assignments").select("status,operational_assets(asset_code,metadata,vehicle_profiles(model))").eq("project_id",input.projectId).eq("status","ASSIGNED").is("deleted_at",null).limit(1).maybeSingle(),
    input.client.from("project_operational_contracts").select("contact_status,contact_first_name,contact_last_name,contact_phone,contact_email,service_start_at,service_end_at,staff_arrival_at,assembly_start_at,disassembly_start_at,operational_end_at,access_instructions,operational_notes").eq("project_id",input.projectId).maybeSingle(),
  ]);
  if(error)throw error;if(vehicleError)throw vehicleError;if(operationalError)throw operationalError;const project=data as unknown as ProjectRecord;
  if(input.requireCommercialReadiness&&(!project.quotations.some(item=>item.status==="ACCEPTED")||!project.agreements.some(item=>item.status==="SIGNED")))throw new Error("La cotización aprobada y el acuerdo firmado son necesarios para sincronizar el evento.");
  const customer=relation<{full_name:string;phone:string|null;email:string|null;metadata:unknown}>(project.customers);if(!customer)throw new Error("La reserva no tiene un cliente asociado.");
  const notes=typeof project.operations?.notes==="string"?project.operations.notes:"";const duration=Math.max(1,...project.project_services.map(service=>Number(service.duration_hours??0)));const legacyStart=String(project.event_time??"18:00").slice(0,5);const[legacyStartHour,legacyStartMinute]=legacyStart.split(":").map(Number);const totalMinutes=legacyStartHour*60+legacyStartMinute+Math.round(duration*60);const legacyEnd=`${String(Math.floor(totalMinutes/60)%24).padStart(2,"0")}:${String(totalMinutes%60).padStart(2,"0")}`;const legacyEndDate=plusDays(project.event_date,Math.floor(totalMinutes/1440));const serviceStart=operational?.service_start_at?chileDateTime(operational.service_start_at):{date:project.event_date,time:legacyStart};const serviceEnd=operational?.service_end_at?chileDateTime(operational.service_end_at):{date:legacyEndDate,time:legacyEnd};
  const eventType:CalendarOperationalEventType=/WEDDING|MATRIMONIO/i.test(project.project_type)?"WEDDING":/CORPORATE|EMPRESA/i.test(project.project_type)?"CORPORATE":/BIRTHDAY|CUMPLE/i.test(project.project_type)?"BIRTHDAY":/GRAD/i.test(project.project_type)?"GRADUATION":"INTERNAL";
  const activeAssignments=project.assignments.filter(item=>!["REJECTED","CANCELLED"].includes(item.status));const staff=activeAssignments.map(item=>{const member=relation<{first_name:string;last_name:string}>(item.staff);return member?`${member.first_name} ${member.last_name} (${item.assignment_type})`:""}).filter(Boolean);const operatorAssignment=activeAssignments.find(item=>item.assignment_type==="OPERATOR"),operator=operatorAssignment?.staff;const operatorRecord=relation<{first_name:string;last_name:string}>(operator);const window=resolveEventOperationalWindow({assignmentStaffCalls:activeAssignments.map(item=>item.staff_call_at),staffArrivalAt:operational?.staff_arrival_at,serviceStartAt:operational?.service_start_at??`${serviceStart.date}T${serviceStart.time}:00-04:00`,serviceEndAt:operational?.service_end_at??`${serviceEnd.date}T${serviceEnd.time}:00-04:00`});const calendarStart=chileDateTime(window.operationalStartAt);
  const asset=relation<{asset_code?:string;metadata?:unknown;vehicle_profiles?:unknown}>(vehicle?.operational_assets);const profile=relation<{model?:string}>(asset?.vehicle_profiles);const assetMetadata=asset?.metadata&&typeof asset.metadata==="object"?asset.metadata as Record<string,unknown>:{};const vehicleName=profile?.model??String(assetMetadata.name??asset?.asset_code??"Pendiente de asignación");const address=line(notes,"Dirección evento:")??String((customer.metadata&&typeof customer.metadata==="object"?(customer.metadata as Record<string,unknown>).address:"")||project.location||"Dirección pendiente");
  const services=project.project_services.map(service=>service.service_code).filter(Boolean);const extras=project.project_services.flatMap(service=>Array.isArray(service.extras)?service.extras.filter((value):value is string=>typeof value==="string"):[]);const appUrl=process.env.NEXT_PUBLIC_APP_URL??"https://orbit.boom-box.cl";
  const operationalName=[operational?.contact_first_name,operational?.contact_last_name].filter(Boolean).join(" ");const canonicalContact=operational?.contact_status==="CONFIRMED"?`${operationalName} · ${operational.contact_phone??"Sin teléfono"}`:line(notes,"Contacto operacional:")??"Contacto operacional pendiente de confirmar";const canonicalNotes=operational?.operational_notes??(notes||"Sin notas operacionales");
  const calendarInput:CalendarOperationalEventInput={orbitEventId:project.orbit_event_id,planId:project.id,planStatus:"APPROVED",sequence:1,eventId:project.id,customerName:customer.full_name,customerPhone:customer.phone??"Sin teléfono",customerEmail:customer.email??"Sin correo",eventType,service:services.join(" + ")||"Servicio por confirmar",contractedHours:duration,eventDate:serviceStart.date,calendarStartDate:calendarStart.date,calendarStartTime:calendarStart.time,operator:operatorRecord?`${operatorRecord.first_name} ${operatorRecord.last_name}`:"Pendiente de asignación",blackBox:"Pendiente",booth:"Pendiente",assignedVehicle:vehicleName,operatorCallTime:`${calendarStart.date} · ${calendarStart.time}`,mountingWindow:operational?.assembly_start_at?`Desde ${new Date(operational.assembly_start_at).toLocaleTimeString("es-CL",{hour:"2-digit",minute:"2-digit",timeZone:"America/Santiago"})}`:"45 minutos",serviceStart:serviceStart.time,serviceStartDate:serviceStart.date,serviceEnd:serviceEnd.time,serviceEndDate:serviceEnd.date,dismantlingWindow:operational?.disassembly_start_at?`Desde ${new Date(operational.disassembly_start_at).toLocaleTimeString("es-CL",{hour:"2-digit",minute:"2-digit",timeZone:"America/Santiago"})}`:"30 minutos",operationalNotes:canonicalNotes,extras,customerAddress:address,venue:project.location??"Por confirmar",municipality:project.city??"Por confirmar",operationalContact:canonicalContact,assignedStaff:staff,commercialNotes:line(notes,"Notas comerciales:")??"Sin notas comerciales",portalUrl:`${appUrl}/projects/${project.id}#portal-cliente`,orbitProjectUrl:`${appUrl}/projects/${project.id}`,updatedAt:new Date().toISOString()};
  const repository=new SupabaseGoogleCalendarSyncRepository(input.client);const existing=await repository.findByOrbitEventId(project.orbit_event_id);if(input.onlyExisting&&!existing)return null;const cancelled=["CANCELLED","CANCELED","CANCELADO","CANCELADA"].includes(project.status.toUpperCase());const operation=input.operation??(cancelled?"CANCEL":existing?.status==="CANCELLED"?"RESTORE":"UPSERT");if(operation==="CANCEL"&&!existing?.googleEventId)return null;
  const engine=new GoogleCalendarLive(await loadGoogleWorkspaceConnection(),new GoogleCalendarApiProvider(await loadGoogleWorkspaceAccessToken()),repository);const result=await engine.synchronize(calendarInput,operation);if(!result.ok)throw new Error(result.error.message);
  const messages={CREATED:"Evento creado en Google Calendar.",UPDATED:"Evento actualizado en Google Calendar.",UNCHANGED:"Google Calendar ya estaba sincronizado.",CANCELLED:"Evento cancelado en Google Calendar.",RESTORED:"Evento restaurado en Google Calendar."}as const;const message=messages[result.operation];const{error:timelineError}=await input.client.from("timeline_events").insert({project_id:project.id,event_type:`CALENDAR_${result.operation}`,title:message,description:message,orbit_event_id:project.orbit_event_id,actor_id:input.actorId,actor_label:"Administrador",source:"Calendar",action:`CALENDAR_${result.operation}`,entity_type:"CalendarSync",entity_id:result.record.googleEventId??project.id,human_message:message,correlation_id:`calendar:${project.orbit_event_id}:${result.operation}:${randomUUID()}`,created_by:input.actorId});if(timelineError)throw timelineError;return{operation:result.operation,googleEventId:result.record.googleEventId};
}

export async function removeCancelledReservationCalendar(input:{client:SupabaseClient;projectId:string;actorId:string}):Promise<{removed:boolean;googleEventId?:string}>{
  const{data:project,error:projectError}=await input.client.from("projects").select("id,customer_id,orbit_event_id").eq("id",input.projectId).single();if(projectError)throw projectError;
  const{data:sync,error:syncError}=await input.client.from("calendar_sync").select("external_event_id,status").eq("project_id",input.projectId).maybeSingle();if(syncError)throw syncError;
  const googleEventId=sync?.external_event_id??undefined;if(!googleEventId||sync?.status==="DELETED")return{removed:false,googleEventId};
  const provider=new GoogleCalendarApiProvider(await loadGoogleWorkspaceAccessToken());await provider.deleteEvent(googleEventId);const synchronizedAt=new Date().toISOString();
  const{error:updateError}=await input.client.from("calendar_sync").update({status:"DELETED",external_url:null,last_synced_at:synchronizedAt,last_error:null}).eq("project_id",input.projectId);if(updateError)throw updateError;
  const message="Evento eliminado de Google Calendar al cancelar la reserva.";const{error:timelineError}=await input.client.from("timeline_events").insert({customer_id:project.customer_id,project_id:project.id,event_type:"CALENDAR_EVENT_REMOVED",title:message,description:message,orbit_event_id:project.orbit_event_id,actor_id:input.actorId,actor_label:"Administrador",source:"Calendar",action:"CALENDAR_EVENT_REMOVED",entity_type:"CalendarSync",entity_id:googleEventId,human_message:message,correlation_id:`calendar:${project.orbit_event_id}:deleted:${randomUUID()}`,created_by:input.actorId});if(timelineError)throw timelineError;
  return{removed:true,googleEventId};
}
