"use client";

import { useRef, useState, useTransition } from "react";
import { Download, FileSpreadsheet, Upload } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { importStaffRowsAction } from "./staff-import.actions";
import { parseStaffImportFile } from "./staff-import.parser";
import type { StaffImportPreview } from "./types";

export function StaffImport() {
  const inputRef = useRef<HTMLInputElement>(null); const [preview, setPreview] = useState<StaffImportPreview>(); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const selectFile = async (file?: File) => { if (!file) return; try { setPreview(await parseStaffImportFile(file)); setMessage(""); } catch (error) { setPreview(undefined); setMessage(error instanceof Error ? error.message : "No fue posible leer el archivo."); } };
  const confirm = () => preview?.valid && startTransition(async () => { const result = await importStaffRowsAction(preview.rows); setMessage(result.ok ? `${result.imported} integrantes importados correctamente.` : result.error); if (result.ok) { setPreview(undefined); if (inputRef.current) inputRef.current.value = ""; } });
  return <section className="rounded-2xl border bg-card p-5 sm:p-6" id="importar-staff"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-3"><FileSpreadsheet aria-hidden="true" className="size-5 text-brand" /><h2 className="text-xl font-semibold">Importar Staff</h2></div><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Carga únicamente la nómina oficial BOOMBOX. ORBIT valida RUT, clasificación operacional y capacidades antes de guardar.</p></div><div className="flex flex-wrap gap-2"><a className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-4 text-sm font-medium hover:bg-accent" download href="/templates/orbit-staff-import.xlsx"><Download className="size-4" />Plantilla Excel</a><a className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-4 text-sm font-medium hover:bg-accent" download href="/templates/orbit-staff-import.csv"><Download className="size-4" />Plantilla CSV</a></div></div><div className="mt-6 rounded-xl border border-dashed p-5"><input accept=".xlsx,.csv" className="sr-only" onChange={(event) => void selectFile(event.target.files?.[0])} ref={inputRef} type="file" /><ActionButton icon={Upload} label="Seleccionar archivo" onClick={() => inputRef.current?.click()} variant="outline" />{preview && <div className="mt-5 flex flex-wrap items-center gap-3"><StatusBadge label={`${preview.rows.length} filas`} variant="info" /><StatusBadge label={preview.valid ? "Listo para importar" : `${preview.issues.length} errores`} variant={preview.valid ? "success" : "danger"} /></div>}{preview?.issues.length ? <ul className="mt-4 space-y-2 text-sm text-danger">{preview.issues.slice(0, 8).map((issue) => <li key={`${issue.rowNumber}-${issue.field}-${issue.message}`}>Fila {issue.rowNumber} · {issue.field}: {issue.message}</li>)}</ul> : null}{preview?.valid && <div className="mt-5"><ActionButton disabled={pending} label={pending ? "Importando…" : "Confirmar importación"} onClick={confirm} /></div>}{message && <p className="mt-4 text-sm font-medium">{message}</p>}</div></section>;
}
