"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerActionClient } from "@/lib/supabase/server";
import { SupabaseProfitRepository } from "@/features/profit-engine";
import type { SupabaseClient } from "@supabase/supabase-js";

const fileTypes=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const amount=(data:FormData,key:string)=>{const value=Number(data.get(key)??0);if(!Number.isFinite(value)||value<0)throw new Error("Revisa los montos ingresados.");return value;};

async function context(){const client=await createSupabaseServerActionClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw error??new Error("Tu sesión expiró. Vuelve a iniciar sesión.");return{client,userId:data.user.id};}
function message(error:unknown){if(error instanceof Error&&!/PGRST|JWT|duplicate|constraint|violates|column/i.test(error.message))return error.message;return"No fue posible guardar el gasto. Revisa la información e inténtalo nuevamente.";}

export async function saveExpenseAction(data:FormData):Promise<{ok:boolean;message:string}>{let uploadedPath="";try{
  const{client,userId}=await context();const id=text(data,"id");const occurredOn=text(data,"occurredOn");const supplier=text(data,"supplier");const category=text(data,"category");const description=text(data,"description");
  if(!occurredOn||!supplier||!category||!description)throw new Error("Completa fecha, categoría, proveedor y descripción.");
  const subtotal=amount(data,"subtotal");const vat=amount(data,"vat");const exempt=amount(data,"exempt");const total=subtotal+vat+exempt;
  if(total<=0)throw new Error("El total del gasto debe ser mayor a cero.");
  const file=data.get("receipt");if(file instanceof File&&file.size){if(!fileTypes.has(file.type))throw new Error("El comprobante debe ser JPG, PNG, WEBP o PDF.");if(file.size>20_971_520)throw new Error("El archivo supera el máximo de 20 MB.");const extension=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"bin";uploadedPath=`${userId}/${occurredOn}/${crypto.randomUUID()}.${extension}`;const{error}=await client.storage.from("orbit-expenses").upload(uploadedPath,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(error)throw error;}
  const association=text(data,"associationType");const associationId=text(data,"associationId")||null;if(!["EVENT","VEHICLE","STAFF","EQUIPMENT","RESOURCE","GENERAL"].includes(association))throw new Error("Selecciona una asociación operacional válida.");if(association!=="GENERAL"&&!associationId)throw new Error("Selecciona el registro al que pertenece este gasto.");if(association==="GENERAL"&&category!=="ADMINISTRATION")throw new Error("Los gastos generales deben registrarse en la categoría Administración.");const metadata=JSON.stringify({description,supplierRut:text(data,"supplierRut"),documentType:text(data,"documentType")||"OTHER",exempt,paymentMethod:text(data,"paymentMethod")||"TRANSFER",associationType:association,associationId,auditReason:id?"Gasto actualizado desde el Centro de Gastos":"Gasto registrado desde el Centro de Gastos"});const payload={occurred_on:occurredOn,category,supplier,document_number:text(data,"documentNumber")||null,subtotal,vat,total,currency:"CLP",status:text(data,"status")||"PENDING",project_id:association==="EVENT"?associationId:null,vehicle_id:association==="VEHICLE"?associationId:null,supply_id:association==="RESOURCE"?associationId:null,...(uploadedPath&&{receipt_path:uploadedPath}),updated_by:userId,approval_reason:metadata};
  const previous=id?await client.from("expenses").select("project_id").eq("id",id).maybeSingle():null;if(previous?.error)throw previous.error;const result=id?await client.from("expenses").update(payload).eq("id",id).is("deleted_at",null):await client.from("expenses").insert({...payload,created_by:userId}).select("id").single();if(result.error)throw result.error;
  if(!id&&association==="EVENT"&&associationId){const{data:project}=await client.from("projects").select("customer_id").eq("id",associationId).maybeSingle();await client.from("timeline_events").insert({project_id:associationId,customer_id:project?.customer_id??null,event_type:"EXPENSE_REGISTERED",title:"Gasto registrado",description:`${supplier} · ${new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(total)}`,new_state:text(data,"status")||"PENDING",reason:"Registro operacional",created_by:userId});}
  const affected=new Set([previous?.data?.project_id,association==="EVENT"?associationId:null].filter((value):value is string=>Boolean(value)));for(const projectId of affected)await syncProjectExpenseCost(client,projectId);
  revalidatePath("/finance");revalidatePath("/finance/expenses");revalidatePath("/operations");return{ok:true,message:id?"Gasto actualizado correctamente.":"Gasto registrado correctamente."};
}catch(error){if(uploadedPath){try{const{client}=await context();await client.storage.from("orbit-expenses").remove([uploadedPath]);}catch{}}return{ok:false,message:message(error)};}}

export async function deleteExpenseAction(id:string):Promise<{ok:boolean;message:string}>{try{const{client,userId}=await context();const current=await client.from("expenses").select("project_id").eq("id",id).maybeSingle();const{error}=await client.from("expenses").update({deleted_at:new Date().toISOString(),updated_by:userId,approval_reason:"Gasto eliminado desde el Centro de Gastos"}).eq("id",id).is("deleted_at",null);if(error)throw error;if(current.data?.project_id)await syncProjectExpenseCost(client,current.data.project_id);revalidatePath("/finance");revalidatePath("/finance/expenses");revalidatePath("/operations");return{ok:true,message:"Gasto eliminado correctamente."};}catch(error){return{ok:false,message:message(error)};}}

export async function expenseReceiptUrlAction(path:string):Promise<{ok:boolean;url?:string;message?:string}>{try{const{client}=await context();const{data,error}=await client.storage.from("orbit-expenses").createSignedUrl(path,300);if(error)throw error;return{ok:true,url:data.signedUrl};}catch(error){return{ok:false,message:message(error)};}}

async function syncProjectExpenseCost(client:SupabaseClient,projectId:string){const[{data:expenses,error:expenseError},{data:snapshot,error:snapshotError}]=await Promise.all([client.from("expenses").select("total").eq("project_id",projectId).is("deleted_at",null),client.from("profit_snapshots").select("id,version").eq("project_id",projectId).is("deleted_at",null).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(expenseError)throw expenseError;if(snapshotError)throw snapshotError;if(snapshot)await new SupabaseProfitRepository(client).update({snapshotId:snapshot.id,expectedVersion:snapshot.version,expenseCost:(expenses??[]).reduce((sum,item)=>sum+Number(item.total??0),0),reason:"Gastos operacionales sincronizados desde el Centro de Gastos"});}
