"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Archive, Camera, ChevronLeft, ChevronRight, Lightbulb, MapPin, Star, Upload, UserRound, Wrench } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { completeExperienceReviewAction } from "./actions";
import type { ExistingExperienceReview, ExperienceKnowledgeItem } from "./types";

const ratings=[{value:"EXCELLENT",label:"Excelente"},{value:"GOOD",label:"Buena"},{value:"AVERAGE",label:"Promedio"},{value:"POOR",label:"Deficiente"}];
const steps=["Calificación","Cliente","Operación","Equipamiento","Staff","Lugar","Cliente","Aprendizajes","Evidencia","Archivar"];

export function ExperienceReviewEngine({projectId,existing,knowledge,staff}:{projectId:string;existing?:ExistingExperienceReview;knowledge:readonly ExperienceKnowledgeItem[];staff:{operator?:string;assembly?:string;disassembly?:string}}){
  const router=useRouter(); const [step,setStep]=useState(1); const [pending,startTransition]=useTransition(); const [feedback,setFeedback]=useState(""); const [complete,setComplete]=useState(Boolean(existing));
  const submit=(form:HTMLFormElement)=>startTransition(async()=>{const result=await completeExperienceReviewAction(projectId,new FormData(form));if(result.ok){setComplete(true);setFeedback(result.message);router.refresh();}else setFeedback(result.error)});
  if(complete)return <section className="rounded-2xl border bg-card p-5 sm:p-6" id="experience-review"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-success-soft text-success"><Archive className="size-5"/></span><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted">Experience Review</p><h2 className="mt-1 text-xl font-semibold">Conocimiento operacional archivado</h2><p className="mt-2 text-sm text-muted">Esta revisión es permanente y se mostrará cuando BOOMBOX vuelva a trabajar con este cliente, lugar o Staff.</p>{feedback&&<p className="mt-3 text-sm text-success">{feedback}</p>}</div></div></section>;
  return <section className="rounded-2xl border bg-card p-5 sm:p-6" id="experience-review"><header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Experience Review Engine</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Convertir la experiencia en conocimiento</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Completa la revisión al cerrar el evento. El historial permanece en Timeline; aquí se conserva lo que BOOMBOX debe repetir, evitar y recordar.</p></div><StatusBadge label={`Paso ${step} de 10`} variant="info"/></header>
    {knowledge.length>0&&<details className="mt-5 rounded-xl border bg-background/25 p-4"><summary className="cursor-pointer font-medium">Conocimiento previo disponible · {knowledge.length}</summary><div className="mt-4 grid gap-3 lg:grid-cols-2">{knowledge.slice(0,6).map(item=><article className="rounded-xl border p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.eventName}</p><p className="mt-1 text-xs text-muted">{item.venue} · {new Date(item.createdAt).toLocaleDateString("es-CL")}</p></div><span className="text-sm text-brand">{"★".repeat(item.rating)}</span></div>{item.recommendations&&<p className="mt-3 text-sm text-muted">{item.recommendations}</p>}</article>)}</div></details>}
    <form className="mt-6" onSubmit={(event)=>{event.preventDefault();submit(event.currentTarget)}}>
      <div className="min-h-[310px]">
        <Step active={step===1} icon={<Star/>} title="Calificación general"><p className="mb-4 text-sm text-muted">¿Cómo resultó la experiencia completa?</p><div className="flex flex-wrap gap-2">{[1,2,3,4,5].map(value=><label className="cursor-pointer" key={value}><input className="peer sr-only" defaultChecked={value===5} name="generalRating" type="radio" value={value}/><span className="flex min-h-12 items-center gap-1 rounded-xl border px-4 peer-checked:border-brand peer-checked:bg-brand/10 peer-checked:text-brand">{Array.from({length:value},(_,index)=><Star className="size-4 fill-current" key={index}/>)}</span></label>)}</div></Step>
        <Step active={step===2} icon={<UserRound/>} title="Experiencia del cliente"><Rating name="customerExperience"/></Step>
        <Step active={step===3} icon={<Lightbulb/>} title="Experiencia operacional"><Rating name="operationalExperience"/></Step>
        <Step active={step===4} icon={<Wrench/>} title="Revisión de equipamiento"><div className="grid gap-3 sm:grid-cols-2">{[["totem","Tótem"],["case","Case"],["printer","Impresora"],["camera","Cámara"]].map(([name,label])=><fieldset className="rounded-xl border p-4" key={name}><legend className="px-1 font-medium">{label}</legend><textarea className="mt-2 min-h-20 w-full rounded-lg border bg-background p-3 text-sm" name={`${name}Condition`} placeholder="Condición y observaciones"/><label className="mt-3 flex items-center gap-2 text-sm"><input className="size-4 accent-[var(--brand)]" name={`${name}Maintenance`} type="checkbox"/>Requiere mantención</label></fieldset>)}</div></Step>
        <Step active={step===5} icon={<UserRound/>} title="Revisión de Staff"><div className="grid gap-3 sm:grid-cols-3"><TextArea label={`Operador · ${staff.operator??"Sin asignar"}`} name="operatorReview"/><TextArea label={`Montaje · ${staff.assembly??"Sin asignar"}`} name="assemblyReview"/><TextArea label={`Desmontaje · ${staff.disassembly??"Sin asignar"}`} name="disassemblyReview"/></div><TextArea className="mt-3" label="Comentarios generales" name="staffComments"/></Step>
        <Step active={step===6} icon={<MapPin/>} title="Conocimiento del lugar"><TextArea label="Notas operacionales permanentes" name="venueKnowledge" placeholder="Accesos, estacionamiento, carga, horarios, restricciones, contactos…"/></Step>
        <Step active={step===7} icon={<UserRound/>} title="Conocimiento del cliente"><TextArea label="Preferencias permanentes" name="customerKnowledge" placeholder="Estilo de comunicación, preferencias, decisiones y detalles que no debemos volver a preguntar…"/></Step>
        <Step active={step===8} icon={<Lightbulb/>} title="Lecciones aprendidas"><div className="grid gap-3 lg:grid-cols-3"><TextArea label="Repetir" name="lessonsRepeat"/><TextArea label="Evitar" name="lessonsAvoid"/><TextArea label="Recomendaciones" name="recommendations"/></div></Step>
        <Step active={step===9} icon={<Camera/>} title="Evidencia"><p className="mb-4 text-sm text-muted">JPG, PNG o WEBP. Máximo 15 MB por archivo.</p><div className="grid gap-3 sm:grid-cols-3"><FileField label="Montaje" name="setupEvidence"/><FileField label="Evento" name="eventEvidence"/><FileField label="Desmontaje" name="teardownEvidence"/></div></Step>
        <Step active={step===10} icon={<Archive/>} title="Archivar y generar conocimiento"><div className="rounded-xl border border-brand/30 bg-brand/5 p-5"><p className="font-semibold">Esta acción es permanente.</p><p className="mt-2 text-sm leading-6 text-muted">ORBIT archivará el evento, guardará el aprendizaje, registrará la evidencia y generará eventos inmutables en Timeline y Auditoría.</p></div></Step>
      </div>
      {feedback&&<p aria-live="polite" className="mb-4 rounded-xl border px-4 py-3 text-sm">{feedback}</p>}
      <footer className="flex items-center justify-between gap-3 border-t pt-5"><ActionButton disabled={step===1||pending} icon={ChevronLeft} label="Anterior" onClick={()=>setStep(value=>Math.max(1,value-1))} type="button" variant="outline"/>{step<10?<ActionButton icon={ChevronRight} label="Continuar" onClick={()=>setStep(value=>Math.min(10,value+1))} type="button"/>:<ActionButton disabled={pending} icon={Archive} label={pending?"Archivando…":"Archivar evento"} type="submit"/>}</footer>
    </form>
  </section>;
}

function Step({active,icon,title,children}:{active:boolean;icon:React.ReactNode;title:string;children:React.ReactNode}){return <fieldset className={active?"block":"hidden"}><legend className="mb-5 flex items-center gap-3 text-xl font-semibold"><span className="grid size-10 place-items-center rounded-xl bg-brand/10 text-brand [&>svg]:size-5">{icon}</span>{title}</legend>{children}</fieldset>}
function Rating({name}:{name:string}){return <div className="grid gap-2 sm:grid-cols-4">{ratings.map((rating,index)=><label className="cursor-pointer" key={rating.value}><input className="peer sr-only" defaultChecked={index===0} name={name} type="radio" value={rating.value}/><span className="grid min-h-14 place-items-center rounded-xl border px-3 text-sm font-medium peer-checked:border-brand peer-checked:bg-brand/10 peer-checked:text-brand">{rating.label}</span></label>)}</div>}
function TextArea({label,name,placeholder,className=""}:{label:string;name:string;placeholder?:string;className?:string}){return <label className={`block text-sm font-medium ${className}`}>{label}<textarea className="mt-2 min-h-28 w-full rounded-xl border bg-background p-3 text-sm font-normal" name={name} placeholder={placeholder}/></label>}
function FileField({label,name}:{label:string;name:string}){return <label className="flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed p-4 text-center transition hover:border-brand"><Upload className="size-5 text-brand"/><span className="mt-2 text-sm font-medium">{label}</span><span className="mt-1 text-xs text-muted">Seleccionar imagen</span><input accept="image/jpeg,image/png,image/webp" className="sr-only" name={name} type="file"/></label>}
