"use client";

import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { CheckCircle2, FileSignature, RotateCcw, ShieldCheck } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";

export interface CustomerSigningExperienceProps { token: string; customer: string; project: string; eventDate: string; service: string; agreementVersion: string; clauses: readonly { title: string; content: string }[]; }
export function CustomerSigningExperience(props: CustomerSigningExperienceProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const [ink,setInk] = useState(false); const [accepted,setAccepted] = useState(false); const [pending,setPending] = useState(false); const [done,setDone] = useState(false); const [message,setMessage] = useState("");
  useEffect(() => { const canvas=canvasRef.current;if(!canvas)return;const rect=canvas.getBoundingClientRect();const ratio=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const context=canvas.getContext("2d");context?.scale(ratio,ratio);if(context){context.lineCap="round";context.lineJoin="round";context.lineWidth=2.5;context.strokeStyle="#f59e0b";} },[]);
  const point=(event:ReactPointerEvent<HTMLCanvasElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};};
  const start=(event:ReactPointerEvent<HTMLCanvasElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);drawing.current=true;const context=event.currentTarget.getContext("2d");const p=point(event);context?.beginPath();context?.moveTo(p.x,p.y);};
  const draw=(event:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const context=event.currentTarget.getContext("2d");const p=point(event);context?.lineTo(p.x,p.y);context?.stroke();setInk(true);};
  const stop=()=>{drawing.current=false;}; const clear=()=>{const canvas=canvasRef.current;if(canvas)canvas.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);setInk(false);setMessage("");};
  const confirm=async()=>{const canvas=canvasRef.current;if(!canvas||!accepted||!ink)return;setPending(true);setMessage("");try{const response=await fetch(`/api/signing/${encodeURIComponent(props.token)}/confirm`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signatureDataUrl:canvas.toDataURL("image/png")})});const result=await response.json() as {ok?:boolean;message?:string};if(!response.ok||!result.ok)throw new Error(result.message??"No fue posible confirmar la firma.");setDone(true);}catch(error){setMessage(error instanceof Error?error.message:"No fue posible confirmar la firma.");}finally{setPending(false);}};
  if(done)return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><div className="w-full max-w-xl rounded-3xl border bg-card p-8 text-center sm:p-12"><CheckCircle2 className="mx-auto size-12 text-success" /><p className="mt-6 text-sm font-semibold uppercase tracking-[0.18em] text-brand">Acuerdo firmado</p><h1 className="mt-3 text-3xl font-semibold">¡Todo listo!</h1><p className="mt-4 leading-7 text-muted">Tu firma quedó registrada y el acuerdo fue almacenado de forma segura. No necesitas realizar otra acción.</p></div></main>;
  return <main className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6 sm:py-12"><div className="mx-auto max-w-3xl"><header className="rounded-3xl border bg-card p-6 sm:p-9"><div className="flex items-center gap-3 text-brand"><FileSignature className="size-6" /><span className="text-sm font-semibold">BOOMBOX · Acuerdo digital</span></div><h1 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Revisa y confirma tu experiencia</h1><p className="mt-4 leading-7 text-muted">{props.customer} · {props.project} · {props.eventDate}</p><div className="mt-6 rounded-xl border bg-background/40 p-4 text-sm"><strong>{props.service}</strong><span className="mx-2 text-muted">·</span>Versión {props.agreementVersion}</div></header><section className="mt-6 rounded-3xl border bg-card p-6 sm:p-9"><h2 className="text-2xl font-semibold">Condiciones</h2><div className="mt-6 space-y-3">{props.clauses.map((clause,index)=><details className="rounded-xl border bg-background/30 p-4" key={`${clause.title}-${index}`} open={index===0}><summary className="cursor-pointer font-medium">{clause.title}</summary><p className="mt-3 text-sm leading-6 text-muted">{clause.content}</p></details>)}</div><label className="mt-7 flex cursor-pointer items-start gap-3 rounded-xl border p-4"><input checked={accepted} className="mt-1 size-5 accent-[var(--brand)]" onChange={(event)=>setAccepted(event.target.checked)} type="checkbox"/><span><strong>He leído y acepto las condiciones del servicio.</strong><span className="mt-1 block text-sm text-muted">La firma quedará vinculada únicamente a este acuerdo.</span></span></label></section><section className="mt-6 rounded-3xl border bg-card p-6 sm:p-9"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-brand"/><h2 className="text-2xl font-semibold">Tu firma</h2></div><p className="mt-3 text-sm leading-6 text-muted">Firma con el dedo, mouse o lápiz. Puedes limpiar y firmar nuevamente antes de confirmar.</p><canvas aria-label="Área para firmar" className="mt-6 h-64 w-full touch-none rounded-xl border border-dashed bg-background" onPointerCancel={stop} onPointerDown={start} onPointerLeave={stop} onPointerMove={draw} onPointerUp={stop} ref={canvasRef}/><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:justify-between"><ActionButton disabled={!ink||pending} icon={RotateCcw} label="Firmar nuevamente" onClick={clear} variant="outline"/><ActionButton disabled={!ink||!accepted||pending} label={pending?"Confirmando…":"Confirmar firma"} onClick={()=>void confirm()}/></div>{message&&<p className="mt-4 text-sm text-danger">{message}</p>}</section></div></main>;
}
