import { CHILE_VAT_RATE } from "@/features/business-core";
import type { SupplyDefinition } from "../types/supply.types";

export const INITIAL_SUPPLY_CATALOG: readonly SupplyDefinition[] = [
  {
    id: "dnp-rx1-media",
    name: "DNP RX1 Media",
    supplier: "DNP",
    purchasePrice: 260170,
    vatIncluded: true,
    unit: "PHOTO",
    usefulLife: "1.400 fotografías",
    calculationMethod: "PRODUCTION_OUTPUT",
    lastUpdated: "05 agosto 2026",
    status: "ACTIVE",
    productionUnits: 1400,
    contents: ["2 rollos", "2 ribbons"],
  },
  {
    id: "magnets",
    name: "Imanes",
    supplier: "Proveedor BOOMBOX",
    purchasePrice: 225000,
    vatIncluded: true,
    unit: "EVENT",
    usefulLife: "100 eventos",
    calculationMethod: "EVENT_CAPACITY",
    lastUpdated: "05 agosto 2026",
    status: "LOW_STOCK",
    operationalCapacityEvents: 100,
    additionalCostBeforeVat: 45000,
    contents: [`Corte: $45.000 + IVA (${Math.round(CHILE_VAT_RATE * 100)}%)`],
  },
  {
    id: "scrapbook",
    name: "Scrapbook",
    supplier: "Proveedor BOOMBOX",
    purchasePrice: 7500,
    vatIncluded: true,
    unit: "EVENT",
    usefulLife: "1 evento",
    calculationMethod: "DIRECT_EVENT_COST",
    lastUpdated: "05 agosto 2026",
    status: "ACTIVE",
  },
  {
    id: "pens",
    name: "Lápices",
    supplier: "Proveedor BOOMBOX",
    purchasePrice: 1900,
    vatIncluded: true,
    unit: "MONTH",
    usefulLife: "2 meses",
    calculationMethod: "MONTHLY_AMORTIZATION",
    lastUpdated: "05 agosto 2026",
    status: "ACTIVE",
    standardQuantity: 4,
    usefulLifeMonths: 2,
    contents: ["4 lápices por kit operacional"],
  },
  {
    id: "double-sided-tape",
    name: "Cinta doble contacto",
    supplier: "Proveedor BOOMBOX",
    purchasePrice: 2000,
    vatIncluded: true,
    unit: "MONTH",
    usefulLife: "2 meses",
    calculationMethod: "MONTHLY_AMORTIZATION",
    lastUpdated: "05 agosto 2026",
    status: "ACTIVE",
    standardQuantity: 1,
    usefulLifeMonths: 2,
  },
] as const;
