import {NextResponse} from "next/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {GoogleGmailApiProvider} from "@/features/connectors/google-gmail/provider/google-gmail-live.provider";
import {loadGoogleWorkspaceAccessToken} from "@/features/connectors/google-workspace/application/google-workspace.repository";

const localParts=(date:Date)=>{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date),get=(type:string)=>parts.find(item=>item.type===type)?.value??"00";return{date:`${get("year")}-${get("month")}-${get("day")}`,time:`${get("hour")}:${get("minute")}`}};
const localMinutes=(date:string,time:string)=>Date.parse(`${date}T${time.slice(0,5)}:00Z`)/60000;

export async function GET(request:Request){
  const expected=process.env.CRON_SECRET;if(!expected)return NextResponse.json({error:"Cron is not configured."},{status:503});const authorized=request.headers.get("authorization")===`Bearer ${expected}`;if(!authorized)return NextResponse.json({error:"Unauthorized"},{status:401});
  const admin=createAdminClient(),now=localParts(new Date()),today=now.date,end=new Date(`${today}T12:00:00Z`);end.setUTCDate(end.getUTCDate()+3);
  const{data:logisticsAlerts,error:logisticsAlertError}=await admin.rpc("refresh_logistics_notifications",{p_reference:new Date().toISOString()});
  if(logisticsAlertError)return NextResponse.json({error:logisticsAlertError.message},{status:500});
  const{data,error}=await admin.from("assignments").select("id,project_id,staff_id,assignment_type,status,staff_call_at,staff(first_name,email),projects(id,name,customer_id,event_date,event_time,location,city,customers(full_name))").is("deleted_at",null).in("status",["PENDING","PENDING_CONFIRMATION","ASSIGNED","CONFIRMED","ACCEPTED"]).gte("projects.event_date",today).lte("projects.event_date",end.toISOString().slice(0,10));if(error)return NextResponse.json({error:error.message},{status:500});
  let delivered=0;for(const row of data??[]){const project=Array.isArray(row.projects)?row.projects[0]:row.projects,staff=Array.isArray(row.staff)?row.staff[0]:row.staff;if(!project||!staff?.email)continue;const call=row.staff_call_at?new Date(row.staff_call_at):null,difference=call?Math.round((call.getTime()-Date.now())/60000):localMinutes(project.event_date,project.event_time??"00:00")-localMinutes(now.date,now.time),window=[48,24,2].find(hours=>difference<=hours*60&&difference>(hours*60)-65);if(!window)continue;const correlation=`staff-assignment-reminder:${row.id}:${window}`,title=window===2?"Hora de salir al Evento":`Recordatorio de Evento · ${window} horas`,maps=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${project.location??""}, ${project.city??""}`)}`;
    const{data:inserted}=await admin.from("internal_notifications").upsert({project_id:project.id,customer_id:project.customer_id,staff_id:row.staff_id,notification_type:"STAFF_ASSIGNMENT_REMINDER",title,message:`${project.event_date} ${project.event_time?.slice(0,5)??""} · ${project.name}`,status:"UNREAD",correlation_id:correlation,category:"OPERATIONS",priority:window===2?"HIGH":"NORMAL",action_required:window===2,entity_type:"Assignment",entity_id:row.id,related_href:"/staff-portal",metadata:{hours_before:window,maps}},{onConflict:"correlation_id",ignoreDuplicates:true}).select("id");if(!inserted?.length)continue;
    try{const sent=await new GoogleGmailApiProvider(await loadGoogleWorkspaceAccessToken()).send({to:staff.email,subject:title,textBody:`Hola ${staff.first_name}. ${project.name} comienza en ${window} horas.\nFecha: ${project.event_date}\nHora: ${project.event_time?.slice(0,5)}\nUbicación: ${project.location??"Por confirmar"}\nRuta: ${maps}\nPortal Staff: ${(process.env.NEXT_PUBLIC_APP_URL??"https://orbit.boom-box.cl")}/login?access=staff`,htmlBody:`<main style="font-family:Arial,sans-serif;line-height:1.6"><h1>${title}</h1><p>Hola ${staff.first_name}, revisa tu paquete operacional en Portal Staff.</p><p><strong>${project.event_date} · ${project.event_time?.slice(0,5)}</strong><br>${project.location??"Ubicación por confirmar"}</p><p><a href="${maps}">Iniciar navegación</a></p></main>`,driveFileIds:[]});await admin.from("internal_notifications").update({metadata:{hours_before:window,maps,email_status:"SENT",message_id:sent.messageId}}).eq("id",inserted[0].id);delivered++;}catch(sendError){await admin.from("internal_notifications").update({metadata:{hours_before:window,maps,email_status:"FAILED",error:sendError instanceof Error?sendError.message:"Unknown"}}).eq("id",inserted[0].id);}
  }
  return NextResponse.json({ok:true,delivered,logisticsAlerts:Number(logisticsAlerts??0)});
}
