import {NextRequest,NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {loadAccountantExportData} from "@/features/accountant-export/data";
import {createCsv,createSingleWorkbook,createSummaryPdf,createZip} from "@/features/accountant-export/files";
import {DEFAULT_ACCOUNTANT_EXPORT_CONFIG,type AccountantExportConfig} from "@/features/accountant-export/types";

export const runtime="nodejs";
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
export async function GET(request:NextRequest){try{const client=await createSupabaseServerClient();const{data:auth,error:authError}=await client.auth.getUser();if(authError||!auth.user)return NextResponse.json({message:"Tu sesión expiró. Vuelve a iniciar sesión."},{status:401});const{data:profile}=await client.from("profiles").select("role").eq("id",auth.user.id).single();if(!profile||!["CEO","ADMINISTRATOR"].includes(profile.role))return NextResponse.json({message:"Solo Administración puede exportar información contable."},{status:403});const params=request.nextUrl.searchParams;const from=params.get("from")??"",to=params.get("to")??"",format=(params.get("format")??"zip").toLowerCase();if(!validDate(from)||!validDate(to)||from>to)return NextResponse.json({message:"Selecciona un período válido."},{status:400});const{data:settings}=await client.from("company_settings").select("pdf_configuration").eq("settings_key","PRIMARY").maybeSingle();const stored=settings?.pdf_configuration&&typeof settings.pdf_configuration==="object"?(settings.pdf_configuration as Record<string,unknown>).accountantExport:null;const config={...DEFAULT_ACCOUNTANT_EXPORT_CONFIG,...(stored&&typeof stored==="object"?stored:{})} as AccountantExportConfig;const data=await loadAccountantExportData(client,from,to);const date=new Date(`${from}T12:00:00Z`);const month=`${["ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"][date.getUTCMonth()]}_${date.getUTCFullYear()}`;let body:Buffer;let contentType:string;let fileName:string;if(format==="xlsx"){body=await createSingleWorkbook(data);contentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";fileName=`CONTABILIDAD_${month}.xlsx`;}else if(format==="csv"){body=createCsv(data,config);contentType="text/csv; charset=utf-8";fileName=`CONTABILIDAD_${month}.csv`;}else if(format==="pdf"){body=await createSummaryPdf(data);contentType="application/pdf";fileName=`RESUMEN_CONTABLE_${month}.pdf`;}else{body=await createZip(data);contentType="application/zip";fileName=`CONTABILIDAD_${month}.zip`;}return new NextResponse(new Uint8Array(body),{headers:{"Content-Type":contentType,"Content-Disposition":`attachment; filename=\"${fileName}\"`,"Cache-Control":"private, no-store"}});}catch(error){console.error("[accountant-export]",error);return NextResponse.json({message:"No fue posible generar la exportación contable. Inténtalo nuevamente."},{status:500})}}
