"use client";

import { Check, ChevronLeft, ChevronRight, Clock3, FileSignature, Link2, PenLine, Sparkles, X } from "lucide-react";
import { useId, useMemo, useState } from "react";
import { ActionButton } from "@/components/ui/action-button";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { projectOrigins, projectServices, projectTypes, type ProjectDraft, type ProjectOrigin, type ProjectService, type ProjectType } from "../types/project";

const steps = ["Cliente", "Evento", "Servicio + extras", "Método", "Acuerdo", "Pago", "Portal"] as const;
const initialDraft: ProjectDraft = { client: { name: "", email: "", phone: "", rut: "", address: "" }, event: { date: "", time: "", location: "", city: "", durationHours: 2, extras: [] }, services: [], notes: "" };
const typeLabels: Record<ProjectType, string> = { Wedding: "Matrimonio", Corporate: "Corporativo", Birthday: "Cumpleaños", Private: "Privado", Other: "Otro" };
const originLabels: Record<ProjectOrigin, string> = { WhatsApp: "WhatsApp", Instagram: "Instagram", Google: "Google", Website: "Página Web", Referral: "Referido", FormerClient: "Cliente antiguo", Other: "Otro" };
const extraOptions = ["Branding", "QR", "Imanes", "Scrapbook", "Transporte"] as const;

export interface NewProjectDrawerProps { open: boolean; onClose: () => void; onCreate: (draft: ProjectDraft) => Promise<void>; }

function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) {
  const id = useId();
  return <label className="block text-sm font-medium" htmlFor={id}>{label}<input className="mt-2 h-11 w-full rounded-lg border bg-background px-3 text-sm outline-none transition focus:ring-2 focus:ring-brand/40" id={id} {...props}/></label>;
}

function TextArea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) {
  const id = useId();
  return <label className="block text-sm font-medium" htmlFor={id}>{label}<textarea className="mt-2 min-h-24 w-full rounded-lg border bg-background px-3 py-3 text-sm outline-none transition focus:ring-2 focus:ring-brand/40" id={id} {...props}/></label>;
}

export function NewProjectDrawer({ open, onClose, onCreate }: NewProjectDrawerProps) {
  const [step,setStep]=useState(0); const [method,setMethod]=useState<"MANUAL">("MANUAL"); const [draft,setDraft]=useState<ProjectDraft>(initialDraft); const [endTime,setEndTime]=useState(""); const [operationalContact,setOperationalContact]=useState(""); const [additionalHours,setAdditionalHours]=useState(0); const [specialRequests,setSpecialRequests]=useState(""); const [commercialNotes,setCommercialNotes]=useState(""); const [payment,setPayment]=useState({reservation:"",balance:"",invoice:"",terms:"Cash"}); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  const totalHours=(draft.event.durationHours??2)+additionalHours;
  const summary=useMemo(()=>({service:draft.services.join(" · ")||"Servicio pendiente",extras:draft.event.extras?.join(" · ")||"Sin extras",hours:`${totalHours} horas`}),[draft.event.extras,draft.services,totalHours]);
  if(!open)return null;
  const reset=()=>{setStep(0);setMethod("MANUAL");setDraft(initialDraft);setEndTime("");setOperationalContact("");setAdditionalHours(0);setSpecialRequests("");setCommercialNotes("");setPayment({reservation:"",balance:"",invoice:"",terms:"Cash"});setError("");onClose();};
  const client=(field:keyof ProjectDraft["client"],value:string)=>setDraft(current=>({...current,client:{...current.client,[field]:value}}));
  const event=(field:keyof ProjectDraft["event"],value:string|number|string[])=>setDraft(current=>({...current,event:{...current.event,[field]:value}}));
  const toggleExtra=(value:string)=>event("extras",draft.event.extras?.includes(value)?draft.event.extras.filter(item=>item!==value):[...(draft.event.extras??[]),value]);
  const valid=step===0?Boolean(draft.client.name&&draft.client.phone&&draft.client.email&&draft.client.rut&&draft.client.address&&draft.origin):step===1?Boolean(draft.type&&draft.event.location&&draft.event.city&&draft.event.date&&draft.event.time&&endTime&&operationalContact):step===2?Boolean(draft.services.length&&draft.event.durationHours):step===3?method==="MANUAL":true;
  const create=async()=>{if(!valid)return;setSubmitting(true);setError("");try{await onCreate({...draft,event:{...draft.event,durationHours:totalHours},notes:[draft.notes,`Horario: ${draft.event.time}–${endTime}`,`Contacto operacional: ${operationalContact}`,specialRequests&&`Solicitudes especiales: ${specialRequests}`,commercialNotes&&`Notas comerciales: ${commercialNotes}`,payment.reservation&&`Reserva: ${payment.reservation}`,payment.balance&&`Saldo: ${payment.balance}`,payment.invoice&&`Factura: ${payment.invoice}`,`Condición de pago: ${payment.terms}`].filter(Boolean).join("\n")});reset();}catch(cause){setError(cause instanceof Error?cause.message:"No fue posible crear la reserva.");}finally{setSubmitting(false);}};
  return <><button aria-label="Cerrar nueva reserva" className="fixed inset-0 z-40 cursor-default bg-black/45 backdrop-blur-[2px]" onClick={reset}/><aside aria-label="Nueva reserva" className="fixed inset-y-0 right-0 z-50 flex w-full max-w-2xl flex-col border-l bg-card shadow-2xl">
    <header className="flex items-start justify-between border-b p-5 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Nueva reserva · Paso {step+1} de {steps.length}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{steps[step]}</h2></div><Button aria-label="Cerrar" onClick={reset} size="icon" variant="ghost"><X className="size-4"/></Button></header>
    <div className="flex gap-1.5 border-b px-5 py-4 sm:px-7">{steps.map((label,index)=><span aria-label={label} className={cn("h-1.5 flex-1 rounded-full bg-accent",index<=step&&"bg-brand")} key={label}/>)}</div>
    <div className="flex-1 overflow-y-auto p-5 sm:p-7">
      {step===0&&<div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="Nombre completo" onChange={e=>client("name",e.target.value)} required value={draft.client.name}/><Field label="RUT" onChange={e=>client("rut",e.target.value)} required value={draft.client.rut}/><Field label="Teléfono" onChange={e=>client("phone",e.target.value)} required type="tel" value={draft.client.phone}/><Field label="Correo" onChange={e=>client("email",e.target.value)} required type="email" value={draft.client.email}/></div><Field label="Dirección" onChange={e=>client("address",e.target.value)} required value={draft.client.address}/><label className="block text-sm font-medium">Origen del contacto<select className="mt-2 h-11 w-full rounded-lg border bg-background px-3" onChange={e=>setDraft(current=>({...current,origin:e.target.value as ProjectOrigin}))} value={draft.origin??""}><option disabled value="">Selecciona un origen</option>{projectOrigins.map(origin=><option key={origin} value={origin}>{originLabels[origin]}</option>)}</select></label></div>}
      {step===1&&<div className="space-y-6"><div><p className="mb-3 text-sm font-medium">Tipo de evento</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{projectTypes.map(type=><button className={cn("min-h-12 rounded-xl border p-3 text-left text-sm",draft.type===type&&"border-brand bg-brand/5")} key={type} onClick={()=>setDraft(current=>({...current,type}))}>{typeLabels[type]}</button>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Lugar" onChange={e=>event("location",e.target.value)} required value={draft.event.location}/><Field label="Comuna" onChange={e=>event("city",e.target.value)} required value={draft.event.city}/><Field label="Fecha" onChange={e=>event("date",e.target.value)} required type="date" value={draft.event.date}/><Field label="Hora de inicio" onChange={e=>event("time",e.target.value)} required type="time" value={draft.event.time}/><Field label="Hora de término" onChange={e=>setEndTime(e.target.value)} required type="time" value={endTime}/><Field label="Contacto operacional" onChange={e=>setOperationalContact(e.target.value)} required value={operationalContact}/></div><TextArea label="Notas especiales" onChange={e=>setDraft(current=>({...current,notes:e.target.value}))} value={draft.notes}/></div>}
      {step===2&&<div className="grid gap-6 lg:grid-cols-[1fr_17rem]"><div className="space-y-6"><div><p className="mb-3 text-sm font-medium">Servicio</p><div className="grid grid-cols-2 gap-2">{projectServices.map(service=><label className={cn("flex min-h-12 items-center gap-2 rounded-xl border p-3 text-sm",draft.services.includes(service)&&"border-brand bg-brand/5")} key={service}><input checked={draft.services.includes(service)} onChange={()=>setDraft(current=>({...current,services:current.services.includes(service)?current.services.filter(item=>item!==service):[...current.services,service as ProjectService]}))} type="checkbox"/>{service}</label>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Duración base" min="2" onChange={e=>event("durationHours",Number(e.target.value))} required type="number" value={draft.event.durationHours}/><Field label="Horas adicionales" min="0" onChange={e=>setAdditionalHours(Number(e.target.value))} type="number" value={additionalHours}/></div><div><p className="mb-3 text-sm font-medium">Extras</p><div className="grid grid-cols-2 gap-2">{extraOptions.map(extra=><label className={cn("flex min-h-11 items-center gap-2 rounded-xl border p-3 text-sm",draft.event.extras?.includes(extra)&&"border-brand bg-brand/5")} key={extra}><input checked={draft.event.extras?.includes(extra)??false} onChange={()=>toggleExtra(extra)} type="checkbox"/>{extra}</label>)}</div></div><TextArea label="Solicitudes especiales" onChange={e=>setSpecialRequests(e.target.value)} value={specialRequests}/><TextArea label="Notas comerciales" onChange={e=>setCommercialNotes(e.target.value)} value={commercialNotes}/></div><aside className="h-fit rounded-2xl border bg-brand/5 p-5 lg:sticky lg:top-0"><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Resumen en vivo</p><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-muted">Servicio</dt><dd className="mt-1 font-semibold">{summary.service}</dd></div><div><dt className="text-muted">Duración</dt><dd className="mt-1 font-semibold">{summary.hours}</dd></div><div><dt className="text-muted">Extras</dt><dd className="mt-1 font-semibold">{summary.extras}</dd></div></dl><p className="mt-5 border-t pt-4 text-xs leading-5 text-muted">La cotización oficial se calcula con el motor comercial aprobado.</p></aside></div>}
      {step===3&&<div className="space-y-4"><p className="text-sm leading-6 text-muted">Elige cómo continuar esta reserva.</p><button className="w-full rounded-2xl border border-brand bg-brand/5 p-5 text-left" onClick={()=>setMethod("MANUAL")}><PenLine className="size-5 text-brand"/><span className="mt-4 block font-semibold">Manual</span><span className="mt-1 block text-sm leading-6 text-muted">Habilitado. Continúa con acuerdo, firma, pago y Portal desde ORBIT.</span></button><div aria-disabled="true" className="rounded-2xl border bg-background/30 p-5 opacity-70"><div className="flex items-center justify-between"><Sparkles className="size-5 text-muted"/><span className="rounded-full border px-3 py-1 text-xs font-semibold">Próximamente</span></div><span className="mt-4 block font-semibold">Automático</span><span className="mt-1 block text-sm leading-6 text-muted">El cliente completará sus datos mediante un enlace de reserva. Esta opción aún no está habilitada.</span></div></div>}
      {step===4&&<div className="space-y-5"><div className="rounded-2xl border bg-brand/5 p-5"><FileSignature className="size-5 text-brand"/><h3 className="mt-3 text-lg font-semibold">Acuerdo preparado dentro del evento</h3><p className="mt-2 text-sm leading-6 text-muted">Al completar la reserva se abrirá Event 360°. Desde allí podrás generar el acuerdo, revisarlo, enviarlo y seguir la firma sin cambiar de contexto.</p></div>{["Generar acuerdo","Vista previa","Enviar acuerdo","Seguimiento de firma"].map((label,index)=><div className="flex items-center gap-3 rounded-xl border p-4" key={label}><span className="grid size-7 place-items-center rounded-full bg-brand/10 text-xs font-semibold text-brand">{index+1}</span><span className="text-sm font-medium">{label}</span></div>)}</div>}
      {step===5&&<div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="Pago de reserva" min="0" onChange={e=>setPayment(current=>({...current,reservation:e.target.value}))} type="number" value={payment.reservation}/><Field label="Saldo restante" min="0" onChange={e=>setPayment(current=>({...current,balance:e.target.value}))} type="number" value={payment.balance}/><Field label="Factura / referencia" onChange={e=>setPayment(current=>({...current,invoice:e.target.value}))} value={payment.invoice}/><label className="block text-sm font-medium">Condición de pago<select className="mt-2 h-11 w-full rounded-lg border bg-background px-3" onChange={e=>setPayment(current=>({...current,terms:e.target.value}))} value={payment.terms}>{["Cash","15 días","30 días","45 días","60 días","90 días"].map(term=><option key={term}>{term}</option>)}</select></label></div><p className="rounded-xl border bg-background/35 p-4 text-sm leading-6 text-muted">Los movimientos financieros se confirman posteriormente desde el evento; este paso deja registrada la condición comercial inicial.</p></div>}
      {step===6&&<div className="space-y-5 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-success/10 text-success"><Check className="size-6"/></span><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Reserva lista para completar</p><h3 className="mt-2 text-2xl font-semibold">Portal del cliente</h3><p className="mt-3 text-sm leading-6 text-muted">Al crear la reserva se abrirá Event 360°, donde podrás generar el Portal y continuar con acuerdo, firma y pago.</p></div><div className="grid gap-3 sm:grid-cols-3">{["Copiar enlace","Abrir Portal","Enviar acceso"].map(label=><Button disabled key={label} variant="outline"><Link2 className="mr-2 size-4"/>{label}</Button>)}</div><p className="text-xs text-muted">Estas acciones se habilitan cuando la reserva y su token de Portal existen.</p></div>}
      {error&&<p className="mt-4 text-sm text-danger">{error}</p>}
    </div>
    <footer className="flex items-center justify-between gap-3 border-t p-5 sm:p-7"><ActionButton disabled={step===0} icon={ChevronLeft} label="Atrás" onClick={()=>setStep(current=>current-1)} variant="outline"/>{step<steps.length-1?<ActionButton disabled={!valid} icon={ChevronRight} iconPosition="end" label="Continuar" onClick={()=>setStep(current=>current+1)}/>:<ActionButton disabled={submitting} icon={Clock3} label={submitting?"Creando reserva…":"Completar reserva"} onClick={()=>void create()}/>}</footer>
  </aside></>;
}
