"use client";

import { useState } from "react";
import { simulateBiancaMessage, type BiancaSimulationResult } from "./simulator";

export function BiancaLab() {
  const [message, setMessage] = useState("");
  const [result, setResult] = useState<BiancaSimulationResult | null>(null);
  return <section className="space-y-5 rounded-3xl border bg-card p-5 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Founder Lab · Simulación</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">BIANCA</h1><p className="mt-2 text-sm text-muted">Prueba razonamiento comercial y escalamiento con fixtures aislados. <strong>SIMULACIÓN · NO SE ENVIARÁ NINGÚN MENSAJE.</strong></p></div><textarea className="min-h-28 w-full rounded-xl border bg-background p-3 text-sm" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Escribe un mensaje simulado…" aria-label="Mensaje simulado"/><button className="min-h-11 rounded-xl bg-brand px-4 text-sm font-semibold text-brand-foreground disabled:opacity-50" disabled={!message.trim()} onClick={() => setResult(simulateBiancaMessage(message))}>SIMULAR RESPUESTA</button>{result && <div className="grid gap-4 border-t pt-5 md:grid-cols-2"><div className="space-y-3"><h2 className="font-semibold">Decisión BIANCA</h2><dl className="grid gap-2 text-sm"><div><dt className="text-muted">Intent</dt><dd className="font-medium">{result.intent}</dd></div><div><dt className="text-muted">Estado cliente</dt><dd>{result.customerState}</dd></div><div><dt className="text-muted">Datos extraídos</dt><dd>{result.extracted.join(" · ") || "Sin datos"}</dd></div><div><dt className="text-muted">Falta</dt><dd>{result.missing.join(" · ") || "Nada crítico"}</dd></div><div><dt className="text-muted">Fuentes consultadas</dt><dd>{result.sources.join(" · ")}</dd></div>{result.capacity && <div><dt className="text-muted">Capacidad</dt><dd className="font-semibold">{result.capacity}</dd></div>}</dl></div><div className="space-y-3"><h2 className="font-semibold">Respuesta propuesta</h2><p className="rounded-xl border bg-background p-3 text-sm whitespace-pre-wrap">{result.proposedResponse}</p><dl className="grid gap-2 text-sm"><div><dt className="text-muted">Acción</dt><dd>{result.proposedAction}</dd></div><div><dt className="text-muted">Escalamiento</dt><dd className="font-semibold">{result.escalation ? `Sí · ${result.escalationReason}` : "No"}</dd></div><div><dt className="text-muted">Control</dt><dd>{result.controlState}</dd></div><div><dt className="text-muted">Founder alert</dt><dd>{result.founderAlert ? "Esperada" : "No"}</dd></div><div><dt className="text-muted">WhatsApp Founder externo</dt><dd>{result.externalFounderWhatsApp === "OFF" ? "OFF" : "Payload preparado; no enviado"}</dd></div></dl></div></div>}</section>;
}
