"use client";
import{useState,useTransition}from"react";
import{ArrowDown,ArrowUp,EyeOff,GripVertical,Settings2,Star}from"lucide-react";
import{useRouter}from"next/navigation";
import{Button}from"@/components/ui/button";
import{useModuleManager,type OrbitModuleKey}from"@/features/module-manager";
import{saveFounderWorkspaceAction}from"./actions";
import{QUICK_ACTIONS,WIDGETS,type FounderWorkspacePreferences,type QuickActionKey,type WorkspaceWidgetKey}from"./catalog";

export type WorkspaceValues=Record<WorkspaceWidgetKey,{value:string;detail:string}>;
export function FounderWorkspaceExperience({currentDate,founderName,initialPreferences,pendingTasks,todayEvents,values}:{currentDate:string;founderName:string;initialPreferences:FounderWorkspacePreferences;pendingTasks:number;todayEvents:number;values:WorkspaceValues}){
  const router=useRouter();const{isEnabled}=useModuleManager();const[prefs,setPrefs]=useState(initialPreferences);const[dragged,setDragged]=useState<{kind:"action"|"widget";key:string}|null>(null);const[pending,startTransition]=useTransition();const[message,setMessage]=useState("");
  const persist=(next:FounderWorkspacePreferences)=>{setPrefs(next);startTransition(async()=>{const result=await saveFounderWorkspaceAction(next);setMessage(result.ok?"Escritorio guardado":"No se guardó el cambio. Intenta nuevamente.")})};
  const reorder=<T extends string>(items:T[],source:T,target:T)=>{const next=items.filter(x=>x!==source);next.splice(next.indexOf(target),0,source);return next};
  const move=<T extends string>(items:T[],key:T,direction:-1|1)=>{const index=items.indexOf(key);const target=Math.max(0,Math.min(items.length-1,index+direction));if(index===target)return items;const next=[...items];next.splice(index,1);next.splice(target,0,key);return next};
  const drop=(kind:"action"|"widget",target:string)=>{if(!dragged||dragged.kind!==kind||dragged.key===target)return;persist(kind==="action"?{...prefs,quickActionOrder:reorder(prefs.quickActionOrder,dragged.key as QuickActionKey,target as QuickActionKey)}:{...prefs,widgetOrder:reorder(prefs.widgetOrder,dragged.key as WorkspaceWidgetKey,target as WorkspaceWidgetKey)});setDragged(null)};
  const visibleActions=prefs.quickActionOrder.map(key=>QUICK_ACTIONS.find(item=>item.key===key)!).filter(item=>item&&!prefs.hiddenQuickActions.includes(item.key)&&isEnabled(item.module as OrbitModuleKey)).sort((a,b)=>Number(prefs.favoriteQuickActions.includes(b.key))-Number(prefs.favoriteQuickActions.includes(a.key)));
  const visibleWidgets=prefs.widgetOrder.map(key=>WIDGETS.find(item=>item.key===key)!).filter(item=>item&&!prefs.hiddenWidgets.includes(item.key)&&isEnabled(item.module as OrbitModuleKey));
  const dashboard=prefs.moduleWorkspaces.DASHBOARD;const dashboardSelectors:Record<string,string>={DASHBOARD_HEADER:"#founder-workspace > header",DASHBOARD_QUICK_ACTIONS:"#founder-workspace > section:nth-of-type(1)",DASHBOARD_WIDGETS:"#founder-workspace > section:nth-of-type(2)"};const dashboardCss=dashboard.sectionOrder.map((key,index)=>`${dashboardSelectors[key]}{order:${index};${dashboard.hiddenSections.includes(key)?"display:none;":""}}`).join("");
  return <main className="flex flex-col gap-8" id="founder-workspace"><style>{dashboardCss}</style>
    <header className="rounded-3xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">🏠 Mi Escritorio</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Buenos días, {founderName} 👋</h1><p className="mt-2 text-sm text-muted">{currentDate}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><HeaderMetric label="Eventos de hoy" value={todayEvents}/><HeaderMetric label="Tareas operacionales pendientes" value={pendingTasks}/></div></header>
    <section aria-labelledby="workspace-actions"><WorkspaceTitle id="workspace-actions" title="Acciones rápidas" subtitle="Tus favoritas permanecen primero. Arrastra o usa los controles para cambiar el orden."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{visibleActions.map(item=>{const Icon=item.icon;const favorite=prefs.favoriteQuickActions.includes(item.key);return <article className="group rounded-2xl border bg-card p-4" draggable key={item.key} onDragStart={()=>setDragged({kind:"action",key:item.key})} onDragOver={event=>event.preventDefault()} onDrop={()=>drop("action",item.key)}><button className="flex min-h-16 w-full items-center gap-3 text-left" onClick={()=>router.push(item.href)}><span className="grid size-11 place-items-center rounded-xl bg-brand/10 text-brand"><Icon className="size-5"/></span><span className="flex-1 font-semibold">{item.label}</span><GripVertical className="size-4 text-muted"/></button><div className="mt-3 flex flex-wrap gap-2 border-t pt-3"><OrderButtons down={()=>persist({...prefs,quickActionOrder:move(prefs.quickActionOrder,item.key,1)})} label={item.label} up={()=>persist({...prefs,quickActionOrder:move(prefs.quickActionOrder,item.key,-1)})}/><MiniButton active={favorite} label="Favorito" onClick={()=>persist({...prefs,favoriteQuickActions:favorite?prefs.favoriteQuickActions.filter(key=>key!==item.key):[...prefs.favoriteQuickActions,item.key]})}><Star className="size-3.5"/></MiniButton><MiniButton label="Ocultar" onClick={()=>persist({...prefs,hiddenQuickActions:[...prefs.hiddenQuickActions,item.key]})}><EyeOff className="size-3.5"/></MiniButton></div></article>})}</div></section>
    <section aria-labelledby="workspace-widgets"><WorkspaceTitle id="workspace-widgets" title="Widgets" subtitle="Cada tarjeta conserva su módulo y sus datos; aquí solo controlas presentación."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visibleWidgets.map(item=>{const Icon=item.icon;const data=values[item.key];return <article className="rounded-2xl border bg-card p-4" draggable key={item.key} onDragStart={()=>setDragged({kind:"widget",key:item.key})} onDragOver={event=>event.preventDefault()} onDrop={()=>drop("widget",item.key)}><button className="w-full text-left" onClick={()=>router.push(item.href)}><span className="flex items-center justify-between"><Icon className="size-4 text-brand"/><GripVertical className="size-4 text-muted"/></span><strong className="mt-4 block text-2xl">{data.value}</strong><span className="mt-1 block text-sm font-semibold">{item.label}</span><span className="mt-2 block text-xs text-muted">{data.detail}</span></button><div className="flex flex-wrap gap-2"><OrderButtons down={()=>persist({...prefs,widgetOrder:move(prefs.widgetOrder,item.key,1)})} label={item.label} up={()=>persist({...prefs,widgetOrder:move(prefs.widgetOrder,item.key,-1)})}/><MiniButton label="Ocultar" onClick={()=>persist({...prefs,hiddenWidgets:[...prefs.hiddenWidgets,item.key]})}><EyeOff className="size-3.5"/></MiniButton></div></article>})}</div></section>
    <section className="rounded-2xl border bg-card p-5" id="founder-workspace-settings"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Configuración</p><h2 className="mt-2 text-xl font-semibold">Founder Workspace</h2><p className="mt-1 text-sm text-muted">{pending?"Guardando…":message||"El orden y la visibilidad son personales para esta cuenta."}</p></div><Button onClick={()=>router.push("/settings#founder-workspace")} variant="outline"><Settings2 className="mr-2 size-4"/>Administrar ocultos</Button></div></section>
  </main>;
}
function HeaderMetric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-background/30 p-4"><strong className="text-2xl">{value}</strong><p className="mt-1 text-sm text-muted">{label}</p></div>}
function WorkspaceTitle({id,title,subtitle}:{id:string;title:string;subtitle:string}){return <header className="mb-4"><h2 className="text-xl font-semibold" id={id}>{title}</h2><p className="mt-1 text-sm text-muted">{subtitle}</p></header>}
function MiniButton({active=false,children,label,onClick}:{active?:boolean;children:React.ReactNode;label:string;onClick:()=>void}){return <button className={`mt-3 inline-flex min-h-9 items-center gap-1.5 rounded-lg border px-3 text-xs font-medium ${active?"border-brand/40 text-brand":"text-muted hover:text-foreground"}`} onClick={onClick}>{children}{label}</button>}
function OrderButtons({down,label,up}:{down:()=>void;label:string;up:()=>void}){return <><button aria-label={`Mover ${label} antes`} className="mt-3 grid size-9 place-items-center rounded-lg border text-muted hover:text-foreground" onClick={up}><ArrowUp className="size-3.5"/></button><button aria-label={`Mover ${label} después`} className="mt-3 grid size-9 place-items-center rounded-lg border text-muted hover:text-foreground" onClick={down}><ArrowDown className="size-3.5"/></button></>}
