import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
const read=(path:string)=>readFile(new URL(path,import.meta.url),"utf8");

test("canonical modal locks and restores background scroll",async()=>{const[source,lock]=await Promise.all([read("../components/ui/mobile-dialog.tsx"),read("../components/ui/modal-scroll-lock.ts")]);assert.match(source,/acquireModalScrollLock\(\)/);assert.match(lock,/body\.style\.position="fixed"/);assert.match(lock,/window\.scrollTo\(\{left:current\.x,top:current\.y/);assert.match(source,/event\.target===event\.currentTarget/)});
test("modal owns dynamic viewport, internal scroll and safe footer",async()=>{const source=await read("../components/ui/mobile-dialog.tsx");assert.match(source,/100dvh-env\(safe-area-inset-top\)-env\(safe-area-inset-bottom\)/);assert.match(source,/data-orbit-modal-scroll/);assert.match(source,/overflow-y-auto overscroll-contain/);assert.match(source,/touch-pan-y/);assert.match(source,/data-orbit-modal-footer/);assert.match(source,/safe-area-inset-bottom/)});
test("focus trap, Escape and dialog accessibility remain active",async()=>{const source=await read("../components/ui/mobile-dialog.tsx");assert.match(source,/aria-modal="true"/);assert.match(source,/aria-labelledby/);assert.match(source,/event\.key==="Escape"/);assert.match(source,/event\.key!=="Tab"/)});
test("320x800, 390x844 and 430x932 use one viewport-independent rule",async()=>{const source=await read("../components/ui/mobile-dialog.tsx");for(const viewport of [[320,800],[390,844],[430,932]]){assert.ok(viewport[0]>=320&&viewport[1]>=800);assert.doesNotMatch(source,new RegExp(`${viewport[0]}px|${viewport[1]}px`))}assert.match(source,/w-full flex-col overflow-hidden/)});
test("Event mobile editing exposes schedule and sticky external actions",async()=>{const source=await read("../features/crm/event-center.tsx");assert.match(source,/<MobileDialog/);assert.match(source,/mobile-event-editor/);assert.match(source,/\["time","Hora"/);assert.match(source,/form="mobile-event-editor"/)});
test("Customer mobile editing keeps edit permission surface and save cancel",async()=>{const source=await read("../features/crm/customer-profile.tsx");assert.match(source,/Editar cliente/);assert.match(source,/sticky bottom-0/);assert.match(source,/>Cancelar</);assert.match(source,/Guardar/)});
test("review details uses canonical internal scrolling",async()=>{const source=await read("../features/portal-authentication/staff-portal-dashboard.tsx");assert.match(source,/<MobileDialog[\s\S]*title="Resumen operacional completo"/)});
test("presentation fix preserves existing actions and performs no data access",async()=>{const[customer,event,dialog]=await Promise.all([read("../features/crm/customer-profile.tsx"),read("../features/crm/event-center.tsx"),read("../components/ui/mobile-dialog.tsx")]);assert.match(customer,/updateCrmCustomerAction/);assert.match(event,/updateCrmEventAction/);assert.doesNotMatch(dialog,/supabase|insert\(|update\(|delete\(/i)});
