import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
const read=(path:string)=>readFile(new URL(path,import.meta.url),"utf8");

test("wizard steps 1-7 share one complete internal scroll region",async()=>{const source=await read("../features/projects/components/new-project-drawer.tsx");assert.match(source,/data-reservation-wizard-scroll/);assert.match(source,/min-h-0 flex-1 overflow-y-auto overscroll-contain/);assert.match(source,/Paso \{step \+ 1\} de \{steps\.length\}/);assert.match(source,/steps\.map/)});
test("reservation summary never overlays forms below desktop breakpoint",async()=>{const[source,css]=await Promise.all([read("../features/projects/components/new-project-drawer.tsx"),read("../app/globals.css")]);assert.doesNotMatch(source,/max-lg:sticky max-lg:bottom-0/);assert.match(source,/h-fit lg:sticky lg:top-0/);assert.match(css,/@media \(min-width: 48rem\) and \(max-width: 63\.99rem\)[\s\S]*position: static !important/)});
test("desktop and mobile actions reserve layout and safe area",async()=>{const source=await read("../features/projects/components/new-project-drawer.tsx");assert.match(source,/data-reservation-wizard-actions/);assert.match(source,/shrink-0[\s\S]*safe-area-inset-bottom/);for(const size of [[1366,768],[1440,900],[1920,1080],[320,800],[390,844],[430,932]])assert.ok(size[0]>=320&&size[1]>=768)});
test("corporate 30-day credit emits one active receivable with canonical due-date trigger",async()=>{const[action,migration]=await Promise.all([read("../features/projects/actions/customer.actions.ts"),read("../supabase/migrations/0176_empresa_credit_receivable_integrity.sql")]);assert.match(action,/sync_project_receivable_terms/);assert.match(migration,/when 30 then 'DAYS_30'/);assert.match(migration,/issue_date=coalesce\(issue_date,current_date\)/);assert.match(migration,/invoices_one_active_receivable_per_project_uq/)});
test("corporate custom terms remain supported and missing terms are rejected",async()=>{const migration=await read("../supabase/migrations/0176_empresa_credit_receivable_integrity.sql");assert.match(migration,/term_days>0 then 'CUSTOM'/);assert.match(migration,/custom_term_days=case[\s\S]*invoice_term='CUSTOM'/);assert.match(migration,/requiere un plazo positivo/)});
test("optional receipt does not block corporate reservation",async()=>{const wizard=await read("../features/projects/components/new-project-drawer.tsx");assert.match(wizard,/!paymentReceiptRequired \|\|[\s\S]*Boolean\(receipt\)/);assert.match(wizard,/required=\{paymentReceiptRequired\}/)});
test("0151 removes nonexistent quotation total while preserving function signature and grants",async()=>{const sql=await read("../supabase/migrations/0151_manual_corporate_receivable_retry_fix.sql");assert.match(sql,/create or replace function public\.sync_project_commercial_state\(p_project_id uuid\)/);assert.doesNotMatch(sql,/q\.total/);assert.match(sql,/q\.final_customer_price, q\.grand_total, 0/);assert.match(sql,/grant execute[\s\S]*authenticated,service_role/)});
test("failed AR retry remains idempotent without creating a parallel FAC receivable",async()=>{const[action,wizard,migration]=await Promise.all([read("../features/projects/actions/customer.actions.ts"),read("../features/projects/components/new-project-drawer.tsx"),read("../supabase/migrations/0176_empresa_credit_receivable_integrity.sql")]);assert.doesNotMatch(action,/invoiceNumber = `FAC-/);assert.match(action,/sync_project_receivable_terms/);assert.match(migration,/invoices_one_active_receivable_per_project_uq/);assert.match(action,/createWithProject\(draft\)/);assert.match(wizard,/manualReservationDraftKey/);assert.match(wizard,/reservationTransactionId/)});
test("0151 installation performs no reservation repair",async()=>{const sql=await read("../supabase/migrations/0151_manual_corporate_receivable_retry_fix.sql");const top=sql.replace(/\$\$[\s\S]*?\$\$/g,"FUNCTION_BODY");assert.doesNotMatch(top,/insert into|delete from|update public\.(projects|invoices|quotations)/i)});
