import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
const read=(path:string)=>readFile(new URL(path,import.meta.url),"utf8");

test("wizard steps 1-7 share one complete internal scroll region",async()=>{const source=await read("../features/projects/components/new-project-drawer.tsx");assert.match(source,/data-reservation-wizard-scroll/);assert.match(source,/min-h-0 flex-1 overflow-y-auto overscroll-contain/);assert.match(source,/Paso \{step \+ 1\} de \{steps\.length\}/);assert.match(source,/steps\.map/)});
test("reservation summary never overlays forms below desktop breakpoint",async()=>{const[source,css]=await Promise.all([read("../features/projects/components/new-project-drawer.tsx"),read("../app/globals.css")]);assert.doesNotMatch(source,/max-lg:sticky max-lg:bottom-0/);assert.match(source,/h-fit lg:sticky lg:top-0/);assert.match(css,/@media \(min-width: 48rem\) and \(max-width: 63\.99rem\)[\s\S]*position: static !important/)});
test("desktop and mobile actions reserve layout and safe area",async()=>{const source=await read("../features/projects/components/new-project-drawer.tsx");assert.match(source,/data-reservation-wizard-actions/);assert.match(source,/shrink-0[\s\S]*safe-area-inset-bottom/);for(const size of [[1366,768],[1440,900],[1920,1080],[320,800],[390,844],[430,932]])assert.ok(size[0]>=320&&size[1]>=768)});
test("corporate 30-day credit emits an active receivable with canonical due-date trigger",async()=>{const action=await read("../features/projects/actions/customer.actions.ts");assert.match(action,/paymentCondition === "CORPORATE_CREDIT"/);assert.match(action,/status: corporateCredit \? "ISSUED" : "DRAFT"/);assert.match(action,/issue_date: corporateCredit \? issueDate : null/);assert.match(action,/termDays === 30[\s\S]*"DAYS_30"/)});
test("corporate custom and missing terms remain supported without parallel classification",async()=>{const action=await read("../features/projects/actions/customer.actions.ts");assert.match(action,/termDays > 0[\s\S]*"CUSTOM"[\s\S]*"CASH"/);assert.match(action,/custom_term_days:[\s\S]*paymentTerm === "CUSTOM"/);assert.match(action,/projects[\s\S]*finance/)});
test("optional receipt does not block corporate reservation",async()=>{const wizard=await read("../features/projects/components/new-project-drawer.tsx");assert.match(wizard,/!paymentReceiptRequired \|\|[\s\S]*Boolean\(receipt\)/);assert.match(wizard,/required=\{paymentReceiptRequired\}/)});
test("0151 removes nonexistent quotation total while preserving function signature and grants",async()=>{const sql=await read("../supabase/migrations/0151_manual_corporate_receivable_retry_fix.sql");assert.match(sql,/create or replace function public\.sync_project_commercial_state\(p_project_id uuid\)/);assert.doesNotMatch(sql,/q\.total/);assert.match(sql,/q\.final_customer_price, q\.grand_total, 0/);assert.match(sql,/grant execute[\s\S]*authenticated,service_role/)});
test("failed AR retry remains idempotent and draft-preserving",async()=>{const[action,wizard]=await Promise.all([read("../features/projects/actions/customer.actions.ts"),read("../features/projects/components/new-project-drawer.tsx")]);assert.match(action,/invoiceNumber = `FAC-/);assert.match(action,/upsert\([\s\S]*onConflict: "invoice_number"/);assert.match(action,/createWithProject\(draft\)/);assert.match(wizard,/manualReservationDraftKey/);assert.match(wizard,/reservationTransactionId/);assert.match(action,/reference/)});
test("0151 installation performs no reservation repair",async()=>{const sql=await read("../supabase/migrations/0151_manual_corporate_receivable_retry_fix.sql");const top=sql.replace(/\$\$[\s\S]*?\$\$/g,"FUNCTION_BODY");assert.doesNotMatch(top,/insert into|delete from|update public\.(projects|invoices|quotations)/i)});
