import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const migration = read("supabase/migrations/0192_wedding_due_date_and_document_navigation.sql");
const viewer = read("components/documents/orbit-document-viewer.tsx");
const hub = read("features/external-tax-documents/event-commercial-document-hub.tsx");
const oc = read("features/commercial-documents/customer-purchase-order-center.tsx");
const sii = read("features/external-tax-documents/external-tax-documents-center.tsx");
const ledger = read("features/accounts-receivable/event-payment-manager.tsx");
const crm = read("features/crm/customer-event-operations.tsx");
const collection = read("features/accounts-receivable/accounts-receivable-center.tsx");
const backfill = migration.slice(migration.indexOf("-- Reconcile every active Production Wedding"));

test("Matrimonio is selected by canonical Event type", () => assert.match(migration, /project_type,''\)\)='WEDDING'/));
test("Wedding balance is due on the Event date", () => assert.match(migration, /new\.due_date=wedding_date/));
test("Wedding due-date origin is persisted", () => assert.match(migration, /due_date_source='EVENT_DATE'/));
test("explicitly agreed dates override the Event default", () => assert.match(migration, /due_date_source<>'EXPLICIT'/));
test("manual Founder due-date edits become explicit", () => assert.match(migration, /due_date=p_due_date,due_date_source='EXPLICIT'/));
test("Event date changes resynchronize the shared receivable", () => assert.match(migration, /new\.event_date is distinct from old\.event_date/));
test("Event type changes resynchronize the shared receivable", () => assert.match(migration, /new\.project_type is distinct from old\.project_type/));
test("corporate credit terms remain independent", () => assert.match(migration, /condition='CORPORATE_CREDIT'/));
test("custom corporate terms remain supported", () => assert.match(migration, /invoice_term='CUSTOM'/));
test("backfill only targets active Production receivables", () => assert.match(backfill, /financial_record_state='ACTIVE'[\s\S]*record_origin='PRODUCTION'/));
test("backfill excludes cancelled and archived Events", () => assert.match(backfill, /not in\('CANCELLED','CANCELED','ARCHIVED'\)/));
test("backfill does not change the Payment Ledger", () => assert.doesNotMatch(backfill, /update public\.invoice_payments|insert into public\.invoice_payments/));
test("backfill does not rewrite paid amounts", () => assert.doesNotMatch(backfill, /paid_amount\s*=/));
test("backfill does not rewrite accepted quotation snapshots", () => assert.doesNotMatch(backfill, /accepted_snapshot\s*=|update public\.quotations/));
test("migration has no record-specific UUID conditions", () => assert.doesNotMatch(migration, /[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i));
test("shared viewer is rendered through a top-level portal", () => assert.match(viewer, /createPortal\([\s\S]*document\.body/));
test("shared viewer has an always-visible close action", () => assert.match(viewer, /aria-label="Cerrar y volver al Evento"/));
test("shared viewer has an explicit return action", () => assert.match(viewer, /Volver al Evento/));
test("shared viewer supports keyboard close", () => assert.match(viewer, /event\.key === "Escape"/));
test("shared viewer locks background scrolling", () => assert.match(viewer, /document\.body\.style\.overflow = "hidden"/));
test("shared viewer is mobile viewport and safe-area aware", () => { assert.match(viewer, /h-\[100dvh\]/); assert.match(viewer, /safe-area-inset-top/); });
test("shared viewer keeps protected documents inside ORBIT", () => assert.match(viewer, /<iframe[\s\S]*src=\{src\}/));
test("Event contract and Quote use the shared viewer", () => { assert.match(hub, /OrbitDocumentViewer/); assert.match(hub, /Contrato del Evento/); assert.match(hub, /Cotización/); });
test("OC and SII documents use the Event viewer callback", () => { assert.match(oc, /onPreview/); assert.match(sii, /onPreview/); });
test("payment receipts use the shared viewer", () => assert.match(ledger, /OrbitDocumentViewer/));
test("CRM protected documents use the shared viewer", () => assert.match(crm, /OrbitDocumentViewer/));
test("Accounts Receivable contracts use the shared viewer", () => assert.match(collection, /OrbitDocumentViewer/));
test("document API routes and signed URL actions remain canonical", () => { assert.match(hub, /pdfHref/); assert.match(crm, /getCrmDocumentUrlAction/); assert.match(ledger, /getReceivableReceiptUrlAction/); });
