"use client";

import { type ElementType } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowRight, Calculator, CircleArrowDown, CircleArrowUp, CircleDollarSign, Download, Landmark, Plus, ReceiptText, TrendingUp, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";

const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
export interface FinancialDashboardData { monthlyRevenue:number;monthlyExpenses:number;accountsReceivable:number;accountsPayable:number;projectedCashFlow:number;grossMargin:number;netMargin:number;projectedVat:number;overdueAccounts:number;upcomingPayments:number;upcomingCollections:number;expenses:readonly {id:string;supplier:string;date:string;total:number;status:string}[] }

export function FinancialDashboard({data}:{data:FinancialDashboardData}) {
  const router=useRouter();
  const kpis=[
    {label:"Ingresos del mes",value:data.monthlyRevenue,icon:CircleArrowUp,href:"/reports?period=month&metric=revenue",detail:"Abrir detalle de ventas"},
    {label:"Gastos del mes",value:data.monthlyExpenses,icon:CircleArrowDown,href:"/finance/expenses",detail:"Abrir centro de gastos"},
    {label:"Cuentas por cobrar",value:data.accountsReceivable,icon:WalletCards,href:"/finance/receivables?status=outstanding",detail:"Revisar saldos pendientes"},
    {label:"Cuentas por pagar",value:data.accountsPayable,icon:ReceiptText,href:"#accounts-payable",detail:"Revisar compromisos con proveedores"},
    {label:"Flujo de caja proyectado",value:data.projectedCashFlow,icon:Landmark,href:"/finance/cash-flow",detail:"Abrir Cash Flow Center"},
    {label:"Margen bruto",value:data.grossMargin,icon:TrendingUp,href:"#profitability",detail:"Abrir rentabilidad"},
    {label:"Margen neto",value:data.netMargin,icon:CircleDollarSign,href:"#profitability",detail:"Abrir rentabilidad"},
    {label:"IVA proyectado",value:data.projectedVat,icon:Calculator,href:"#tax-summary",detail:"Abrir resumen tributario"},
  ] as const;
  const go=(href:string)=>href.startsWith("#")?document.querySelector(href)?.scrollIntoView({behavior:"smooth",block:"start"}):router.push(href);
  const exportCsv=()=>{const rows=[["Indicador","Monto CLP"],["Ingresos del mes",data.monthlyRevenue],["Gastos del mes",data.monthlyExpenses],["Cuentas por cobrar",data.accountsReceivable],["Cuentas por pagar",data.accountsPayable],["Flujo de caja proyectado",data.projectedCashFlow],["Margen bruto",data.grossMargin],["Margen neto",data.netMargin],["IVA proyectado",data.projectedVat],[],["Proveedor","Fecha","Total","Estado"],...data.expenses.map((expense)=>[expense.supplier,expense.date,expense.total,expense.status])];const csv=rows.map((row)=>row.map((cell)=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));link.download=`orbit-finanzas-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);};
  return <>
    <section className="space-y-6"><header className="rounded-3xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Finanzas · Control operacional</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Dashboard Financiero</h1><p className="mt-3 max-w-2xl text-sm text-muted sm:text-base">Ingresos, obligaciones, caja y márgenes de BOOMBOX en una sola lectura.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Button className="min-h-12" onClick={()=>router.push("/finance/expenses?create=1")}><Plus className="size-4"/>Nuevo gasto</Button><Button className="min-h-12" onClick={()=>router.push("/finance/receivables#invoices")} variant="outline"><Plus className="size-4"/>Nuevo ingreso</Button><Button className="min-h-12" onClick={exportCsv} variant="outline"><Download className="size-4"/>Exportar para contador</Button></div></header>
      <section aria-label="Indicadores financieros" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({label,value,icon:Icon,href,detail})=><button className="group rounded-2xl border bg-card p-5 text-left transition hover:border-brand/50 hover:bg-brand/[.03] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand" key={label} onClick={()=>go(href)}><span className="flex items-center justify-between"><Icon className="size-5 text-brand"/><ArrowRight className="size-4 text-muted transition group-hover:translate-x-1"/></span><strong className="mt-5 block text-2xl tracking-tight">{money.format(value)}</strong><span className="mt-1 block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted">{detail}</span></button>)}</section>
      <section aria-labelledby="financial-alerts" className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Atención financiera</p><h2 className="mt-1 text-2xl font-semibold" id="financial-alerts">Alertas</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Alert label="Cuentas vencidas" value={data.overdueAccounts} icon={AlertTriangle} onClick={()=>router.push("/finance/receivables?status=overdue")}/><Alert label="Pagos próximos" value={data.upcomingPayments} icon={CircleArrowDown} onClick={()=>go("#accounts-payable")}/><Alert label="Cobros próximos" value={data.upcomingCollections} icon={CircleArrowUp} onClick={()=>router.push("/finance/receivables?status=upcoming")}/><Alert label="IVA proyectado" value={data.projectedVat} icon={Calculator} onClick={()=>go("#tax-summary")}/></div></section>
      <section className="grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border bg-card p-5 lg:col-span-2" id="expense-center"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-brand">Gastos</p><h2 className="mt-1 text-xl font-semibold">Centro de gastos</h2></div><Button onClick={()=>router.push("/finance/expenses?create=1")}><Plus className="size-4"/>Nuevo gasto</Button></div><div className="mt-5 divide-y">{data.expenses.slice(0,8).map((expense)=><div className="grid grid-cols-[1fr_auto] gap-3 py-3 text-sm" key={expense.id}><div><p className="font-medium">{expense.supplier}</p><p className="mt-1 text-xs text-muted">{expense.date} · {expense.status}</p></div><strong>{money.format(expense.total)}</strong></div>)}{!data.expenses.length&&<p className="py-6 text-sm text-muted">Los gastos registrados aparecerán aquí.</p>}</div><Button className="mt-4 w-full" onClick={()=>router.push("/finance/expenses")} variant="outline">Abrir Centro de Gastos<ArrowRight className="size-4"/></Button></article><div className="space-y-4"><Summary id="accounts-payable" label="Cuentas por pagar" value={data.accountsPayable} detail="Obligaciones pendientes con proveedores."/><button className="w-full rounded-2xl border bg-card p-5 text-left transition hover:border-brand" onClick={()=>router.push("/finance/cash-flow")}><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted">Caja proyectada</p><p className="mt-2 text-2xl font-semibold text-brand">{money.format(data.projectedCashFlow)}</p><p className="mt-2 text-sm text-muted">Abrir proyección y detalle de movimientos.</p></button><Summary id="tax-summary" label="Resumen tributario" value={data.projectedVat} detail="IVA débito menos IVA crédito registrado."/></div></section>
    </section>
  </>;
}

function Alert({icon:Icon,label,onClick,value}:{icon:ElementType;label:string;onClick:()=>void;value:number}){return <button className="rounded-2xl border bg-card p-4 text-left transition hover:border-brand" onClick={onClick}><span className="flex items-center justify-between"><Icon className="size-4 text-brand"/><ArrowRight className="size-3.5 text-muted"/></span><strong className="mt-4 block text-xl">{money.format(value)}</strong><span className="mt-1 block text-sm">{label}</span></button>}
function Summary({detail,id,label,value}:{detail:string;id:string;label:string;value:number}){return <article className="scroll-mt-24 rounded-2xl border bg-card p-5" id={id}><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted">{label}</p><p className="mt-2 text-2xl font-semibold text-brand">{money.format(value)}</p><p className="mt-2 text-sm text-muted">{detail}</p></article>}
