/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type WeekEvent = { id:string; name:string|null; eventDate:string; startTime:string|null; customer:string; service:string; address:string; reservation:string; operator:string; readiness:string; href:string };

export default async function OperationsWeekPage() {
  const client = await createSupabaseServerClient();
  const { data: auth, error: authError } = await client.auth.getUser();
  if (authError || !auth.user) throw authError ?? new Error("Sesión requerida.");
  const today = new Date(); today.setHours(0,0,0,0);
  const end = new Date(today); end.setDate(end.getDate()+7);
  const { data, error } = await client.from("projects").select("id,name,event_date,start_time,venue,address,city,status,customers(full_name,phone),project_services(service_code),crm_reservations(status),operations").gte("event_date",today.toISOString().slice(0,10)).lt("event_date",end.toISOString().slice(0,10)).is("deleted_at",null).order("event_date",{ascending:true});
  if (error) throw error;
  const events: WeekEvent[] = (data??[]).map((row:any)=>{
    const customer=Array.isArray(row.customers)?row.customers[0]:row.customers; const reservation=Array.isArray(row.crm_reservations)?row.crm_reservations[0]:row.crm_reservations; const service=Array.isArray(row.project_services)?row.project_services[0]:row.project_services; const op=row.operations??{};
    const missing=[!row.address&&!row.venue,!service?.service_code,!customer?.phone,!op.operatorId||!op.operatorName];
    return {id:row.id,name:row.name,eventDate:row.event_date,startTime:row.start_time,customer:customer?.full_name??"Cliente sin nombre",service:service?.service_code??"Servicio pendiente",address:row.address??row.venue??row.city??"Dirección pendiente",reservation:reservation?.status??"Sin reserva",operator:op.operatorName??"Operador pendiente",readiness:missing.filter(Boolean).length>=2?"CRÍTICO":missing.some(Boolean)?"ATENCIÓN":"LISTO",href:`/projects/${row.id}`};
  });
  const groups=[{label:"HOY",items:events.filter(e=>e.eventDate===today.toISOString().slice(0,10))},{label:"MAÑANA",items:events.filter(e=>e.eventDate===new Date(today.getTime()+86400000).toISOString().slice(0,10))},{label:"PRÓXIMOS 7 DÍAS",items:events.filter(e=>![today.toISOString().slice(0,10),new Date(today.getTime()+86400000).toISOString().slice(0,10)].includes(e.eventDate))}];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-widest text-brand">Agenda operacional</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Semana de eventos</h1><p className="mt-2 text-sm text-muted">Qué ocurre esta semana y qué falta para ejecutar cada evento sin errores.</p></header><nav className="flex flex-wrap gap-2"><Link className="min-h-11 rounded-xl border px-4 py-3 text-sm font-semibold text-brand" href="/operations">Volver a Operations</Link><Link className="min-h-11 rounded-xl border px-4 py-3 text-sm font-semibold text-brand" href="/events">Ver calendario completo</Link></nav>{error?<p className="rounded-xl border border-danger/30 bg-danger/5 p-4 text-sm">No fue posible cargar la agenda operacional.</p>:groups.map(group=><section aria-labelledby={group.label} className="space-y-3" key={group.label}><h2 className="text-sm font-bold uppercase tracking-widest" id={group.label}>{group.label} <span className="text-muted">· {group.items.length}</span></h2>{group.items.length?group.items.map(event=><Link className="block rounded-2xl border bg-card p-4 transition hover:border-brand/40 sm:p-5" href={event.href} key={event.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{event.name??"Evento sin nombre"}</h3><p className="mt-1 text-sm text-muted">{event.eventDate} {event.startTime??"· hora pendiente"} · {event.customer}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${event.readiness==="CRÍTICO"?"bg-danger-soft text-danger":event.readiness==="ATENCIÓN"?"bg-warning-soft text-warning":"bg-success-soft text-success"}`}>{event.readiness}</span></div><div className="mt-4 grid gap-2 text-xs text-muted sm:grid-cols-2 lg:grid-cols-4"><span>Servicio: <strong className="text-foreground">{event.service}</strong></span><span>Dirección: <strong className="text-foreground">{event.address}</strong></span><span>Reserva: <strong className="text-foreground">{event.reservation}</strong></span><span>Operador: <strong className="text-foreground">{event.operator}</strong></span></div></Link>):<p className="rounded-xl border border-dashed p-4 text-sm text-muted">No hay eventos en este período.</p>}</section>)}</main>;
}
