/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { reminderProjection } from "@/features/operations-agenda-v11/domain";

type WeekEvent = { id:string; name:string|null; eventDate:string; startTime:string|null; customer:string; service:string; address:string; reservation:string; operator:string; readiness:string; checklist:string; reminder:string; reminderAttempt:string|null; reminderError:string|null; staffStatus:string; resourcesStatus:string; resourceDetails:string[]; href:string };

export default async function OperationsWeekPage() {
  const client = await createSupabaseServerClient();
  const { data: auth, error: authError } = await client.auth.getUser();
  if (authError || !auth.user) throw authError ?? new Error("Sesión requerida.");
  await client.rpc("reconcile_operational_agenda_alerts");
  const today = new Date(); today.setHours(0,0,0,0);
  const end = new Date(today); end.setDate(end.getDate()+7);
  const { data, error } = await client.from("projects").select("id,name,event_date,event_time,location,city,status,customers(full_name,phone),project_services(service_code),crm_reservations(status),operations,event_checklists(status,event_checklist_items(completed,mandatory))").gte("event_date",today.toISOString().slice(0,10)).lt("event_date",end.toISOString().slice(0,10)).is("deleted_at",null).order("event_date",{ascending:true});
  if (error) throw error;
  const ids=(data??[]).map((row:any)=>row.id); const assignmentsResult=ids.length?await client.from("assignments").select("project_id,staff_id,status,start_time,finish_time,staff(first_name,last_name),resources").in("project_id",ids).is("deleted_at",null).not("status","in","(CANCELLED,REJECTED)"):null; const assignments=assignmentsResult?.data??[]; const requirementsResult=ids.length?await client.from("event_operational_requirements").select("id,project_id,label,required_quantity,assigned_quantity,requirement_type,asset_type,status").in("project_id",ids).eq("status","ACTIVE"):null; const requirements=requirementsResult?.data??[]; const physicalAssignmentsResult=ids.length?await client.from("asset_assignments").select("project_id,operational_requirement_id,asset_id,assignment_status,planned_start_at,planned_end_at,operational_assets(asset_code,asset_type,status)").in("project_id",ids).eq("assignment_status","ASSIGNED").is("deleted_at",null):null; const physicalAssignments=physicalAssignmentsResult?.data??[]; const reminderResult=ids.length?await client.from("communications").select("project_id,status,occurred_at,failure_reason").in("project_id",ids).eq("communication_type","PRE_EVENT_REMINDER").order("occurred_at",{ascending:false}):null; const reminders=reminderResult?.data??[];
  const events: WeekEvent[] = (data??[]).map((row:any)=>{
    const customer=Array.isArray(row.customers)?row.customers[0]:row.customers; const reservation=Array.isArray(row.crm_reservations)?row.crm_reservations[0]:row.crm_reservations; const service=Array.isArray(row.project_services)?row.project_services[0]:row.project_services; const op=row.operations??{}; const venue=typeof op.venueName==="string"?op.venueName:typeof op.venue==="string"?op.venue:null; const eventAssignments=assignments.filter((item:any)=>item.project_id===row.id); const operatorAssignment=eventAssignments.find((item:any)=>String(item.assignment_type??"").toUpperCase().includes("OPERATOR")); const operator=Array.isArray(operatorAssignment?.staff)?operatorAssignment.staff[0]:operatorAssignment?.staff; const staffWindows=eventAssignments.map((item:any)=>({id:item.staff_id,start:item.start_time??(row.event_date&&row.event_time?`${row.event_date}T${row.event_time}`:null),end:item.finish_time})); const hasStaffConflict=staffWindows.some((a:any,i:number)=>staffWindows.slice(i+1).some((b:any)=>a.id===b.id&&a.start&&a.end&&b.start&&b.end&&new Date(a.start)<new Date(b.end)&&new Date(b.start)<new Date(a.end))); const staffStatus=eventAssignments.length===0||staffWindows.some((x:any)=>!x.start||!x.end)?"NO VERIFICABLE":hasStaffConflict?"CONFLICTO":"OK";
    const missing=[!row.location&&!venue,!service?.service_code,!customer?.phone,!operatorAssignment];
    const checklist=Array.isArray(row.event_checklists)?row.event_checklists[0]:row.event_checklists; const checklistItems=checklist?.event_checklist_items??[]; const checklistDone=checklistItems.filter((item:any)=>item.completed).length; const checklistTotal=checklistItems.filter((item:any)=>item.mandatory).length;
    const reminder=reminderProjection(reminders.filter((item:any)=>item.project_id===row.id));
    const eventRequirements=requirements.filter((item:any)=>item.project_id===row.id && item.requirement_type==="PHYSICAL_UNIT"); const eventPhysicalAssignments=physicalAssignments.filter((item:any)=>item.project_id===row.id); const resourcesStatus=eventRequirements.length===0?"NO VERIFICABLE":eventPhysicalAssignments.some((item:any)=>["MAINTENANCE","OUT_OF_SERVICE"].includes(String((Array.isArray(item.operational_assets)?item.operational_assets[0]:item.operational_assets)?.status)))?"CONFLICTO":eventRequirements.some((item:any)=>Number(item.assigned_quantity??0)<Number(item.required_quantity??0))?"INCOMPLETO":"OK"; const resourceDetails=eventPhysicalAssignments.map((item:any)=>{const asset=Array.isArray(item.operational_assets)?item.operational_assets[0]:item.operational_assets;return asset?`${asset.asset_code} · ${asset.asset_type} · ${asset.status}`:"Activo sin datos";}); const readiness=staffStatus==="CONFLICTO"||resourcesStatus==="CONFLICTO"||["ERROR","BLOQUEADO"].includes(reminder.status)?"CRÍTICO":missing.filter(Boolean).length>=2||resourcesStatus==="INCOMPLETO"?"CRÍTICO":missing.some(Boolean)||resourcesStatus==="NO VERIFICABLE"||reminder.status==="PENDIENTE"?"ATENCIÓN":"LISTO";
    return {id:row.id,name:row.name,eventDate:row.event_date,startTime:row.event_time,customer:customer?.full_name??"Cliente sin nombre",service:service?.service_code??"Servicio pendiente",address:row.location??venue??row.city??"Dirección pendiente",reservation:reservation?.status??"Sin reserva",operator:operator?.first_name?`${operator.first_name} ${operator.last_name??""}`:"Operador pendiente",readiness,href:`/projects/${row.id}`,checklist:`${checklistDone}/${checklistTotal||0}`,reminder:reminder.status,reminderAttempt:reminder.lastAttemptAt,reminderError:reminder.error,staffStatus,resourcesStatus,resourceDetails};
  });
  const groups=[{label:"HOY",items:events.filter(e=>e.eventDate===today.toISOString().slice(0,10))},{label:"MAÑANA",items:events.filter(e=>e.eventDate===new Date(today.getTime()+86400000).toISOString().slice(0,10))},{label:"PRÓXIMOS 7 DÍAS",items:events.filter(e=>![today.toISOString().slice(0,10),new Date(today.getTime()+86400000).toISOString().slice(0,10)].includes(e.eventDate))}];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-widest text-brand">Agenda operacional</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Semana de eventos</h1><p className="mt-2 text-sm text-muted">Qué ocurre esta semana y qué falta para ejecutar cada evento sin errores.</p></header><nav className="flex flex-wrap gap-2"><Link className="min-h-11 rounded-xl border px-4 py-3 text-sm font-semibold text-brand" href="/operations">Volver a Operations</Link><Link className="min-h-11 rounded-xl border px-4 py-3 text-sm font-semibold text-brand" href="/events">Ver calendario completo</Link></nav>{error?<p className="rounded-xl border border-danger/30 bg-danger/5 p-4 text-sm">No fue posible cargar la agenda operacional.</p>:groups.map(group=><section aria-labelledby={group.label} className="space-y-3" key={group.label}><h2 className="text-sm font-bold uppercase tracking-widest" id={group.label}>{group.label} <span className="text-muted">· {group.items.length}</span></h2>{group.items.length?group.items.map(event=><Link className="block rounded-2xl border bg-card p-4 transition hover:border-brand/40 sm:p-5" href={event.href} key={event.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{event.name??"Evento sin nombre"}</h3><p className="mt-1 text-sm text-muted">{event.eventDate} {event.startTime??"· hora pendiente"} · {event.customer}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${event.readiness==="CRÍTICO"?"bg-danger-soft text-danger":event.readiness==="ATENCIÓN"?"bg-warning-soft text-warning":"bg-success-soft text-success"}`}>{event.readiness}</span></div><div className="mt-4 grid gap-2 text-xs text-muted sm:grid-cols-2 lg:grid-cols-4"><span>Servicio: <strong className="text-foreground">{event.service}</strong></span><span>Dirección: <strong className="text-foreground">{event.address}</strong></span><span>Reserva: <strong className="text-foreground">{event.reservation}</strong></span><span>Operador: <strong className="text-foreground">{event.operator}</strong></span><span>Staff: <strong className="text-foreground">{event.staffStatus}</strong></span><span>Recursos: <strong className="text-foreground">{event.resourcesStatus}</strong>{event.resourceDetails.length?<small className="block">{event.resourceDetails.join(", ")}</small>:null}</span><span>Reminder: <strong className="text-foreground">{event.reminder}</strong>{event.reminderAttempt?<small className="ml-1">· {event.reminderAttempt}</small>:null}{event.reminderError?<small className="block text-danger">{event.reminderError}</small>:null}</span></div></Link>):<p className="rounded-xl border border-dashed p-4 text-sm text-muted">No hay eventos en este período.</p>}</section>)}</main>;
}
