import { CashFlowCenter, type CashFlowTransaction } from "@/features/cash-flow";
import { createSupabaseServerClient } from "@/lib/supabase/server";

function relation<T>(value:unknown):T|undefined{return Array.isArray(value)?value[0]as T|undefined:value as T|undefined}

export default async function CashFlowPage(){
  const client=await createSupabaseServerClient();
  const[paymentsResult,invoicesResult,expensesResult,staffEventsResult,staffFinancialsResult,blockCostsResult,fuelResult,vehiclesResult,officeRentResult,reimbursementPaymentsResult]=await Promise.all([
    client.from("invoice_payments").select("id,invoice_id,amount,paid_at,method,reference").order("paid_at",{ascending:false}),
    client.from("accounts_receivable_projection").select("id,invoice_number,project_id,customer_id,customer_type,due_date,amount,paid_amount,outstanding_balance,effective_status,customers(full_name),projects(name)"),
    client.from("expenses").select("id,occurred_on,category,supplier,total,status,receipt_path,approval_reason,event_staff_settlement_id").is("deleted_at",null).order("occurred_on",{ascending:false}),
    client.from("event_staff_payments").select("id,project_id,staff_id,total_internal_payment,paid_amount,paid_at,settlement_status,status,projects!inner(event_date),staff(first_name,last_name)").is("deleted_at",null).eq("status","CONFIRMED").gt("total_internal_payment",0),
    client.from("staff_settlement_financials").select("settlement_id,payroll_net,payroll_paid_amount,reimbursement_pending_amount,remaining_balance"),
    client.from("event_staff_block_costs").select("id,project_id,block_id,staff_id,role,amount,duration_minutes,status,event_operational_blocks(name,start_at,end_at),projects!inner(name,event_date,orbit_event_id),staff(first_name,last_name)").eq("status","RESOLVED").order("created_at",{ascending:false}),
    client.from("vehicle_fuel_logs").select("id,asset_id,fuel_date,total_amount,receipt_path,gas_station"),
    client.from("vehicle_profiles").select("asset_id,model"),
    client.from("office_lease_income_items").select("id,item_type,description,amount,office_lease_payments(id,paid_on,payment_method,receipt_number,office_lease_obligations(period,office_lease_settings(concept,tenant_legal_name)))").order("created_at",{ascending:false}),
    client.from("staff_reimbursement_payments").select("id,project_id,staff_id,amount,paid_on,method,projects(name),staff(first_name,last_name)").order("paid_on",{ascending:false}),
  ]);
  const error=paymentsResult.error??invoicesResult.error??expensesResult.error??staffEventsResult.error??staffFinancialsResult.error??blockCostsResult.error??fuelResult.error??vehiclesResult.error??officeRentResult.error??reimbursementPaymentsResult.error;if(error)throw error;
  const transactions:CashFlowTransaction[]=[];const invoices=new Map((invoicesResult.data??[]).map(item=>[item.id,item]));
  for(const payment of paymentsResult.data??[]){const invoice=invoices.get(payment.invoice_id);const customer=relation<{full_name?:string}>(invoice?.customers);const project=relation<{name?:string}>(invoice?.projects);transactions.push({id:payment.id,kind:"INCOMING",date:payment.paid_at.slice(0,10),amount:Number(payment.amount),title:invoice?.customer_type==="CORPORATE"?"Pago corporativo":"Pago de reserva",detail:[invoice?.invoice_number,customer?.full_name,project?.name].filter(Boolean).join(" · ")||"Ingreso registrado",href:"/finance/receivables",source:payment.method||"Ingreso manual"});}
  const expenseReceipts=new Set((expensesResult.data??[]).map(item=>item.receipt_path).filter(Boolean));
  for(const expense of expensesResult.data??[]){if(expense.event_staff_settlement_id)continue;let metadata:Record<string,unknown>={};try{metadata=JSON.parse(expense.approval_reason??"{}");}catch{}const paid=expense.status==="PAID";transactions.push({id:expense.id,kind:paid?"OUTGOING":"PENDING_PAYMENT",date:expense.occurred_on,amount:Number(expense.total),title:expense.supplier||"Gasto BOOMBOX",detail:String(metadata.description??expense.category),href:`/finance/expenses?expense=${expense.id}`,source:expense.category});}
  const financialBySettlement=new Map((staffFinancialsResult.data??[]).map(item=>[item.settlement_id,item]));for(const payment of staffEventsResult.data??[]){const project=relation<{event_date?:string}>(payment.projects);if(!project?.event_date)continue;const member=relation<{first_name?:string;last_name?:string}>(payment.staff);const name=`${member?.first_name??""} ${member?.last_name??""}`.trim()||"Staff BOOMBOX";const financial=financialBySettlement.get(payment.id),payrollPaid=Number(financial?.payroll_paid_amount??payment.paid_amount),payrollPending=Math.max(0,Number(financial?.payroll_net??payment.total_internal_payment)-payrollPaid),reimbursementPending=Number(financial?.reimbursement_pending_amount??0);if(payrollPaid>0)transactions.push({id:`staff-paid-${payment.id}`,kind:"OUTGOING",date:payment.paid_at??project.event_date,amount:payrollPaid,title:payment.settlement_status==="ADVANCE"?"Anticipo de honorarios Staff":"Pago de honorarios Staff",detail:name,href:`/projects/${payment.project_id}#staff-assignment`,source:"Liquidación del Evento"});if(payrollPending>0)transactions.push({id:`staff-pending-${payment.id}`,kind:"PENDING_PAYMENT",date:project.event_date,amount:payrollPending,title:"Honorarios Staff pendientes",detail:name,href:`/resources/staff`,source:"Liquidación del Evento"});if(reimbursementPending>0)transactions.push({id:`staff-reimbursement-pending-${payment.id}`,kind:"PENDING_PAYMENT",date:project.event_date,amount:reimbursementPending,title:"Reembolso Staff pendiente",detail:name,href:"/resources/staff",source:"Reembolso aprobado"});}
  for(const cost of blockCostsResult.data??[]){const project=relation<{name?:string;event_date?:string;orbit_event_id?:string}>(cost.projects),member=relation<{first_name?:string;last_name?:string}>(cost.staff),block=relation<{name?:string;start_at?:string;end_at?:string}>(cost.event_operational_blocks);if(!project?.event_date)continue;const staffName=`${member?.first_name??""} ${member?.last_name??""}`.trim()||"Staff BOOMBOX";const minutes=Number(cost.duration_minutes??0),duration=`${Math.floor(minutes/60)}h${String(minutes%60).padStart(2,"0")}`;transactions.push({id:`staff-block-cost-${cost.id}`,kind:"PENDING_PAYMENT",date:project.event_date,amount:Number(cost.amount??0),title:`${project.orbit_event_id??project.name??"Evento"} · ${block?.name??"Bloque"}`,detail:`${staffName} · ${cost.role} · ${duration} · ${Number(cost.amount??0).toLocaleString("es-CL")} CLP`,href:`/projects/${cost.project_id}#staff-assignment`,source:"Costo Staff por bloque"});}
  for(const payment of reimbursementPaymentsResult.data??[]){const member=relation<{first_name?:string;last_name?:string}>(payment.staff),project=relation<{name?:string}>(payment.projects);transactions.push({id:`staff-reimbursement-paid-${payment.id}`,kind:"OUTGOING",date:payment.paid_on,amount:Number(payment.amount),title:"Reembolso Staff pagado",detail:[`${member?.first_name??""} ${member?.last_name??""}`.trim(),project?.name].filter(Boolean).join(" · "),href:"/resources/staff",source:payment.method||"Pago de reembolso"});}
  const vehicles=new Map((vehiclesResult.data??[]).map(item=>[item.asset_id,item.model]));
  for(const fuel of fuelResult.data??[]){if(expenseReceipts.has(fuel.receipt_path))continue;transactions.push({id:fuel.id,kind:"OUTGOING",date:fuel.fuel_date,amount:Number(fuel.total_amount),title:"Combustible",detail:`${vehicles.get(fuel.asset_id)??"Vehículo"} · ${fuel.gas_station}`,href:"/resources",source:"Flota"});}
  for(const item of officeRentResult.data??[]){const payment=relation<{id?:string;paid_on?:string;payment_method?:string;receipt_number?:number;office_lease_obligations?:unknown}>(item.office_lease_payments);if(!payment?.paid_on)continue;const obligation=relation<{period?:string;office_lease_settings?:unknown}>(payment.office_lease_obligations),settings=relation<{concept?:string;tenant_legal_name?:string}>(obligation?.office_lease_settings);const guarantee=item.item_type==="SECURITY_DEPOSIT";transactions.push({id:`office-rent-item-${item.id}`,kind:"INCOMING",date:payment.paid_on,amount:Number(item.amount),title:item.description||(guarantee?"Mes de garantía":settings?.concept??"Arriendo Oficina"),detail:`${settings?.tenant_legal_name??"Arrendatario"} · Recibo N°${String(payment.receipt_number).padStart(3,"0")}`,href:"/office-rent",source:guarantee?"Garantía no recurrente":payment.payment_method||"Ingreso de arriendo"});}
  const today=new Date().toLocaleDateString("en-CA",{timeZone:"America/Santiago"});
  for(const invoice of invoicesResult.data??[]){if(!["PENDING","PARTIALLY_PAID","OVERDUE"].includes(invoice.effective_status)||Number(invoice.outstanding_balance)<=0)continue;const customer=relation<{full_name?:string}>(invoice.customers);transactions.push({id:invoice.id,kind:"PENDING_COLLECTION",date:invoice.due_date??today,amount:Number(invoice.outstanding_balance),title:invoice.invoice_number,detail:customer?.full_name??"Cliente BOOMBOX",href:`/finance/receivables?invoice=${invoice.id}`,source:invoice.customer_type==="CORPORATE"?"Cobranza corporativa":"Saldo de reserva",overdue:Boolean(invoice.due_date&&invoice.due_date<today)});}
  return <CashFlowCenter data={{generatedAt:new Date().toISOString(),transactions}}/>;
}
