"use client";
import Link from"next/link";
import{useMemo,useState}from"react";
import{CalendarClock,ExternalLink,Landmark,ReceiptText,Search,TriangleAlert,UsersRound,WalletCards}from"lucide-react";
import{WorkspaceLayout}from"@/components/layout/workspace-layout";
import{StatusBadge}from"@/components/ui/status-badge";
import type{AccountsPayableDataset,PayableItem,PayableStatus,PayableType}from"./types";

const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`));
type Priority="HIGH"|"MEDIUM"|"LOW";type Risk="HIGH"|"MEDIUM"|"LOW";
const priorityMeta={HIGH:{label:"Alta",className:"bg-danger/10 text-danger"},MEDIUM:{label:"Media",className:"bg-warning/10 text-warning"},LOW:{label:"Baja",className:"bg-success/10 text-success"}};
const statusMeta:Record<PayableStatus,{label:string;variant:"neutral"|"warning"|"success"|"danger"}>={PENDING:{label:"Pendiente",variant:"warning"},PARTIAL:{label:"Parcial",variant:"warning"},PAID:{label:"Pagado",variant:"success"},OVERDUE:{label:"Vencido",variant:"danger"},CANCELLED:{label:"Cancelado",variant:"neutral"},ARCHIVED:{label:"Archivado",variant:"neutral"}};
const typeLabels:Record<PayableType,string>={STAFF:"Staff",SUPPLIER:"Proveedor",COMPANY_EXPENSE:"Gasto empresa",BANK:"Banco",MERCADO_PAGO:"Mercado Pago"};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago"}).format(new Date());
const plusDays=(base:string,days:number)=>{const value=new Date(`${base}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
function priority(item:PayableItem):Priority{const now=today();if(item.status==="OVERDUE"||item.dueDate<=now||item.criticalSupplier)return"HIGH";if(item.dueDate<=plusDays(now,7))return"MEDIUM";return"LOW";}
function risk(item:PayableItem):Risk{if(item.criticalSupplier||(item.status==="OVERDUE"&&!item.documentAvailable))return"HIGH";if(!item.documentAvailable)return"MEDIUM";return"LOW";}
function nextAction(item:PayableItem){if(item.type==="STAFF"&&!item.documentAvailable)return{label:"Falta boleta",detail:"Esperar documento SII antes del cierre."};if(!item.documentAvailable&&item.type!=="STAFF")return{label:"Esperar factura",detail:"Documento tributario pendiente."};const value=priority(item);if(value==="HIGH")return{label:"Pagar hoy",detail:item.status==="OVERDUE"?"Compromiso vencido.":"Vence hoy o es proveedor crítico."};if(value==="MEDIUM")return{label:"Revisar",detail:"Vence dentro de los próximos 7 días."};return{label:"Esperar",detail:`Vence ${date(item.dueDate)}.`};}

export function AccountsPayableCenter({dataset}:{dataset:AccountsPayableDataset}){const[query,setQuery]=useState("");const[month,setMonth]=useState("");const[status,setStatus]=useState<"ALL"|PayableStatus>("ALL");const[type,setType]=useState<"ALL"|PayableType>("ALL");const[priorityFilter,setPriorityFilter]=useState<"ALL"|Priority>("ALL");const[riskFilter,setRiskFilter]=useState<"ALL"|Risk>("ALL");const[amount,setAmount]=useState("");const[kpi,setKpi]=useState("ALL");const items=useMemo(()=>dataset.items.filter(item=>{const text=`${item.beneficiary} ${item.relatedEvent??""} ${typeLabels[item.type]} ${item.documentLabel}`.toLowerCase();const matchesKpi=kpi==="ALL"||(kpi==="PENDING"&&item.outstanding>0)||(kpi==="OVERDUE"&&item.status==="OVERDUE")||(kpi==="THIS_WEEK"&&item.outstanding>0&&item.dueDate>=today()&&item.dueDate<=plusDays(today(),7))||(kpi==="NEXT_WEEK"&&item.outstanding>0&&item.dueDate>plusDays(today(),7)&&item.dueDate<=plusDays(today(),14))||(kpi==="RECURRING"&&item.recurring)||(kpi==="SUPPLIER"&&["SUPPLIER","COMPANY_EXPENSE","BANK"].includes(item.type))||(kpi==="STAFF"&&item.type==="STAFF");return(!query||text.includes(query.toLowerCase()))&&(!month||item.dueDate.startsWith(month))&&(status==="ALL"||item.status===status)&&(type==="ALL"||item.type===type)&&(priorityFilter==="ALL"||priority(item)===priorityFilter)&&(riskFilter==="ALL"||risk(item)===riskFilter)&&(!amount||String(Math.round(item.outstanding)).includes(amount.replace(/\D/g,"")))&&matchesKpi}),[amount,dataset.items,kpi,month,priorityFilter,query,riskFilter,status,type]);return <WorkspaceLayout bottomAction={null} className="max-w-none p-0" copilot={null} header={null} timeline={null} mainContent={<main className="flex flex-col gap-6 pb-10">
 <section className="rounded-3xl border bg-card p-5 sm:p-7" data-workspace-label="Cuentas por Pagar" data-workspace-section="PAYABLES_HEADER"><StatusBadge label="Proyección financiera canónica" variant="success"/><p className="mt-5 text-xs font-semibold uppercase tracking-[.2em] text-brand">Finanzas · Compromisos</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Cuentas por Pagar</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Quién debe recibir dinero, cuánto, cuándo, por qué y qué decisión corresponde hoy. Finanzas consolida y abre el registro de origen; nunca edita.</p></section>
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-7" data-workspace-label="Resumen de Pagos" data-workspace-section="PAYABLES_KPIS"><Kpi active={kpi==="PENDING"} icon={<WalletCards/>} label="Total pendiente" onClick={()=>setKpi("PENDING")} value={money(dataset.metrics.totalPending)}/><Kpi active={kpi==="OVERDUE"} danger icon={<TriangleAlert/>} label="Vencido" onClick={()=>setKpi("OVERDUE")} value={money(dataset.metrics.overdue)}/><Kpi active={kpi==="THIS_WEEK"} icon={<CalendarClock/>} label="Esta semana" onClick={()=>setKpi("THIS_WEEK")} value={money(dataset.metrics.thisWeek)}/><Kpi active={kpi==="NEXT_WEEK"} icon={<CalendarClock/>} label="Próxima semana" onClick={()=>setKpi("NEXT_WEEK")} value={money(dataset.metrics.nextWeek)}/><Kpi active={kpi==="RECURRING"} icon={<ReceiptText/>} label="Recurrentes" onClick={()=>setKpi("RECURRING")} value={money(dataset.metrics.recurring)}/><Kpi active={kpi==="SUPPLIER"} icon={<Landmark/>} label="Saldo proveedores" onClick={()=>setKpi("SUPPLIER")} value={money(dataset.metrics.supplierBalance)}/><Kpi active={kpi==="STAFF"} icon={<UsersRound/>} label="Saldo Staff" onClick={()=>setKpi("STAFF")} value={money(dataset.metrics.staffBalance)}/></section>
 <section className="rounded-2xl border bg-card p-4 sm:p-5" data-workspace-label="Prioridad de Pagos" data-workspace-section="PAYABLES_PRIORITY"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Prioridad visual</h2><p className="mt-1 text-xs text-muted">Alta: vencido, vence hoy o proveedor crítico. Media: vence dentro de 7 días.</p></div><div className="flex gap-2">{(["HIGH","MEDIUM","LOW"]as Priority[]).map(value=><button className={`rounded-full px-3 py-1.5 text-xs font-semibold ${priorityFilter===value?priorityMeta[value].className:"bg-background text-muted"}`} key={value} onClick={()=>setPriorityFilter(priorityFilter===value?"ALL":value)}>{priorityMeta[value].label} · {dataset.items.filter(item=>priority(item)===value).length}</button>)}</div></div></section>
 <section className="space-y-5" data-workspace-label="Compromisos Canónicos" data-workspace-section="PAYABLES_MANAGEMENT"><div className="grid gap-3 rounded-2xl border bg-card p-4 sm:grid-cols-2 xl:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar beneficiario, proveedor o Evento</span><input className="min-h-11 w-full rounded-xl border bg-background pl-10 pr-3 text-sm" onChange={event=>setQuery(event.target.value)} placeholder="Beneficiario, proveedor o Evento" value={query}/></label><input aria-label="Filtrar por mes" className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setMonth(event.target.value)} type="month" value={month}/><input aria-label="Filtrar por monto" className="min-h-11 rounded-xl border bg-background px-3 text-sm" inputMode="numeric" onChange={event=>setAmount(event.target.value)} placeholder="Monto pendiente" value={amount}/><Filter label="Estado" onChange={value=>setStatus(value as typeof status)} value={status} values={[["ALL","Todos"],...["PENDING","PARTIAL","PAID","OVERDUE","CANCELLED","ARCHIVED"].map(value=>[value,statusMeta[value as PayableStatus].label])]}/><Filter label="Tipo" onChange={value=>setType(value as typeof type)} value={type} values={[["ALL","Todos"],...Object.entries(typeLabels)]}/><Filter label="Prioridad" onChange={value=>setPriorityFilter(value as typeof priorityFilter)} value={priorityFilter} values={[["ALL","Todas"],["HIGH","Alta"],["MEDIUM","Media"],["LOW","Baja"]]}/><Filter label="Riesgo" onChange={value=>setRiskFilter(value as typeof riskFilter)} value={riskFilter} values={[["ALL","Todos"],["HIGH","Alto"],["MEDIUM","Medio"],["LOW","Bajo"]]}/><button className="min-h-11 rounded-xl border px-3 text-sm font-medium hover:border-brand" onClick={()=>{setQuery("");setMonth("");setAmount("");setStatus("ALL");setType("ALL");setPriorityFilter("ALL");setRiskFilter("ALL");setKpi("ALL")}}>Limpiar filtros</button></div>
 <div className="overflow-hidden rounded-2xl border bg-card"><div className="hidden overflow-x-auto xl:block"><table className="w-full min-w-[1850px] text-left text-sm"><thead className="border-b bg-background/40 text-xs uppercase tracking-wide text-muted"><tr>{["Beneficiario","Tipo / Evento","Monto original","Ajustes","Reembolsos","Pagado","Pendiente","Vencimiento","Estado","Prioridad","Próxima acción","Documento","Origen"].map(label=><th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{items.map(item=><PayableRow item={item} key={item.id}/>)}</tbody></table></div><div className="space-y-3 p-3 xl:hidden">{items.map(item=><PayableCard item={item} key={item.id}/>)}</div>{!items.length?<div className="p-10 text-center"><ReceiptText className="mx-auto size-8 text-brand"/><p className="mt-3 font-semibold">No hay compromisos para estos filtros.</p><p className="mt-1 text-sm text-muted">La vista solo consolida registros canónicos existentes.</p></div>:null}</div></section>
 </main>}/>}

function PayableRow({item}:{item:PayableItem}){const p=priority(item),action=nextAction(item),meta=statusMeta[item.status];return <tr className="align-top"><td className="px-4 py-4"><strong>{item.beneficiary}</strong><small className="mt-1 block text-muted">{item.sourceTable}</small></td><td className="px-4 py-4"><Pill className="bg-brand/10 text-brand" label={typeLabels[item.type]}/><small className="mt-2 block max-w-44 text-muted">{item.relatedEvent??"Sin Evento"}</small></td><td className="px-4 py-4">{money(item.originalAmount)}</td><td className="px-4 py-4">{money(item.adjustments)}</td><td className="px-4 py-4">{money(item.reimbursements)}</td><td className="px-4 py-4">{money(item.alreadyPaid)}</td><td className="px-4 py-4 font-semibold">{money(item.outstanding)}</td><td className="px-4 py-4">{date(item.dueDate)}</td><td className="px-4 py-4"><StatusBadge label={meta.label} variant={meta.variant}/></td><td className="px-4 py-4"><Pill className={priorityMeta[p].className} label={priorityMeta[p].label}/></td><td className="px-4 py-4"><strong className="text-xs text-brand">{action.label}</strong><small className="mt-1 block max-w-40 text-muted">{action.detail}</small></td><td className="px-4 py-4"><span className={item.documentAvailable?"text-success":"text-warning"}>{item.documentLabel}</span></td><td className="px-4 py-3"><SourceActions item={item}/></td></tr>}
function PayableCard({item}:{item:PayableItem}){const p=priority(item),action=nextAction(item),meta=statusMeta[item.status];return <article className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.beneficiary}</h2><p className="mt-1 text-sm text-muted">{typeLabels[item.type]} · {item.relatedEvent??"Sin Evento"}</p></div><StatusBadge label={meta.label} variant={meta.variant}/></div><div className="mt-3 flex gap-2"><Pill className={priorityMeta[p].className} label={`Prioridad ${priorityMeta[p].label}`}/><Pill className={risk(item)==="HIGH"?"bg-danger/10 text-danger":risk(item)==="MEDIUM"?"bg-warning/10 text-warning":"bg-success/10 text-success"} label={`Riesgo ${risk(item)==="HIGH"?"alto":risk(item)==="MEDIUM"?"medio":"bajo"}`}/></div><dl className="mt-4 grid grid-cols-2 gap-3"><Small label="Original" value={money(item.originalAmount)}/><Small label="Ajustes" value={money(item.adjustments)}/><Small label="Reembolsos" value={money(item.reimbursements)}/><Small label="Pagado" value={money(item.alreadyPaid)}/><Small label="Pendiente" value={money(item.outstanding)}/><Small label="Vence" value={date(item.dueDate)}/></dl><div className="mt-4 rounded-xl bg-background p-3"><p className="text-xs font-semibold text-brand">{action.label}</p><p className="mt-1 text-xs text-muted">{action.detail}</p></div><SourceActions item={item}/></article>}
function SourceActions({item}:{item:PayableItem}){return <div className="mt-3 min-w-52 space-y-1"><Link className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-sm hover:bg-background" href={item.canonicalHref}><ExternalLink className="size-4"/>Abrir origen canónico</Link>{item.projectId?<Link className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-sm hover:bg-background" href={`/projects/${item.projectId}`}><ExternalLink className="size-4"/>Abrir Evento</Link>:null}<details><summary className="flex min-h-9 cursor-pointer list-none items-center gap-2 rounded-lg px-2 text-sm hover:bg-background"><CalendarClock className="size-4"/>Ver timeline</summary><div className="mt-2 space-y-3 rounded-lg border bg-background/30 p-3">{item.timeline.map(entry=><div className="border-l-2 border-brand/40 pl-3 text-xs" key={entry.id}><strong>{entry.label}</strong><span className="block text-muted">{date(entry.date)} · {entry.detail}{entry.amount!==null?` · ${money(entry.amount)}`:""}</span></div>)}</div></details></div>}
function Kpi({icon,label,value,danger=false,active=false,onClick}:{icon:React.ReactNode;label:string;value:string;danger?:boolean;active?:boolean;onClick:()=>void}){return <button className={`rounded-2xl border bg-card p-4 text-left transition hover:border-brand/50 ${danger?"border-danger/30":""} ${active?"ring-2 ring-brand/50":""}`} onClick={onClick}><span className={`grid size-9 place-items-center rounded-lg [&_svg]:size-5 ${danger?"bg-danger/10 text-danger":"bg-brand/10 text-brand"}`}>{icon}</span><p className="mt-4 text-lg font-semibold xl:text-xl">{value}</p><p className="mt-1 text-xs text-muted">{label} · ver origen</p></button>}
function Filter({label,value,onChange,values}:{label:string;value:string;onChange:(value:string)=>void;values:string[][]}){return <label className="text-xs font-semibold uppercase tracking-wide text-muted">{label}<select className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3 text-sm font-normal normal-case" onChange={event=>onChange(event.target.value)} value={value}>{values.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
function Pill({label,className}:{label:string;className:string}){return <span className={`inline-flex rounded-full px-2 py-1 text-[11px] font-semibold ${className}`}>{label}</span>}
function Small({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-semibold uppercase tracking-wider text-muted">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>}
