import "server-only";
import type{SupabaseClient}from"@supabase/supabase-js";
import type{AccountsPayableDataset,PayableItem,PayableStatus,PayableTimelineItem,PayableType}from"./types";

type Row = Record<string, unknown>;
const n=(value:unknown)=>Number(value??0)||0;
const day=(value:unknown)=>String(value??"").slice(0,10);
const relation=<T,>(value:T|T[]|null|undefined):T|undefined=>Array.isArray(value)?value[0]:value??undefined;
const metadata=(value:unknown):Record<string,unknown>=>{if(value&&typeof value==="object")return value as Record<string,unknown>;try{return JSON.parse(String(value??"{}"))}catch{return{}}};
const endOfMonth=(value:string)=>{const date=new Date(`${value.slice(0,7)}-01T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);return date.toISOString().slice(0,10)};
const statusFor=(raw:string,outstanding:number,dueDate:string,today:string):PayableStatus=>{if(raw==="CANCELLED")return"CANCELLED";if(raw==="ARCHIVED")return"ARCHIVED";if(outstanding<=0||raw==="PAID")return"PAID";if(dueDate&&dueDate<today)return"OVERDUE";if(["ADVANCE","PARTIAL","PARTIALLY_PAID"].includes(raw))return"PARTIAL";return"PENDING"};

export async function loadAccountsPayable(client:SupabaseClient):Promise<AccountsPayableDataset>{
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago"}).format(new Date());
 const[settlementsResult,staffResult,projectsResult,adjustmentsResult,movementsResult,expensesResult,runsResult,rulesResult,mpResult]=await Promise.all([
  client.from("staff_settlement_financials").select("settlement_id,staff_id,project_id,accounting_month,original_net,adjustment_total,reimbursement_total,final_amount,paid_amount,remaining_balance,settlement_status,sii_receipt_status"),
  client.from("staff").select("id,first_name,last_name").is("deleted_at",null),
  client.from("projects").select("id,name,event_date,deleted_at").is("deleted_at",null),
  client.from("event_staff_settlement_adjustments").select("id,settlement_id,reason,amount,comment,created_at").order("created_at"),
  client.from("event_staff_settlement_movements").select("id,settlement_id,movement_type,amount,movement_date,method,notes,receipt_path,created_at").is("deleted_at",null).order("movement_date"),
  client.from("expenses").select("id,project_id,event_staff_settlement_id,category,supplier,document_number,occurred_on,total,status,receipt_path,approval_reason,created_at").is("deleted_at",null).order("occurred_on"),
  client.from("finance_recurring_expense_runs").select("rule_id,expense_id,accounting_month"),
  client.from("finance_recurring_expense_rules").select("id,name,category,amount,frequency,next_due_date,active,bank_account_id,finance_bank_accounts(name,account_kind)").eq("active",true),
  client.from("mercado_pago_transactions").select("id,external_id,project_id,fee_amount,settlement_status,transfer_status,available_at,transferred_at,created_at").gt("fee_amount",0),
 ]);
 const failure=[settlementsResult,staffResult,projectsResult,adjustmentsResult,movementsResult,expensesResult,runsResult,rulesResult,mpResult].find(result=>result.error)?.error;if(failure)throw failure;
 const staff=new Map((staffResult.data??[]).map(row=>[row.id,`${row.first_name} ${row.last_name}`.trim()]));const projects=new Map((projectsResult.data??[]).map(row=>[row.id,row]));
 const adjustmentsBySettlement=new Map<string,Row[]>();for(const row of adjustmentsResult.data??[]){const list=adjustmentsBySettlement.get(row.settlement_id)??[];list.push(row);adjustmentsBySettlement.set(row.settlement_id,list)}
 const movementsBySettlement=new Map<string,Row[]>();for(const row of movementsResult.data??[]){const list=movementsBySettlement.get(row.settlement_id)??[];list.push(row);movementsBySettlement.set(row.settlement_id,list)}
 const expensesBySettlement=new Map<string,Row[]>();for(const row of expensesResult.data??[]){if(!row.event_staff_settlement_id)continue;const list=expensesBySettlement.get(row.event_staff_settlement_id)??[];list.push(row);expensesBySettlement.set(row.event_staff_settlement_id,list)}
 const recurringExpenseIds=new Set((runsResult.data??[]).map(row=>row.expense_id));const items:PayableItem[]=[];
 for(const row of settlementsResult.data??[]){const project=projects.get(row.project_id);if(!project)continue;const due=endOfMonth(row.accounting_month);const adjustments=adjustmentsBySettlement.get(row.settlement_id)??[];const movements=movementsBySettlement.get(row.settlement_id)??[];const reimbursements=expensesBySettlement.get(row.settlement_id)??[];const outstanding=n(row.remaining_balance);const timeline:PayableTimelineItem[]=[{id:`created-${row.settlement_id}`,kind:"CREATED",date:project.event_date,label:"Liquidación creada",detail:project.name,amount:n(row.original_net)},...adjustments.map(value=>({id:String(value.id),kind:"ADJUSTMENT" as const,date:day(value.created_at),label:"Ajuste",detail:`${value.reason} · ${value.comment}`,amount:n(value.amount)})),...movements.map(value=>({id:String(value.id),kind:"PAYMENT" as const,date:day(value.movement_date),label:value.movement_type==="ADVANCE"?"Anticipo":"Pago",detail:String(value.method??"Método no registrado"),amount:value.movement_type==="REVERSAL"?-n(value.amount):n(value.amount)})),...reimbursements.map(value=>({id:String(value.id),kind:"RECEIPT" as const,date:day(value.occurred_on),label:"Reembolso operacional",detail:String(value.supplier??value.category??"Gasto operacional"),amount:n(value.total)})),{id:`status-${row.settlement_id}`,kind:"STATUS",date:today,label:"Estado actual",detail:String(row.settlement_status),amount:outstanding}];items.push({id:`staff-${row.settlement_id}`,sourceId:row.settlement_id,sourceTable:"event_staff_payments",beneficiary:staff.get(row.staff_id)??"Colaborador",type:"STAFF",relatedEvent:project.name,projectId:row.project_id,originalAmount:n(row.original_net),adjustments:n(row.adjustment_total),reimbursements:n(row.reimbursement_total),alreadyPaid:n(row.paid_amount),outstanding,dueDate:due,status:statusFor(row.settlement_status,outstanding,due,today),documentLabel:row.sii_receipt_status==="RECEIVED"?"Boleta SII recibida":"Boleta SII pendiente",documentAvailable:row.sii_receipt_status==="RECEIVED",canonicalHref:`/resources/staff?workspace=payroll&settlement=${row.settlement_id}`,recurring:false,criticalSupplier:false,timeline});}
 for(const row of expensesResult.data??[]){if(row.event_staff_settlement_id)continue;const meta=metadata(row.approval_reason);const due=day(meta.dueDate)||row.occurred_on;const type:PayableType=row.category==="BANK_CHARGES"?"BANK":row.project_id?"SUPPLIER":"COMPANY_EXPENSE";const outstanding=row.status==="PAID"||row.status==="CANCELLED"?0:n(row.total);const project=projects.get(row.project_id);items.push({id:`expense-${row.id}`,sourceId:row.id,sourceTable:"expenses",beneficiary:row.supplier??"Proveedor",type,relatedEvent:project?.name??null,projectId:row.project_id,originalAmount:n(row.total),adjustments:0,reimbursements:0,alreadyPaid:row.status==="PAID"?n(row.total):0,outstanding,dueDate:due,status:statusFor(row.status,outstanding,due,today),documentLabel:row.document_number?`Documento ${row.document_number}`:row.receipt_path?"Comprobante disponible":"Documento pendiente",documentAvailable:Boolean(row.receipt_path||row.document_number),canonicalHref:`/finance/expenses?expense=${row.id}`,recurring:recurringExpenseIds.has(row.id)||Boolean(meta.recurringRuleId),criticalSupplier:Boolean(meta.criticalSupplier),timeline:[{id:`created-${row.id}`,kind:"CREATED",date:day(row.created_at),label:"Gasto creado",detail:String(meta.description??row.category),amount:n(row.total)},{id:`receipt-${row.id}`,kind:"RECEIPT",date:row.occurred_on,label:row.receipt_path?"Comprobante adjunto":"Comprobante pendiente",detail:row.document_number??"Sin número de documento",amount:null},{id:`status-${row.id}`,kind:"STATUS",date:today,label:"Estado actual",detail:row.status,amount:outstanding}]});}
 for(const row of rulesResult.data??[]){const account=relation<Row>(row.finance_bank_accounts);const type:PayableType=account?.account_kind==="BANK"||row.category==="BANK_CHARGES"?"BANK":"COMPANY_EXPENSE";items.push({id:`recurring-${row.id}`,sourceId:row.id,sourceTable:"finance_recurring_expense_rules",beneficiary:row.name,type,relatedEvent:null,projectId:null,originalAmount:n(row.amount),adjustments:0,reimbursements:0,alreadyPaid:0,outstanding:n(row.amount),dueDate:row.next_due_date,status:statusFor("PENDING",n(row.amount),row.next_due_date,today),documentLabel:"Documento por recibir",documentAvailable:false,canonicalHref:`/finance/banking?rule=${row.id}`,recurring:true,criticalSupplier:false,timeline:[{id:`scheduled-${row.id}`,kind:"CREATED",date:row.next_due_date,label:"Próxima recurrencia",detail:`${row.frequency} · ${account?.name??"Cuenta no asignada"}`,amount:n(row.amount)},{id:`status-${row.id}`,kind:"STATUS",date:today,label:"Estado actual",detail:"Programado",amount:n(row.amount)}]});}
 for(const row of mpResult.data??[]){const project=projects.get(row.project_id);const paid=["PAID","SETTLED","COMPLETED"].includes(String(row.settlement_status).toUpperCase());const due=day(row.available_at)||day(row.created_at);const amount=n(row.fee_amount);items.push({id:`mp-${row.id}`,sourceId:row.id,sourceTable:"mercado_pago_transactions",beneficiary:"Mercado Pago",type:"MERCADO_PAGO",relatedEvent:project?.name??null,projectId:row.project_id,originalAmount:amount,adjustments:0,reimbursements:0,alreadyPaid:paid?amount:0,outstanding:paid?0:amount,dueDate:due,status:statusFor(paid?"PAID":"PENDING",paid?0:amount,due,today),documentLabel:`Transacción ${row.external_id}`,documentAvailable:true,canonicalHref:`/finance/banking?transaction=${row.id}`,recurring:false,criticalSupplier:false,timeline:[{id:`created-${row.id}`,kind:"CREATED",date:day(row.created_at),label:"Comisión Mercado Pago",detail:row.external_id,amount},{id:`status-${row.id}`,kind:"STATUS",date:today,label:"Estado actual",detail:`${row.settlement_status} · ${row.transfer_status}`,amount:paid?0:amount}]});}
 const active=items.filter(item=>!["PAID","CANCELLED","ARCHIVED"].includes(item.status));const addDays=(days:number)=>{const value=new Date(`${today}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};const week=addDays(7),nextWeek=addDays(14);const sum=(rows:PayableItem[])=>rows.reduce((total,item)=>total+item.outstanding,0);
 return{generatedAt:new Date().toISOString(),items:items.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),metrics:{totalPending:sum(active),overdue:sum(active.filter(item=>item.status==="OVERDUE")),thisWeek:sum(active.filter(item=>item.dueDate>=today&&item.dueDate<=week)),nextWeek:sum(active.filter(item=>item.dueDate>week&&item.dueDate<=nextWeek)),recurring:sum(active.filter(item=>item.recurring)),supplierBalance:sum(active.filter(item=>item.type==="SUPPLIER"||item.type==="COMPANY_EXPENSE"||item.type==="BANK")),staffBalance:sum(active.filter(item=>item.type==="STAFF"))}};
}
