"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { ExternalLink, Mail, Search } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";

type PortalData = NonNullable<Awaited<ReturnType<typeof import("./customer-portal.service").loadCustomerPortal>>>;
type Category = "CONTRACTS" | "PAYMENTS" | "DESIGNS" | "REMINDERS" | "GALLERY" | "GENERAL";
type Status = "SENT" | "DELIVERED" | "OPENED" | "FAILED" | "PENDING" | "COMPLETED";
type Item = { id:string; date:string; type:string; subject:string; preview:string; category:Category; status:Status; messageId?:string|null };

const actionLabels: Record<string,string> = {
  RESERVATION_CREATED:"Reserva creada", AUTOMATIC_BOOKING_INVITATION_SENT:"Invitación enviada", RESERVATION_COMPLETED:"Reserva completada", RESERVATION_CONFIRMED:"Reserva completada", RESERVATION_CONFIRMATION_SENT:"Reserva completada", AGREEMENT_SENT:"Contrato enviado", AGREEMENT_SIGNED:"Contrato firmado", PAYMENT_REMINDER_SENT:"Recordatorio de pago", PAYMENT_RECEIVED:"Pago recibido", DESIGN_SENT:"Diseño enviado", DESIGN_APPROVED:"Diseño aprobado", EVENT_REMINDER_SENT:"Recordatorio del evento", GALLERY_AVAILABLE:"Galería disponible", THANK_YOU_SENT:"Mensaje de agradecimiento",
};
const communicationLabels: Record<string,string> = { AUTOMATIC_BOOKING_INVITATION:"Invitación enviada", RESERVATION_CONFIRMATION:"Reserva completada", CONTRACT:"Contrato enviado", PAYMENT:"Pago", PAYMENT_REMINDER:"Recordatorio de pago", DESIGN:"Diseño enviado", EVENT_REMINDER:"Recordatorio del evento", GALLERY:"Galería disponible", THANK_YOU:"Mensaje de agradecimiento" };
const filters: Array<{value:"ALL"|Category;label:string}> = [{value:"ALL",label:"Todos"},{value:"CONTRACTS",label:"Contratos"},{value:"PAYMENTS",label:"Pagos"},{value:"DESIGNS",label:"Diseños"},{value:"REMINDERS",label:"Recordatorios"},{value:"GALLERY",label:"Galería"},{value:"GENERAL",label:"General"}];

function category(value:string):Category { const key=value.toUpperCase(); if(key.includes("AGREEMENT")||key.includes("CONTRACT"))return "CONTRACTS";if(key.includes("PAYMENT"))return "PAYMENTS";if(key.includes("DESIGN"))return "DESIGNS";if(key.includes("REMINDER"))return "REMINDERS";if(key.includes("GALLERY"))return "GALLERY";return "GENERAL"; }
function status(value:string, timeline=false):Status { if(timeline)return "COMPLETED";const key=value.toUpperCase();if(key==="DELIVERED")return "DELIVERED";if(key==="OPENED")return "OPENED";if(key==="FAILED")return "FAILED";if(key==="SENT")return "SENT";return "PENDING"; }
function statusLabel(value:Status){return {SENT:"Enviado",DELIVERED:"Entregado",OPENED:"Abierto",FAILED:"Fallido",PENDING:"Pendiente",COMPLETED:"Completado"}[value];}
function formatDate(value:string){return new Intl.DateTimeFormat("es-CL",{dateStyle:"medium"}).format(new Date(value));}
function formatTime(value:string){return new Intl.DateTimeFormat("es-CL",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));}

export function CustomerCommunicationCenter({data}:{data:PortalData}){
  const [query,setQuery]=useState("");const deferredQuery=useDeferredValue(query);const [filter,setFilter]=useState<"ALL"|Category>("ALL");
  const items=useMemo(()=>{
    const communicationIds=new Set(data.communications.map(item=>item.id));
    const emails:Item[]=data.communications.map(item=>({id:`mail-${item.id}`,date:item.occurred_at??item.created_at,type:communicationLabels[item.communication_type]??item.communication_type.replaceAll("_"," "),subject:item.subject??communicationLabels[item.communication_type]??"Comunicación BOOMBOX",preview:item.body??"Comunicación enviada por BOOMBOX.",category:category(item.communication_type),status:status(item.status),messageId:item.external_message_id}));
    const events:Item[]=data.communicationTimeline.filter(item=>!item.communication_id||!communicationIds.has(item.communication_id)).map(item=>({id:`timeline-${item.id}`,date:item.occurred_at,type:actionLabels[item.action]??item.title,subject:item.title,preview:item.description??item.title,category:category(item.action),status:"COMPLETED"}));
    return [...emails,...events].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
  },[data.communicationTimeline,data.communications]);
  const visible=useMemo(()=>{const term=deferredQuery.trim().toLocaleLowerCase("es");return items.filter(item=>(filter==="ALL"||item.category===filter)&&(!term||`${item.subject} ${item.type} ${formatDate(item.date)}`.toLocaleLowerCase("es").includes(term)));},[deferredQuery,filter,items]);
  return <section className="scroll-mt-6 rounded-3xl border border-border/80 bg-card p-5 sm:p-7" id="communications"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Comunicaciones</p><h2 className="mt-2 text-xl font-semibold tracking-tight">Centro de Comunicación</h2><p className="mt-1 text-sm leading-6 text-muted">Revisa lo que BOOMBOX ha enviado y lo que todavía está pendiente.</p></div><span className="text-xs text-muted">Más recientes primero</span></div>
    <div className="mt-5 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]"><label className="relative"><Search aria-hidden="true" className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar comunicaciones</span><input className="min-h-11 w-full rounded-xl border border-border bg-background pl-10 pr-3 text-sm" onChange={event=>setQuery(event.target.value)} placeholder="Buscar por fecha, tipo o asunto" type="search" value={query}/></label><div className="flex gap-2 overflow-x-auto pb-1" role="group" aria-label="Filtrar comunicaciones">{filters.map(option=><button aria-pressed={filter===option.value} className={`min-h-11 shrink-0 rounded-xl border px-3 text-xs font-semibold transition-colors ${filter===option.value?"border-brand bg-brand/10 text-brand":"border-border bg-background text-muted hover:text-foreground"}`} key={option.value} onClick={()=>setFilter(option.value)} type="button">{option.label}</button>)}</div></div>
    <div className="mt-5 space-y-3">{visible.length?visible.map(item=><article className="rounded-2xl border border-border/80 bg-background/35 p-4 sm:p-5" key={item.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-brand/10 text-brand"><Mail className="size-5"/></span><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-brand">{item.type}</p><h3 className="mt-1 font-semibold">{item.subject}</h3><p className="mt-2 line-clamp-3 whitespace-pre-line text-sm leading-6 text-muted">{item.preview}</p></div></div><div className="flex shrink-0 flex-row items-center gap-2 sm:flex-col sm:items-end"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status==="FAILED"?"bg-danger/10 text-danger":item.status==="PENDING"?"bg-warning/10 text-warning":"bg-success/10 text-success"}`}>{statusLabel(item.status)}</span><time className="text-xs text-muted" dateTime={item.date}>{formatDate(item.date)} · {formatTime(item.date)}</time></div></div>{item.messageId?<div className="mt-4 border-t border-border/70 pt-4"><ActionButton icon={ExternalLink} label="Abrir correo original" onClick={()=>window.open(`https://mail.google.com/mail/u/0/#all/${encodeURIComponent(item.messageId!)}`,"_blank","noopener,noreferrer")} variant="outline"/></div>:null}</article>):<div className="rounded-2xl border border-dashed border-border p-8 text-center"><Mail className="mx-auto size-6 text-muted"/><p className="mt-3 text-sm font-semibold">No hay comunicaciones para esta búsqueda.</p><p className="mt-1 text-xs text-muted">Los nuevos correos y eventos aparecerán aquí automáticamente.</p></div>}</div>
  </section>;
}
