"use client";
import { useMemo, useState, useTransition } from "react";
import { CheckCircle2, Clock3, CreditCard, Download, FileText, Images, MapPin, Send, ShieldCheck, Sparkles, Upload } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { submitPortalRequestAction } from "./actions";

type PortalData = Awaited<ReturnType<typeof import("./customer-portal.service").loadCustomerPortal>> & {};
const money=(value:number|string|null|undefined)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(Number(value??0));
function Panel({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="rounded-3xl border border-border/80 bg-card p-5 sm:p-7"><h2 className="text-xl font-semibold tracking-tight">{title}</h2>{description&&<p className="mt-1 text-sm leading-6 text-muted">{description}</p>}<div className="mt-5">{children}</div></section>}
function State({label,ready}:{label:string;ready:boolean}){return <div className="flex min-h-12 items-center justify-between gap-3 rounded-xl border border-border/70 px-3"><span className="text-sm font-medium">{label}</span><StatusBadge label={ready?"Listo":"En proceso"} variant={ready?"success":"warning"}/></div>}

export function CustomerPortalHome({data,token}:{data:NonNullable<PortalData>;token:string}){
 const project=data.project as typeof data.project & {customers:{full_name:string;email:string;phone:string};finance:Record<string,unknown>;operations:Record<string,unknown>};
 const eventDate=project.event_date?new Date(`${project.event_date}T12:00:00Z`):null; const days=eventDate?Math.ceil((eventDate.getTime()-Date.now())/86400000):null;
 const countdown=days==null?"Fecha por confirmar":days<0?"Evento finalizado":days===0?"Hoy":days===1?"Mañana":`${days} días`;
 const [type,setType]=useState<"MESSAGE"|"QUESTION"|"ADDITIONAL_SERVICE"|"DESIGN_COMMENT">("MESSAGE"); const [message,setMessage]=useState(""); const [feedback,setFeedback]=useState(""); const [pending,startTransition]=useTransition();
 const contractedExtras=useMemo(()=>data.services.flatMap(service=>Array.isArray(service.extras)?service.extras:[]).map(String),[data.services]);
 const availableExtras=["Imanes ilimitados","Scrapbook","Branding","QR corporativo","Operador adicional","Impresión adicional"].filter(extra=>!contractedExtras.includes(extra));
 const agreementSigned=data.agreement?.status==="SIGNED"; const quoteApproved=data.quotation?.status==="ACCEPTED"; const paymentStatus=String(project.finance?.status??project.finance?.paymentStatus??"PENDING"); const paymentReady=["PAID","APPROVED","CONFIRMED"].includes(paymentStatus);
 const submit=()=>startTransition(async()=>{const result=await submitPortalRequestAction({token,type,message});setFeedback(result.ok?result.message:result.error);if(result.ok)setMessage("");});
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-7xl space-y-6 px-4 py-5 sm:px-6 sm:py-8 lg:px-8 lg:py-10">
  <header className="overflow-hidden rounded-3xl border border-border/80 bg-card p-6 sm:p-9 lg:p-12"><BrandLogo className="h-16 w-48 sm:h-20 sm:w-60" priority surface="dark"/><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Tu experiencia BOOMBOX</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Hola, {project.customers.full_name}.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted">Todo lo importante de tu evento, en un solo lugar.</p></div><div className="rounded-2xl border border-brand/20 bg-brand/5 p-5 lg:min-w-56"><p className="text-xs font-semibold uppercase tracking-wider text-muted">Cuenta regresiva</p><p className="mt-2 text-3xl font-semibold text-brand">{countdown}</p></div></div>
  <div className="mt-9 grid gap-4 border-t border-border/70 pt-7 sm:grid-cols-3"><div><p className="text-xs text-muted">Evento</p><p className="mt-1 font-semibold">{project.name}</p></div><div><p className="text-xs text-muted">Fecha</p><p className="mt-1 font-semibold">{eventDate?new Intl.DateTimeFormat("es-CL",{dateStyle:"long",timeZone:"UTC"}).format(eventDate):"Por confirmar"}</p></div><div><p className="text-xs text-muted">Estado</p><p className="mt-1 font-semibold">{project.status}</p></div></div></header>
  <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-6">
   <Panel title="Estado de tu evento" description="Actualizamos cada paso a medida que BOOMBOX confirma el avance."><div className="grid gap-3 sm:grid-cols-2"><State label="Reserva confirmada" ready={["CONFIRMED","RESERVED","COMPLETED"].includes(project.status)}/><State label="Cotización aprobada" ready={quoteApproved}/><State label="Acuerdo firmado" ready={agreementSigned}/><State label="Pago" ready={paymentReady}/><State label="Diseño" ready={data.uploads.length>0}/><State label="Operación" ready={String(project.operations?.status??"")==="READY"}/></div></Panel>
   <Panel title="Servicios y extras" description="Solo mostramos lo contratado para tu evento."><div className="space-y-3">{data.services.map(service=><div className="flex items-center gap-3 rounded-xl border border-border/70 p-4" key={service.service_code}><Sparkles className="size-5 text-brand"/><div><p className="font-semibold">{service.service_code}</p><p className="text-sm text-muted">{service.duration_hours?`${service.duration_hours} horas`:"Duración acordada"}</p></div></div>)}</div>{contractedExtras.length>0&&<div className="mt-5"><p className="text-sm font-semibold">Extras contratados</p><p className="mt-2 text-sm text-muted">{contractedExtras.join(" · ")}</p></div>}<div className="mt-5"><p className="text-sm font-semibold">Servicios adicionales disponibles</p><div className="mt-2 flex flex-wrap gap-2">{availableExtras.map(extra=><button className="min-h-10 rounded-full border border-border px-3 text-sm hover:border-brand" key={extra} onClick={()=>{setType("ADDITIONAL_SERVICE");setMessage(`Quiero solicitar información sobre ${extra}.`);}} type="button">{extra}</button>)}</div><p className="mt-3 text-xs text-muted">La solicitud será revisada por BOOMBOX. No se aprobará automáticamente.</p></div></Panel>
   <Panel title="Centro de diseño" description="Comparte logos, imágenes, instrucciones y comentarios con nuestro equipo."><form className="grid gap-3" encType="multipart/form-data" method="post" action={`/api/portal/${encodeURIComponent(token)}/upload`}><input className="min-h-12 rounded-xl border border-dashed border-border bg-background p-3 text-sm" name="file" required type="file" accept="image/*,.pdf,.ai,.eps,.svg"/><textarea className="min-h-24 rounded-xl border border-border bg-background p-3 text-sm" name="instructions" placeholder="Instrucciones o comentarios para el diseño"/><ActionButton icon={Upload} label="Subir al Centro de Diseño" type="submit"/></form>{data.uploads.length>0&&<ul className="mt-4 space-y-2">{data.uploads.map(file=><li className="text-sm text-muted" key={file.id}>✓ {file.file_name}</li>)}</ul>}</Panel>
   <Panel title="Información del evento"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border p-4"><MapPin className="size-5 text-brand"/><p className="mt-3 text-xs text-muted">Lugar</p><p className="mt-1 font-semibold">{project.location||"Por confirmar"}</p><p className="text-sm text-muted">{project.city}</p></div><div className="rounded-xl border p-4"><Clock3 className="size-5 text-brand"/><p className="mt-3 text-xs text-muted">Horario</p><p className="mt-1 font-semibold">{project.event_time?.slice(0,5)||"Por confirmar"}</p></div></div><div className="mt-5 space-y-3">{data.timeline.slice(0,6).map(item=><div className="border-l-2 border-brand/40 pl-4" key={item.id}><p className="text-sm font-medium">{item.human_message}</p><p className="mt-1 text-xs text-muted">{new Intl.DateTimeFormat("es-CL",{dateStyle:"medium"}).format(new Date(item.occurred_at))}</p></div>)}</div></Panel>
  </div><aside className="space-y-6">
   <Panel title="Pagos"><div className="grid gap-3"><div className="rounded-xl border p-4"><CreditCard className="size-5 text-brand"/><p className="mt-3 text-xs text-muted">Total acordado</p><p className="mt-1 text-2xl font-semibold">{money(data.quotation?.final_customer_price??data.quotation?.grand_total)}</p></div><State label="Pago de reserva" ready={paymentReady}/><State label="Saldo pendiente" ready={paymentStatus==="PAID"}/><p className="text-xs text-muted">Vencimiento: {data.quotation?.expiration_date??"Por confirmar"}</p></div></Panel>
   <Panel title="Documentos"><div className="space-y-2">{data.quotation&&<DocumentRow label={`Cotización ${data.quotation.quotation_number}`} ready={Boolean(data.quotation.drive_file_id)}/>}<DocumentRow label="Acuerdo" ready={Boolean(data.agreement)}/><DocumentRow label="Acuerdo firmado" ready={agreementSigned}/>{data.documents.map(doc=><DocumentRow key={doc.id} label={doc.document_type} ready={Boolean(doc.drive_file_id)}/>)}</div></Panel>
   <Panel title="Google"><div className="space-y-3"><State label="Invitación de Calendar" ready={data.calendar?.status==="SYNCHRONIZED"}/><State label="Documentos en Drive" ready={data.documents.some(document=>Boolean(document.drive_file_id))}/><State label="Notificaciones por correo" ready={true}/></div></Panel>
   <Panel title="Mensajes" description="Tus mensajes quedan registrados en el historial del evento."><select className="min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" onChange={event=>setType(event.target.value as typeof type)} value={type}><option value="MESSAGE">Mensaje</option><option value="QUESTION">Pregunta</option><option value="ADDITIONAL_SERVICE">Servicio adicional</option><option value="DESIGN_COMMENT">Comentario de diseño</option></select><textarea className="mt-3 min-h-28 w-full rounded-xl border border-border bg-background p-3 text-sm" onChange={event=>setMessage(event.target.value)} placeholder="¿Cómo podemos ayudarte?" value={message}/><ActionButton className="mt-3 w-full" disabled={pending||!message.trim()} icon={Send} label={pending?"Enviando…":"Enviar a BOOMBOX"} onClick={submit} type="button"/><p className="mt-3 text-xs text-muted" role="status">{feedback}</p></Panel>
   {project.status==="COMPLETED"&&<Panel title="Tus recuerdos"><div className="space-y-3"><ActionButton className="w-full" icon={Images} label="Abrir galería"/><ActionButton className="w-full" icon={Download} label="Descargar fotografías" variant="outline"/></div></Panel>}
  </aside></div>
  <footer className="flex flex-col items-center gap-2 border-t border-border/70 py-8 text-center"><ShieldCheck className="size-5 text-brand"/><p className="text-sm font-semibold">Acceso privado y seguro</p><p className="text-xs text-muted">Este enlace vence el {new Intl.DateTimeFormat("es-CL",{dateStyle:"long"}).format(new Date(data.access.expires_at))}.</p></footer>
 </div></main>;
}
function DocumentRow({label,ready}:{label:string;ready:boolean}){return <div className="flex min-h-12 items-center gap-3 rounded-xl border border-border/70 px-3"><FileText className="size-4 text-brand"/><span className="min-w-0 flex-1 truncate text-sm font-medium">{label}</span>{ready?<CheckCircle2 className="size-4 text-success"/>:<StatusBadge label="En preparación" variant="warning"/>}</div>}
