"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Clock3, Download, Eye, FileImage, MessageSquareText, RefreshCw, Send } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { respondToDesignAction } from "./actions";

type PortalData = NonNullable<Awaited<ReturnType<typeof import("./customer-portal.service").loadCustomerPortal>>>;
type Project = PortalData["project"] & { operations: Record<string, unknown> };
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(value)) : "Pendiente";

export function CustomerDesignExperience({data,token}:{data:PortalData;token:string}){
  const router=useRouter();const project=data.project as Project;const designs=data.documents.filter(document=>document.document_type==="DESIGN");const current=designs.at(-1);const version=current?designs.findIndex(document=>document.id===current.id)+1:0;
  const status=String(project.operations.designStatus??(current?"PENDING":"PENDING"));const approved=status==="APPROVED";const rejected=status==="REJECTED"||status==="CHANGES_REQUESTED";const badge=approved?{label:"Aprobado",variant:"success" as const}:rejected?{label:"Rechazado",variant:"danger" as const}:{label:"Pendiente",variant:"warning" as const};
  const comments=data.requests.filter(request=>request.request_type==="DESIGN_COMMENT");const [comment,setComment]=useState("");const [feedback,setFeedback]=useState("");const [pending,startTransition]=useTransition();const [preview,setPreview]=useState(false);const documentUrl=current?`/api/portal/${encodeURIComponent(token)}/design/${current.id}`:"";
  const respond=(decision:"APPROVE"|"REQUEST_CHANGES")=>startTransition(async()=>{const result=await respondToDesignAction({token,decision,comment});setFeedback(result.ok?result.message:result.error);if(result.ok){setComment("");router.refresh();}});

  return <section className="scroll-mt-6 overflow-hidden rounded-3xl border border-border/80 bg-card" id="design"><header className="border-b border-border/70 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Centro de diseño</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Mi diseño</h2><p className="mt-2 text-sm text-muted">Revisa, descarga y responde sobre la versión vigente.</p></div><StatusBadge label={badge.label} variant={badge.variant}/></div>{approved&&<div className="mt-5 flex items-center gap-2 rounded-xl border border-success/25 bg-success/5 p-4 font-semibold text-success"><CheckCircle2 className="size-5"/>✅ Diseño Aprobado</div>}</header>
    <div className="grid gap-6 p-5 sm:p-7 xl:grid-cols-[minmax(0,1.15fr)_minmax(19rem,.85fr)]"><div className="space-y-5"><div className="overflow-hidden rounded-2xl border border-border bg-background">{current&&preview?<iframe className="h-[32rem] w-full bg-white sm:h-[42rem]" src={documentUrl} title="Vista previa del diseño"/>:<div className="flex min-h-80 flex-col items-center justify-center p-8 text-center"><FileImage className="size-10 text-brand"/><p className="mt-4 font-semibold">{current?`Diseño actual · Versión ${version}`:"Diseño pendiente"}</p><p className="mt-2 max-w-sm text-sm leading-6 text-muted">{current?"Abre la vista previa para revisar el archivo preparado por BOOMBOX.":"Tu diseño aparecerá aquí cuando nuestro equipo publique la primera versión."}</p></div>}</div>{current&&<div className="flex flex-wrap gap-3"><ActionButton icon={Eye} label={preview?"Ocultar vista previa":"Ver diseño"} onClick={()=>setPreview(value=>!value)} variant="outline"/><ActionButton icon={Download} label="Descargar diseño" onClick={()=>window.open(`${documentUrl}?download=1`,"_blank","noopener,noreferrer")} variant="outline"/></div>}
      {current&&!approved&&<div className="rounded-2xl border border-border/80 bg-background/30 p-4 sm:p-5"><h3 className="font-semibold">Tu respuesta</h3><textarea className="mt-3 min-h-28 w-full rounded-xl border border-border bg-background p-3 text-sm" onChange={event=>setComment(event.target.value)} placeholder="Escribe aquí los cambios que necesitas" value={comment}/><div className="mt-3 flex flex-col gap-3 sm:flex-row"><ActionButton disabled={pending} icon={CheckCircle2} label={pending?"Guardando…":"Aprobar diseño"} onClick={()=>respond("APPROVE")}/><ActionButton disabled={pending||!comment.trim()} icon={RefreshCw} label="Solicitar cambios" onClick={()=>respond("REQUEST_CHANGES")} variant="outline"/></div><p className="mt-3 text-sm" role="status">{feedback}</p></div>}
    </div><aside className="space-y-5"><Card title="Información"><Row label="Versión actual" value={current?`Versión ${version}`:"Sin versión"}/><Row label="Estado" value={badge.label}/><Row label="Notas del diseñador" value={String(project.operations.designNotes??"Sin notas")}/><Row label="Fecha de aprobación" value={date(String(project.operations.designApprovedAt??""))}/></Card>
      <Card title="Historial de versiones">{designs.length?<ol className="space-y-3">{[...designs].reverse().map((design,index)=><li className="flex items-start gap-3" key={design.id}><FileImage className="mt-0.5 size-4 text-brand"/><div><p className="text-sm font-semibold">Versión {designs.length-index}</p><p className="text-xs text-muted">{date(design.created_at)}</p></div></li>)}</ol>:<Empty text="Sin versiones publicadas."/>}</Card>
      <Card title="Aprobaciones y comentarios">{data.designTimeline.length||comments.length?<div className="space-y-3">{data.designTimeline.map(item=><History key={item.id} label={item.title} value={date(item.occurred_at)}/>) }{comments.map(item=><div className="rounded-xl border border-border/70 p-3" key={item.id}><div className="flex items-center gap-2"><MessageSquareText className="size-4 text-brand"/><p className="text-sm font-semibold">{item.subject||"Comentario del cliente"}</p></div><p className="mt-2 text-sm text-muted">{item.message}</p><p className="mt-2 text-xs text-muted">{date(item.created_at)}</p></div>)}</div>:<Empty text="Aún no existe historial."/>}</Card></aside></div>
  </section>;
}

function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-border/80 bg-background/30 p-4 sm:p-5"><h3 className="font-semibold">{title}</h3><div className="mt-4 space-y-3">{children}</div></section>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 text-sm"><span className="text-muted">{label}</span><strong className="max-w-[60%] text-right">{value}</strong></div>}
function History({label,value}:{label:string;value:string}){return <div className="flex gap-3"><Clock3 className="mt-0.5 size-4 text-brand"/><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted">{value}</p></div></div>}
function Empty({text}:{text:string}){return <div className="flex min-h-20 items-center justify-center rounded-xl border border-dashed border-border p-4 text-center text-sm text-muted"><Send className="mr-2 size-4"/>{text}</div>}
