"use client";

import { useState } from "react";
import Image from "next/image";
import { Download, FolderHeart, Images, Play, Share2 } from "lucide-react";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";

type PortalData=NonNullable<Awaited<ReturnType<typeof import("./customer-portal.service").loadCustomerPortal>>>;
type FileItem=PortalData["gallery"]["photos"][number];

export function CustomerGalleryExperience({data,token}:{data:PortalData;token:string}){
  const gallery=data.gallery;const files=[...gallery.photos,...gallery.videos];const[selected,setSelected]=useState<FileItem|null>(files[0]??null);const[feedback,setFeedback]=useState("");const available=gallery.status==="AVAILABLE";
  const mediaUrl=(file:FileItem)=>`/api/portal/${encodeURIComponent(token)}/gallery/${encodeURIComponent(file.id)}`;
  const share=async(file:FileItem)=>{try{if(!file.webViewLink){setFeedback("El enlace para compartir aún no está disponible.");return}const url=file.webViewLink;if(navigator.share)await navigator.share({title:file.name,text:"Galería BOOMBOX",url});else{await navigator.clipboard.writeText(url);setFeedback("Enlace copiado.")}}catch{setFeedback("No fue posible compartir el archivo.")}};
  return <section className="scroll-mt-6 overflow-hidden rounded-3xl border border-border/80 bg-card" id="gallery"><header className="border-b border-border/70 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Recuerdos BOOMBOX</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Mi galería</h2><p className="mt-2 text-sm text-muted">Tus fotografías, videos y álbumes directamente desde Google Drive.</p></div><StatusBadge label={available?"Galería disponible":"Galería próximamente"} variant={available?"success":"warning"}/></div></header>
    {!available?<div className="flex min-h-80 flex-col items-center justify-center p-8 text-center"><Images className="size-11 text-brand"/><h3 className="mt-4 text-xl font-semibold">Gallery Coming Soon</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted">Tu galería aparecerá aquí cuando BOOMBOX publique el contenido de tu evento.</p></div>:<div className="space-y-6 p-5 sm:p-7">
      {selected&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_18rem]"><div className="relative flex min-h-80 items-center justify-center overflow-hidden rounded-2xl border border-border bg-black sm:min-h-[32rem]">{selected.mimeType.startsWith("video/")?<video className="max-h-[38rem] w-full" controls preload="metadata" src={mediaUrl(selected)}/>:<Image alt={selected.name} className="object-contain" fill sizes="(min-width: 1280px) 70vw, 100vw" src={mediaUrl(selected)} unoptimized/>}</div><aside className="rounded-2xl border border-border/80 bg-background/30 p-5"><p className="text-xs text-muted">Vista actual</p><h3 className="mt-2 break-words font-semibold">{selected.name}</h3>{selected.albumName&&<p className="mt-2 text-sm text-muted">Álbum: {selected.albumName}</p>}<div className="mt-5 grid gap-3"><ActionButton icon={Download} label="Descargar" onClick={()=>window.open(`${mediaUrl(selected)}?download=1`,"_blank","noopener,noreferrer")}/><ActionButton icon={Share2} label="Compartir" onClick={()=>void share(selected)} variant="outline"/></div><p className="mt-3 text-xs text-muted" role="status">{feedback}</p></aside></div>}
      {gallery.albums.length>0&&<div><h3 className="font-semibold">Álbumes</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{gallery.albums.map(album=><button className="flex min-h-20 items-center gap-3 rounded-xl border border-border/80 bg-background/30 p-4 text-left transition-colors hover:border-brand/50" key={album.id} onClick={()=>setSelected(files.find(file=>file.albumId===album.id)??selected)} type="button"><FolderHeart className="size-5 text-brand"/><span><span className="block text-sm font-semibold">{album.name}</span><span className="text-xs text-muted">{album.count} archivos</span></span></button>)}</div></div>}
      <div className="grid gap-6 lg:grid-cols-2"><MediaGrid files={gallery.photos} icon={Images} label="Fotos" onSelect={setSelected} selected={selected}/><MediaGrid files={gallery.videos} icon={Play} label="Videos" onSelect={setSelected} selected={selected}/></div>
    </div>}
  </section>;
}

function MediaGrid({files,icon:Icon,label,onSelect,selected}:{files:FileItem[];icon:typeof Images;label:string;onSelect:(file:FileItem)=>void;selected:FileItem|null}){return <section><div className="flex items-center gap-2"><Icon className="size-5 text-brand"/><h3 className="font-semibold">{label}</h3><span className="text-sm text-muted">{files.length}</span></div>{files.length?<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{files.map(file=><button className={`min-h-24 overflow-hidden rounded-xl border p-3 text-left transition-colors ${selected?.id===file.id?"border-brand bg-brand/5":"border-border/80 bg-background/30 hover:border-brand/50"}`} key={file.id} onClick={()=>onSelect(file)} type="button"><Icon className="size-5 text-brand"/><span className="mt-3 block truncate text-sm font-semibold">{file.name}</span><span className="mt-1 block text-xs text-muted">{file.albumName??label}</span></button>)}</div>:<p className="mt-3 rounded-xl border border-dashed border-border p-4 text-sm text-muted">Sin {label.toLocaleLowerCase("es-CL")} publicadas.</p>}</section>}
