import { StaffManagement, SupabaseStaffRepository, createStaffManagementSnapshot } from "@/features/resources";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { StaffPinReset } from "@/features/portal-authentication";
import { StaffOperationCenter } from "@/features/resources/staff-operation-center";
import type { StaffOperationalRecord } from "@/features/resources/staff-operation-center.actions";
import {StaffPaymentsCenter,type StaffPaymentEvent,type StaffPaymentMonth}from"@/features/staff-payments";

export default async function StaffManagementPage() {
  const client = await createSupabaseServerClient();
  const repository = new SupabaseStaffRepository(client);
  const members = await repository.findAll();
  const [{data:staff,error:staffError},{data:assignments,error:assignmentError},{data:history,error:historyError},{data:audit,error:auditError},{data:vehicles,error:vehicleError},{data:projects,error:projectError}]=await Promise.all([
    client.from("staff").select("id,version,first_name,last_name,rut,phone,email,role,status,bank,account_type,account_number,emergency_contact").is("deleted_at",null).order("last_name"),
    client.from("assignments").select("id,staff_id,project_id,assignment_type,status,resources,arrival_time,start_time,finish_time,assigned_vehicle,projects!inner(name,project_type,event_date),operational_assets(asset_code)").is("deleted_at",null).order("created_at",{ascending:false}),
    client.from("timeline_events").select("id,staff_id,human_message,occurred_at").not("staff_id","is",null).order("occurred_at",{ascending:false}).limit(500),
    client.from("audit_events").select("id,entity_id,action,occurred_at").eq("entity_type","staff").order("occurred_at",{ascending:false}).limit(500),
    client.from("vehicle_profiles").select("asset_id,model,operational_assets!inner(status,deleted_at)").is("operational_assets.deleted_at",null).eq("operational_assets.status","AVAILABLE").order("model"),
    client.from("projects").select("id,name,project_type,event_date").is("deleted_at",null).order("event_date"),
  ]);
  if(staffError)throw staffError;if(assignmentError)throw assignmentError;if(historyError)throw historyError;if(auditError)throw auditError;if(vehicleError)throw vehicleError;if(projectError)throw projectError;
  const[{data:paymentRows,error:paymentError},{data:paymentMonths,error:paymentMonthError}]=await Promise.all([
    client.from("event_staff_payments").select("id,staff_id,total_internal_payment,status,projects!inner(name,event_date)").is("deleted_at",null).order("created_at",{ascending:false}),
    client.from("staff_payment_months").select("id,staff_id,month,tax_amount,advances,paid_amount,status,staff_payment_documents(id,document_type,file_name,created_at)").order("month",{ascending:false}),
  ]);if(paymentError)throw paymentError;if(paymentMonthError)throw paymentMonthError;
  const operationalStaff:StaffOperationalRecord[]=(staff??[]).map((row)=>{const emergency=(row.emergency_contact??{})as Record<string,unknown>;const timelineHistory=(history??[]).filter((item)=>item.staff_id===row.id).map((item)=>({id:`timeline-${item.id}`,message:item.human_message,occurredAt:item.occurred_at}));const auditHistory=(audit??[]).filter((item)=>item.entity_id===row.id).map((item)=>({id:`audit-${item.id}`,message:item.action==="INSERT"?"Perfil de Staff creado.":item.action==="UPDATE"?"Perfil de Staff actualizado.":"Perfil de Staff eliminado.",occurredAt:item.occurred_at}));return{id:row.id,version:row.version,firstName:row.first_name,lastName:row.last_name,rut:row.rut??"",phone:row.phone??"",email:row.email??"",role:row.role as StaffOperationalRecord["role"],status:row.status as StaffOperationalRecord["status"],bank:row.bank??"",accountType:row.account_type??"",accountNumber:row.account_number??"",emergencyName:typeof emergency.name==="string"?emergency.name:"",emergencyPhone:typeof emergency.phone==="string"?emergency.phone:"",assignments:(assignments??[]).filter((item)=>item.staff_id===row.id).flatMap((item)=>{const project=Array.isArray(item.projects)?item.projects[0]:item.projects;if(!project)return[];const asset=Array.isArray(item.operational_assets)?item.operational_assets[0]:item.operational_assets;const resources=(item.resources??{})as Record<string,unknown>;return[{id:item.id,projectId:item.project_id,eventName:project.name,service:project.project_type,date:project.event_date,vehicle:asset?.asset_code??(typeof resources.vehicle==="string"?resources.vehicle:"Sin vehículo"),role:item.assignment_type,status:item.status,arrivalTime:item.arrival_time?.slice(0,5)??"",startTime:item.start_time?.slice(0,5)??"",finishTime:item.finish_time?.slice(0,5)??""}];}),history:[...timelineHistory,...auditHistory].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt))};});
  const projectOptions=(projects??[]).map((project)=>({id:project.id,label:`${project.name} · ${project.event_date}`,service:project.project_type,date:project.event_date}));
  const vehicleOptions=(vehicles??[]).map((vehicle)=>({id:vehicle.asset_id,label:vehicle.model}));
  const paymentEvents:StaffPaymentEvent[]=(paymentRows??[]).flatMap(row=>{const project=Array.isArray(row.projects)?row.projects[0]:row.projects;return project?[{id:row.id,staffId:row.staff_id,eventName:project.name,eventDate:project.event_date,amount:Number(row.total_internal_payment),status:row.status}]:[]});
  const monthlyRecords:StaffPaymentMonth[]=(paymentMonths??[]).map(row=>({id:row.id,staffId:row.staff_id,month:row.month,tax:Number(row.tax_amount),advances:Number(row.advances),paid:Number(row.paid_amount),status:row.status,documents:(row.staff_payment_documents??[]).map(document=>({id:document.id,type:document.document_type,name:document.file_name,createdAt:document.created_at}))}));
  return <div className="space-y-8"><StaffOperationCenter initialStaff={operationalStaff} projects={projectOptions} vehicles={vehicleOptions}/><StaffPaymentsCenter staff={operationalStaff.map(member=>({id:member.id,name:`${member.firstName} ${member.lastName}`,rut:member.rut}))} events={paymentEvents} months={monthlyRecords}/><StaffPinReset members={members.map(member=>({id:member.profile.id,name:`${member.profile.firstName} ${member.profile.lastName}`}))}/><details className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-semibold">Vista operacional detallada y disponibilidad</summary><div className="mt-6"><StaffManagement snapshot={createStaffManagementSnapshot({ members })} /></div></details></div>;
}
