import { StaffManagement, SupabaseStaffRepository, createStaffManagementSnapshot } from "@/features/resources";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { StaffPinReset } from "@/features/portal-authentication";
import { StaffOperationCenter } from "@/features/resources/staff-operation-center";
import type { StaffOperationalRecord } from "@/features/resources/staff-operation-center.actions";
import {StaffPaymentsCenter,type StaffPaymentEvent,type StaffPaymentMonth}from"@/features/staff-payments";
import { PersonalWorkspaceSections } from "@/features/founder-workspace";

export default async function StaffManagementPage() {
  const client = await createSupabaseServerClient();
  const repository = new SupabaseStaffRepository(client);
  const members = await repository.findAll();
  const [{data:staff,error:staffError},{data:assignments,error:assignmentError},{data:history,error:historyError},{data:audit,error:auditError},{data:vehicles,error:vehicleError},{data:projects,error:projectError}]=await Promise.all([
    client.from("staff").select("id,version,first_name,last_name,rut,phone,email,role,capabilities,status,bank,account_type,account_number,emergency_contact,portal_enabled,pin_updated_at,portal_password_change_required,portal_invitation_sent_at").is("deleted_at",null).order("last_name"),
    client.from("assignments").select("id,staff_id,project_id,assignment_type,status,resources,arrival_time,start_time,finish_time,assigned_vehicle,projects!inner(name,project_type,event_date),operational_assets(asset_code)").is("deleted_at",null).order("created_at",{ascending:false}),
    client.from("timeline_events").select("id,staff_id,human_message,occurred_at").not("staff_id","is",null).order("occurred_at",{ascending:false}).limit(500),
    client.from("audit_events").select("id,entity_id,action,occurred_at").eq("entity_type","staff").order("occurred_at",{ascending:false}).limit(500),
    client.from("vehicle_profiles").select("asset_id,model,operational_assets!inner(status,deleted_at)").is("operational_assets.deleted_at",null).eq("operational_assets.status","AVAILABLE").order("model"),
    client.from("projects").select("id,name,project_type,event_date").is("deleted_at",null).order("event_date"),
  ]);
  if(staffError)throw staffError;if(assignmentError)throw assignmentError;if(historyError)throw historyError;if(auditError)throw auditError;if(vehicleError)throw vehicleError;if(projectError)throw projectError;
  const[{data:paymentRows,error:paymentError},{data:paymentMonths,error:paymentMonthError},{data:financialEvents,error:financialEventsError}]=await Promise.all([
    client.from("event_staff_payments").select("id,staff_id,tasks,total_internal_payment,operator_payment,assembly_payment,disassembly_payment,override_reason,status,settlement_status,paid_amount,paid_at,sii_receipt_status,projects!inner(id,name,event_date,project_type,customer_id,customers!projects_customer_id_fkey(full_name),project_services(service_code,duration_hours))").is("deleted_at",null).order("created_at",{ascending:false}),
    client.from("staff_payment_months").select("id,staff_id,month,tax_amount,advances,paid_amount,status,staff_payment_documents(id,document_type,file_name,created_at)").order("month",{ascending:false}),
    client.from("financial_event_records").select("project_id,revenue,status"),
  ]);if(paymentError)throw paymentError;if(paymentMonthError)throw paymentMonthError;if(financialEventsError)throw financialEventsError;
  const today=new Date().toISOString().slice(0,10);const revenueByProject=new Map((financialEvents??[]).filter(item=>item.status==="CONFIRMED").map(item=>[item.project_id,Number(item.revenue)]));
  const operationalStaff:StaffOperationalRecord[]=(staff??[]).map((row)=>{const emergency=(row.emergency_contact??{})as Record<string,unknown>;const timelineHistory=(history??[]).filter((item)=>item.staff_id===row.id).map((item)=>({id:`timeline-${item.id}`,message:item.human_message,occurredAt:item.occurred_at}));const auditHistory=(audit??[]).filter((item)=>item.entity_id===row.id).map((item)=>({id:`audit-${item.id}`,message:item.action==="INSERT"?"Perfil de Staff creado.":item.action==="UPDATE"?"Perfil de Staff actualizado.":"Perfil de Staff eliminado.",occurredAt:item.occurred_at}));const memberAssignments=(assignments??[]).filter((item)=>item.staff_id===row.id).flatMap((item)=>{const project=Array.isArray(item.projects)?item.projects[0]:item.projects;if(!project)return[];const asset=Array.isArray(item.operational_assets)?item.operational_assets[0]:item.operational_assets;const resources=(item.resources??{})as Record<string,unknown>;return[{id:item.id,projectId:item.project_id,eventName:project.name,service:project.project_type,date:project.event_date,vehicle:asset?.asset_code??(typeof resources.vehicle==="string"?resources.vehicle:"Sin vehículo"),role:item.assignment_type,status:item.status,arrivalTime:item.arrival_time?.slice(0,5)??"",startTime:item.start_time?.slice(0,5)??"",finishTime:item.finish_time?.slice(0,5)??""}];});const memberPayments=(paymentRows??[]).filter(item=>item.staff_id===row.id&&item.status!=="CANCELLED");const projectIds=new Set(memberAssignments.map(item=>item.projectId));return{id:row.id,version:row.version,firstName:row.first_name,lastName:row.last_name,rut:row.rut??"",phone:row.phone??"",email:row.email??"",role:row.role as StaffOperationalRecord["role"],skills:(row.capabilities??[]) as StaffOperationalRecord["skills"],status:row.status as StaffOperationalRecord["status"],bank:row.bank??"",accountType:row.account_type??"",accountNumber:row.account_number??"",emergencyName:typeof emergency.name==="string"?emergency.name:"",emergencyPhone:typeof emergency.phone==="string"?emergency.phone:"",assignments:memberAssignments,history:[...timelineHistory,...auditHistory].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)),financial:{upcomingEvents:new Set(memberAssignments.filter(item=>item.date>=today&&!['COMPLETED','CANCELLED','REJECTED'].includes(item.status)).map(item=>item.projectId)).size,pendingPayments:memberPayments.filter(item=>item.status!=="PAID").reduce((sum,item)=>sum+Number(item.total_internal_payment),0),completedEvents:new Set(memberAssignments.filter(item=>item.status==="COMPLETED").map(item=>item.projectId)).size,revenueGenerated:[...projectIds].reduce((sum,id)=>sum+(revenueByProject.get(id)??0),0),totalCost:memberPayments.reduce((sum,item)=>sum+Number(item.total_internal_payment),0)}};});
  const projectOptions=(projects??[]).map((project)=>({id:project.id,label:`${project.name} · ${project.event_date}`,service:project.project_type,date:project.event_date}));
  const vehicleOptions=(vehicles??[]).map((vehicle)=>({id:vehicle.asset_id,label:vehicle.model}));
  const paymentEvents:StaffPaymentEvent[]=(paymentRows??[]).flatMap(row=>{const project=Array.isArray(row.projects)?row.projects[0]:row.projects;if(!project)return[];const customer=Array.isArray(project.customers)?project.customers[0]:project.customers;const service=Array.isArray(project.project_services)?project.project_services[0]:project.project_services;return[{id:row.id,staffId:row.staff_id,projectId:project.id,eventName:project.name,eventDate:project.event_date,customer:customer?.full_name??"Sin cliente",service:service?.service_code??project.project_type,durationHours:Number(service?.duration_hours??0),roles:row.tasks??[],amount:Number(row.total_internal_payment),operator:Number(row.operator_payment),assembly:Number(row.assembly_payment),disassembly:Number(row.disassembly_payment),overrideReason:row.override_reason??"",status:row.status,settlementStatus:row.settlement_status,paidAmount:Number(row.paid_amount),paidAt:row.paid_at??"",receiptStatus:row.sii_receipt_status}]});
  const monthlyRecords:StaffPaymentMonth[]=(paymentMonths??[]).map(row=>({id:row.id,staffId:row.staff_id,month:row.month,tax:Number(row.tax_amount),advances:Number(row.advances),paid:Number(row.paid_amount),status:row.status,documents:(row.staff_payment_documents??[]).map(document=>({id:document.id,type:document.document_type,name:document.file_name,createdAt:document.created_at}))}));
  return <PersonalWorkspaceSections moduleKey="STAFF" sections={[
    {key:"STAFF_CENTER",label:"Gestión de Staff",content:<StaffOperationCenter initialStaff={operationalStaff} projects={projectOptions} vehicles={vehicleOptions}/>},
    {key:"STAFF_PAYMENTS",label:"Pagos de Staff",content:<StaffPaymentsCenter staff={operationalStaff.map(member=>({id:member.id,name:`${member.firstName} ${member.lastName}`,rut:member.rut}))} events={paymentEvents} months={monthlyRecords}/>},
    {key:"STAFF_ACCESS",label:"Accesos de Staff",content:<StaffPinReset members={(staff??[]).map(member=>({id:member.id,name:`${member.first_name} ${member.last_name}`,rut:member.rut??"",email:member.email??"",enabled:Boolean(member.portal_enabled),hasPin:Boolean(member.pin_updated_at),firstLoginPending:Boolean(member.portal_password_change_required),invitationSentAt:member.portal_invitation_sent_at??null}))}/>},
    {key:"STAFF_AVAILABILITY",label:"Disponibilidad detallada",content:<details className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-semibold">Vista operacional detallada y disponibilidad</summary><div className="mt-6"><StaffManagement snapshot={createStaffManagementSnapshot({ members })} /></div></details>},
  ]}/>;
}
