"use client";
import {useState,useTransition} from "react";
import {Archive,CalendarDays,CheckCircle2,Download,FileSpreadsheet,FileText,Settings2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {saveAccountantExportConfigAction} from "./actions";
import type {AccountantExportConfig} from "./types";

const files=["01_VENTAS.xlsx","02_COMPRAS.xlsx","03_PAGOS.xlsx","04_COBRANZAS.xlsx","05_MOVIMIENTOS_BANCARIOS.xlsx","06_RESUMEN_CONTABLE.pdf"];
export function AccountantExportCenter({initialConfig}:{initialConfig:AccountantExportConfig}){const now=new Date();const year=now.getFullYear(),month=String(now.getMonth()+1).padStart(2,"0");const lastDay=String(new Date(year,now.getMonth()+1,0).getDate()).padStart(2,"0");const[from,setFrom]=useState(`${year}-${month}-01`);const[to,setTo]=useState(`${year}-${month}-${lastDay}`);const[config,setConfig]=useState(initialConfig);const[isSaving,startSaving]=useTransition();const[message,setMessage]=useState("");const valid=Boolean(from&&to&&from<=to);const href=(format:string)=>`/api/finance/accountant-export?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&format=${format.toLowerCase()}`;const preferred=config.preferredFormat.toLowerCase();
  const save=()=>startSaving(async()=>{const form=new FormData();Object.entries(config).forEach(([key,value])=>form.set(key,value));const result=await saveAccountantExportConfigAction(form);setMessage(result.ok?result.message:result.error)});
  return <main className="space-y-6"><header className="rounded-3xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Finanzas · Cierre mensual</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Centro de Exportación Contable</h1><p className="mt-3 max-w-3xl text-sm text-muted sm:text-base">Prepara ventas, compras, pagos, cobranzas, movimientos bancarios y el resumen mensual usando únicamente los registros productivos de ORBIT.</p></header>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-5"><article className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand/10 text-brand"><CalendarDays className="size-5"/></span><div><h2 className="font-semibold">Período contable</h2><p className="text-sm text-muted">Selecciona el rango exacto que recibirá Contabilidad.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Desde <span className="block text-xs font-normal text-muted">DD/MM/AAAA</span><input className="h-12 w-full rounded-xl border bg-background px-3" onChange={event=>setFrom(event.target.value)} type="date" value={from}/></label><label className="space-y-2 text-sm font-medium">Hasta <span className="block text-xs font-normal text-muted">DD/MM/AAAA</span><input className="h-12 w-full rounded-xl border bg-background px-3" onChange={event=>setTo(event.target.value)} type="date" value={to}/></label></div>{!valid&&<p className="mt-3 text-sm text-red-500">La fecha final debe ser igual o posterior a la fecha inicial.</p>}</article>
      <article className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand/10 text-brand"><Download className="size-5"/></span><div><h2 className="font-semibold">Formatos disponibles</h2><p className="text-sm text-muted">Descarga el paquete completo o un formato individual.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button asChild className="min-h-12 sm:col-span-2"><a aria-disabled={!valid} href={valid?href(preferred):undefined}><Archive className="size-4"/>📤 EXPORTAR PARA CONTADOR</a></Button><Button asChild variant="outline"><a aria-disabled={!valid} href={valid?href("xlsx"):undefined}><FileSpreadsheet className="size-4"/>Excel (.xlsx)</a></Button><Button asChild variant="outline"><a aria-disabled={!valid} href={valid?href("csv"):undefined}><FileText className="size-4"/>CSV (.csv)</a></Button><Button asChild variant="outline"><a aria-disabled={!valid} href={valid?href("pdf"):undefined}><FileText className="size-4"/>PDF (.pdf)</a></Button><Button asChild variant="outline"><a aria-disabled={!valid} href={valid?href("zip"):undefined}><Archive className="size-4"/>ZIP completo</a></Button></div></article></div>
      <aside className="space-y-5"><article className="rounded-2xl border border-brand/25 bg-brand/[.04] p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-brand">Paquete automático</p><h2 className="mt-2 text-xl font-semibold">CONTABILIDAD_MES_AAAA.zip</h2><div className="mt-4 space-y-2">{files.map(file=><div className="flex items-center gap-2 text-sm" key={file}><CheckCircle2 className="size-4 shrink-0 text-brand"/><span>{file}</span></div>)}</div><p className="mt-5 border-t pt-4 text-xs leading-5 text-muted">Los saldos se concilian con las fuentes productivas y se eliminan duplicados de comprobantes de combustible ya registrados como gasto.</p></article></aside></section>
    <section className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><Settings2 className="size-5 text-brand"/><div><h2 className="font-semibold">Configuración administrativa</h2><p className="text-sm text-muted">Preferencias persistentes para futuras exportaciones.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Select label="Formato preferido" value={config.preferredFormat} onChange={value=>setConfig({...config,preferredFormat:value as AccountantExportConfig["preferredFormat"]})} options={["ZIP","XLSX","CSV","PDF"]}/><Select label="Formato de fecha" value={config.dateFormat} onChange={value=>setConfig({...config,dateFormat:value as AccountantExportConfig["dateFormat"]})} options={["DD/MM/YYYY","YYYY-MM-DD"]}/><Select label="Separador decimal" value={config.decimalSeparator} onChange={value=>setConfig({...config,decimalSeparator:value as AccountantExportConfig["decimalSeparator"]})} options={[",","."]}/><Select label="Separador CSV" value={config.csvSeparator} onChange={value=>setConfig({...config,csvSeparator:value as AccountantExportConfig["csvSeparator"]})} options={[";",","]}/><label className="space-y-2 text-sm font-medium">Software contable<input className="h-11 w-full rounded-xl border bg-background px-3" onChange={event=>setConfig({...config,accountingSoftware:event.target.value})} value={config.accountingSoftware}/></label></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button disabled={isSaving} onClick={save}>{isSaving?"Guardando...":"Guardar configuración"}</Button>{message&&<p className="text-sm text-muted" role="status">{message}</p>}</div></section></main>}
function Select({label,onChange,options,value}:{label:string;onChange:(value:string)=>void;options:string[];value:string}){return <label className="space-y-2 text-sm font-medium">{label}<select className="h-11 w-full rounded-xl border bg-background px-3" onChange={event=>onChange(event.target.value)} value={value}>{options.map(option=><option key={option} value={option}>{option}</option>)}</select></label>}
