import type {SupabaseClient} from "@supabase/supabase-js";
import type {AccountantExportData,AccountantSummary,Cell,ExportTable} from "./types";

const n=(value:unknown)=>Number(value??0)||0;
const relation=<T>(value:unknown):T|undefined=>Array.isArray(value)?value[0] as T|undefined:value as T|undefined;
const metadata=(value:unknown):Record<string,unknown>=>{if(value&&typeof value==="object")return value as Record<string,unknown>;try{return JSON.parse(String(value??"{}"))}catch{return{}}};

export async function loadAccountantExportData(client:SupabaseClient,from:string,to:string):Promise<AccountantExportData>{
  const [companyResult,invoicesResult,paymentsResult,expensesResult,staffEventsResult,fuelResult,vehiclesResult,profitsResult]=await Promise.all([
    client.from("company_settings").select("legal_name,tax_id,currency").eq("settings_key","PRIMARY").maybeSingle(),
    client.from("accounts_receivable_projection").select("id,invoice_number,quotation_id,customer_type,status,effective_status,issue_date,due_date,payment_term,amount,paid_amount,outstanding_balance,customers(full_name,metadata),quotations(subtotal,tax_total,grand_total,final_customer_price)").lte("issue_date",to).order("issue_date"),
    client.from("invoice_payments").select("id,invoice_id,amount,paid_at,method,reference,invoices(invoice_number,customer_id,customers(full_name))").gte("paid_at",`${from}T00:00:00`).lte("paid_at",`${to}T23:59:59.999`).order("paid_at"),
    client.from("expenses").select("id,occurred_on,category,supplier,document_number,subtotal,vat,total,status,receipt_path,approval_reason").is("deleted_at",null).gte("occurred_on",from).lte("occurred_on",to).order("occurred_on"),
    client.from("event_staff_payments").select("id,project_id,total_internal_payment,paid_amount,paid_at,settlement_status,status,staff(first_name,last_name,bank,account_number),projects!inner(name,event_date)").is("deleted_at",null).neq("status","CANCELLED").gte("projects.event_date",from).lte("projects.event_date",to).order("paid_at"),
    client.from("vehicle_fuel_logs").select("id,asset_id,fuel_date,total_amount,receipt_path,gas_station").gte("fuel_date",from).lte("fuel_date",to).order("fuel_date"),
    client.from("vehicle_profiles").select("asset_id,model"),
    client.from("profit_snapshots").select("id,project_id,revenue,operational_cost,gross_margin,gross_margin_percent,created_at,projects!inner(event_date)").is("deleted_at",null).gte("projects.event_date",from).lte("projects.event_date",to).order("created_at",{ascending:false}),
  ]);
  const error=companyResult.error??invoicesResult.error??paymentsResult.error??expensesResult.error??staffEventsResult.error??fuelResult.error??vehiclesResult.error??profitsResult.error;if(error)throw error;
  const company=companyResult.data??{legal_name:"BOOMBOX",tax_id:"",currency:"CLP"};
  const invoices=invoicesResult.data??[];const periodInvoices=invoices.filter(row=>row.issue_date&&row.issue_date>=from&&row.issue_date<=to);
  const salesRows:Cell[][]=periodInvoices.map(invoice=>{const customer=relation<{full_name?:string;metadata?:unknown}>(invoice.customers);const quote=relation<{subtotal?:number;tax_total?:number;grand_total?:number;final_customer_price?:number}>(invoice.quotations);const total=n(invoice.amount);const vat=n(quote?.tax_total);const net=quote?n(quote.subtotal):Math.max(0,total-vat);return[invoice.issue_date,invoice.customer_type==="CORPORATE"?"Factura":"Reserva",invoice.invoice_number,String(metadata(customer?.metadata).rut??""),customer?.full_name??"",net,vat,Math.max(0,total-net-vat),total,invoice.payment_term,invoice.effective_status,invoice.due_date]});
  const purchaseRows:Cell[][]=(expensesResult.data??[]).map(expense=>{const meta=metadata(expense.approval_reason);return[expense.occurred_on,expense.supplier??"",String(meta.supplierRut??""),String(meta.documentType??"Otro"),expense.document_number??"",n(expense.subtotal),n(expense.vat),n(meta.exempt),n(expense.total),String(meta.paymentMethod??""),expense.status]});
  const paymentRows:Cell[][]=[];const bankRows:{date:string;bank:string;account:string;description:string;income:number;expense:number;document:string}[]=[];
  for(const expense of expensesResult.data??[]){if(expense.status!=="PAID")continue;const meta=metadata(expense.approval_reason);const bank=String(meta.bank??"");const method=String(meta.paymentMethod??"");paymentRows.push([expense.occurred_on,expense.supplier??"Proveedor",expense.document_number??expense.category,n(expense.total),method,bank,expense.status]);bankRows.push({date:expense.occurred_on,bank,account:String(meta.account??""),description:expense.supplier??expense.category,income:0,expense:n(expense.total),document:expense.document_number??""});}
  for(const settlement of staffEventsResult.data??[]){const paid=n(settlement.paid_amount);if(paid<=0)continue;const staff=relation<{first_name?:string;last_name?:string;bank?:string;account_number?:string}>(settlement.staff);const project=relation<{name?:string;event_date?:string}>(settlement.projects);const name=`${staff?.first_name??""} ${staff?.last_name??""}`.trim()||"Staff BOOMBOX";const date=settlement.paid_at??project?.event_date??from;const document=`Liquidación Evento · ${project?.name??settlement.project_id}`;paymentRows.push([date,name,document,paid,"Transferencia",staff?.bank??"",settlement.settlement_status]);bankRows.push({date,bank:staff?.bank??"",account:staff?.account_number??"",description:`Pago Staff · ${name}`,income:0,expense:paid,document});}
  const expenseReceipts=new Set((expensesResult.data??[]).map(row=>row.receipt_path).filter(Boolean));const vehicles=new Map((vehiclesResult.data??[]).map(row=>[row.asset_id,row.model]));
  for(const fuel of fuelResult.data??[]){if(expenseReceipts.has(fuel.receipt_path))continue;const vehicle=vehicles.get(fuel.asset_id)??"Vehículo";paymentRows.push([fuel.fuel_date,fuel.gas_station??vehicle,`Combustible · ${vehicle}`,n(fuel.total_amount),"","","Pagado"]);bankRows.push({date:fuel.fuel_date,bank:"",account:"",description:`Combustible · ${vehicle}`,income:0,expense:n(fuel.total_amount),document:""});}
  const invoiceMap=new Map(invoices.map(row=>[row.id,row]));const collectionRows:Cell[][]=[];
  for(const payment of paymentsResult.data??[]){const linked=relation<{invoice_number?:string;customers?:unknown}>(payment.invoices);const customer=relation<{full_name?:string}>(linked?.customers);const invoice=invoiceMap.get(payment.invoice_id);collectionRows.push([payment.paid_at.slice(0,10),customer?.full_name??"",linked?.invoice_number??"",n(payment.amount),n(invoice?.outstanding_balance),payment.method]);bankRows.push({date:payment.paid_at.slice(0,10),bank:"",account:"",description:`Cobranza · ${customer?.full_name??linked?.invoice_number??"Cliente"}`,income:n(payment.amount),expense:0,document:linked?.invoice_number??""});}
  bankRows.sort((a,b)=>a.date.localeCompare(b.date));let balance=0;const bankMovementRows:Cell[][]=bankRows.map(row=>{balance+=row.income-row.expense;return[row.date,row.bank,row.account,row.description,row.income,row.expense,balance,row.document]});
  const latestProfit=new Map<string,NonNullable<typeof profitsResult.data>[number]>();for(const row of profitsResult.data??[])if(!latestProfit.has(row.project_id))latestProfit.set(row.project_id,row);const profits=[...latestProfit.values()];const profitRevenue=profits.reduce((sum,row)=>sum+n(row.revenue),0);const gross=profits.reduce((sum,row)=>sum+n(row.gross_margin),0);
  const summary:AccountantSummary={totalRevenue:salesRows.reduce((sum,row)=>sum+n(row[8]),0),totalExpenses:purchaseRows.reduce((sum,row)=>sum+n(row[8]),0),totalIncome:collectionRows.reduce((sum,row)=>sum+n(row[3]),0),totalOutgoing:paymentRows.reduce((sum,row)=>sum+n(row[3]),0),netRevenue:salesRows.reduce((sum,row)=>sum+n(row[5]),0),netExpenses:purchaseRows.reduce((sum,row)=>sum+n(row[5])+n(row[7]),0),vatDebit:salesRows.reduce((sum,row)=>sum+n(row[6]),0),vatCredit:purchaseRows.reduce((sum,row)=>sum+n(row[6]),0),vatDifference:0,accountsReceivable:invoices.filter(row=>row.status!=="CANCELLED"&&(!row.issue_date||row.issue_date<=to)).reduce((sum,row)=>sum+n(row.outstanding_balance),0),accountsPayable:purchaseRows.filter(row=>row[10]!=="PAID"&&row[10]!=="CANCELLED").reduce((sum,row)=>sum+n(row[8]),0),bankBalance:balance,grossMargin:gross,netMargin:profitRevenue?gross/profitRevenue:0};summary.vatDifference=summary.vatDebit-summary.vatCredit;
  const tables:ExportTable[]=[
    {name:"VENTAS",fileName:"01_VENTAS.xlsx",headers:["Fecha","Tipo de Documento","Número de Documento","RUT Cliente","Nombre Cliente","Monto Neto","IVA","Monto Exento","Total","Método de Pago","Estado","Fecha de Vencimiento"],rows:salesRows},
    {name:"COMPRAS",fileName:"02_COMPRAS.xlsx",headers:["Fecha","Proveedor","RUT Proveedor","Tipo de Documento","Número de Documento","Monto Neto","IVA","Monto Exento","Total","Método de Pago","Estado"],rows:purchaseRows},
    {name:"PAGOS",fileName:"03_PAGOS.xlsx",headers:["Fecha","Proveedor / Staff","Documento Relacionado","Monto","Método de Pago","Banco","Estado"],rows:paymentRows},
    {name:"COBRANZAS",fileName:"04_COBRANZAS.xlsx",headers:["Fecha","Cliente","Documento Relacionado","Monto Cobrado","Saldo Pendiente","Método de Pago"],rows:collectionRows},
    {name:"MOVIMIENTOS_BANCARIOS",fileName:"05_MOVIMIENTOS_BANCARIOS.xlsx",headers:["Fecha","Banco","Cuenta","Descripción","Ingreso","Egreso","Saldo","Documento Relacionado"],rows:bankMovementRows},
  ];return{from,to,company:{legalName:company.legal_name,taxId:company.tax_id??"",currency:company.currency},tables,summary};
}
