import ExcelJS from "exceljs";
import JSZip from "jszip";
import {PDFDocument,rgb,StandardFonts} from "pdf-lib";
import type {AccountantExportConfig,AccountantExportData,Cell,ExportTable} from "./types";

const orange="F28E2B",dark="151515";
function workbook(){const book=new ExcelJS.Workbook();book.creator="ORBIT · BOOMBOX";book.company="BOOMBOX";book.created=new Date();return book}
function addSheet(book:ExcelJS.Workbook,table:ExportTable){const sheet=book.addWorksheet(table.name.slice(0,31),{views:[{state:"frozen",ySplit:1,showGridLines:false}]});sheet.addRow(table.headers);for(const row of table.rows)sheet.addRow(row);const header=sheet.getRow(1);header.height=28;header.eachCell(cell=>{cell.font={bold:true,color:{argb:"FFFFFFFF"}};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:`FF${dark}`}};cell.alignment={vertical:"middle"};});sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,sheet.rowCount),column:table.headers.length}};sheet.columns.forEach((column,index)=>{const values=[table.headers[index],...table.rows.map(row=>String(row[index]??""))];column.width=Math.min(34,Math.max(12,...values.map(value=>value.length+2)));if(table.headers[index]?.match(/Monto|IVA|Total|Saldo|Ingreso|Egreso/))column.numFmt='"$"#,##0;[Red]("$"#,##0);-';});sheet.getRow(1).eachCell(cell=>{cell.border={bottom:{style:"medium",color:{argb:`FF${orange}`}}};});return sheet}
export async function createSingleWorkbook(data:AccountantExportData){const book=workbook();for(const table of data.tables)addSheet(book,table);return Buffer.from(await book.xlsx.writeBuffer())}
export async function createTableWorkbook(table:ExportTable){const book=workbook();addSheet(book,table);return Buffer.from(await book.xlsx.writeBuffer())}

function csvCell(value:Cell,separator:string,decimalSeparator:string){const raw=typeof value==="number"?String(value).replace(".",decimalSeparator):String(value??"");return `"${raw.replaceAll('"','""')}"`.replaceAll(`"${separator}`,`"${separator}`)}
export function createCsv(data:AccountantExportData,config:AccountantExportConfig){const rows:string[]=[];for(const table of data.tables){rows.push(`"${table.name}"`,table.headers.map(value=>csvCell(value,config.csvSeparator,config.decimalSeparator)).join(config.csvSeparator),...table.rows.map(row=>row.map(value=>csvCell(value,config.csvSeparator,config.decimalSeparator)).join(config.csvSeparator)),"");}return Buffer.from(`\ufeff${rows.join("\r\n")}`,"utf8")}

const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
export async function createSummaryPdf(data:AccountantExportData){const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const page=pdf.addPage([595.28,841.89]);const {height}=page.getSize();page.drawRectangle({x:0,y:height-128,width:595.28,height:128,color:rgb(.055,.055,.055)});page.drawText("ORBIT",{x:46,y:height-62,size:24,font:bold,color:rgb(1,1,1)});page.drawText("RESUMEN CONTABLE",{x:46,y:height-92,size:13,font:bold,color:rgb(.95,.56,.17)});page.drawText(`${data.company.legalName} · ${data.company.taxId||"RUT no informado"}`,{x:46,y:height-111,size:9,font:regular,color:rgb(.75,.75,.78)});page.drawText(`Periodo: ${data.from} al ${data.to}`,{x:46,y:height-155,size:10,font:bold,color:rgb(.16,.16,.18)});const entries:[string,number,boolean?][]=[["Total ingresos por ventas",data.summary.totalRevenue],["Total gastos",data.summary.totalExpenses],["Total cobrado",data.summary.totalIncome],["Total egresado",data.summary.totalOutgoing],["Ingresos netos",data.summary.netRevenue],["Gastos netos",data.summary.netExpenses],["IVA débito",data.summary.vatDebit],["IVA crédito",data.summary.vatCredit],["Diferencia IVA",data.summary.vatDifference,true],["Cuentas por cobrar",data.summary.accountsReceivable],["Cuentas por pagar",data.summary.accountsPayable],["Saldo bancario del período",data.summary.bankBalance,true],["Margen bruto",data.summary.grossMargin],["Margen neto",data.summary.netMargin*100,true]];let y=height-196;for(const[label,value,strong]of entries){if(strong)page.drawRectangle({x:40,y:y-9,width:515,height:30,color:rgb(.965,.965,.97)});page.drawText(label,{x:50,y,size:10,font:strong?bold:regular,color:rgb(.2,.2,.22)});const shown=label==="Margen neto"?`${value.toFixed(1)}%`:money(value);page.drawText(shown,{x:392,y,size:10,font:bold,color:strong?rgb(.85,.38,.05):rgb(.12,.12,.14)});y-=36;}page.drawText("Generado con datos productivos de ORBIT. Sin registros duplicados.",{x:46,y:42,size:8,font:regular,color:rgb(.45,.45,.48)});return Buffer.from(await pdf.save())}

export async function createZip(data:AccountantExportData){const zip=new JSZip();for(const table of data.tables)zip.file(table.fileName,await createTableWorkbook(table));zip.file("06_RESUMEN_CONTABLE.pdf",await createSummaryPdf(data));return zip.generateAsync({type:"nodebuffer",compression:"DEFLATE",compressionOptions:{level:6}})}
