"use client";
import Link from "next/link";
import { useMemo,useState,useTransition } from "react";
import { CalendarClock,ExternalLink,FileSignature,History,Landmark,Mail,ReceiptText,Search,TriangleAlert,WalletCards } from "lucide-react";
import { WorkspaceLayout } from "@/components/layout/workspace-layout";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { getReceivableContractUrlAction,sendReceivableReminderAction } from "./actions";
import type { ReceivableDataset,ReceivableInvoice } from "./types";

const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
const date=(value:string|null)=>value?new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"Sin fecha";
type DisplayStatus="PENDING"|"PARTIAL"|"PAID"|"OVERDUE"|"CREDIT"|"CANCELLED"|"ARCHIVED";
const statusMeta:Record<DisplayStatus,{label:string;variant:"neutral"|"info"|"warning"|"success"|"danger"}>={PENDING:{label:"Pendiente",variant:"warning"},PARTIAL:{label:"Parcial",variant:"warning"},PAID:{label:"Pagado",variant:"success"},OVERDUE:{label:"Vencido",variant:"danger"},CREDIT:{label:"Crédito",variant:"info"},CANCELLED:{label:"Cancelado",variant:"neutral"},ARCHIVED:{label:"Archivado",variant:"neutral"}};
function displayStatus(invoice:ReceivableInvoice):DisplayStatus{if(invoice.recordState==="ARCHIVED")return"ARCHIVED";if(invoice.status==="CANCELLED")return"CANCELLED";if(invoice.status==="PAID")return"PAID";if(invoice.status==="OVERDUE")return"OVERDUE";if(invoice.status==="PARTIALLY_PAID")return"PARTIAL";if(invoice.paymentTerm!=="CASH")return"CREDIT";return"PENDING";}

export function AccountsReceivableCenter({dataset}:{dataset:ReceivableDataset}){
 const[query,setQuery]=useState("");const[status,setStatus]=useState<"ALL"|DisplayStatus>("ALL");const[month,setMonth]=useState("");const[amount,setAmount]=useState("");const[view,setView]=useState<"ACTIVE"|"HISTORY">("ACTIVE");
 const source=view==="ACTIVE"?dataset.invoices:dataset.historyInvoices;
 const invoices=useMemo(()=>source.filter(invoice=>{const state=displayStatus(invoice);const text=`${invoice.customerName} ${invoice.projectName} ${invoice.service} ${invoice.invoiceNumber}`.toLowerCase();const monthValue=invoice.dueDate??invoice.issueDate??"";return(status==="ALL"||state===status)&&(!query||text.includes(query.toLowerCase()))&&(!month||monthValue.startsWith(month))&&(!amount||[invoice.amount,invoice.paidAmount,invoice.outstandingBalance].some(value=>String(Math.round(value)).includes(amount.replace(/\D/g,""))));}),[amount,month,query,source,status]);
 return <WorkspaceLayout bottomAction={null} className="max-w-none p-0" copilot={null} header={null} timeline={null} mainContent={<main className="flex flex-col gap-6 pb-10" id="receivables-workspace">
  <section className="rounded-3xl border bg-card p-5 sm:p-7" data-workspace-label="Cuentas por Cobrar" data-workspace-section="RECEIVABLES_HEADER"><StatusBadge label="Registros financieros canónicos" variant="success"/><p className="mt-5 text-xs font-semibold uppercase tracking-[.2em] text-brand">Finanzas · Cobranza</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Cuentas por Cobrar</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Quién debe, cuánto, desde cuándo y por qué. Finanzas consolida el ledger del Evento y nunca modifica saldos directamente.</p></section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4" data-workspace-label="Indicadores de Cobranza" data-workspace-section="RECEIVABLES_KPIS"><Kpi icon={<WalletCards/>} label="Valor contractual activo" value={money(dataset.metrics.accountsReceivable)}/><Kpi icon={<Landmark/>} label="Pendiente de cobro" value={money(dataset.metrics.outstandingBalance)}/><Kpi danger={dataset.metrics.overdueBalance>0} icon={<TriangleAlert/>} label="Saldo vencido" value={money(dataset.metrics.overdueBalance)}/><Kpi icon={<CalendarClock/>} label="Promedio de cobro" value={dataset.metrics.averageCollectionDays===null?"Sin historial":`${dataset.metrics.averageCollectionDays} días`}/></section>
  <section className="space-y-5" data-workspace-label="Gestión de Cuentas" data-workspace-section="RECEIVABLES_MANAGEMENT"><div className="rounded-2xl border bg-card p-4 sm:p-5"><div className="flex flex-wrap gap-2" role="tablist"><Button onClick={()=>setView("ACTIVE")} variant={view==="ACTIVE"?"default":"outline"}>Activas</Button><Button onClick={()=>setView("HISTORY")} variant={view==="HISTORY"?"default":"outline"}>Historial</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_1fr]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar cliente, evento o servicio</span><input className="min-h-11 w-full rounded-xl border bg-background pl-10 pr-3 text-sm" onChange={event=>setQuery(event.target.value)} placeholder="Cliente, Evento o servicio" value={query}/></label><input aria-label="Filtrar por mes" className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setMonth(event.target.value)} type="month" value={month}/><input aria-label="Filtrar por monto" className="min-h-11 rounded-xl border bg-background px-3 text-sm" inputMode="numeric" onChange={event=>setAmount(event.target.value)} placeholder="Monto" value={amount}/><select aria-label="Filtrar por estado" className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setStatus(event.target.value as typeof status)} value={status}><option value="ALL">Todos los estados</option>{Object.entries(statusMeta).map(([key,meta])=><option key={key} value={key}>{meta.label}</option>)}</select></div></div>
  <div className="overflow-hidden rounded-2xl border bg-card"><div className="hidden overflow-x-auto xl:block"><table className="w-full min-w-[1280px] text-left text-sm"><thead className="border-b bg-background/40 text-xs uppercase tracking-wide text-muted"><tr>{["Cliente","Evento / Servicio","Valor contrato","Cobrado","Pendiente","Vencimiento","Días atraso","Estado","Documento","Último pago","Acciones"].map(label=><th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{invoices.map(invoice=><ReceivableRow invoice={invoice} key={invoice.id}/>)}</tbody></table></div><div className="space-y-3 p-3 xl:hidden">{invoices.map(invoice=><ReceivableCard invoice={invoice} key={invoice.id}/>)}</div>{!invoices.length?<div className="p-10 text-center"><ReceiptText className="mx-auto size-8 text-brand"/><p className="mt-3 font-semibold">No hay cuentas para estos filtros.</p><p className="mt-1 text-sm text-muted">Prueba otro cliente, mes, monto o estado.</p></div>:null}</div></section>
 </main>}/>;
}

function ReceivableRow({invoice}:{invoice:ReceivableInvoice}){const state=displayStatus(invoice);const meta=statusMeta[state];return <tr className="align-top"><td className="px-4 py-4"><Link className="font-semibold hover:text-brand" href={`/customers/${invoice.customerId}`}>{invoice.customerName}</Link><small className="mt-1 block text-muted">{invoice.invoiceNumber}</small></td><td className="px-4 py-4"><Link className="font-medium hover:text-brand" href={`/projects/${invoice.projectId}`}>{invoice.projectName}</Link><small className="mt-1 block text-muted">{invoice.service}</small></td><td className="px-4 py-4 font-medium">{money(invoice.amount)}</td><td className="px-4 py-4">{money(invoice.paidAmount)}</td><td className="px-4 py-4 font-semibold">{money(invoice.outstandingBalance)}</td><td className="px-4 py-4">{date(invoice.dueDate)}</td><td className={invoice.daysRemaining!==null&&invoice.daysRemaining<0?"px-4 py-4 font-semibold text-danger":"px-4 py-4"}>{invoice.daysRemaining!==null&&invoice.daysRemaining<0?Math.abs(invoice.daysRemaining):"—"}</td><td className="px-4 py-4"><StatusBadge label={meta.label} variant={meta.variant}/></td><td className="px-4 py-4">{invoice.contractAvailable?"Disponible":"Pendiente"}</td><td className="px-4 py-4">{invoice.lastPayment?<><strong>{money(invoice.lastPayment.amount)}</strong><small className="block text-muted">{date(invoice.lastPayment.paidAt)}</small></>:"Sin pagos"}</td><td className="px-4 py-3"><CanonicalActions invoice={invoice}/></td></tr>}
function ReceivableCard({invoice}:{invoice:ReceivableInvoice}){const meta=statusMeta[displayStatus(invoice)];return <article className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><Link className="font-semibold" href={`/customers/${invoice.customerId}`}>{invoice.customerName}</Link><p className="mt-1 text-sm">{invoice.projectName} · {invoice.service}</p></div><StatusBadge label={meta.label} variant={meta.variant}/></div><dl className="mt-4 grid grid-cols-2 gap-3"><Small label="Valor contrato" value={money(invoice.amount)}/><Small label="Cobrado" value={money(invoice.paidAmount)}/><Small label="Pendiente" value={money(invoice.outstandingBalance)}/><Small label="Vencimiento" value={date(invoice.dueDate)}/><Small label="Días atraso" value={invoice.daysRemaining!==null&&invoice.daysRemaining<0?String(Math.abs(invoice.daysRemaining)):"—"}/><Small label="Último pago" value={invoice.lastPayment?`${money(invoice.lastPayment.amount)} · ${date(invoice.lastPayment.paidAt)}`:"Sin pagos"}/></dl><CanonicalActions invoice={invoice}/></article>}

function CanonicalActions({invoice}:{invoice:ReceivableInvoice}){const[pending,start]=useTransition();const[message,setMessage]=useState("");const openContract=()=>start(async()=>{const result=await getReceivableContractUrlAction(invoice.id);if(result.ok)window.open(result.url,"_blank","noopener,noreferrer");else setMessage(result.error);});const reminder=()=>{if(!window.confirm(`Enviar recordatorio de pago a ${invoice.customerName} por ${money(invoice.outstandingBalance)}?`))return;start(async()=>{const result=await sendReceivableReminderAction(invoice.id);setMessage(result.ok?"Recordatorio enviado y auditado.":result.error);});};return <div className="min-w-52"><div className="flex flex-col gap-1"><ActionLink href={`/projects/${invoice.projectId}`} icon={<ExternalLink/>} label="Abrir Evento"/><ActionLink href={`/projects/${invoice.projectId}#payment-management`} icon={<WalletCards/>} label="Abrir Payment Ledger"/><button className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-left text-sm hover:bg-background disabled:opacity-50" disabled={pending||!invoice.contractAvailable} onClick={openContract}><FileSignature className="size-4"/>Abrir contrato</button>{invoice.outstandingBalance>0&&!(["CANCELLED","ARCHIVED"] as DisplayStatus[]).includes(displayStatus(invoice))?<button className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-left text-sm hover:bg-background disabled:opacity-50" disabled={pending} onClick={reminder}><Mail className="size-4"/>{pending?"Procesando…":"Enviar recordatorio"}</button>:null}<details><summary className="flex min-h-9 cursor-pointer list-none items-center gap-2 rounded-lg px-2 text-sm hover:bg-background"><History className="size-4"/>Ver historial</summary><div className="mt-2 space-y-2 rounded-lg border bg-background/30 p-3">{invoice.paymentHistory.length?invoice.paymentHistory.map(payment=><div className="text-xs" key={payment.id}><strong>{money(payment.amount)}</strong><span className="block text-muted">{date(payment.paidAt)} · {payment.method}</span></div>):<p className="text-xs text-muted">Sin movimientos de pago.</p>}</div></details></div>{message?<p aria-live="polite" className="mt-2 text-xs text-muted">{message}</p>:null}</div>}
function ActionLink({href,icon,label}:{href:string;icon:React.ReactNode;label:string}){return <Link className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-sm hover:bg-background" href={href}><span className="[&_svg]:size-4">{icon}</span>{label}</Link>}
function Kpi({icon,label,value,danger=false}:{icon:React.ReactNode;label:string;value:string;danger?:boolean}){return <article className={`rounded-2xl border bg-card p-4 sm:p-5 ${danger?"border-danger/30":""}`}><span className={`grid size-9 place-items-center rounded-lg ${danger?"bg-danger/10 text-danger":"bg-brand/10 text-brand"}`}>{icon}</span><p className="mt-4 text-xl font-semibold sm:text-2xl">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></article>}
function Small({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-semibold uppercase tracking-wider text-muted">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>}
