"use server";
import {createHash,randomUUID}from"node:crypto";import{revalidatePath}from"next/cache";
import{createAdminClient}from"@/lib/supabase/admin";import{createSupabaseServerActionClient}from"@/lib/supabase/server";
import{loadPortalSession}from"@/features/portal-authentication/portal-auth.service";import{mapStaffMonthlyAccount,monthlyBoletaPath,monthlyReceiptPath,monthlySettlementPath,STAFF_MONTHLY_ACCOUNT_SELECT}from"./model";
import{syncStaffDocumentArchive}from"./drive-archive.service";
import{createStaffMonthlySettlementPdf}from"./settlement-pdf";
const allowed=new Set(["application/pdf","image/jpeg","image/png","image/webp"]);
const fileFrom=(form:FormData)=>{const file=form.get("file");if(!(file instanceof File)||!file.size)throw new Error("Adjunta un PDF o imagen.");if(!allowed.has(file.type)||file.size>15*1024*1024)throw new Error("Archivo inválido o superior a 15 MB.");return file};
const refresh=()=>{revalidatePath("/staff-portal");revalidatePath("/resources/staff")};
export async function submitMonthlyBoletaAction(form:FormData){try{const session=await loadPortalSession("STAFF");if(!session?.staff_id)throw new Error("Tu sesión expiró.");const file=fileFrom(form),month=String(form.get("month")??"").slice(0,7),id=randomUUID(),path=monthlyBoletaPath(session.staff_id,month,id,file.name),admin=createAdminClient(),bytes=await file.arrayBuffer();const upload=await admin.storage.from("orbit-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const{data:documentId,error}=await admin.rpc("submit_staff_monthly_boleta",{p_staff_id:session.staff_id,p_month:`${month}-01`,p_bucket:"orbit-documents",p_path:path,p_file_name:file.name,p_mime_type:file.type,p_actor:null});if(error){await admin.storage.from("orbit-documents").remove([path]);throw error}try{await syncStaffDocumentArchive(admin,String(documentId))}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Boleta enviada para revisión."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible subir la boleta."}}}
async function adminContext(){const client=await createSupabaseServerActionClient(),{data}=await client.auth.getUser();if(!data.user)throw new Error("Tu sesión expiró.");const{data:profile}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(!profile||!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Acceso administrativo requerido.");return client}
export async function reviewMonthlyBoletaAction(form:FormData){try{const client=await adminContext(),{data,error}=await client.rpc("review_staff_monthly_boleta",{p_account_id:String(form.get("accountId")??""),p_action:String(form.get("action")??""),p_reason:String(form.get("reason")??"")});if(error)throw error;if(String(form.get("action"))==="APPROVE"&&data?.boleta_document_id)try{await syncStaffDocumentArchive(createAdminClient(),data.boleta_document_id)}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Boleta revisada."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible revisar la boleta."}}}
export async function generateMonthlyStaffAccountsAction(form:FormData){try{const client=await adminContext(),month=String(form.get("month")??"").slice(0,7);const{data,error}=await client.rpc("generate_staff_monthly_accounts",{p_month:`${month}-01`});if(error)throw error;refresh();return{ok:true,message:`${Number(data??0)} liquidaciones actualizadas desde Eventos del período.`}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible generar las liquidaciones."}}}
export async function completeSettlementEventAction(projectId:string){try{const client=await adminContext();const{error}=await client.rpc("mark_event_completed",{p_project_id:projectId});if(error)throw error;refresh();return{ok:true,message:"Evento marcado como completado."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible completar el Evento."}}}
export async function finalizeMonthlyStaffAccountAction(form:FormData){try{const client=await adminContext(),accountId=String(form.get("accountId")??""),{error}=await client.rpc("finalize_staff_monthly_account",{p_account_id:accountId});if(error)throw error;const admin=createAdminClient(),{data:row,error:rowError}=await admin.from("staff_monthly_accounts").select(STAFF_MONTHLY_ACCOUNT_SELECT).eq("id",accountId).single();if(rowError)throw rowError;const{data:staff,error:staffError}=await admin.from("staff").select("first_name,last_name,rut,role").eq("id",row.staff_id).single();if(staffError)throw staffError;const account=mapStaffMonthlyAccount(row),pdf=await createStaffMonthlySettlementPdf({account,staff:{name:`${staff.first_name} ${staff.last_name}`,rut:staff.rut??"",role:staff.role??""}}),path=monthlySettlementPath(account.staffId,account.month),upload=await admin.storage.from("orbit-documents").upload(path,pdf,{contentType:"application/pdf",upsert:true});if(upload.error)throw upload.error;let{data:document}=await admin.from("staff_onboarding_documents").select("id").eq("staff_id",account.staffId).eq("storage_bucket","orbit-documents").eq("storage_path",path).eq("status","ACTIVE").maybeSingle();if(!document){const inserted=await admin.from("staff_onboarding_documents").insert({invitation_id:null,staff_id:account.staffId,document_type:"STAFF_MONTHLY_SETTLEMENT",category:"LIQUIDACIONES",applicable_month:account.month,friendly_label:`Liquidación mensual ${account.month.slice(0,7)}`,status:"ACTIVE",storage_bucket:"orbit-documents",storage_path:path,file_name:`liquidacion-staff-${account.month.slice(0,7)}.pdf`,mime_type:"application/pdf"}).select("id").single();if(inserted.error)throw inserted.error;document=inserted.data}const link=await admin.from("staff_monthly_accounts").update({settlement_document_id:document.id}).eq("id",accountId);if(link.error)throw link.error;try{await syncStaffDocumentArchive(admin,document.id)}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Liquidación finalizada, PDF protegido y snapshot histórico congelado."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible finalizar la liquidación."}}}
export async function registerMonthlyStaffPaymentAction(form:FormData){let path="";try{const client=await adminContext(),file=fileFrom(form),staffId=String(form.get("staffId")??""),month=String(form.get("month")??"").slice(0,7),accountId=String(form.get("accountId")??""),bytes=await file.arrayBuffer(),fileHash=createHash("sha256").update(Buffer.from(bytes)).digest("hex"),key=createHash("sha256").update([accountId,String(form.get("amount")),String(form.get("paymentDate")),String(form.get("method")),String(form.get("reference")),fileHash].join("|")).digest("hex"),admin=createAdminClient();const{data:current}=await client.from("staff_monthly_accounts").select("payment_status,payment_idempotency_key").eq("id",accountId).maybeSingle();if(current?.payment_status==="PAID")return{ok:true,message:"Este pago ya estaba registrado; no se creó un duplicado."};path=monthlyReceiptPath(staffId,month,key,file.name);const upload=await admin.storage.from("orbit-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const{data,error}=await client.rpc("register_staff_monthly_payment",{p_account_id:accountId,p_payment_date:String(form.get("paymentDate")??""),p_amount:Number(form.get("amount")),p_method:String(form.get("method")??""),p_reference:String(form.get("reference")??""),p_idempotency_key:key,p_bucket:"orbit-documents",p_path:path,p_file_name:file.name,p_mime_type:file.type});if(error){await admin.storage.from("orbit-documents").remove([path]);throw error}if(data?.payment_receipt_document_id)try{await syncStaffDocumentArchive(admin,data.payment_receipt_document_id)}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Pago final registrado una sola vez con comprobante."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible registrar el pago."}}}
