"use server";
import {createHash,randomUUID}from"node:crypto";import{revalidatePath}from"next/cache";
import{createAdminClient}from"@/lib/supabase/admin";import{createSupabaseServerActionClient}from"@/lib/supabase/server";
import{loadPortalSession}from"@/features/portal-authentication/portal-auth.service";import{monthlyBoletaPath,monthlyReceiptPath}from"./model";
import{syncStaffDocumentArchive}from"./drive-archive.service";
const allowed=new Set(["application/pdf","image/jpeg","image/png","image/webp"]);
const fileFrom=(form:FormData)=>{const file=form.get("file");if(!(file instanceof File)||!file.size)throw new Error("Adjunta un PDF o imagen.");if(!allowed.has(file.type)||file.size>15*1024*1024)throw new Error("Archivo inválido o superior a 15 MB.");return file};
const refresh=()=>{revalidatePath("/staff-portal");revalidatePath("/resources/staff")};
export async function submitMonthlyBoletaAction(form:FormData){try{const session=await loadPortalSession("STAFF");if(!session?.staff_id)throw new Error("Tu sesión expiró.");const file=fileFrom(form),month=String(form.get("month")??"").slice(0,7),id=randomUUID(),path=monthlyBoletaPath(session.staff_id,month,id,file.name),admin=createAdminClient(),bytes=await file.arrayBuffer();const upload=await admin.storage.from("orbit-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const{data:documentId,error}=await admin.rpc("submit_staff_monthly_boleta",{p_staff_id:session.staff_id,p_month:`${month}-01`,p_bucket:"orbit-documents",p_path:path,p_file_name:file.name,p_mime_type:file.type,p_actor:null});if(error){await admin.storage.from("orbit-documents").remove([path]);throw error}try{await syncStaffDocumentArchive(admin,String(documentId))}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Boleta enviada para revisión."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible subir la boleta."}}}
async function adminContext(){const client=await createSupabaseServerActionClient(),{data}=await client.auth.getUser();if(!data.user)throw new Error("Tu sesión expiró.");const{data:profile}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(!profile||!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Acceso administrativo requerido.");return client}
export async function reviewMonthlyBoletaAction(form:FormData){try{const client=await adminContext(),{data,error}=await client.rpc("review_staff_monthly_boleta",{p_account_id:String(form.get("accountId")??""),p_action:String(form.get("action")??""),p_reason:String(form.get("reason")??"")});if(error)throw error;if(String(form.get("action"))==="APPROVE"&&data?.boleta_document_id)try{await syncStaffDocumentArchive(createAdminClient(),data.boleta_document_id)}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Boleta revisada."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible revisar la boleta."}}}
export async function registerMonthlyStaffPaymentAction(form:FormData){let path="";try{const client=await adminContext(),file=fileFrom(form),staffId=String(form.get("staffId")??""),month=String(form.get("month")??"").slice(0,7),accountId=String(form.get("accountId")??""),id=randomUUID();path=monthlyReceiptPath(staffId,month,id,file.name);const bytes=await file.arrayBuffer(),admin=createAdminClient(),upload=await admin.storage.from("orbit-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const key=createHash("sha256").update([accountId,String(form.get("amount")),String(form.get("paymentDate")),path].join("|")).digest("hex"),{data,error}=await client.rpc("register_staff_monthly_payment",{p_account_id:accountId,p_payment_date:String(form.get("paymentDate")??""),p_amount:Number(form.get("amount")),p_method:String(form.get("method")??""),p_reference:String(form.get("reference")??""),p_idempotency_key:key,p_bucket:"orbit-documents",p_path:path,p_file_name:file.name,p_mime_type:file.type});if(error){await admin.storage.from("orbit-documents").remove([path]);throw error}if(data?.payment_receipt_document_id)try{await syncStaffDocumentArchive(admin,data.payment_receipt_document_id)}catch(driveError){console.error("[ORBIT][STAFF_DRIVE_ARCHIVE]",driveError)}refresh();return{ok:true,message:"Pago registrado con comprobante."}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible registrar el pago."}}}
