export type StaffMonthlyAccount = {
  id:string; staffId:string; month:string; expectedAmount:number;
  workNet:number; boletaGross:number; withholdingRate:number; withholdingAmount:number; boletaNet:number;
  advancesTotal:number; reimbursementsTotal:number; finalTransferAmount:number; excessAdvance:number; eventCount:number;
  settlementStatus:"DRAFT"|"FINALIZED"; reviewRequired:boolean; reviewReason:string;
  settlementDocumentId:string|null;
  calculation:StaffMonthlyCalculation;
  boletaStatus:"PENDING"|"RECEIVED"|"APPROVED"|"REJECTED";
  boletaDocumentId:string|null; rejectionReason:string;
  paymentStatus:"PENDING"|"READY_TO_PAY"|"PAID"; paidAmount:number; paidAt:string;
  paymentMethod:string; paymentReference:string; receiptDocumentId:string|null; driveSyncStatus:string;
};
export type StaffMonthlyDetail={settlementId:string;projectId:string;eventDate:string;event:string;customer:string;service:string;location:string;roles:string[];hours:number;workNet:number;reimbursements:number;advances:number};
export type StaffMonthlyBlockingEvent={settlementId:string;projectId:string;eventId:string;eventDate:string;event:string;service:string;status:string};
export type StaffMonthlyCalculation={source:string;rateSemantics:"NET";periodSource:"EVENT_DATE";rounding:string;details:StaffMonthlyDetail[];blockingEvents:StaffMonthlyBlockingEvent[]};
export const STAFF_MONTHLY_ACCOUNT_SELECT="id,staff_id,accounting_month,expected_amount,work_net,boleta_gross,withholding_rate,withholding_amount,boleta_net,advances_total,reimbursements_total,final_transfer_amount,excess_advance,event_count,calculation,settlement_status,settlement_document_id,review_required,review_reason,boleta_status,boleta_document_id,boleta_rejection_reason,payment_status,paid_amount,paid_at,payment_method,payment_reference,payment_receipt_document_id,drive_sync_status";
export function mapStaffMonthlyAccount(row:Record<string,unknown>):StaffMonthlyAccount{const calculation=(row.calculation&&typeof row.calculation==="object"?row.calculation:{}) as Partial<StaffMonthlyCalculation>;return{id:String(row.id),staffId:String(row.staff_id),month:String(row.accounting_month),expectedAmount:Number(row.expected_amount??0),workNet:Number(row.work_net??0),boletaGross:Number(row.boleta_gross??0),withholdingRate:Number(row.withholding_rate??0),withholdingAmount:Number(row.withholding_amount??0),boletaNet:Number(row.boleta_net??0),advancesTotal:Number(row.advances_total??0),reimbursementsTotal:Number(row.reimbursements_total??0),finalTransferAmount:Number(row.final_transfer_amount??row.expected_amount??0),excessAdvance:Number(row.excess_advance??0),eventCount:Number(row.event_count??0),settlementStatus:(row.settlement_status??"DRAFT") as StaffMonthlyAccount["settlementStatus"],settlementDocumentId:row.settlement_document_id?String(row.settlement_document_id):null,reviewRequired:Boolean(row.review_required),reviewReason:String(row.review_reason??""),calculation:{source:String(calculation.source??"CANONICAL_STAFF_MONTHLY_SETTLEMENT_V1"),rateSemantics:"NET",periodSource:"EVENT_DATE",rounding:String(calculation.rounding??"ROUND_CLP_HALF_AWAY_FROM_ZERO"),details:Array.isArray(calculation.details)?calculation.details:[],blockingEvents:Array.isArray(calculation.blockingEvents)?calculation.blockingEvents as StaffMonthlyBlockingEvent[]:[]},boletaStatus:String(row.boleta_status) as StaffMonthlyAccount["boletaStatus"],boletaDocumentId:row.boleta_document_id?String(row.boleta_document_id):null,rejectionReason:String(row.boleta_rejection_reason??""),paymentStatus:String(row.payment_status) as StaffMonthlyAccount["paymentStatus"],paidAmount:Number(row.paid_amount??0),paidAt:String(row.paid_at??""),paymentMethod:String(row.payment_method??""),paymentReference:String(row.payment_reference??""),receiptDocumentId:row.payment_receipt_document_id?String(row.payment_receipt_document_id):null,driveSyncStatus:String(row.drive_sync_status??"PENDING")};}
export const staffMonthLabel=(month:string)=>new Date(`${month.slice(0,7)}-01T12:00:00Z`).toLocaleDateString("es-CL",{month:"long",year:"numeric"});
export const monthlyBoletaPath=(staffId:string,month:string,id:string,fileName:string)=>`staff/${staffId}/03_BOLETAS/${month.slice(0,7)}/${id}-${fileName.replace(/[^a-zA-Z0-9._-]+/g,"-")}`;
export const monthlyReceiptPath=(staffId:string,month:string,id:string,fileName:string)=>`staff/${staffId}/05_COMPROBANTES_PAGO/${month.slice(0,7)}/${id}-${fileName.replace(/[^a-zA-Z0-9._-]+/g,"-")}`;
export const monthlySettlementPath=(staffId:string,month:string)=>`staff/${staffId}/04_LIQUIDACIONES/${month.slice(0,7)}/liquidacion-mensual.pdf`;
