import{PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage}from"pdf-lib";
import type{StaffMonthlyAccount}from"./model.ts";
type Input={account:StaffMonthlyAccount;staff:{name:string;rut:string;role:string}};
const PAGE:[number,number]=[595.28,841.89],orange=rgb(.96,.49,.05),black=rgb(.045,.05,.06),muted=rgb(.38,.4,.44),line=rgb(.88,.89,.91);
const money=(value:number)=>`$${Math.round(value).toLocaleString("es-CL")}`;
const staffMonthLabel=(month:string)=>new Date(`${month.slice(0,7)}-01T12:00:00Z`).toLocaleDateString("es-CL",{month:"long",year:"numeric"});
const safe=(value:string)=>value.replace(/[–—]/g,"-").replace(/\s+/g," ").trim();
function base(pdf:PDFDocument,regular:PDFFont,bold:PDFFont,title:string){const page=pdf.addPage(PAGE);page.drawRectangle({x:0,y:PAGE[1]-112,width:PAGE[0],height:112,color:black});page.drawText("BOOMBOX",{x:42,y:PAGE[1]-52,size:20,font:bold,color:rgb(1,1,1)});page.drawText("ORBIT · LIQUIDACIÓN MENSUAL",{x:42,y:PAGE[1]-78,size:10,font:bold,color:orange});page.drawText(safe(title).toUpperCase(),{x:42,y:PAGE[1]-96,size:9,font:regular,color:rgb(.78,.8,.83)});page.drawText("Documento emitido por BOOMBOX mediante ORBIT.",{x:42,y:28,size:8,font:regular,color:muted});return page}
function label(page:PDFPage,font:PDFFont,text:string,x:number,y:number){page.drawText(safe(text).toUpperCase(),{x,y,size:8,font,color:muted})}
function value(page:PDFPage,font:PDFFont,text:string,x:number,y:number,size=10,color=black){page.drawText(safe(text),{x,y,size,font,color})}
export async function createStaffMonthlySettlementPdf({account,staff}:Input){const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),period=staffMonthLabel(account.month);let page=base(pdf,regular,bold,period),y=PAGE[1]-150;
  label(page,bold,"Operador",42,y);value(page,bold,staff.name,42,y-17,12);label(page,bold,"RUT",260,y);value(page,regular,staff.rut||"No informado",260,y-17);label(page,bold,"Rol",420,y);value(page,regular,staff.role||"Staff BOOMBOX",420,y-17);y-=68;
    page.drawText("DETALLE DE SERVICIOS REALIZADOS",{x:42,y,size:10,font:bold,color:orange});y-=24;
  for(const detail of account.calculation.details){if(y<118){page=base(pdf,regular,bold,period);y=PAGE[1]-145;page.drawText("DETALLE DE SERVICIOS REALIZADOS · CONTINUACIÓN",{x:42,y,size:10,font:bold,color:orange});y-=25}page.drawLine({start:{x:42,y:y+8},end:{x:553,y:y+8},thickness:.6,color:line});value(page,bold,new Date(`${detail.eventDate}T12:00:00Z`).toLocaleDateString("es-CL"),42,y-8,9);value(page,bold,detail.service,112,y-8,9);value(page,regular,detail.location||"Lugar no informado",250,y-8,8);value(page,bold,money(detail.workNet),475,y-8,9);value(page,regular,`${detail.roles.join(" + ")} · ${detail.hours} horas${detail.advances>0?` · Adelanto ${money(detail.advances)}`:""}`,112,y-24,8,muted);y-=48}
  if(y<390){page=base(pdf,regular,bold,period);y=PAGE[1]-145}
  page.drawText("RESUMEN DEL MES",{x:42,y,size:10,font:bold,color:orange});y-=26;const rows:[string,string][]=[["N° de servicios",String(account.eventCount)],["Total trabajado",money(account.workNet)],[`Retención / impuesto (${account.withholdingRate.toLocaleString("es-CL")}%)`,money(account.withholdingAmount)],["Líquido según boleta",money(account.boletaNet)],["Adelantos realizados",`-${money(account.advancesTotal)}`],["Reembolsos",money(account.reimbursementsTotal)],["Saldo final a transferir",money(account.finalTransferAmount)]];for(const[rowLabel,rowValue]of rows){page.drawLine({start:{x:42,y:y+8},end:{x:553,y:y+8},thickness:.5,color:line});value(page,regular,rowLabel,48,y-10,9);value(page,bold,rowValue,425,y-10,10);y-=32}
  y-=6;page.drawRectangle({x:42,y:y-92,width:511,height:98,color:rgb(1,.965,.92),borderColor:orange,borderWidth:2});page.drawText("MONTO TOTAL BOLETA SII A EMITIR",{x:62,y:y-20,size:10,font:bold,color:orange});page.drawText(money(account.boletaGross),{x:62,y:y-58,size:26,font:bold,color:black});page.drawText("Este es el monto exacto que debes ingresar en SII.",{x:62,y:y-78,size:9,font:bold,color:muted});
  return Buffer.from(await pdf.save());
}
