"use client";
import { X } from "lucide-react";
import { type ReactNode, useEffect, useId, useRef } from "react";
import { createPortal } from "react-dom";
import {acquireModalScrollLock} from "./modal-scroll-lock";
type Props={children:ReactNode;description?:string;footer?:ReactNode;onClose:()=>void;title:string;eyebrow?:string;size?:"md"|"lg"|"xl";variant?:"default"|"fullscreen-mobile"};
const widths={md:"lg:max-w-lg",lg:"lg:max-w-2xl",xl:"lg:max-w-4xl"}as const;
const focusable='button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';
export function MobileDialog({children,description,footer,onClose,title,eyebrow,size="lg",variant="default"}:Props){const titleId=useId(),descriptionId=useId(),panelRef=useRef<HTMLDivElement>(null),fullscreen=variant==="fullscreen-mobile";useEffect(()=>{const releaseLock=acquireModalScrollLock();panelRef.current?.querySelector<HTMLElement>(focusable)?.focus({preventScroll:true});const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")return onClose();if(event.key!=="Tab"||!panelRef.current)return;const items=[...panelRef.current.querySelectorAll<HTMLElement>(focusable)];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKeyDown);return()=>{document.removeEventListener("keydown",onKeyDown);releaseLock()}},[onClose]);const overlay=fullscreen?"items-stretch bg-card lg:items-center lg:bg-black/70 lg:p-6":"items-end bg-black/70 sm:items-center sm:p-6";const panel=fullscreen?"h-[100dvh] border-0 shadow-none lg:h-auto lg:max-h-[min(92dvh,56rem)] lg:rounded-2xl lg:border lg:shadow-2xl":"h-[calc(100dvh-env(safe-area-inset-top))] rounded-t-2xl border shadow-2xl sm:h-auto sm:max-h-[min(92dvh,56rem)] sm:rounded-2xl";return createPortal(<div aria-describedby={description?descriptionId:undefined} aria-labelledby={titleId} aria-modal="true" className={`fixed inset-0 z-[100] flex h-[100dvh] min-h-0 justify-center overflow-hidden ${overlay}`} data-orbit-modal-overlay data-orbit-modal-variant={variant} onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}} role="dialog"><div className={`flex min-h-0 w-full flex-col overflow-hidden bg-card ${panel} ${widths[size]}`} data-orbit-modal-panel ref={panelRef}><header className={`flex shrink-0 items-start justify-between gap-4 border-b px-4 sm:px-6 ${fullscreen?"pb-4 pt-[max(1rem,env(safe-area-inset-top))] lg:py-4":"py-4"}`} data-orbit-modal-header><div className="min-w-0">{eyebrow?<p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">{eyebrow}</p>:null}<h2 className="mt-1 text-xl font-semibold" id={titleId}>{title}</h2>{description?<p className="mt-1 text-sm text-muted" id={descriptionId}>{description}</p>:null}</div><button aria-label="Cerrar" className="grid size-11 shrink-0 place-items-center rounded-xl border" data-orbit-modal-close onClick={onClose} type="button"><X className="size-4"/></button></header><main className="min-h-0 flex-1 touch-pan-y overflow-x-hidden overflow-y-auto overscroll-y-contain px-4 py-5 [scrollbar-gutter:stable] [-webkit-overflow-scrolling:touch] sm:px-6" data-orbit-modal-scroll>{children}</main>{footer?<footer className="shrink-0 border-t bg-card px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-3 sm:px-6" data-orbit-modal-footer>{footer}</footer>:null}</div></div>,document.body)}
