"use client";
import { X } from "lucide-react";
import { type ReactNode, useEffect, useId, useRef } from "react";
import { createPortal } from "react-dom";
import {acquireModalScrollLock} from "./modal-scroll-lock";
type Props={children:ReactNode;description?:string;footer?:ReactNode;onClose:()=>void;title:string;eyebrow?:string;size?:"md"|"lg"|"xl"};
const widths={md:"sm:max-w-lg",lg:"sm:max-w-2xl",xl:"sm:max-w-4xl"}as const;
const focusable='button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';
export function MobileDialog({children,description,footer,onClose,title,eyebrow,size="lg"}:Props){const titleId=useId(),descriptionId=useId(),panelRef=useRef<HTMLDivElement>(null);useEffect(()=>{const releaseLock=acquireModalScrollLock();panelRef.current?.querySelector<HTMLElement>(focusable)?.focus({preventScroll:true});const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")return onClose();if(event.key!=="Tab"||!panelRef.current)return;const items=[...panelRef.current.querySelectorAll<HTMLElement>(focusable)];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKeyDown);return()=>{document.removeEventListener("keydown",onKeyDown);releaseLock()}},[onClose]);return createPortal(<div aria-describedby={description?descriptionId:undefined} aria-labelledby={titleId} aria-modal="true" className="fixed inset-0 z-[100] flex h-[100dvh] min-h-0 items-end justify-center overflow-hidden bg-black/70 sm:items-center sm:p-6" data-orbit-modal-overlay onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}} role="dialog"><div className={`flex h-[calc(100dvh-env(safe-area-inset-top))] min-h-0 w-full flex-col overflow-hidden rounded-t-2xl border bg-card shadow-2xl sm:h-auto sm:max-h-[min(92dvh,56rem)] sm:rounded-2xl ${widths[size]}`} data-orbit-modal-panel ref={panelRef}><header className="flex shrink-0 items-start justify-between gap-4 border-b px-4 py-4 sm:px-6"><div className="min-w-0">{eyebrow?<p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">{eyebrow}</p>:null}<h2 className="mt-1 text-xl font-semibold" id={titleId}>{title}</h2>{description?<p className="mt-1 text-sm text-muted" id={descriptionId}>{description}</p>:null}</div><button aria-label="Cerrar" className="grid size-11 shrink-0 place-items-center rounded-xl border" onClick={onClose} type="button"><X className="size-4"/></button></header><div className="min-h-0 flex-1 touch-pan-y overflow-x-hidden overflow-y-auto overscroll-y-contain px-4 py-5 [scrollbar-gutter:stable] [-webkit-overflow-scrolling:touch] sm:px-6" data-orbit-modal-scroll>{children}</div>{footer?<footer className="shrink-0 border-t bg-card px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-3 sm:px-6" data-orbit-modal-footer>{footer}</footer>:null}</div></div>,document.body)}
