"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { MapPin, Pencil, Plus, Power, Search, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { mutateEventVenueAction } from "./actions";
import type { VenueAdministrationProjection, VenueAdministrationRecord } from "./types";

const money = new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
type Panel = { mode:"create" } | { mode:"edit"; venue:VenueAdministrationRecord } | null;

export function EventVenueCenter({canEdit,projection}:{canEdit:boolean;projection:VenueAdministrationProjection}) {
  const router=useRouter(); const [query,setQuery]=useState(""); const [panel,setPanel]=useState<Panel>(null); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
  const visible=useMemo(()=>projection.records.filter((venue)=>`${venue.name} ${venue.municipality} ${venue.province}`.toLowerCase().includes(query.toLowerCase())),[projection.records,query]);
  const changeStatus=(venue:VenueAdministrationRecord)=>{const reason=window.prompt(`Motivo para ${venue.enabled?"deshabilitar":"habilitar"} ${venue.name}:`);if(!reason)return;startTransition(async()=>{const result=await mutateEventVenueAction({operation:"UPDATE",venue:{...venue,enabled:!venue.enabled},expectedVersion:projection.version,reason});setMessage(result.ok?"Estado actualizado y auditado.":result.error);if(result.ok)router.refresh();});};
  const remove=(venue:VenueAdministrationRecord)=>{if(!window.confirm(`¿Eliminar ${venue.name} de las sedes?`))return;const reason=window.prompt("Motivo de eliminación:");if(!reason)return;startTransition(async()=>{const result=await mutateEventVenueAction({operation:"DELETE",venue,expectedVersion:projection.version,reason});setMessage(result.ok?"Sede eliminada y auditada.":result.error);if(result.ok)router.refresh();});};
  return <div className="space-y-5">
    <div className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">Sedes de eventos</h2><p className="mt-1 text-sm text-muted">Ubicación y recargos utilizados automáticamente por Nueva Reserva.</p></div>{canEdit&&<Button onClick={()=>setPanel({mode:"create"})}><Plus className="size-4"/>Crear sede</Button>}</div></div>
    <label className="relative block"><Search className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar sede</span><input className="min-h-11 w-full rounded-xl border bg-card pl-10 pr-4 text-sm" onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar por sede, comuna o provincia" value={query}/></label>
    {message&&<p className="rounded-xl border bg-card p-3 text-sm" role="status">{message}</p>}
    <div className="grid gap-4 lg:grid-cols-2">{visible.map((venue)=><article className="rounded-2xl border bg-card p-5" key={venue.code}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="rounded-xl border bg-background p-2.5 text-brand"><MapPin className="size-4"/></span><div><h3 className="font-semibold">{venue.name}</h3><p className="mt-1 text-xs text-muted">{venue.municipality} · {venue.province}</p></div></div><StatusBadge label={venue.enabled?"Activa":"Inactiva"} variant={venue.enabled?"success":"neutral"}/></div><dl className="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><div><dt className="text-xs text-muted">Recargo especial</dt><dd className="mt-1 font-semibold">{money.format(venue.surcharge)}</dd></div><div><dt className="text-xs text-muted">Orden</dt><dd className="mt-1 font-semibold">{venue.displayOrder}</dd></div></dl><p className="mt-4 text-sm text-muted">{venue.notes||"Sin notas operacionales."}</p>{canEdit&&<div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4"><Action icon={<Pencil/>} label="Editar" onClick={()=>setPanel({mode:"edit",venue})}/><Action disabled={pending} icon={<Power/>} label={venue.enabled?"Deshabilitar":"Habilitar"} onClick={()=>changeStatus(venue)}/><Action danger disabled={pending} icon={<Trash2/>} label="Eliminar" onClick={()=>remove(venue)}/></div>}</article>)}</div>
    {!visible.length&&<div className="rounded-2xl border border-dashed p-8 text-center"><p className="font-semibold">No hay sedes que coincidan.</p><p className="mt-1 text-sm text-muted">Ajusta la búsqueda o crea una nueva sede.</p></div>}
    {panel&&<VenuePanel panel={panel} projection={projection} onClose={()=>setPanel(null)} onSaved={(text)=>{setPanel(null);setMessage(text);router.refresh();}}/>}
  </div>;
}

function VenuePanel({panel,projection,onClose,onSaved}:{panel:Exclude<Panel,null>;projection:VenueAdministrationProjection;onClose:()=>void;onSaved:(message:string)=>void}) {
  const venue=panel.mode==="edit"?panel.venue:null; const [error,setError]=useState(""); const [saving,startSaving]=useTransition();
  const submit=(data:FormData)=>{const value={code:venue?.code,name:String(data.get("name")??""),municipality:String(data.get("municipality")??""),province:String(data.get("province")??""),surcharge:Number(data.get("surcharge")??0),notes:String(data.get("notes")??""),enabled:data.get("enabled")==="on",displayOrder:Number(data.get("displayOrder")??0)};startSaving(async()=>{const result=await mutateEventVenueAction({operation:venue?"UPDATE":"CREATE",venue:value,expectedVersion:projection.version,reason:String(data.get("reason")??"")});if(!result.ok)return setError(result.error);onSaved(venue?"Sede actualizada y auditada.":"Sede creada y auditada.");});};
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 sm:max-w-2xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Master Data</p><h3 className="mt-1 text-2xl font-semibold">{venue?"Editar sede":"Crear sede"}</h3></div><button className="rounded-lg border p-2" onClick={onClose} aria-label="Cerrar"><X className="size-4"/></button></div><form action={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><Field defaultValue={venue?.name} label="Nombre de la sede" name="name" required/><Field defaultValue={venue?.municipality} label="Comuna" name="municipality" required/><Field defaultValue={venue?.province} label="Provincia" name="province" required/><Field defaultValue={venue?.surcharge.toString()??"0"} label="Recargo especial" min="0" name="surcharge" required type="number"/><Field defaultValue={venue?.displayOrder.toString()??String((projection.records.length+1)*10)} label="Orden" min="0" name="displayOrder" required type="number"/><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-3 text-sm"><input defaultChecked={venue?.enabled??true} name="enabled" type="checkbox"/>Activa</label><label className="text-sm font-medium sm:col-span-2">Notas<textarea className="mt-2 min-h-24 w-full rounded-xl border bg-background p-3" defaultValue={venue?.notes} name="notes"/></label><Field className="sm:col-span-2" label="Razón del cambio" name="reason" required/>{error&&<p className="text-sm text-danger sm:col-span-2" role="alert">{error}</p>}<Button className="sm:col-span-2" disabled={saving}>{saving?"Guardando…":venue?"Guardar cambios":"Crear sede"}</Button></form></div></div>;
}

function Action({danger,disabled,icon,label,onClick}:{danger?:boolean;disabled?:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={`rounded-lg border px-2 py-2 text-xs font-semibold ${danger?"text-danger":""}`} disabled={disabled} onClick={onClick}><span className="mr-1 inline-block [&>svg]:size-3.5">{icon}</span>{label}</button>}
function Field({className="",label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className={`text-sm font-medium ${className}`}>{label}<input className="mt-2 h-11 w-full rounded-xl border bg-background px-3" {...props}/></label>}
