"use client";

import { useMemo, useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Pencil, Plus, Power, Search, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { createServiceAction, deleteServiceAction, setServiceEnabledAction, updateServiceAction } from "./actions";
import type { ServiceAdministrationRecord, ServiceExtraCode } from "./types";

const money = new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const extraOptions: readonly {code:ServiceExtraCode;label:string}[]=[
  {code:"QR",label:"QR"},{code:"UNLIMITED_MAGNETS",label:"Imanes"},{code:"SCRAPBOOK",label:"Scrapbook"},
  {code:"BRANDING",label:"Branding"},{code:"TRANSPORT",label:"Transporte"},{code:"ADDITIONAL_HOURS",label:"Horas adicionales"},
];

type Panel = {mode:"create"}|{mode:"edit";service:ServiceAdministrationRecord}|null;

export function ServicesPricingCenter({canEdit,initialServices}:{canEdit:boolean;initialServices:readonly ServiceAdministrationRecord[]}) {
  const router=useRouter(); const [query,setQuery]=useState(""); const [panel,setPanel]=useState<Panel>(null); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
  const visible=useMemo(()=>initialServices.filter((service)=>`${service.name} ${service.code} ${service.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.displayOrder-b.displayOrder),[initialServices,query]);
  const toggle=(service:ServiceAdministrationRecord)=>{const reason=window.prompt(`Motivo para ${service.enabled?"deshabilitar":"habilitar"} ${service.name}:`);if(!reason)return;startTransition(async()=>{const result=await setServiceEnabledAction({id:service.id,code:service.code,enabled:!service.enabled,expectedVersion:service.version,reason});setMessage(result.ok?"Estado actualizado y auditado.":result.error);if(result.ok)router.refresh();});};
  const remove=(service:ServiceAdministrationRecord)=>{if(!window.confirm(`¿Eliminar ${service.name} del catálogo comercial?`))return;const reason=window.prompt("Motivo de eliminación:");if(!reason)return;startTransition(async()=>{const result=await deleteServiceAction({id:service.id,code:service.code,expectedVersion:service.version,reason});setMessage(result.ok?"Servicio eliminado y auditado.":result.error);if(result.ok)router.refresh();});};
  return <div className="space-y-5">
    <div className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">Servicios y precios</h2><p className="mt-1 text-sm text-muted">Catálogo comercial persistente. Los cambios activos quedan disponibles para Nueva Reserva.</p></div>{canEdit&&<Button onClick={()=>{setMessage("");setPanel({mode:"create"});}}><Plus className="size-4"/>Crear servicio</Button>}</div></div>
    <label className="relative block"><Search className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar servicio</span><input className="min-h-11 w-full rounded-xl border bg-card pl-10 pr-4 text-sm" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar por servicio, código o categoría"/></label>
    {message&&<p className="rounded-xl border bg-card p-3 text-sm" role="status">{message}</p>}
    <div className="grid gap-4 lg:grid-cols-2">{visible.map((service)=><article className="rounded-2xl border bg-card p-5" key={service.id}>
      <div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">{service.name}</p><p className="mt-1 text-xs text-muted">{service.category} · {service.code}</p></div><StatusBadge label={service.enabled?"Activo":"Inactivo"} variant={service.enabled?"success":"neutral"}/></div>
      <p className="mt-4 text-sm leading-6 text-muted">{service.description||"Sin descripción comercial."}</p>
      <dl className="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><Detail label="Precio base" value={service.basePrice===null?"Por definir":money.format(service.basePrice)}/><Detail label="Horas" value={`${service.minimumHours}–${service.maximumHours}`}/><Detail label="Hora adicional" value={service.additionalHourPrice===null?"No aplica":money.format(service.additionalHourPrice)}/><Detail label="Orden" value={String(service.displayOrder)}/></dl>
      <div className="mt-4 flex flex-wrap gap-2">{service.compatibleExtras.map((extra)=><span className="rounded-full border px-2.5 py-1 text-xs" key={extra}>{extraOptions.find((item)=>item.code===extra)?.label??extra}</span>)}{!service.compatibleExtras.length&&<span className="text-xs text-muted">Sin extras compatibles</span>}</div>
      {canEdit&&<div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4"><Action label="Editar" icon={<Pencil/>} onClick={()=>{setMessage("");setPanel({mode:"edit",service});}}/><Action disabled={pending} label={service.enabled?"Deshabilitar":"Habilitar"} icon={<Power/>} onClick={()=>toggle(service)}/><Action danger disabled={pending} label="Eliminar" icon={<Trash2/>} onClick={()=>remove(service)}/></div>}
    </article>)}</div>
    {!visible.length&&<div className="rounded-2xl border border-dashed p-8 text-center"><p className="font-semibold">No hay servicios que coincidan.</p><p className="mt-1 text-sm text-muted">Ajusta la búsqueda o crea un nuevo servicio.</p></div>}
    {panel&&<ServicePanel panel={panel} onClose={()=>setPanel(null)} onSaved={(text)=>{setPanel(null);setMessage(text);router.refresh();}}/>}
  </div>;
}

function ServicePanel({panel,onClose,onSaved}:{panel:Exclude<Panel,null>;onClose:()=>void;onSaved:(message:string)=>void}) {
  const service=panel.mode==="edit"?panel.service:null; const [error,setError]=useState(""); const [saving,startSaving]=useTransition();
  const submit=(data:FormData)=>{setError("");const compatibleExtras=data.getAll("compatibleExtras").map(String) as ServiceExtraCode[];const defaultExtras=data.getAll("defaultExtras").map(String) as ServiceExtraCode[];const input={id:service?.id,priceId:service?.priceId,expectedVersion:service?.version,expectedPriceVersion:service?.priceVersion,code:String(data.get("code")??""),name:String(data.get("name")??""),category:String(data.get("category")??""),basePrice:data.get("basePrice")===""?null:Number(data.get("basePrice")),minimumHours:Number(data.get("minimumHours")),maximumHours:Number(data.get("maximumHours")),additionalHourPrice:data.get("additionalHourPrice")===""?null:Number(data.get("additionalHourPrice")),enabled:data.get("enabled")==="on",displayOrder:Number(data.get("displayOrder")),description:String(data.get("description")??""),compatibleExtras,defaultExtras,behavior:String(data.get("behavior")??"SELECTABLE"),reason:String(data.get("reason")??"")};
    startSaving(async()=>{const result=service?await updateServiceAction(input):await createServiceAction(input);if(!result.ok)return setError(result.error);onSaved(service?"Servicio actualizado y auditado.":"Servicio creado y auditado.");});};
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 sm:max-w-3xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Administración comercial</p><h3 className="mt-1 text-2xl font-semibold">{service?"Editar servicio":"Crear servicio"}</h3></div><button className="rounded-lg border p-2" onClick={onClose} aria-label="Cerrar"><X className="size-4"/></button></div>
    <form action={submit} className="mt-6 grid gap-4 sm:grid-cols-2">
      <Field defaultValue={service?.name} label="Nombre del servicio" name="name" required/><Field defaultValue={service?.code} disabled={!!service} label="Código" name="code" required/>{service&&<input type="hidden" name="code" value={service.code}/>}<Field defaultValue={service?.category} label="Categoría" name="category" required/><Field defaultValue={service?.basePrice?.toString()} label="Precio base" min="0" name="basePrice" type="number"/><Field defaultValue={service?.minimumHours.toString()??"2"} label="Horas mínimas" min="1" name="minimumHours" required type="number"/><Field defaultValue={service?.maximumHours.toString()??"4"} label="Horas máximas" min="1" name="maximumHours" required type="number"/><Field defaultValue={service?.additionalHourPrice?.toString()} label="Precio hora adicional" min="0" name="additionalHourPrice" type="number"/><Field defaultValue={service?.displayOrder.toString()??"100"} label="Orden de visualización" min="0" name="displayOrder" required type="number"/>
      <label className="text-sm font-medium">Comportamiento<select className="mt-2 h-11 w-full rounded-xl border bg-background px-3" defaultValue={service?.behavior??"SELECTABLE"} name="behavior"><option value="SELECTABLE">Duración seleccionable</option><option value="FIXED">Duración fija</option><option value="SINGLE_SERVICE">Servicio único</option></select></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-3 text-sm"><input defaultChecked={service?.enabled??true} name="enabled" type="checkbox"/>Activo</label>
      <label className="sm:col-span-2 text-sm font-medium">Descripción<textarea className="mt-2 min-h-24 w-full rounded-xl border bg-background p-3" defaultValue={service?.description} name="description"/></label>
      <ExtrasField label="Extras compatibles" name="compatibleExtras" selected={service?.compatibleExtras??[]}/><ExtrasField label="Extras incluidos por defecto" name="defaultExtras" selected={service?.defaultExtras??[]}/>
      <Field label="Razón del cambio" name="reason" placeholder="Obligatoria para auditoría" required className="sm:col-span-2"/>{error&&<p className="sm:col-span-2 text-sm text-danger" role="alert">{error}</p>}<Button className="sm:col-span-2" disabled={saving}>{saving?"Guardando…":service?"Guardar cambios":"Crear servicio"}</Button>
    </form></div></div>;
}

function ExtrasField({label,name,selected}:{label:string;name:string;selected:readonly ServiceExtraCode[]}){return <fieldset className="rounded-xl border p-4"><legend className="px-1 text-sm font-semibold">{label}</legend><div className="mt-2 grid gap-2">{extraOptions.map((extra)=><label className="flex items-center gap-2 text-sm" key={extra.code}><input defaultChecked={selected.includes(extra.code)} name={name} type="checkbox" value={extra.code}/>{extra.label}</label>)}</div></fieldset>}
function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
function Action({danger,disabled,icon,label,onClick}:{danger?:boolean;disabled?:boolean;icon:ReactNode;label:string;onClick:()=>void}){return <button className={`rounded-lg border px-2 py-2 text-xs font-semibold transition hover:bg-accent ${danger?"text-danger":""}`} disabled={disabled} onClick={onClick}>{<span className="mr-1 inline-block [&>svg]:size-3.5">{icon}</span>}{label}</button>}
function Field({className="",label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className={`text-sm font-medium ${className}`}>{label}<input className="mt-2 h-11 w-full rounded-xl border bg-background px-3" {...props}/></label>}
