"use client";

import { useMemo, useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Car, Pencil, Plus, Power, Search, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { mutateTransportZoneAction } from "./actions";
import type { TransportZoneAdministrationRecord } from "./types";

const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
type Panel={mode:"create"}|{mode:"edit";zone:TransportZoneAdministrationRecord}|null;

export function TransportCenter({canEdit,initialZones}:{canEdit:boolean;initialZones:readonly TransportZoneAdministrationRecord[]}) {
  const router=useRouter(); const [query,setQuery]=useState(""); const [panel,setPanel]=useState<Panel>(null); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
  const visible=useMemo(()=>initialZones.filter((zone)=>`${zone.province} ${zone.municipalities.join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.displayOrder-b.displayOrder),[initialZones,query]);
  const mutateMunicipality=(zone:TransportZoneAdministrationRecord,operation:"CREATE"|"UPDATE"|"DELETE",current?:string)=>{const next=operation==="DELETE"?null:window.prompt(operation==="CREATE"?`Nueva comuna para ${zone.province}:`:`Nuevo nombre para ${current}:`,current??"");if(operation!=="DELETE"&&!next?.trim())return;if(operation==="DELETE"&&!window.confirm(`¿Eliminar ${current} de ${zone.province}?`))return;const reason=window.prompt("Motivo del cambio:");if(!reason)return;const municipalities=operation==="CREATE"?[...zone.municipalities,next!.trim()]:operation==="DELETE"?zone.municipalities.filter((item)=>item!==current):zone.municipalities.map((item)=>item===current?next!.trim():item);startTransition(async()=>{const result=await mutateTransportZoneAction({operation:"UPDATE",zone:{...zone,municipalities},reason});setMessage(result.ok?"Comuna actualizada y auditada.":result.error);if(result.ok)router.refresh();});};
  const toggle=(zone:TransportZoneAdministrationRecord)=>{const reason=window.prompt(`Motivo para ${zone.enabled?"deshabilitar":"habilitar"} ${zone.province}:`);if(!reason)return;startTransition(async()=>{const result=await mutateTransportZoneAction({operation:"UPDATE",zone:{...zone,enabled:!zone.enabled},reason});setMessage(result.ok?"Estado actualizado y auditado.":result.error);if(result.ok)router.refresh();});};
  const remove=(zone:TransportZoneAdministrationRecord)=>{if(!window.confirm(`¿Eliminar la provincia ${zone.province} y su configuración de transporte?`))return;const reason=window.prompt("Motivo de eliminación:");if(!reason)return;startTransition(async()=>{const result=await mutateTransportZoneAction({operation:"DELETE",zone,reason});setMessage(result.ok?"Provincia eliminada y auditada.":result.error);if(result.ok)router.refresh();});};
  return <div className="space-y-5"><div className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">Provincias y transporte</h2><p className="mt-1 text-sm text-muted">Cobertura territorial utilizada automáticamente en cada reserva.</p></div>{canEdit&&<Button onClick={()=>setPanel({mode:"create"})}><Plus className="size-4"/>Crear provincia</Button>}</div></div>
    <label className="relative block"><Search className="absolute left-3 top-3.5 size-4 text-muted"/><span className="sr-only">Buscar provincia o comuna</span><input className="min-h-11 w-full rounded-xl border bg-card pl-10 pr-4 text-sm" onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar provincia o comuna" value={query}/></label>{message&&<p className="rounded-xl border bg-card p-3 text-sm" role="status">{message}</p>}
    <div className="grid gap-4 xl:grid-cols-2">{visible.map((zone)=><article className="rounded-2xl border bg-card p-5" key={zone.id}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="rounded-xl border bg-background p-2.5 text-brand"><Car className="size-4"/></span><div><h3 className="font-semibold">{zone.province}</h3><p className="mt-1 text-sm font-semibold text-brand">{zone.transportValue===null?"Valor por confirmar":money.format(zone.transportValue)}</p></div></div><StatusBadge label={zone.enabled?"Activa":"Inactiva"} variant={zone.enabled?"success":"neutral"}/></div><div className="mt-5 border-t pt-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted">Comunas</p>{canEdit&&<button className="text-xs font-semibold text-brand" onClick={()=>mutateMunicipality(zone,"CREATE")}>+ Agregar comuna</button>}</div><div className="mt-3 space-y-2">{zone.municipalities.map((municipality)=><div className="flex min-h-10 items-center justify-between rounded-lg border px-3 text-sm" key={municipality}><span>{municipality}</span>{canEdit&&<span className="flex gap-1"><button aria-label={`Editar ${municipality}`} className="p-2 text-muted" onClick={()=>mutateMunicipality(zone,"UPDATE",municipality)}><Pencil className="size-3.5"/></button><button aria-label={`Eliminar ${municipality}`} className="p-2 text-danger" onClick={()=>mutateMunicipality(zone,"DELETE",municipality)}><Trash2 className="size-3.5"/></button></span>}</div>)}{!zone.municipalities.length&&<p className="rounded-lg border border-dashed p-3 text-sm text-muted">Sin comunas asignadas.</p>}</div></div>{canEdit&&<div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4"><Action icon={<Pencil/>} label="Editar" onClick={()=>setPanel({mode:"edit",zone})}/><Action disabled={pending} icon={<Power/>} label={zone.enabled?"Deshabilitar":"Habilitar"} onClick={()=>toggle(zone)}/><Action danger disabled={pending} icon={<Trash2/>} label="Eliminar" onClick={()=>remove(zone)}/></div>}</article>)}</div>{!visible.length&&<div className="rounded-2xl border border-dashed p-8 text-center"><p className="font-semibold">No hay zonas que coincidan.</p></div>}{panel&&<ZonePanel panel={panel} onClose={()=>setPanel(null)} onSaved={(text)=>{setPanel(null);setMessage(text);router.refresh();}}/>}</div>;
}

function ZonePanel({panel,onClose,onSaved}:{panel:Exclude<Panel,null>;onClose:()=>void;onSaved:(message:string)=>void}){const zone=panel.mode==="edit"?panel.zone:null;const [error,setError]=useState("");const [saving,startSaving]=useTransition();const submit=(data:FormData)=>{const value={id:zone?.id,code:zone?.code,province:String(data.get("province")??""),transportValue:data.get("transportValue")===""?null:Number(data.get("transportValue")),enabled:data.get("enabled")==="on",displayOrder:Number(data.get("displayOrder")??0),municipalities:String(data.get("municipalities")??"").split("\n").map((item)=>item.trim()).filter(Boolean),expectedVersion:zone?.version};startSaving(async()=>{const result=await mutateTransportZoneAction({operation:zone?"UPDATE":"CREATE",zone:value,reason:String(data.get("reason")??"")});if(!result.ok)return setError(result.error);onSaved(zone?"Provincia actualizada y auditada.":"Provincia creada y auditada.");});};return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 sm:max-w-2xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Master Data</p><h3 className="mt-1 text-2xl font-semibold">{zone?"Editar provincia":"Crear provincia"}</h3></div><button aria-label="Cerrar" className="rounded-lg border p-2" onClick={onClose}><X className="size-4"/></button></div><form action={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><Field defaultValue={zone?.province} label="Provincia" name="province" required/><Field defaultValue={zone?.transportValue?.toString()} label="Valor de transporte" min="0" name="transportValue" type="number"/><Field defaultValue={zone?.displayOrder.toString()??"100"} label="Orden" min="0" name="displayOrder" required type="number"/><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-3 text-sm"><input defaultChecked={zone?.enabled??true} name="enabled" type="checkbox"/>Activa</label><label className="text-sm font-medium sm:col-span-2">Comunas <span className="font-normal text-muted">(una por línea)</span><textarea className="mt-2 min-h-36 w-full rounded-xl border bg-background p-3" defaultValue={zone?.municipalities.join("\n")} name="municipalities"/></label><Field className="sm:col-span-2" label="Razón del cambio" name="reason" required/>{error&&<p className="text-sm text-danger sm:col-span-2" role="alert">{error}</p>}<Button className="sm:col-span-2" disabled={saving}>{saving?"Guardando…":zone?"Guardar cambios":"Crear provincia"}</Button></form></div></div>}
function Action({danger,disabled,icon,label,onClick}:{danger?:boolean;disabled?:boolean;icon:ReactNode;label:string;onClick:()=>void}){return <button className={`rounded-lg border px-2 py-2 text-xs font-semibold ${danger?"text-danger":""}`} disabled={disabled} onClick={onClick}><span className="mr-1 inline-block [&>svg]:size-3.5">{icon}</span>{label}</button>}
function Field({className="",label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className={`text-sm font-medium ${className}`}>{label}<input className="mt-2 h-11 w-full rounded-xl border bg-background px-3" {...props}/></label>}
