"use client";

import { useMemo, useState, useTransition } from "react";
import { AlertTriangle, PackageCheck, UserRoundCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { assignStaffAction, removeStaffAssignmentAction } from "@/features/resources/staff-management/actions";
import { missingPhysicalUnits } from "@/features/operations/resource-planning";
import { assignPhysicalResourcesAction, releaseOperationalAssetAction, replacePhysicalResourceAction } from "./actions";
import type { AssetStatus, AssetType } from "./types";

type Task = "ASSEMBLY" | "OPERATOR" | "DISASSEMBLY";
export interface EquipmentAssetOption { id: string; code: string; type: AssetType; status: AssetStatus; available: boolean; conflict?: { projectName: string; startAt: string; endAt: string }; }
export interface PhysicalResourceAssignment { assignmentId: string; assetId: string; code: string; status: AssetStatus; }
export interface PhysicalResourceRequirement { id: string; label: string; assetType: AssetType; required: number; assigned: number; assignments: readonly PhysicalResourceAssignment[]; options: readonly EquipmentAssetOption[]; }
export interface EquipmentStaffOption { id: string; name: string; group: "CALYPSO" | "GREEN"; capabilities: readonly Task[]; status: string; }
export interface CurrentStaffAssignment { id: string; staffId: string; name: string; task: Task; status: string; }
export interface EquipmentAssignmentPanelProps { projectId: string; orbitEventId: string; projectType: string; requirements: readonly PhysicalResourceRequirement[]; staff: readonly EquipmentStaffOption[]; currentStaff: readonly CurrentStaffAssignment[]; }

const STATUS:Record<AssetStatus,{label:string;variant:"success"|"info"|"warning"|"danger"}>={AVAILABLE:{label:"Disponible",variant:"success"},ASSIGNED:{label:"Planificado",variant:"info"},IN_EVENT:{label:"En uso",variant:"info"},MAINTENANCE:{label:"Mantención",variant:"warning"},OUT_OF_SERVICE:{label:"Fuera de servicio",variant:"danger"}};
const TASK={ASSEMBLY:"Montaje",OPERATOR:"Operación",DISASSEMBLY:"Desmontaje"} as const;

export function EquipmentAssignmentPanel(props:EquipmentAssignmentPanelProps){
  const router=useRouter();const[message,setMessage]=useState("");const[pending,startTransition]=useTransition();
  const run=(operation:()=>Promise<{ok:boolean;error?:string}>)=>{setMessage("Actualizando planificación…");startTransition(async()=>{const result=await operation();setMessage(result.ok?"Planificación de recursos actualizada.":result.error??"No fue posible actualizar los recursos.");if(result.ok)router.refresh();});};
  return <section className="space-y-5 scroll-mt-24" id="physical-resource-planning" aria-labelledby="equipment-title">
    <div><p className="text-xs font-medium uppercase tracking-[0.18em] text-brand">Operations 1.0 · Phase C</p><h2 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl" id="equipment-title">Recursos físicos</h2><p className="mt-2 text-sm text-muted">Selecciona los equipos reales. ORBIT valida la ventana operacional y nunca asigna silenciosamente.</p></div>
    {!props.requirements.length?<div className="rounded-2xl border border-dashed p-5 text-sm text-muted">Este Evento no requiere activos físicos configurados.</div>:props.requirements.map(requirement=><RequirementPlanner key={requirement.id} projectId={props.projectId} requirement={requirement} pending={pending} run={run}/>)}
    <StaffSelector assignments={props.currentStaff} onAssign={(staffId,task)=>run(()=>assignStaffAction({staffId,projectId:props.projectId,assignmentType:task,resources:{task,payrollLinked:true},reason:"Asignación operacional manual"}))} onRemove={assignmentId=>run(()=>removeStaffAssignmentAction(assignmentId,"Retiro manual desde Workspace"))} pending={pending} staff={props.staff}/>
    <p aria-live="polite" className="text-sm font-medium">{message}</p>
  </section>;
}

function RequirementPlanner({projectId,requirement,pending,run}:{projectId:string;requirement:PhysicalResourceRequirement;pending:boolean;run:(operation:()=>Promise<{ok:boolean;error?:string}>)=>void}){
  const[query,setQuery]=useState("");const[filter,setFilter]=useState("AVAILABLE");const[selected,setSelected]=useState<string[]>([]);const[replacement,setReplacement]=useState<Record<string,string>>({});
  const missing=missingPhysicalUnits(requirement.required,requirement.assignments.length);
  const options=requirement.options.filter(asset=>asset.code.toLowerCase().includes(query.trim().toLowerCase())&&(filter==="ALL"||(filter==="AVAILABLE"?asset.available:asset.status===filter)));
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):current.length<missing?[...current,id]:current);
  return <article className="rounded-2xl border bg-card p-4 sm:p-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><PackageCheck className="mt-1 size-5 shrink-0 text-brand"/><div><h3 className="font-semibold">{requirement.label}</h3><p className="mt-1 text-sm text-muted">Tipo {requirement.assetType}</p></div></div><div className="flex flex-wrap gap-2"><StatusBadge label={`${requirement.required} requeridos`} variant="info"/><StatusBadge label={`${requirement.assignments.length} asignados`} variant={missing?"warning":"success"}/>{missing?<StatusBadge label={`${missing} pendientes`} variant="warning"/>:<StatusBadge label="Recursos completos" variant="success"/>}</div></header>
    {requirement.assignments.length?<div className="mt-5 grid gap-3 lg:grid-cols-2">{requirement.assignments.map(item=><div className="rounded-xl border bg-background/35 p-4" key={item.assignmentId}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{item.code}</p><p className="text-xs text-muted">Asignado a este Evento</p></div><StatusBadge label={STATUS[item.status].label} variant={STATUS[item.status].variant}/></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><select className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setReplacement(current=>({...current,[item.assignmentId]:event.target.value}))} value={replacement[item.assignmentId]??""}><option value="">Seleccionar reemplazo…</option>{requirement.options.filter(asset=>asset.available&&asset.id!==item.assetId).map(asset=><option key={asset.id} value={asset.id}>{asset.code}</option>)}</select><ActionButton disabled={pending||!replacement[item.assignmentId]} label="Reemplazar" onClick={()=>run(()=>replacePhysicalResourceAction({projectId,assignmentId:item.assignmentId,assetId:replacement[item.assignmentId],reason:"Reemplazo manual desde Event Workspace"}))}/></div><ActionButton className="mt-2" disabled={pending} label="Quitar asignación" onClick={()=>run(()=>releaseOperationalAssetAction({projectId,assignmentId:item.assignmentId,reason:"Desasignación manual desde Event Workspace"}))} variant="outline"/></div>)}</div>:null}
    {missing>0?<div className="mt-5 border-t pt-5"><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><input className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setQuery(event.target.value)} placeholder="Buscar código o nombre…" value={query}/><select className="min-h-11 rounded-xl border bg-background px-3 text-sm" onChange={event=>setFilter(event.target.value)} value={filter}><option value="AVAILABLE">Disponibles</option><option value="ALL">Todos</option><option value="MAINTENANCE">Mantención</option><option value="OUT_OF_SERVICE">Fuera de servicio</option></select></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{options.map(asset=><label className={`rounded-xl border p-3 ${asset.available?"cursor-pointer":"opacity-65"}`} key={asset.id}><div className="flex items-start gap-3"><input checked={selected.includes(asset.id)} className="mt-1 size-4" disabled={!asset.available||pending} onChange={()=>toggle(asset.id)} type="checkbox"/><div className="min-w-0"><p className="font-medium">{asset.code}</p><p className="text-xs text-muted">{STATUS[asset.status].label}</p>{asset.conflict?<p className="mt-1 flex gap-1 text-xs text-danger"><AlertTriangle className="size-3 shrink-0"/>{asset.conflict.projectName} · {formatWindow(asset.conflict.startAt,asset.conflict.endAt)}</p>:null}</div></div></label>)}{!options.length?<p className="text-sm text-muted">No hay equipos para este filtro.</p>:null}</div><ActionButton className="mt-4" disabled={pending||!selected.length} label={`Asignar ${selected.length||""} equipo${selected.length===1?"":"s"}`.trim()} onClick={()=>run(()=>assignPhysicalResourcesAction({projectId,requirementId:requirement.id,assetIds:selected,reason:"Planificación manual desde Event Workspace"}))}/></div>:null}
  </article>;
}

const formatWindow=(start:string,end:string)=>`${new Date(start).toLocaleString("es-CL",{dateStyle:"short",timeStyle:"short",timeZone:"America/Santiago"})} – ${new Date(end).toLocaleTimeString("es-CL",{hour:"2-digit",minute:"2-digit",timeZone:"America/Santiago"})}`;

function StaffSelector({staff,assignments,onAssign,onRemove,pending}:{staff:readonly EquipmentStaffOption[];assignments:readonly CurrentStaffAssignment[];onAssign:(staffId:string,task:Task)=>void;onRemove:(assignmentId:string)=>void;pending:boolean}){
  const[task,setTask]=useState<Task>("OPERATOR");const[staffId,setStaffId]=useState("");const eligible=useMemo(()=>staff.filter(member=>member.status==="ACTIVE"&&member.capabilities.includes(task)),[staff,task]);
  return <div className="rounded-2xl border bg-card p-4 sm:p-6"><div className="flex items-center gap-3"><UserRoundCheck className="size-5 text-brand"/><h3 className="font-semibold">Staff operacional</h3></div><div className="mt-5 grid gap-3 md:grid-cols-[180px_1fr_auto]"><select className="min-h-11 rounded-lg border bg-background px-3 text-sm" onChange={event=>{setTask(event.target.value as Task);setStaffId("");}} value={task}>{Object.entries(TASK).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select className="min-h-11 rounded-lg border bg-background px-3 text-sm" onChange={event=>setStaffId(event.target.value)} value={staffId}><option value="">Seleccionar colaborador…</option>{eligible.map(member=><option key={member.id} value={member.id}>{member.name} · {member.group}</option>)}</select><ActionButton disabled={pending||!staffId} label="Asignar" onClick={()=>staffId&&onAssign(staffId,task)}/></div><div className="mt-5 space-y-2">{assignments.map(assignment=><div className="flex flex-col gap-3 rounded-xl border bg-background/40 p-4 sm:flex-row sm:items-center sm:justify-between" key={assignment.id}><div><p className="font-medium">{assignment.name}</p><p className="mt-1 text-sm text-muted">{TASK[assignment.task]} · {assignment.status}</p></div><ActionButton disabled={pending} label="Retirar" onClick={()=>onRemove(assignment.id)} variant="outline"/></div>)}</div></div>;
}
