"use client";

import { useMemo, useState, useTransition } from "react";
import { Box, PackageCheck, Sparkles, UserRoundCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { assignStaffAction, removeStaffAssignmentAction } from "@/features/resources/staff-management/actions";
import { assignOperationalAssetAction, releaseOperationalAssetAction } from "./actions";
import type { AssetStatus, AssetType } from "./types";

type Task = "ASSEMBLY" | "OPERATOR" | "DISASSEMBLY";
export interface EquipmentAssetOption { id: string; code: string; type: AssetType; status: AssetStatus; usageCounter: number; qrKey: string; current?: { assignmentId: string; projectName: string; date: string; time: string; operator: string }; }
export interface EquipmentStaffOption { id: string; name: string; group: "CALYPSO" | "GREEN"; capabilities: readonly Task[]; status: string; }
export interface CurrentStaffAssignment { id: string; staffId: string; name: string; task: Task; status: string; }
export interface EquipmentAssignmentPanelProps { projectId: string; orbitEventId: string; projectType: string; assets: readonly EquipmentAssetOption[]; staff: readonly EquipmentStaffOption[]; currentStaff: readonly CurrentStaffAssignment[]; }

const STATUS = { AVAILABLE: { label: "Disponible", variant: "success" }, ASSIGNED: { label: "Asignado", variant: "info" }, MAINTENANCE: { label: "Mantención", variant: "warning" }, OUT_OF_SERVICE: { label: "Fuera de servicio", variant: "danger" } } as const;
const TASK = { ASSEMBLY: "Montaje", OPERATOR: "Operación", DISASSEMBLY: "Desmontaje" } as const;

export function EquipmentAssignmentPanel(props: EquipmentAssignmentPanelProps) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const recommendation = ["Wedding", "Corporate"].includes(props.projectType) ? "Totem White" : ["Birthday", "Graduation"].includes(props.projectType) ? "Totem Black" : undefined;
  const currentTotem = props.assets.find((asset) => asset.type === "TOTEM" && asset.current?.projectName === "Este evento");
  const currentCase = props.assets.find((asset) => asset.type === "CASE" && asset.current?.projectName === "Este evento");
  const run = (operation: () => Promise<{ ok: boolean; error?: string }>) => { setMessage("Actualizando asignación…"); startTransition(async () => { const result = await operation(); setMessage(result.ok ? "Asignación actualizada correctamente." : result.error ?? "No fue posible actualizar la asignación."); if (result.ok) router.refresh(); }); };
  return <section className="space-y-5" aria-labelledby="equipment-title"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-muted">Control operacional</p><h2 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl" id="equipment-title">Asignación manual</h2><p className="mt-2 text-sm text-muted">Operaciones elige cada recurso. ORBIT valida disponibilidad y nunca asigna automáticamente.</p></div>
    {recommendation && <div className="flex items-start gap-3 rounded-xl border border-brand/25 bg-brand/5 p-4 text-sm"><Sparkles className="mt-0.5 size-4 shrink-0 text-brand" /><div><p className="font-semibold">Recomendación NOVA: {recommendation}</p><p className="mt-1 text-muted">Sugerencia según tipo de evento. La decisión permanece en Operaciones.</p></div></div>}
    <div className="grid gap-4 xl:grid-cols-2"><AssetSelector assetType="TOTEM" current={currentTotem} icon="totem" label="Totem" onAssign={(asset) => run(() => assignOperationalAssetAction({ projectId: props.projectId, assetId: asset.id, orbitEventId: props.orbitEventId, reason: "Asignación manual desde Workspace" }))} onRelease={(assignmentId) => run(() => releaseOperationalAssetAction({ projectId: props.projectId, assignmentId, reason: "Liberación manual desde Workspace" }))} options={props.assets.filter((asset) => asset.type === "TOTEM")} pending={pending} /><AssetSelector assetType="CASE" current={currentCase} icon="case" label="Case" onAssign={(asset) => run(() => assignOperationalAssetAction({ projectId: props.projectId, assetId: asset.id, orbitEventId: props.orbitEventId, reason: "Asignación manual desde Workspace" }))} onRelease={(assignmentId) => run(() => releaseOperationalAssetAction({ projectId: props.projectId, assignmentId, reason: "Liberación manual desde Workspace" }))} options={props.assets.filter((asset) => asset.type === "CASE")} pending={pending} /></div>
    <StaffSelector assignments={props.currentStaff} onAssign={(staffId, task) => run(() => assignStaffAction({ staffId, projectId: props.projectId, assignmentType: task, resources: { task, payrollLinked: true }, reason: "Asignación operacional manual" }))} onRemove={(assignmentId) => run(() => removeStaffAssignmentAction(assignmentId, "Retiro manual desde Workspace"))} pending={pending} staff={props.staff} />
    <p aria-live="polite" className="text-sm font-medium">{message}</p>
  </section>;
}

function AssetSelector({ label, options, current, onAssign, onRelease, pending, icon }: { assetType: AssetType; label: string; options: readonly EquipmentAssetOption[]; current?: EquipmentAssetOption; onAssign: (asset: EquipmentAssetOption) => void; onRelease: (assignmentId: string) => void; pending: boolean; icon: "totem" | "case" }) {
  const [query, setQuery] = useState(""); const selected = options.find((asset) => asset.code.toLowerCase() === query.trim().toLowerCase()); const Icon = icon === "totem" ? PackageCheck : Box;
  return <div className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Icon className="size-5 text-brand" /><h3 className="font-semibold">{label}</h3></div>{current && <StatusBadge label="Asignado a este evento" variant="success" />}</div>{current && <div className="mt-5 rounded-xl border bg-background/40 p-4"><p className="text-xl font-semibold">{current.code}</p><p className="mt-1 text-sm text-muted">{current.usageCounter} usos registrados · QR asignado</p><ActionButton className="mt-4" disabled={pending} label="Liberar" onClick={() => current.current && onRelease(current.current.assignmentId)} variant="outline" /></div>}<input className="mt-5 min-h-11 w-full rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-brand" list={`${label}-options`} onChange={(event) => setQuery(event.target.value)} placeholder={current ? `Buscar reemplazo para ${current.code}…` : `Buscar ${label.toLowerCase()}…`} value={query} /><datalist id={`${label}-options`}>{options.filter((asset) => asset.id !== current?.id).map((asset) => <option key={asset.id} value={asset.code}>{STATUS[asset.status].label}</option>)}</datalist>{selected && <div className="mt-4 rounded-xl border bg-background/40 p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{selected.code}</p><StatusBadge label={STATUS[selected.status].label} variant={STATUS[selected.status].variant} /></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted">Evento actual</dt><dd>{selected.current?.projectName ?? "Sin asignación"}</dd></div><div><dt className="text-muted">Fecha y hora</dt><dd>{selected.current ? `${selected.current.date} · ${selected.current.time}` : "Disponible"}</dd></div><div><dt className="text-muted">Operador</dt><dd>{selected.current?.operator ?? "Sin asignar"}</dd></div><div><dt className="text-muted">Uso acumulado</dt><dd>{selected.usageCounter}</dd></div></dl></div>}<ActionButton className="mt-4" disabled={pending || selected?.status !== "AVAILABLE"} label={selected?.status === "AVAILABLE" ? current ? `Reemplazar ${label}` : `Asignar ${label}` : "Selecciona un equipo disponible"} onClick={() => selected && onAssign(selected)} /></div>;
}

function StaffSelector({ staff, assignments, onAssign, onRemove, pending }: { staff: readonly EquipmentStaffOption[]; assignments: readonly CurrentStaffAssignment[]; onAssign: (staffId: string, task: Task) => void; onRemove: (assignmentId: string) => void; pending: boolean }) {
  const [task, setTask] = useState<Task>("OPERATOR"); const [staffId, setStaffId] = useState(""); const eligible = useMemo(() => staff.filter((member) => member.status === "ACTIVE" && member.capabilities.includes(task)), [staff, task]);
  return <div className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><UserRoundCheck className="size-5 text-brand" /><h3 className="font-semibold">Staff operacional</h3></div><div className="mt-5 grid gap-3 md:grid-cols-[180px_1fr_auto]"><select className="min-h-11 rounded-lg border bg-background px-3 text-sm" onChange={(event) => { setTask(event.target.value as Task); setStaffId(""); }} value={task}>{Object.entries(TASK).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select className="min-h-11 rounded-lg border bg-background px-3 text-sm" onChange={(event) => setStaffId(event.target.value)} value={staffId}><option value="">Seleccionar colaborador…</option>{eligible.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.group}</option>)}</select><ActionButton disabled={pending || !staffId} label="Asignar" onClick={() => staffId && onAssign(staffId, task)} /></div>{!eligible.length && <p className="mt-3 text-sm text-warning">No hay Staff activo habilitado para {TASK[task].toLowerCase()}.</p>}<div className="mt-5 space-y-2">{assignments.map((assignment) => <div className="flex flex-col gap-3 rounded-xl border bg-background/40 p-4 sm:flex-row sm:items-center sm:justify-between" key={assignment.id}><div><p className="font-medium">{assignment.name}</p><p className="mt-1 text-sm text-muted">{TASK[assignment.task]} · {assignment.status}</p></div><ActionButton disabled={pending} label="Retirar" onClick={() => onRemove(assignment.id)} variant="outline" /></div>)}</div></div>;
}
