"use client";

import { useMemo, useState, type ReactNode } from "react";
import { BarChart3, BriefcaseBusiness, CalendarRange, Download, FileSpreadsheet, FileText, Gauge, Package, Star, TrendingUp, UsersRound, WalletCards } from "lucide-react";
import { WorkspaceLayout } from "@/components/layout/workspace-layout";
import { ActionButton } from "@/components/ui/action-button";
import { StatusBadge } from "@/components/ui/status-badge";
import type { BusinessIntelligenceDataset, ChartDatum, IntelligenceRange } from "./types";

const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
const number=(value:number,digits=0)=>new Intl.NumberFormat("es-CL",{maximumFractionDigits:digits}).format(value);
const chileDateTimeFormatter = new Intl.DateTimeFormat("es-CL",{
  timeZone:"America/Santiago",
  day:"2-digit",
  month:"2-digit",
  year:"numeric",
  hour:"2-digit",
  minute:"2-digit",
});
const chileInputDate = (value = new Date()) => {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Santiago",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(value);
  const year = parts.find((part) => part.type === "year")?.value ?? "";
  const month = parts.find((part) => part.type === "month")?.value ?? "";
  const day = parts.find((part) => part.type === "day")?.value ?? "";
  return `${year}-${month}-${day}`;
};
const day=(value:string|null|undefined)=>value?.slice(0,10)??"";
const normalized=(value:string)=>value.trim().toLocaleLowerCase("es-CL");

export function BusinessIntelligenceCenter({dataset}:{dataset:BusinessIntelligenceDataset}){
  const [range,setRange]=useState<IntelligenceRange>("MONTH"); const today=chileInputDate(); const [customStart,setCustomStart]=useState(today); const [customEnd,setCustomEnd]=useState(today);
  const metrics=useMemo(()=>calculate(dataset,range,customStart,customEnd,today),[dataset,range,customStart,customEnd,today]);
  const negotiationMetrics=useMemo(()=>dataset.quotations.reduce((result,quotation)=>{const snapshot=(quotation.pricing_snapshot??{}) as Record<string,unknown>;const commercial=(snapshot.commercialNegotiation??{}) as Record<string,unknown>;const official=Number(quotation.official_price??quotation.grand_total);const final=Number(quotation.final_customer_price??quotation.grand_total);const courtesy=Number(snapshot.courtesyValue??commercial.courtesyValue??0);const days=Number(snapshot.paymentTermDays??commercial.paymentTermDays??0);return{officialRevenue:result.officialRevenue+official,discountGiven:result.discountGiven+Number(snapshot.discount??commercial.discountAmount??quotation.discount_total??0),courtesyCost:result.courtesyCost+courtesy,commercialMargin:result.commercialMargin+(final-official+courtesy),paymentDays:result.paymentDays+days,terms:result.terms+(days>0?1:0)}},{officialRevenue:0,discountGiven:0,courtesyCost:0,commercialMargin:0,paymentDays:0,terms:0}),[dataset.quotations]);
  const operationMetrics=useMemo(()=>{const rows=dataset.financialEvents.filter(item=>item.status==="CONFIRMED");const count=rows.length||1;return{averagePersonnelCost:rows.reduce((sum,item)=>sum+Number(item.personnel_cost),0)/count,averageOperationalResourcesCost:rows.reduce((sum,item)=>sum+Number(item.operational_resources_cost),0)/count,averageEventCost:rows.reduce((sum,item)=>sum+Number(item.total_operational_cost),0)/count}},[dataset.financialEvents]);
  const exportRows=()=>[
    ["Métrica","Valor"],["Ingresos de hoy",money(metrics.todayRevenue)],["Profit de hoy",money(metrics.todayProfit)],["Ingresos del mes",money(metrics.monthRevenue)],["Profit del mes",money(metrics.monthProfit)],["Cotizaciones abiertas",String(metrics.openQuotations)],["Conversión",`${metrics.conversion.toFixed(1)}%`],["Ticket promedio",money(metrics.averageTicket)],["Margen promedio",`${metrics.averageMargin.toFixed(1)}%`],["Clientes nuevos",String(metrics.newCustomers)],["Clientes recurrentes",String(metrics.returningCustomers)],["Eventos próximos",String(metrics.upcomingEvents)],["Eventos completados",String(metrics.completedEvents)],["Eventos cancelados",String(metrics.cancelledEvents)]];
  const receivables={total:dataset.receivables.reduce((s,x)=>s+Number(x.amount),0),outstanding:dataset.receivables.reduce((s,x)=>s+Number(x.outstanding_balance),0),overdue:dataset.receivables.filter(x=>x.effective_status==="OVERDUE").reduce((s,x)=>s+Number(x.outstanding_balance),0),aging:["15","30","60","90+"].map(label=>({label,value:dataset.receivables.filter(x=>x.aging_bucket===label).reduce((s,x)=>s+Number(x.outstanding_balance),0)}))};
  return <WorkspaceLayout header={null} timeline={null} copilot={null} className="max-w-none p-0" mainContent={<main className="space-y-6 pb-10" id="business-intelligence">
    <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><StatusBadge label="Datos productivos" variant="success"/><StatusBadge label={`Actualizado ${chileDateTimeFormatter.format(new Date(dataset.generatedAt))}`} variant="neutral"/></div><p className="mt-5 text-xs font-semibold uppercase tracking-[.2em] text-brand">Business Intelligence Center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Inteligencia ejecutiva</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Una lectura comercial, financiera y operacional construida exclusivamente desde los registros productivos de ORBIT.</p></div><div className="flex flex-wrap gap-2 print:hidden"><ActionButton icon={FileText} label="PDF" onClick={()=>window.print()} variant="outline"/><ActionButton icon={FileSpreadsheet} label="Excel" onClick={()=>downloadExcel(exportRows())} variant="outline"/><ActionButton icon={Download} label="CSV" onClick={()=>downloadCsv(exportRows())}/></div></div>
      <div className="mt-6 flex gap-2 overflow-x-auto border-t pt-5 print:hidden">{([['TODAY','Hoy'],['WEEK','Semana'],['MONTH','Mes'],['QUARTER','Trimestre'],['YEAR','Año'],['CUSTOM','Rango']] as [IntelligenceRange,string][]).map(([value,label])=><button className={`min-h-10 shrink-0 rounded-full border px-4 text-sm font-medium ${range===value?"border-brand bg-brand/10 text-brand":"text-muted"}`} key={value} onClick={()=>setRange(value)}>{label}</button>)}</div>
      {range==="CUSTOM"&&<div className="mt-4 grid gap-3 sm:grid-cols-2 print:hidden"><label className="text-sm text-muted">Desde<input className="mt-1 block min-h-11 w-full rounded-xl border bg-background px-3 text-foreground" onChange={event=>setCustomStart(event.target.value)} type="date" value={customStart}/></label><label className="text-sm text-muted">Hasta<input className="mt-1 block min-h-11 w-full rounded-xl border bg-background px-3 text-foreground" onChange={event=>setCustomEnd(event.target.value)} type="date" value={customEnd}/></label></div>}
    </section>

    <section aria-labelledby="executive-dashboard"><Title eyebrow="Resumen" icon={<Gauge/>} id="executive-dashboard" title="Dashboard ejecutivo"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-5"><Kpi href="/projects?financial=revenue&date=today" label="Ingresos de hoy" value={money(metrics.todayRevenue)}/><Kpi href="/projects?financial=profit&date=today" label="Profit de hoy" value={money(metrics.todayProfit)}/><Kpi href="/projects?financial=revenue&period=month" label="Ingresos del mes" value={money(metrics.monthRevenue)}/><Kpi href="/projects?financial=profit&period=month" label="Profit del mes" value={money(metrics.monthProfit)}/><Kpi href="/projects?filter=open-quotations" label="Cotizaciones abiertas" value={String(metrics.openQuotations)}/><Kpi label="Conversión" value={`${metrics.conversion.toFixed(1)}%`}/><Kpi href="/projects?focus=upcoming" label="Próximos eventos" value={String(metrics.upcomingEvents)}/><Kpi href="/projects?status=completed" label="Completados" value={String(metrics.completedEvents)}/><Kpi href="/projects?status=cancelled" label="Cancelados" value={String(metrics.cancelledEvents)}/></div></section>
    <Panel eyebrow="Cobranza" icon={<WalletCards/>} title="Cuentas por Cobrar"><MetricGrid items={[["Total facturado",money(receivables.total)],["Saldo pendiente",money(receivables.outstanding)],["Saldo vencido",money(receivables.overdue)]]}/><Chart title="Facturas por antigüedad" data={receivables.aging} format={money}/></Panel>

    <section className="grid gap-6 xl:grid-cols-2">
      <Panel eyebrow="Ventas" icon={<BriefcaseBusiness/>} title="KPIs comerciales"><MetricGrid items={[["Conversión",`${metrics.conversion.toFixed(1)}%`],["Ticket promedio",money(metrics.averageTicket)],["Ingreso oficial",money(negotiationMetrics.officialRevenue)],["Descuentos otorgados",money(negotiationMetrics.discountGiven)],["Costo de cortesías",money(negotiationMetrics.courtesyCost)],["Margen comercial",money(negotiationMetrics.commercialMargin)],["Plazo promedio",`${negotiationMetrics.terms?number(negotiationMetrics.paymentDays/negotiationMetrics.terms,1):0} días`]]}/><Chart title="Ingresos por servicio" data={metrics.revenueByService} format={money}/><Chart title="Ingresos por tipo de evento" data={metrics.revenueByEventType} format={money}/><Chart title="Ingresos por comuna" data={metrics.revenueByMunicipality} format={money}/><Chart title="Ingresos por vendedor" data={metrics.revenueBySalesperson} format={money}/></Panel>
      <Panel eyebrow="Rentabilidad" icon={<TrendingUp/>} title="KPIs de profit"><MetricGrid items={[["Costo personal promedio",money(operationMetrics.averagePersonnelCost)],["Costo operacional promedio",money(operationMetrics.averageOperationalResourcesCost)],["Costo total promedio",money(operationMetrics.averageEventCost)],["Margen promedio",`${metrics.averageMargin.toFixed(1)}%`],["Margen más bajo",metrics.lowestMargin?`${metrics.lowestMargin.label} · ${metrics.lowestMargin.value.toFixed(1)}%`:"Sin datos"],["Margen más alto",metrics.highestMargin?`${metrics.highestMargin.label} · ${metrics.highestMargin.value.toFixed(1)}%`:"Sin datos"]]}/><Chart title="Profit por evento" data={metrics.profitByEvent} format={money}/><Chart title="Profit por servicio" data={metrics.profitByService} format={money}/><Chart title="Profit por comuna" data={metrics.profitByMunicipality} format={money}/></Panel>
      <Panel eyebrow="Relaciones" icon={<UsersRound/>} title="KPIs de clientes"><MetricGrid items={[["Clientes nuevos",String(metrics.newCustomers)],["Clientes recurrentes",String(metrics.returningCustomers)],["Mayor ingreso",metrics.topCustomerRevenue?.label??"Sin datos"],["Mayor profit",metrics.topCustomerProfit?.label??"Sin datos"],["Lifetime Value promedio",money(metrics.averageLifetimeValue)]]}/><Chart title="Clientes por ingresos" data={metrics.customerRevenue.slice(0,6)} format={money}/></Panel>
      <Panel eyebrow="Equipo" icon={<WalletCards/>} title="KPIs de Staff"><div className="space-y-3">{metrics.staff.length?metrics.staff.map(item=><article className="rounded-xl border p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-muted">{item.events} eventos · {number(item.hours,1)} horas contratadas</p></div><StatusBadge label={item.rating===null?"Sin evaluación":`${item.rating.toFixed(1)} ★`} variant={item.rating===null?"neutral":"success"}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Small label="Costo promedio" value={money(item.averageCost)}/><Small label="Ingreso promedio" value={money(item.averageRevenue)}/><Small label="Profit promedio" value={money(item.averageProfit)}/><Small label="Estado" value={item.status}/></div></article>):<Empty text="Los indicadores aparecerán cuando exista Staff productivo asignado."/>}</div></Panel>
      <Panel eyebrow="Recursos" icon={<Package/>} title="KPIs de equipamiento"><MetricGrid items={[["Totem White más usado",metrics.equipment.mostWhite],["Totem Black más usado",metrics.equipment.mostBlack],["Case más usado",metrics.equipment.mostCase],["En mantención",String(metrics.equipment.maintenance)],["Disponibilidad",`${metrics.equipment.availability.toFixed(1)}%`]]}/><Chart title="Uso de equipamiento" data={metrics.equipment.usage.slice(0,8)} format={value=>`${number(value)} usos`}/></Panel>
      <Panel eyebrow="Aprendizaje" icon={<Star/>} title="Experience Review KPIs"><Chart title="Lugares mejor evaluados" data={metrics.topVenues} format={value=>`${value.toFixed(1)} ★`}/><Chart title="Clientes mejor evaluados" data={metrics.topCustomers} format={value=>`${value.toFixed(1)} ★`}/><PhraseList title="Situaciones operacionales frecuentes" values={metrics.operationalIssues}/><PhraseList title="Recomendaciones recurrentes" values={metrics.recommendations}/></Panel>
    </section>
    <p className="text-xs text-muted">Las cifras excluyen registros de certificación del sistema. No se estiman métricas sin una fuente productiva.</p>
  </main>} bottomAction={null}/>;
}

function calculate(data:BusinessIntelligenceDataset,range:IntelligenceRange,customStart:string,customEnd:string,today:string){
  const {start,end}=bounds(range,customStart,customEnd,today); const projectMap=new Map(data.projects.map(item=>[item.id,item])); const customerMap=new Map(data.customers.map(item=>[item.id,item])); const profileMap=new Map(data.profiles.map(item=>[item.id,item.display_name]));
  const inRange=(value:string|null|undefined)=>{const date=day(value);return Boolean(date&&date>=start&&date<=end)}; const projectInRange=(id:string)=>inRange(projectMap.get(id)?.event_date);
  const truth=data.financialEvents.filter(item=>item.status==="CONFIRMED");const truthIds=new Set(truth.map(item=>item.project_id));const truthRange=truth.filter(item=>projectInRange(item.project_id));
  const accepted=data.quotations.filter(item=>item.status==="ACCEPTED"&&truthIds.has(item.project_id)); const acceptedRange=accepted.filter(item=>projectInRange(item.project_id)); const acceptedIds=new Set(acceptedRange.map(item=>item.id));
  const latestProfits=truth.map(item=>({project_id:item.project_id,gross_margin:item.gross_profit,gross_margin_percent:item.gross_margin})); const profitRange=latestProfits.filter(item=>projectInRange(item.project_id));
  const thisMonth=today.slice(0,7); const revenueFor=(predicate:(projectId:string)=>boolean)=>truth.filter(item=>predicate(item.project_id)).reduce((sum,item)=>sum+item.revenue,0); const profitFor=(predicate:(projectId:string)=>boolean)=>truth.filter(item=>predicate(item.project_id)).reduce((sum,item)=>sum+item.gross_profit,0);
  const valueOf=(quote:typeof data.quotations[number])=>Number(quote.final_customer_price??quote.grand_total); const group=(rows:readonly {label:string;value:number}[])=>groupValues(rows);
  const serviceItems=data.quotationItems.filter(item=>item.item_type==="SERVICE"&&acceptedIds.has(item.quotation_id));
  const revenueByService=group(serviceItems.map(item=>({label:item.label||item.code,value:Number(item.total)})));
  const revenueByEventType=group(acceptedRange.map(item=>({label:projectMap.get(item.project_id)?.project_type??"Sin tipo",value:valueOf(item)})));
  const revenueByMunicipality=group(acceptedRange.map(item=>({label:projectMap.get(item.project_id)?.city??"Sin comuna",value:valueOf(item)})));
  const revenueBySalesperson=group(acceptedRange.map(item=>({label:profileMap.get(item.approved_by??item.created_by??"")??"Sin vendedor",value:valueOf(item)})));
  const profitByEvent=profitRange.map(item=>({label:projectMap.get(item.project_id)?.name??"Evento",value:Number(item.gross_margin)})).sort((a,b)=>b.value-a.value);
  const profitByMunicipality=group(profitRange.map(item=>({label:projectMap.get(item.project_id)?.city??"Sin comuna",value:Number(item.gross_margin)})));
  const profitServiceRows=profitRange.flatMap(item=>{const services=data.services.filter(service=>service.project_id===item.project_id); if(!services.length)return[{label:"Sin servicio",value:Number(item.gross_margin)}];const quote=acceptedRange.find(q=>q.project_id===item.project_id);const items=quote?serviceItems.filter(service=>service.quotation_id===quote.id):[];const total=items.reduce((sum,row)=>sum+Number(row.total),0);return services.map(service=>{const found=items.find(row=>row.code===service.service_code);return{label:service.service_code,value:total&&found?Number(item.gross_margin)*Number(found.total)/total:Number(item.gross_margin)/services.length}})});
  const profitByService=group(profitServiceRows); const margins=profitRange.map(item=>({label:projectMap.get(item.project_id)?.name??"Evento",value:Number(item.gross_margin_percent)})).sort((a,b)=>a.value-b.value);
  const projectsByCustomer=new Map<string,number>(); data.projects.forEach(item=>projectsByCustomer.set(item.customer_id,(projectsByCustomer.get(item.customer_id)??0)+1)); const rangeCustomerIds=new Set(data.projects.filter(item=>inRange(item.event_date)).map(item=>item.customer_id));
  const customerRevenue=group(truth.map(item=>({label:customerMap.get(item.customer_id)?.full_name??"Cliente",value:item.revenue}))); const profitByCustomer=group(truth.map(item=>({label:customerMap.get(item.customer_id)?.full_name??"Cliente",value:item.gross_profit})));
  const reviewMap=new Map(data.reviews.map(item=>[item.id,item])); const incidentsByProject=new Map<string,number>(); data.assetHistory.filter(item=>item.history_type==="INCIDENT"&&item.project_id).forEach(item=>incidentsByProject.set(item.project_id!, (incidentsByProject.get(item.project_id!)??0)+1));
  const staff=data.staff.map(member=>{const assignments=data.assignments.filter(item=>item.staff_id===member.id&&projectInRange(item.project_id));const projectIds=new Set(assignments.map(item=>item.project_id));const hours=[...projectIds].reduce((sum,id)=>sum+data.services.filter(service=>service.project_id===id).reduce((max,service)=>Math.max(max,Number(service.duration_hours??0)),0),0);const ratings=data.reviewStaff.filter(item=>item.staff_id===member.id).map(item=>reviewMap.get(item.review_id)?.general_rating).filter((item):item is number=>typeof item==="number");const payroll=data.payroll.filter(item=>item.staff_id===member.id&&projectInRange(item.project_id)).reduce((sum,item)=>sum+Number(item.total_internal_payment),0);const revenue=[...projectIds].reduce((sum,id)=>sum+Number(acceptedRange.find(item=>item.project_id===id)?.final_customer_price??acceptedRange.find(item=>item.project_id===id)?.grand_total??0),0);const profit=[...projectIds].reduce((sum,id)=>sum+Number(profitRange.find(item=>item.project_id===id)?.gross_margin??0),0);return{id:member.id,name:`${member.first_name} ${member.last_name}`,status:member.status,events:projectIds.size,hours,payroll,averageCost:projectIds.size?payroll/projectIds.size:0,averageRevenue:projectIds.size?revenue/projectIds.size:0,averageProfit:projectIds.size?profit/projectIds.size:0,rating:ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null,incidents:[...projectIds].reduce((sum,id)=>sum+(incidentsByProject.get(id)??0),0)}}).filter(item=>item.events||item.payroll||item.rating!==null).sort((a,b)=>b.events-a.events);
  const productionAssigned=new Set(data.assetAssignments.filter(item=>item.assignment_status==="ASSIGNED").map(item=>item.asset_id)); const effectiveAssets=data.assets.map(item=>({...item,status:item.status==="ASSIGNED"&&!productionAssigned.has(item.id)?"AVAILABLE":item.status})); const usageCounts=new Map<string,number>();data.assetHistory.filter(item=>item.history_type==="OPERATION").forEach(item=>usageCounts.set(item.asset_id,(usageCounts.get(item.asset_id)??0)+1));const assetUsage=effectiveAssets.map(item=>({label:item.asset_code,value:usageCounts.get(item.id)??0})).sort((a,b)=>b.value-a.value);const available=effectiveAssets.filter(item=>item.status==="AVAILABLE").length; const most=(prefix:string)=>{const item=assetUsage.find(candidate=>candidate.label.startsWith(prefix)&&candidate.value>0);return item?.label??"Sin datos"};
  const reviewRange=data.reviews.filter(item=>inRange(item.created_at)); const topVenues=averageGroups(reviewRange.map(item=>({label:[item.venue_name,item.venue_city].filter(Boolean).join(" · "),value:item.general_rating}))); const topCustomers=averageGroups(reviewRange.map(item=>({label:customerMap.get(item.customer_id)?.full_name??"Cliente",value:item.general_rating})));
  const allConversion=data.quotations.filter(item=>inRange(projectMap.get(item.project_id)?.event_date)&&["SENT","ACCEPTED","REJECTED"].includes(item.status));
  return{todayRevenue:revenueFor(id=>projectMap.get(id)?.event_date===today),todayProfit:profitFor(id=>projectMap.get(id)?.event_date===today),monthRevenue:revenueFor(id=>projectMap.get(id)?.event_date?.startsWith(thisMonth)??false),monthProfit:profitFor(id=>projectMap.get(id)?.event_date?.startsWith(thisMonth)??false),openQuotations:data.quotations.filter(item=>["DRAFT","SENT"].includes(item.status)).length,conversion:allConversion.length?allConversion.filter(item=>item.status==="ACCEPTED").length/allConversion.length*100:0,upcomingEvents:data.projects.filter(item=>item.event_date&&item.event_date>=today&&!['Completed','Archived','Cancelled','CANCELLED'].includes(item.status)).length,completedEvents:data.projects.filter(item=>inRange(item.event_date)&&['Completed','Archived'].includes(item.status)).length,cancelledEvents:data.projects.filter(item=>inRange(item.event_date)&&['Cancelled','CANCELLED'].includes(item.status)).length,averageTicket:truthRange.length?truthRange.reduce((sum,item)=>sum+item.revenue,0)/truthRange.length:0,revenueByService,revenueByEventType,revenueByMunicipality,revenueBySalesperson,profitByEvent,profitByService,profitByMunicipality,averageMargin:margins.length?margins.reduce((sum,item)=>sum+item.value,0)/margins.length:0,lowestMargin:margins[0],highestMargin:margins.at(-1),newCustomers:data.customers.filter(item=>inRange(item.created_at)).length,returningCustomers:[...rangeCustomerIds].filter(id=>(projectsByCustomer.get(id)??0)>1).length,topCustomerRevenue:customerRevenue[0],topCustomerProfit:profitByCustomer[0],averageLifetimeValue:customerRevenue.length?customerRevenue.reduce((sum,item)=>sum+item.value,0)/customerRevenue.length:0,customerRevenue,staff,equipment:{mostWhite:most("WHITE-"),mostBlack:most("BLACK-"),mostCase:most("CASE-"),maintenance:effectiveAssets.filter(item=>item.status==="MAINTENANCE").length,availability:effectiveAssets.length?available/effectiveAssets.length*100:0,usage:assetUsage},topVenues,topCustomers,operationalIssues:phraseFrequency(reviewRange.map(item=>item.lessons_avoid)),recommendations:phraseFrequency(reviewRange.map(item=>item.recommendations))};
}

function bounds(range:IntelligenceRange,customStart:string,customEnd:string,today:string){const current=new Date(`${today}T12:00:00`);let start=today;let end=today;if(range==="WEEK"){const value=new Date(current);value.setDate(value.getDate()-6);start=value.toISOString().slice(0,10)}if(range==="MONTH")start=`${today.slice(0,7)}-01`;if(range==="QUARTER"){const month=Math.floor(current.getMonth()/3)*3;start=`${current.getFullYear()}-${String(month+1).padStart(2,"0")}-01`}if(range==="YEAR")start=`${today.slice(0,4)}-01-01`;if(range==="CUSTOM"){start=customStart;end=customEnd}return{start,end}}
function groupValues(rows:readonly {label:string;value:number}[]):ChartDatum[]{const result=new Map<string,number>();rows.forEach(item=>result.set(item.label,(result.get(item.label)??0)+item.value));return[...result].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function averageGroups(rows:readonly {label:string;value:number}[]):ChartDatum[]{const grouped=new Map<string,number[]>();rows.forEach(item=>grouped.set(item.label,[...(grouped.get(item.label)??[]),item.value]));return[...grouped].map(([label,values])=>({label,value:values.reduce((a,b)=>a+b,0)/values.length,secondary:`${values.length} reseñas`})).sort((a,b)=>b.value-a.value)}
function phraseFrequency(values:readonly string[]){const result=new Map<string,number>();values.flatMap(value=>value.split(/[;\n]+/)).map(value=>value.trim()).filter(Boolean).forEach(value=>result.set(normalized(value),(result.get(normalized(value))??0)+1));return[...result].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count).slice(0,6)}

function Title({eyebrow,title,id,icon}:{eyebrow:string;title:string;id?:string;icon:ReactNode}){return <header className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand/10 text-brand [&>svg]:size-5">{icon}</span><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-muted">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold" id={id}>{title}</h2></div></header>}
function Panel({eyebrow,title,icon,children}:{eyebrow:string;title:string;icon:ReactNode;children:ReactNode}){return <section className="break-inside-avoid rounded-2xl border bg-card p-5 sm:p-6"><Title eyebrow={eyebrow} icon={icon} title={title}/><div className="space-y-6">{children}</div></section>}
function Kpi({href,label,value}:{href?:string;label:string;value:string}){const content=<><p className="text-xs text-muted">{label}</p><p className="mt-2 break-words text-xl font-semibold tracking-tight sm:text-2xl">{value}</p></>;return href?<a className="rounded-2xl border bg-card p-4 transition hover:border-brand sm:p-5" href={href}>{content}</a>:<article className="rounded-2xl border bg-card p-4 sm:p-5">{content}</article>}
function MetricGrid({items}:{items:readonly (readonly [string,string])[]}){return <div className="grid grid-cols-2 gap-3">{items.map(([label,value])=><div className="rounded-xl border bg-background/25 p-4" key={label}><p className="text-xs text-muted">{label}</p><p className="mt-2 text-base font-semibold">{value}</p></div>)}</div>}
function Small({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Chart({title,data,format}:{title:string;data:readonly ChartDatum[];format:(value:number)=>string}){const shown=data.slice(0,7);const max=Math.max(...shown.map(item=>Math.abs(item.value)),1);return <div><h3 className="text-sm font-semibold">{title}</h3>{shown.length?<div className="mt-3 space-y-3">{shown.map(item=><div key={item.label}><div className="mb-1 flex items-end justify-between gap-3 text-xs"><span className="truncate text-muted">{item.label}</span><span className="shrink-0 font-medium">{format(item.value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full bg-brand" style={{width:`${Math.max(3,Math.abs(item.value)/max*100)}%`}}/></div></div>)}</div>:<Empty text="Sin datos productivos para este período."/>}</div>}
function PhraseList({title,values}:{title:string;values:readonly {label:string;count:number}[]}){return <div><h3 className="text-sm font-semibold">{title}</h3><div className="mt-3 space-y-2">{values.length?values.map(item=><div className="flex items-center justify-between gap-3 rounded-xl border px-4 py-3" key={item.label}><p className="text-sm first-letter:uppercase">{item.label}</p><StatusBadge label={`${item.count}×`} variant="info"/></div>):<Empty text="Sin aprendizajes registrados en este período."/>}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-5 text-center text-sm text-muted">{text}</div>}
function downloadCsv(rows:readonly (readonly string[])[]){const csv=rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\n");download(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}),"orbit-business-intelligence.csv")}
function downloadExcel(rows:readonly (readonly string[])[]){const table=rows.map(row=>`<Row>${row.map(value=>`<Cell><Data ss:Type="String">${xml(value)}</Data></Cell>`).join("")}</Row>`).join("");const workbook=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="ORBIT BI"><Table>${table}</Table></Worksheet></Workbook>`;download(new Blob([workbook],{type:"application/vnd.ms-excel"}),"orbit-business-intelligence.xls")}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function xml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
