export enum ProjectStatus {
  LEAD = "LEAD",
  INFORMATION_SENT = "INFORMATION_SENT",
  RESERVATION_READY = "RESERVATION_READY",
  CONTRACT_PENDING = "CONTRACT_PENDING",
  WAITING_DEPOSIT = "WAITING_DEPOSIT",
  CONFIRMED = "CONFIRMED",
  PRODUCTION = "PRODUCTION",
  EVENT = "EVENT",
  DELIVERY = "DELIVERY",
  CLOSED = "CLOSED",
  ARCHIVED = "ARCHIVED",
}

export enum ProjectHealth {
  HEALTHY = "HEALTHY",
  ATTENTION = "ATTENTION",
  RISK = "RISK",
  CRITICAL = "CRITICAL",
}

export enum ProjectType {
  WEDDING = "WEDDING",
  CORPORATE = "CORPORATE",
  BIRTHDAY = "BIRTHDAY",
  PRIVATE = "PRIVATE",
  OTHER = "OTHER",
}
