"use client";

import Link from "next/link";
import { ExternalLink, FileText, ReceiptText } from "lucide-react";
import { CustomerPurchaseOrderCenter, type CustomerPurchaseOrderRow } from "@/features/commercial-documents/customer-purchase-order-center";
import { ExternalTaxDocumentsCenter, type ExternalTaxDocumentRow } from "./external-tax-documents-center";

type DocumentRow={id:string;type:string;href?:string;createdAt:string;number?:string;originalFilename?:string;driveArchiveStatus?:string};
type HubProps={projectId:string;customerName:string;customerTaxId?:string;customerKind:"PARTICULAR"|"EMPRESA";quotation?:{id:string;number:string;status:string;revision:number;acceptedAt:string;total:number;href:string;items:readonly {label:string;quantity:number;total:number}[]};contract:{status:string;href?:string;createdAt?:string;signedAt?:string};receivable?:{id:string;paid:number;outstanding:number;dueDate:string|null;status:string};paymentCondition:string;documents:readonly DocumentRow[];taxDocuments:readonly ExternalTaxDocumentRow[]};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
const date=(value:string)=>new Date(value).toLocaleDateString("es-CL");
const labels:Record<string,string>={QUOTATION:"Cotización",AGREEMENT:"Contrato",SIGNED_AGREEMENT:"Contrato firmado",COMMERCIAL_DOCUMENT:"Documento comercial",PAYMENT_RECEIPT:"Comprobante de pago",EXTERNAL_TAX_DOCUMENT:"Documento SII",CUSTOMER_PURCHASE_ORDER:"OC Cliente",DESIGN:"Diseño",GALLERY:"Galería",BACKUP:"Respaldo"};

export function EventCommercialDocumentHub(props:HubProps){
  const receipts=props.documents.filter(item=>item.type==="PAYMENT_RECEIPT");
  const purchaseOrder=props.documents.find(item=>item.type==="CUSTOMER_PURCHASE_ORDER");
  const other=props.documents.filter(item=>!["QUOTATION","AGREEMENT","SIGNED_AGREEMENT","COMMERCIAL_DOCUMENT","PAYMENT_RECEIPT","EXTERNAL_TAX_DOCUMENT","CUSTOMER_PURCHASE_ORDER"].includes(item.type));
  const quotationReady=Boolean(props.quotation&&["ACCEPTED","CONVERTED"].includes(props.quotation.status));
  const contractReady=["SIGNED","COMMERCIAL_DOCUMENT"].includes(props.contract.status);
  const taxReady=props.taxDocuments.length>0;
  const paymentState=(props.receivable?.outstanding??0)<=0&&props.receivable?"PAGADO":(props.receivable?.paid??0)>0?"PARCIAL":"PENDIENTE";
  const ocState=purchaseOrder?"LISTA":props.customerKind==="PARTICULAR"?"NO REQUERIDA":"PENDIENTE";
  const poRow:CustomerPurchaseOrderRow|undefined=purchaseOrder&&purchaseOrder.href?{id:purchaseOrder.id,number:purchaseOrder.number,originalFilename:purchaseOrder.originalFilename,createdAt:purchaseOrder.createdAt,href:purchaseOrder.href,driveArchiveStatus:purchaseOrder.driveArchiveStatus}:undefined;
  return <div className="min-w-0 space-y-6" data-event-commercial-document-hub>
    <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Archivo permanente del Evento</p><h3 className="mt-1 text-2xl font-semibold">DOCUMENTOS COMERCIALES</h3><p className="mt-1 text-sm text-muted">Supabase y cada módulo propietario conservan la verdad canónica; Drive es sólo archivo administrativo.</p></div>
    <section className="rounded-2xl border bg-background/30 p-4"><h4 className="font-semibold">Progreso comercial</h4><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Progress label="COTIZACIÓN" value={quotationReady?"✓":"PENDIENTE"}/><Progress label="OC CLIENTE" value={ocState}/><Progress label="CONTRATO" value={contractReady?"✓":"PENDIENTE"}/><Progress label="FACTURA / SII" value={taxReady?"✓":"PENDIENTE"}/><Progress label="PAGO" value={paymentState}/></div></section>
    <section className="rounded-xl border p-4"><h4 className="font-semibold">COTIZACIÓN</h4>{props.quotation?<div className="mt-3 space-y-3"><dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Datum label="Número" value={props.quotation.number}/><Datum label="Revisión" value={String(props.quotation.revision)}/><Datum label="Aceptada" value={date(props.quotation.acceptedAt)}/><Datum label="Total" value={money(props.quotation.total)}/></dl><div className="space-y-2">{props.quotation.items.map((item,index)=><div className="flex min-w-0 justify-between gap-3 rounded-lg bg-background/40 p-3 text-sm" key={`${item.label}-${index}`}><span className="min-w-0 break-words">{item.label} · {item.quantity}</span><strong>{money(item.total)}</strong></div>)}</div><a className="inline-flex min-h-11 items-center gap-2 font-semibold text-brand" href={props.quotation.href} rel="noreferrer" target="_blank">VER PDF<ExternalLink className="size-4"/></a></div>:<p className="mt-3 text-sm text-muted">No existe una cotización vinculada.</p>}</section>
    <CustomerPurchaseOrderCenter document={poRow} projectId={props.projectId}/>
    <section className="rounded-xl border p-4"><h4 className="font-semibold">CONTRATO</h4><p className="mt-2 text-sm text-muted">Estado: {props.contract.status}{props.contract.signedAt?` · firmado ${date(props.contract.signedAt)}`:props.contract.createdAt?` · generado ${date(props.contract.createdAt)}`:""}</p>{props.contract.href?<a className="mt-2 inline-flex min-h-11 items-center font-semibold text-brand" href={props.contract.href} rel="noreferrer" target="_blank">VER DOCUMENTO</a>:<p className="mt-2 text-sm text-muted">Documento pendiente.</p>}</section>
    <ExternalTaxDocumentsCenter projectId={props.projectId} invoiceId={props.receivable?.id} customerName={props.customerName} customerTaxId={props.customerTaxId} documents={props.taxDocuments}/>
    <section className="grid gap-4 lg:grid-cols-2"><DocumentGroup icon={<ReceiptText className="size-5"/>} title="COMPROBANTES DE PAGO" rows={receipts}/><DocumentGroup icon={<FileText className="size-5"/>} title="OTROS" rows={other}/></section>
    <nav className="flex flex-wrap gap-2" aria-label="Acciones comerciales rápidas"><Action href="#payment-management">Registrar pago</Action><Action href="#payment-management">Ver comprobantes</Action><Action href="/finance/receivables">Ir a Accounts Receivable</Action></nav>
  </div>
}
function Progress({label,value}:{label:string;value:string}){const ready=value==="✓"||value==="LISTA"||value==="PAGADO"||value==="NO REQUERIDA";return <div className="rounded-xl border p-3"><p className="text-xs font-semibold text-muted">{label}</p><p className={`mt-1 font-semibold ${ready?"text-success":"text-amber-600"}`}>{value}</p></div>}
function Datum({label,value}:{label:string;value:string}){return <div><dt className="text-muted">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
function Action({href,children}:{href:string;children:React.ReactNode}){return <Link className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-sm font-semibold transition hover:border-brand" href={href}>{children}</Link>}
function DocumentGroup({icon,title,rows}:{icon:React.ReactNode;title:string;rows:readonly DocumentRow[]}){return <section className="rounded-xl border p-4"><h4 className="flex items-center gap-2 font-semibold">{icon}{title}</h4><div className="mt-3 space-y-2">{rows.length?rows.map(row=><article className="flex items-center justify-between gap-3 rounded-lg bg-background/40 p-3" key={row.id}><div><p className="text-sm font-medium">{labels[row.type]??row.type.replaceAll("_"," ")}</p><p className="text-xs text-muted">{date(row.createdAt)}</p></div>{row.href?<a className="text-sm font-semibold text-brand" href={row.href} rel="noreferrer" target="_blank">VER DOCUMENTO</a>:<span className="text-xs text-muted">Protegido</span>}</article>):<p className="text-sm text-muted">Sin documentos en esta categoría.</p>}</div></section>}
