"use client";

import Link from "next/link";
import { CalendarDays, ChevronLeft, ChevronRight, ExternalLink } from "lucide-react";
import { useMemo, useState } from "react";
import type { CrmOperationalEvent } from "./types";

type CalendarView = "MONTH" | "WEEK" | "DAY";
const pad = (value: number) => String(value).padStart(2, "0");
const iso = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const startOfWeek = (date: Date) => { const next = new Date(date); next.setHours(12, 0, 0, 0); next.setDate(next.getDate() - ((next.getDay() + 6) % 7)); return next; };
const addDays = (date: Date, amount: number) => { const next = new Date(date); next.setDate(next.getDate() + amount); return next; };
const statusLabel = (status: string) => ({ CONFIRMED: "Confirmado", COMPLETED: "Completado", FINISHED: "Completado", CANCELLED: "Cancelado", CANCELED: "Cancelado", UPCOMING: "Pendiente" } as Record<string, string>)[status.toUpperCase()] ?? status;
const statusClass = (status: string) => status.toUpperCase().includes("CANCEL") ? "border-red-500/30 bg-red-500/10 text-red-300" : status.toUpperCase().includes("COMPLET") || status.toUpperCase().includes("FINISH") ? "border-sky-500/30 bg-sky-500/10 text-sky-300" : "border-brand/30 bg-brand/10 text-brand";

function EventPill({ event }: { event: CrmOperationalEvent }) {
  return <Link href={`/projects/${event.projectId}`} className={`block min-w-0 rounded-lg border px-2 py-1.5 text-left text-xs transition hover:border-brand/60 ${statusClass(event.status)}`} title={`${event.customerName} · ${event.service}`}><span className="block truncate font-semibold">{event.time?.slice(0, 5) || "--:--"} · {event.customerName}</span><span className="block truncate opacity-80">{event.service || "Servicio"}{event.municipality ? ` · ${event.municipality}` : ""}</span></Link>;
}

export function CrmCalendar({ initialEvents }: { initialEvents: CrmOperationalEvent[] }) {
  const [view, setView] = useState<CalendarView>("MONTH");
  const [cursor, setCursor] = useState(() => { const now = new Date(); now.setDate(1); return now; });
  const [selectedDay, setSelectedDay] = useState(() => iso(new Date()));
  const [service, setService] = useState("ALL");
  const [status, setStatus] = useState("ALL");
  const events = useMemo(() => initialEvents.filter(event => (service === "ALL" || event.service === service) && (status === "ALL" || statusLabel(event.status) === status)), [initialEvents, service, status]);
  const services = [...new Set(initialEvents.map(event => event.service).filter(Boolean))].sort();
  const monthDays = useMemo(() => { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const start = startOfWeek(first); return Array.from({ length: 42 }, (_, index) => addDays(start, index)); }, [cursor]);
  const weekDays = useMemo(() => Array.from({ length: 7 }, (_, index) => addDays(startOfWeek(cursor), index)), [cursor]);
  const visibleDays = view === "MONTH" ? monthDays : view === "WEEK" ? weekDays : [cursor];
  const eventsFor = (day: Date) => events.filter(event => event.date === iso(day)).sort((a, b) => String(a.time).localeCompare(String(b.time)));
  const move = (amount: number) => { const next = new Date(cursor); next.setMonth(next.getMonth() + (view === "MONTH" ? amount : 0)); if (view === "WEEK") next.setDate(next.getDate() + amount * 7); if (view === "DAY") next.setDate(next.getDate() + amount); setCursor(next); setSelectedDay(iso(next)); };
  const today = () => { const next = new Date(); setCursor(view === "MONTH" ? new Date(next.getFullYear(), next.getMonth(), 1) : next); setSelectedDay(iso(next)); };
  const heading = view === "MONTH" ? cursor.toLocaleDateString("es-CL", { month: "long", year: "numeric" }) : view === "WEEK" ? `${iso(weekDays[0])} – ${iso(weekDays[6])}` : cursor.toLocaleDateString("es-CL", { dateStyle: "long" });
  return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-brand">OPERACIÓN · AGENDA</p><h1 className="mt-2 text-3xl font-semibold">Calendario</h1><p className="mt-2 text-sm text-muted">Eventos y reservas sincronizados desde la fuente operacional de ORBIT.</p></div><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-sm font-semibold" href="/events"><CalendarDays className="size-4"/>Ver listado</Link></header>
    <div className="flex flex-wrap items-center gap-2"><button className="min-h-11 rounded-xl border px-4 text-sm font-semibold" onClick={today}>HOY</button><button aria-label="Período anterior" className="grid size-11 place-items-center rounded-xl border" onClick={() => move(-1)}><ChevronLeft className="size-4"/></button><button aria-label="Período siguiente" className="grid size-11 place-items-center rounded-xl border" onClick={() => move(1)}><ChevronRight className="size-4"/></button><strong className="ml-1 capitalize text-sm sm:text-base">{heading}</strong><div className="ml-auto flex rounded-xl border p-1"><button className={`min-h-9 rounded-lg px-3 text-xs font-semibold ${view === "MONTH" ? "bg-brand text-black" : "text-muted"}`} onClick={() => setView("MONTH")}>MES</button><button className={`min-h-9 rounded-lg px-3 text-xs font-semibold ${view === "WEEK" ? "bg-brand text-black" : "text-muted"}`} onClick={() => setView("WEEK")}>SEMANA</button><button className={`min-h-9 rounded-lg px-3 text-xs font-semibold ${view === "DAY" ? "bg-brand text-black" : "text-muted"}`} onClick={() => setView("DAY")}>DÍA</button></div></div>
    <div className="flex flex-wrap gap-2"><select aria-label="Filtrar servicio" className="min-h-11 rounded-xl border bg-card px-3 text-sm" value={service} onChange={event => setService(event.target.value)}><option value="ALL">Todos los servicios</option>{services.map(item => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filtrar estado" className="min-h-11 rounded-xl border bg-card px-3 text-sm" value={status} onChange={event => setStatus(event.target.value)}><option value="ALL">Todos los estados</option>{["Confirmado", "Pendiente", "Completado", "Cancelado"].map(item => <option key={item} value={item}>{item}</option>)}</select></div>
    <section className="overflow-hidden rounded-2xl border bg-card"><div className="grid grid-cols-7 border-b text-center text-[10px] font-semibold uppercase tracking-wider text-muted sm:text-xs">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map(day => <div className="px-1 py-3" key={day}>{day}</div>)}</div><div className={`grid ${view === "DAY" ? "grid-cols-1" : "grid-cols-7"}`}>{visibleDays.map(day => { const dayEvents = eventsFor(day); const current = iso(day) === iso(new Date()); const selected = iso(day) === selectedDay; return <div className={`min-h-28 min-w-0 border-b border-r p-1.5 text-left align-top sm:min-h-32 sm:p-2 ${view === "MONTH" && day.getMonth() !== cursor.getMonth() ? "opacity-40" : ""} ${selected ? "bg-brand/5" : ""}`} key={iso(day)} onClick={() => { setSelectedDay(iso(day)); if (view === "MONTH") setCursor(day); }} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedDay(iso(day)); if (view === "MONTH") setCursor(day); } }} role="button" tabIndex={0}><span className={`mb-1 inline-flex size-6 items-center justify-center rounded-full text-xs ${current ? "bg-brand font-bold text-black" : "text-muted"}`}>{day.getDate()}</span><div className="space-y-1">{dayEvents.slice(0, view === "MONTH" ? 2 : 8).map(event => <EventPill event={event} key={event.projectId}/>)}{dayEvents.length > (view === "MONTH" ? 2 : 8) ? <span className="block px-1 text-[10px] text-muted">+{dayEvents.length - (view === "MONTH" ? 2 : 8)} más</span> : null}</div></div>; })}</div></section>
    <section className="rounded-2xl border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-brand">AGENDA DEL DÍA</p><h2 className="mt-1 text-lg font-semibold">{new Date(`${selectedDay}T12:00:00`).toLocaleDateString("es-CL", { dateStyle: "long" })}</h2></div><span className="text-sm text-muted">{eventsFor(new Date(`${selectedDay}T12:00:00`)).length} evento(s)</span></div><div className="mt-4 space-y-2">{eventsFor(new Date(`${selectedDay}T12:00:00`)).map(event => <Link className="flex min-h-12 items-center justify-between gap-3 rounded-xl border p-3 text-sm hover:border-brand/50" href={`/projects/${event.projectId}`} key={event.projectId}><span className="min-w-0 truncate"><strong>{event.time?.slice(0, 5) || "--:--"}</strong> — {event.customerName} — {event.service || "Servicio"}<small className="ml-2 text-muted">{event.municipality || event.location || "Ubicación por confirmar"}</small></span><ExternalLink className="size-4 shrink-0 text-brand"/></Link>)}{eventsFor(new Date(`${selectedDay}T12:00:00`)).length === 0 ? <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted">Sin eventos programados para este período.</p> : null}</div></section>
  </div>;
}
