"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ChevronDown, ExternalLink, FileText, FolderSync, Pencil, Plus, ReceiptText, ShieldCheck, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EventPaymentManager } from "@/features/accounts-receivable/event-payment-manager";
import { StaffAssignmentCenter } from "@/features/staff-assignment-center/staff-assignment-center";
import { AgreementSigningControl } from "@/features/projects/signing/agreement-signing-control";
import { associateEventExpenseStaffAction, saveExpenseAction } from "@/features/expense-center/actions";
import { getCrmDocumentUrlAction, openCrmCustomerPortalAction, replaceCrmDocumentAction } from "./actions";
import type { CrmCustomerEventOperations, CrmEventSummary } from "./types";

export function CustomerEventOperations({ event, operations, onEditEvent, reconciliationId }: { event: CrmEventSummary; operations?: CrmCustomerEventOperations; onEditEvent: () => void; reconciliationId?:string }) {
  const router = useRouter();
  const [portalUrl, setPortalUrl] = useState("");
  const [message, setMessage] = useState("");
  const [editingDocument, setEditingDocument] = useState<CrmCustomerEventOperations["documents"][number] | null>(null);
  const [costDetailOpen, setCostDetailOpen] = useState(false);
  const [expenseOpen, setExpenseOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  if (!operations) return <p className="rounded-xl border border-dashed p-5 text-sm text-muted">La información operativa de este Evento no está disponible.</p>;
  const openPortal = () => startTransition(async () => {
    const result = await openCrmCustomerPortalAction(event.projectId);
    if (!result.ok) return setMessage(result.error);
    setPortalUrl(result.url);
    window.open(result.url, "_blank", "noopener,noreferrer");
    setMessage("Portal sincronizado y disponible.");
  });
  const openDocument = (documentId: string, driveFileId: string | null) => startTransition(async () => {
    if (driveFileId) {
      window.open(`https://drive.google.com/file/d/${driveFileId}/view`, "_blank", "noopener,noreferrer");
      return;
    }
    const result = await getCrmDocumentUrlAction(documentId);
    if (!result.ok) {
      setMessage(result.error);
      return;
    }
    window.open(result.url, "_blank", "noopener,noreferrer");
  });
  return <div className="mt-4 space-y-5 border-t pt-5">
    <CommercialSummary summary={operations.commercialSummary}/>
    <ExecutiveFinancialSummary operations={operations} onCostDetail={() => setCostDetailOpen((open) => !open)} open={costDetailOpen}/>
    <div id={`payments-${event.projectId}`}>{operations.receivable ? <EventPaymentManager projectId={event.projectId} receivable={operations.receivable} reconciliationId={reconciliationId} /> : <Empty text="Este Evento no tiene una cuenta por cobrar activa." />}</div>
    <div id={`staff-${event.projectId}`}><StaffAssignmentCenter {...operations.staffAssignments} /></div>
    <section className="rounded-2xl border bg-card p-5 sm:p-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><ReceiptText className="mt-0.5 size-5 text-brand"/><div><h3 className="font-semibold">Gastos adicionales del Evento</h3><p className="mt-1 text-sm text-muted">Alimentación, estacionamiento, combustible extra, hotel o compras imprevistas. No modifica Cost Master.</p></div></div><Button onClick={() => setExpenseOpen(true)}><Plus className="size-4"/>Nuevo gasto del Evento</Button></header><div className="mt-4 divide-y rounded-xl border">{operations.expenses.map((expense) => <div className="grid grid-cols-[1fr_auto] gap-3 p-3 text-sm" key={expense.id}><div><strong>{expense.description}</strong><p className="mt-1 text-xs text-muted">{expense.date} · {expense.category} · {expense.status}</p></div><strong>{money(expense.total)}</strong></div>)}{!operations.expenses.length && <p className="p-4 text-sm text-muted">Sin gastos adicionales registrados.</p>}</div></section>
    <ExpenseResponsibility expenses={operations.expenses} projectId={event.projectId} staff={operations.staffAssignments.staff}/>
    <section className="scroll-mt-24 rounded-2xl border bg-card p-5 sm:p-6" id={`documents-${event.projectId}`}>
      <header className="flex items-start gap-3"><FileText className="mt-0.5 size-5 text-brand"/><div><h3 className="font-semibold">Documentos oficiales</h3><p className="mt-1 text-sm text-muted">Cotización, contrato y documento corporativo del Evento.</p></div></header>
      <div className="mt-4 grid gap-2 sm:grid-cols-2">
        {operations.documents.map((document) => <article className="rounded-xl border p-3" key={document.id}><div className="flex items-center justify-between gap-3"><span><strong className="text-sm">{documentLabel(document.type)}</strong><small className="mt-0.5 block text-muted">{new Date(document.createdAt).toLocaleDateString("es-CL")}</small></span><div className="flex gap-2"><button aria-label={`Abrir ${documentLabel(document.type)}`} className="rounded-lg border p-2 hover:border-brand" disabled={pending} onClick={() => openDocument(document.id, document.driveFileId)} type="button"><ExternalLink className="size-4"/></button><button aria-label={`Reemplazar ${documentLabel(document.type)}`} className="rounded-lg border p-2 hover:border-brand" disabled={pending} onClick={() => setEditingDocument(document)} type="button"><Pencil className="size-4"/></button></div></div></article>)}
        {!operations.documents.length && <p className="text-sm text-muted">Sin documentos registrados.</p>}
      </div>
      {operations.invoices.length > 0 && <div className="mt-5 border-t pt-4"><h4 className="text-sm font-semibold">Facturas</h4><div className="mt-2 grid gap-2 sm:grid-cols-2">{operations.invoices.map((invoice) => <div className="rounded-xl border p-3 text-sm" key={invoice.id}><strong>{invoice.number}</strong><p className="mt-1 text-muted">{invoice.status} · {money(invoice.amount)}</p>{invoice.dueDate && <p className="mt-1 text-xs text-muted">Vence {new Date(`${invoice.dueDate}T12:00:00`).toLocaleDateString("es-CL")}</p>}</div>)}</div></div>}
    </section>
    <div id={`contracts-${event.projectId}`}><AgreementSigningControl agreementId={operations.agreement?.id} projectId={event.projectId} status={operations.agreement?.status ?? "PENDING"} /></div>
    <section className="grid scroll-mt-24 gap-4 md:grid-cols-2" id={`portal-${event.projectId}`}>
      <article className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-brand"/><h3 className="font-semibold">Portal Cliente</h3></div><p className="mt-2 text-sm text-muted">{operations.portalActive ? "Portal activo. Puedes abrirlo, editar su información desde este Evento, sincronizarlo o reenviar manualmente la comunicación oficial." : "Portal pendiente de activar."}</p><div className="mt-4 flex flex-wrap gap-2"><Button disabled={pending} onClick={openPortal} variant="outline"><FolderSync className="size-4"/>{operations.portalActive ? "Abrir / sincronizar Portal" : "Activar Portal"}</Button><Button onClick={onEditEvent} variant="outline"><Pencil className="size-4"/>Editar información</Button></div>{portalUrl && <p className="mt-2 break-all text-xs text-muted">{portalUrl}</p>}</article>
      <article className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-brand"/><h3 className="font-semibold">Google Calendar</h3></div><p className="mt-2 text-sm text-muted">{operations.calendar ? `Sincronización: ${operations.calendar.status}` : "Evento de Calendar aún no disponible."}</p><div className="mt-4 flex flex-wrap gap-2">{operations.calendar?.externalUrl && <Button asChild variant="outline"><a href={operations.calendar.externalUrl} rel="noreferrer" target="_blank"><ExternalLink className="size-4"/>Abrir Calendar</a></Button>}<Button onClick={onEditEvent} variant="outline"><Pencil className="size-4"/>Editar fecha, hora o dirección</Button></div><p className="mt-3 text-xs text-muted">Al guardar, Google Calendar se actualiza automáticamente.</p></article>
    </section>
    {message && <p aria-live="polite" className="rounded-xl border p-3 text-sm">{message}</p>}
    {expenseOpen && <EventExpenseDialog event={event} onClose={() => setExpenseOpen(false)} onSaved={(notice) => { setExpenseOpen(false); setMessage(notice); router.refresh(); }} />}
    {editingDocument && <div aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 sm:items-center sm:p-6" role="dialog"><div className="w-full rounded-t-2xl border bg-card p-5 sm:max-w-lg sm:rounded-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">Documento oficial</p><h3 className="mt-1 text-xl font-semibold">Reemplazar {documentLabel(editingDocument.type)}</h3><p className="mt-1 text-sm text-muted">El Portal y Google Drive se actualizarán sin enviar correos.</p></div><button aria-label="Cerrar" className="rounded-lg border p-2" onClick={() => setEditingDocument(null)}><X className="size-4"/></button></div><form action={(data) => { data.set("documentId", editingDocument.id); data.set("projectId", event.projectId); startTransition(async () => { const result = await replaceCrmDocumentAction(data); if (result.ok) { setEditingDocument(null); setMessage("Documento reemplazado; Portal y Drive sincronizados."); router.refresh(); } else setMessage(result.error); }); }} className="mt-5 space-y-4"><label className="block text-sm"><span className="mb-1.5 block text-muted">Archivo de reemplazo</span><input accept="application/pdf,image/jpeg,image/png,image/webp" className="min-h-11 w-full rounded-xl border bg-background px-3 py-2" name="file" required type="file"/></label><label className="block text-sm"><span className="mb-1.5 block text-muted">Motivo obligatorio</span><input className="min-h-11 w-full rounded-xl border bg-background px-3" name="reason" required/></label><Button className="w-full" disabled={pending}>{pending?"Guardando…":"Guardar y sincronizar"}</Button></form></div></div>}
  </div>;
}

function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed p-5 text-sm text-muted">{text}</p>; }
function documentLabel(type: string) { return ({ QUOTATION: "Cotización", SIGNED_AGREEMENT: "Contrato firmado", COMMERCIAL_DOCUMENT: "Documento corporativo", PAYMENT_RECEIPT: "Comprobante de pago" } as Record<string, string>)[type] ?? type.replaceAll("_", " "); }
const money = (value: number) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value);
function CommercialSummary({ summary }: { summary: CrmCustomerEventOperations["commercialSummary"] }) {
  const rows = [["Servicio", summary.service], ["Duración", summary.duration ? `${summary.duration} horas` : "Por confirmar"], ["Branding", summary.branding], ["QR", summary.qr], ["Imanes", summary.magnets], ["Scrapbook", summary.scrapbook], ["Transporte", summary.transport], ["Horas adicionales", summary.additionalHours]];
  return <section className="rounded-2xl border bg-card p-5 sm:p-6"><h3 className="font-semibold">Configuración contratada</h3><p className="mt-1 text-sm text-muted">Detalle exacto vigente de la experiencia comprada por el Cliente.</p><dl className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{rows.map(([label, value]) => <div className="rounded-xl border bg-background/30 p-3" key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></section>;
}
function ExecutiveFinancialSummary({ operations, onCostDetail, open }: { operations: CrmCustomerEventOperations; onCostDetail: () => void; open: boolean }) {
  const financial = operations.financialSummary;
  const profitability = operations.profitability;
  const rows = [["Valor neto", financial.net], ["IVA", financial.vat], ["Total", financial.total], ["Monto recibido", operations.receivable?.paidAmount ?? 0], ["Saldo pendiente", operations.receivable?.outstandingBalance ?? financial.total], ["Costo operacional", profitability?.totalCost ?? 0], ["Profit", profitability?.profit ?? 0]] as const;
  return <section className="scroll-mt-24 rounded-2xl border bg-card p-5 sm:p-6" id={`profitability-${operations.projectId}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">Resumen financiero ejecutivo</h3><p className="mt-1 text-sm text-muted">IVA separado del ingreso operacional. Rentabilidad proveniente del Business Engine.</p></div>{profitability && <span className="rounded-full border px-3 py-1 text-xs">{profitabilityLabel(profitability.classification)}</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{rows.map(([label, value]) => <div className="rounded-xl border bg-background/30 p-4" key={label}><p className="text-xs text-muted">{label}</p><p className="mt-2 text-lg font-semibold">{money(value)}</p></div>)}<div className="rounded-xl border bg-background/30 p-4"><p className="text-xs text-muted">Margen</p><p className="mt-2 text-lg font-semibold">{(profitability?.margin ?? 0).toFixed(1)}%</p></div></div>{profitability && <button aria-expanded={open} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-sm font-semibold text-brand" onClick={onCostDetail} type="button">Desglose de costos<ChevronDown className={`size-4 transition ${open ? "rotate-180" : ""}`}/></button>}{open && profitability && <CostDetail profitability={profitability}/>} {profitability && <p className="mt-4 text-xs text-muted">Calculado {new Date(profitability.calculatedAt).toLocaleString("es-CL")}</p>}</section>;
}
function ExpenseResponsibility({expenses,staff,projectId}:{expenses:CrmCustomerEventOperations["expenses"];staff:CrmCustomerEventOperations["staffAssignments"]["staff"];projectId:string}){const[pending,start]=useTransition();const[message,setMessage]=useState("");if(!expenses.length)return null;return <section className="rounded-2xl border bg-card p-5 sm:p-6"><h3 className="font-semibold">Responsable de gastos del Evento</h3><p className="mt-1 text-sm text-muted">Asociación opcional para trazabilidad. Nunca aumenta la nómina.</p><form action={data=>start(async()=>{const result=await associateEventExpenseStaffAction(data);setMessage(result.message)})} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input name="projectId" type="hidden" value={projectId}/><select className="min-h-11 rounded-xl border bg-background px-3" name="expenseId" required defaultValue=""><option value="">Seleccionar gasto</option>{expenses.map(expense=><option key={expense.id} value={expense.id}>{expense.description} · {money(expense.total)}</option>)}</select><select className="min-h-11 rounded-xl border bg-background px-3" name="staffId" defaultValue=""><option value="">Sin responsable</option>{staff.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select><Button disabled={pending}>{pending?"Guardando…":"Asociar"}</Button></form>{message?<p className="mt-3 text-sm text-muted">{message}</p>:null}</section>}
function EventExpenseDialog({ event, onClose, onSaved }: { event: CrmEventSummary; onClose: () => void; onSaved: (message: string) => void }) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState("");
  return <div aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 sm:items-center sm:p-6" role="dialog"><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 sm:max-w-2xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">Evento · gasto operacional</p><h3 className="mt-1 text-xl font-semibold">Nuevo gasto del Evento</h3><p className="mt-1 text-sm text-muted">{event.name}. Este registro afecta únicamente este Evento.</p></div><button aria-label="Cerrar" className="rounded-lg border p-2" onClick={onClose} type="button"><X className="size-4"/></button></div><form action={(data) => startTransition(async () => { data.set("associationType", "EVENT"); data.set("associationId", event.projectId); data.set("id", ""); data.set("supplierRut", ""); data.set("documentType", "OTHER"); data.set("documentNumber", ""); data.set("exempt", "0"); const result = await saveExpenseAction(data); if (result.ok) onSaved(result.message); else setError(result.message); })} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Fecha"><input defaultValue={new Date().toISOString().slice(0,10)} name="occurredOn" required type="date"/></Field><Field label="Tipo"><select name="category"><option value="OTHER">Compra imprevista / Otro</option><option value="SERVICES">Alimentación / Servicio</option><option value="TRANSPORT">Estacionamiento / Peaje</option><option value="FUEL">Combustible extra</option><option value="ADMINISTRATION">Hotel</option></select></Field><Field label="Proveedor"><input name="supplier" placeholder="Proveedor o comercio" required/></Field><Field label="Método de pago"><select name="paymentMethod"><option value="TRANSFER">Transferencia</option><option value="CASH">Efectivo</option><option value="CREDIT_CARD">Tarjeta de crédito</option><option value="DEBIT_CARD">Tarjeta de débito</option><option value="CORPORATE_CARD">Tarjeta corporativa</option></select></Field><label className="text-sm sm:col-span-2"><span className="mb-2 block font-medium">Descripción</span><textarea className="min-h-24 w-full rounded-xl border bg-background p-3" name="description" placeholder="Alimentación, estacionamiento, hotel…" required/></label><Field label="Neto"><input min="0" name="subtotal" required type="number"/></Field><Field label="IVA"><input defaultValue="0" min="0" name="vat" type="number"/></Field><Field label="Estado"><select name="status"><option value="PAID">Pagado</option><option value="PENDING">Pendiente</option></select></Field><Field label="Comprobante"><input accept="image/jpeg,image/png,image/webp,application/pdf" name="receipt" type="file"/></Field>{error && <p className="text-sm text-red-500 sm:col-span-2">{error}</p>}<Button className="sm:col-span-2" disabled={pending}>{pending ? "Guardando y recalculando…" : "Guardar gasto y recalcular"}</Button></form></div></div>;
}
function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="text-sm"><span className="mb-2 block font-medium">{label}</span><span className="block [&>*]:min-h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-background [&>*]:px-3 [&>input[type=file]]:py-2">{children}</span></label>; }
function CostDetail({ profitability }: { profitability: NonNullable<CrmCustomerEventOperations["profitability"]> }) {
  const listedTotal = profitability.costBreakdown.reduce((sum, item) => sum + item.amount, 0);
  const reconciliation = profitability.totalCost - listedTotal;
  const groups = [
    { key: "PERSONNEL" as const, title: "Costo de personal", total: profitability.personnelCost },
    { key: "OPERATIONAL" as const, title: "Recursos operacionales", total: profitability.operationalCost },
  ];
  return <div className="mt-4 rounded-xl border border-brand/25 bg-brand/5 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="font-semibold">Detalle del costo usado para calcular el margen</h4><p className="mt-1 text-xs text-muted">Valores oficiales del Business Engine para este Evento.</p></div><strong className="text-brand">{money(profitability.totalCost)}</strong></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{groups.map((group) => <div className="rounded-xl border bg-background/40 p-4" key={group.key}><div className="flex justify-between gap-3 border-b pb-2 text-sm font-semibold"><span>{group.title}</span><span>{money(group.total)}</span></div><dl className="mt-2 space-y-2">{profitability.costBreakdown.filter((item) => item.group === group.key).map((item) => <div className="flex justify-between gap-3 text-sm" key={item.key}><dt className="text-muted">{item.label}</dt><dd>{money(item.amount)}</dd></div>)}</dl></div>)}</div>{Math.abs(reconciliation) >= 1 && <div className="mt-3 flex justify-between gap-3 rounded-lg border border-warning/30 bg-warning/5 px-3 py-2 text-sm"><span>Otros costos considerados por el motor</span><strong>{money(reconciliation)}</strong></div>}<div className="mt-4 flex justify-between gap-3 border-t pt-3 font-semibold"><span>Costo total aplicado</span><span>{money(profitability.totalCost)}</span></div></div>;
}
function profitabilityLabel(value: string) { return value === "HIGHLY_PROFITABLE" ? "🟢 Altamente rentable" : value === "LOW_MARGIN" ? "🔴 Margen bajo" : "🟡 Normal"; }
