"use client";

import { ArrowLeft, Archive, CalendarDays, ExternalLink, FileSignature, Save } from "lucide-react";
import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { CrmCustomerProfile } from "./types";
import { updateCrmCustomerAction } from "./actions";
import { usePersonalWorkspace } from "@/features/founder-workspace/personal-workspace";

const money = (value: number) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value);

export function CustomerProfile({ customer }: { customer: CrmCustomerProfile }) {
  const { preferences } = usePersonalWorkspace();
  const workspace = preferences.moduleWorkspaces.CUSTOMERS;
  const selectors: Record<string, string> = {
    CUSTOMER_INFORMATION: "#customer-workspace > section:nth-of-type(2)",
    CUSTOMER_EVENTS: "#customer-events",
    CUSTOMER_DOCUMENTS: "#customer-documents",
    CUSTOMER_COMMERCIAL_HISTORY: "#customer-commercial-history",
    CUSTOMER_TIMELINE: "#customer-workspace > section:nth-of-type(6)",
  };
  const workspaceCss = workspace.sectionOrder.map((key, index) => `${selectors[key]}{order:${index + 10};${workspace.hiddenSections.includes(key) ? "display:none;" : ""}}`).join("");
  const router = useRouter();
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState("");
  const [pending, startTransition] = useTransition();
  const submit = (form: FormData) => startTransition(async () => {
    const result = await updateCrmCustomerAction({ id: customer.id, fullName: String(form.get("fullName")), rut: String(form.get("rut")), company: String(form.get("company")), phone: String(form.get("phone")), email: String(form.get("email")), address: String(form.get("address")), commercialNotes: String(form.get("commercialNotes")), contacts: parseContacts(String(form.get("contacts"))), reason: String(form.get("reason")) });
    if (!result.ok) return setError(result.error);
    setEditing(false); router.refresh();
  });
  return <div className="flex flex-col gap-7" id="customer-workspace"><style>{workspaceCss}</style>
    <header><Link className="inline-flex items-center gap-2 text-sm text-muted" href="/customers"><ArrowLeft className="size-4"/>Volver a Clientes</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-muted">Relación comercial</p><h1 className="mt-2 text-3xl font-semibold">{customer.fullName}</h1><p className="mt-2 text-sm text-muted">{customer.company || "Cliente particular"} · {customer.rut}</p></div><button className="rounded-xl bg-primary px-4 py-2.5 text-sm text-primary-foreground" onClick={() => setEditing((value) => !value)} type="button">✏ Editar cliente</button></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      [CalendarDays, "Eventos activos", String(customer.activeEvents), "#customer-events"],
      [Archive, "Eventos archivados", String(customer.archivedEvents), "#customer-events"],
      [FileSignature, "Contratos", String(customer.contracts), "#customer-documents"],
      [CalendarDays, "Lifetime Value", money(customer.lifetimeValue), "#customer-commercial-history"],
    ].map(([Icon, label, value, href]) => <a className="rounded-2xl border bg-card p-4 transition hover:border-brand" href={String(href)} key={String(label)}><Icon className="size-4 text-muted"/><p className="mt-4 text-2xl font-semibold">{String(value)}</p><p className="text-sm text-muted">{String(label)}</p><p className="mt-3 text-xs font-semibold text-brand">Ver resumen</p></a>)}</section>
    {editing && <form action={submit} className="grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-2">{[["fullName","Nombre y Apellido",customer.fullName],["rut","RUT",customer.rut],["company","Empresa",customer.company],["phone","Teléfono",customer.phone],["email","Email",customer.email],["address","Dirección",customer.address]].map(([name,label,value]) => <Field key={name} label={label}><input defaultValue={value} name={name}/></Field>)}<label className="text-sm sm:col-span-2"><span className="mb-1.5 block text-muted">Contactos adicionales (Nombre | Email | Teléfono)</span><textarea className="min-h-24 w-full rounded-xl border bg-background p-3" defaultValue={customer.contacts.map((contact) => [contact.name,contact.email,contact.phone].join(" | ")).join("\n")} name="contacts"/></label><label className="text-sm sm:col-span-2"><span className="mb-1.5 block text-muted">Notas comerciales</span><textarea className="min-h-24 w-full rounded-xl border bg-background p-3" defaultValue={customer.commercialNotes} name="commercialNotes"/></label><Field label="Motivo del cambio" wide><input name="reason" required/></Field>{error && <p className="text-sm text-red-500 sm:col-span-2">{error}</p>}<button className="rounded-xl bg-primary px-4 py-2.5 text-primary-foreground sm:col-span-2" disabled={pending}><Save className="mr-2 inline size-4"/>{pending ? "Guardando…" : "Guardar cambios"}</button></form>}
    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Información y contactos</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Teléfono" value={customer.phone}/><Row label="Email" value={customer.email}/><Row label="Dirección" value={customer.address}/><Row label="Notas comerciales" value={customer.commercialNotes}/></dl>{customer.contacts.length > 0 && <div className="mt-4 border-t pt-4">{customer.contacts.map((contact, index) => <p className="mt-2 text-sm" key={`${contact.email}-${index}`}>{contact.name} · {contact.email} · {contact.phone}</p>)}</div>}</article><article className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Resumen de pagos del Cliente</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Valor comercial acumulado" value={money(customer.totalRevenue)}/><Row label="Total recibido" value={money(customer.totalReceived)}/><Row label="Saldo por cobrar" value={money(customer.accountsReceivable)}/><Row label="Movimientos registrados" value={String(customer.payments)}/></dl><p className="mt-4 text-xs text-muted">La gestión de cada movimiento se realiza dentro del Evento correspondiente.</p></article></section>
    <section className="scroll-mt-24" id="customer-events"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Eventos del Cliente</h2><p className="mt-1 text-sm text-muted">Selecciona un Evento para abrir su centro operativo.</p></div><Link className="text-sm font-semibold text-brand" href="/events">Ver todos los Eventos</Link></div><div className="mt-3 grid gap-3">{customer.events.map((event) => <Link className="group flex items-center justify-between gap-4 rounded-2xl border bg-card p-4 transition hover:border-brand" href={`/projects/${event.projectId}`} key={event.projectId}><div><p className="font-medium">{event.type} · {event.name}</p><p className="mt-1 text-sm text-muted">{event.date ? new Date(`${event.date}T12:00:00Z`).toLocaleDateString("es-CL") : "Sin fecha"} · {event.service || "Servicio por confirmar"} · {event.status}</p></div><span className="flex shrink-0 items-center gap-2 text-sm font-semibold text-brand">Abrir Evento<ExternalLink className="size-4"/></span></Link>)}{customer.events.length === 0 && <p className="rounded-2xl border border-dashed p-8 text-center text-muted">Sin Eventos registrados.</p>}</div></section>
    <section className="scroll-mt-24" id="customer-documents"><h2 className="text-lg font-semibold">Documentos y Portal</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Summary label="Contratos" value={String(customer.contracts)}/><Summary label="Documentos" value={String(customer.documents)}/><Summary label="Portal Cliente" value={customer.portalActive ? "Activo" : "Sin activar"}/></div><p className="mt-3 text-xs text-muted">Los documentos operacionales y la administración del Portal se gestionan desde cada Evento.</p></section>
    <section className="scroll-mt-24" id="customer-commercial-history"><h2 className="text-lg font-semibold">Historial comercial</h2><div className="mt-3 space-y-3">{customer.commercialHistory.map((item) => <Link className="block rounded-2xl border bg-card p-4 transition hover:border-brand" href={`/projects/${item.projectId}`} key={item.id}><div className="flex justify-between gap-3"><div><p className="font-medium">{item.type} · {item.title}</p><p className="mt-1 text-xs text-muted">{new Date(item.date).toLocaleString("es-CL")}</p></div><ExternalLink className="size-4 text-brand"/></div><p className="mt-3 text-sm text-muted">{item.detail}</p></Link>)}{customer.commercialHistory.length === 0 && <p className="rounded-2xl border border-dashed p-6 text-sm text-muted">Sin historial comercial registrado.</p>}</div></section>
    <section><h2 className="text-lg font-semibold">Timeline del Cliente</h2><div className="mt-3 max-h-96 space-y-3 overflow-auto rounded-2xl border bg-card p-5">{customer.timeline.map((item) => <div className="border-l-2 pl-3" key={item.id}><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-sm text-muted">{item.message}</p><p className="mt-1 text-xs text-muted">{new Date(item.date).toLocaleString("es-CL")}</p></div>)}{customer.timeline.length === 0 && <p className="text-sm text-muted">Sin actividad registrada.</p>}</div></section>
  </div>;
}

function Field({ children, label, wide }: { children: React.ReactNode; label: string; wide?: boolean }) { return <label className={`text-sm ${wide ? "sm:col-span-2" : ""}`}><span className="mb-1.5 block text-muted">{label}</span><span className="block [&>*]:h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-background [&>*]:px-3">{children}</span></label>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b pb-2 last:border-0"><dt className="text-muted">{label}</dt><dd className="text-right font-medium">{value || "—"}</dd></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
function parseContacts(value: string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [name = "", email = "", phone = ""] = line.split("|").map((item) => item.trim()); return { name, email, phone }; }); }
