"use client";

import { Archive, CalendarDays, Copy, ExternalLink, MoreVertical, Search, Trash2 } from "lucide-react";
import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { CrmOperationalEvent } from "./types";
import { duplicateCrmEventAction, transitionCrmEventAction, updateCrmEventAction } from "./actions";

type View="TODAY"|"UPCOMING"|"COMPLETED"|"CANCELLED"|"ARCHIVED"|"ALL";
const today=new Date().toISOString().slice(0,10);
const statusOf=(event:CrmOperationalEvent):View=>{const status=event.status.toUpperCase();if(status==="ARCHIVED")return"ARCHIVED";if(["CANCELLED","CANCELED"].includes(status))return"CANCELLED";if(["COMPLETED","FINISHED"].includes(status)||(event.date&&event.date<today))return"COMPLETED";if(event.date===today)return"TODAY";return"UPCOMING";};

export function EventCenter({initialEvents}:{initialEvents:CrmOperationalEvent[]}){
  const router=useRouter();const[events]=useState(initialEvents);const[view,setView]=useState<View>("UPCOMING");const[query,setQuery]=useState("");const[editing,setEditing]=useState<CrmOperationalEvent|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
  const filtered=useMemo(()=>events.filter(event=>(view==="ALL"||statusOf(event)===view)&&`${event.customerName} ${event.company} ${event.date??""} ${event.service} ${event.operator} ${event.status}`.toLowerCase().includes(query.toLowerCase())),[events,query,view]);
  const lifecycle=(event:CrmOperationalEvent,action:"ARCHIVE"|"PERMANENT_DELETE")=>{const warning=action==="PERMANENT_DELETE"?"Eliminar SOLO este Evento. El Cliente permanecerá dentro del CRM. ¿Continuar?":"Archivar este Evento y excluirlo de la operación activa. ¿Continuar?";if(!window.confirm(warning))return;const reason=window.prompt("Motivo obligatorio:")?.trim();if(!reason)return;start(async()=>{const result=await transitionCrmEventAction({customerId:event.customerId,projectId:event.projectId,action,reason});if(!result.ok)setError(result.message);else router.refresh();});};
  const duplicate=(event:CrmOperationalEvent)=>{const copyStaff=window.confirm("¿Copiar Staff como asignación pendiente?");const reason=window.prompt("Motivo de duplicación:")?.trim();if(!reason)return;start(async()=>{const result=await duplicateCrmEventAction({customerId:event.customerId,projectId:event.projectId,copyStaff,reason});if(!result.ok)setError(result.error);else router.push(`/projects/${result.projectId}`);});};
  const submit=(form:FormData)=>{if(!editing)return;start(async()=>{const result=await updateCrmEventAction({customerId:editing.customerId,projectId:editing.projectId,date:String(form.get("date")),time:String(form.get("time")),type:String(form.get("type")),location:String(form.get("location")),municipality:String(form.get("municipality")),service:String(form.get("service")),duration:String(form.get("duration")),transport:String(form.get("transport")),reason:String(form.get("reason"))});if(!result.ok)setError(result.error);else{setEditing(null);router.refresh();}});};
  const tabs:[View,string][]=[["TODAY","Eventos de hoy"],["UPCOMING","Próximos"],["COMPLETED","Completados"],["CANCELLED","Cancelados"],["ARCHIVED","Archivados"],["ALL","Todos"]];
  return <div className="space-y-7"><header className="border-b pb-7"><p className="text-xs uppercase tracking-[.18em] text-muted">CRM · OPERACIÓN</p><h1 className="mt-2 text-3xl font-semibold">Eventos</h1><p className="mt-2 text-sm text-muted">Gestiona todos los eventos BOOMBOX sin salir del CRM.</p></header>
    <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([key,label])=><button className={`shrink-0 rounded-xl border px-4 py-2 text-sm ${view===key?"border-brand bg-brand/10 text-brand":""}`} key={key} onClick={()=>setView(key)}>{label} · {events.filter(event=>key==="ALL"||statusOf(event)===key).length}</button>)}</div>
    <label className="flex h-12 items-center gap-3 rounded-xl border bg-card px-4"><Search className="size-4 text-muted"/><input className="min-w-0 flex-1 bg-transparent outline-none" onChange={event=>setQuery(event.target.value)} placeholder="Buscar cliente, empresa, fecha, servicio, operador o estado" value={query}/></label>
    {error&&<p className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-400">{error}</p>}
    <section className="space-y-3">{filtered.map(event=><article className="grid gap-4 rounded-2xl border bg-card p-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center" key={event.projectId}><div><div className="flex flex-wrap items-center gap-2"><CalendarDays className="size-4 text-brand"/><h2 className="font-semibold">{event.customerName}</h2><span className="rounded-full border px-2.5 py-1 text-xs">{event.status}</span></div><p className="mt-2 text-sm text-muted">{event.company||"Cliente particular"} · {event.date?new Date(`${event.date}T12:00:00Z`).toLocaleDateString("es-CL"):"Sin fecha"} · {event.time?.slice(0,5)||"Sin hora"}</p><p className="mt-1 text-sm">{event.service||"Servicio por confirmar"}{event.duration?` · ${event.duration} horas`:""} · Operador: {event.operator}</p></div><div className="flex items-center justify-end gap-2"><Link className="rounded-xl border px-3 py-2 text-sm" href={`/customers/${event.customerId}`}>Cliente</Link><details className="relative"><summary aria-label={`Acciones para ${event.name}`} className="grid size-10 cursor-pointer list-none place-items-center rounded-xl border"><MoreVertical className="size-4"/></summary><div className="absolute right-0 z-20 mt-2 w-56 rounded-xl border bg-card p-2 shadow-xl"><Link className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-accent" href={`/projects/${event.projectId}`}><ExternalLink className="size-4"/>Abrir Evento</Link><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-accent" onClick={()=>setEditing(event)}>Editar Evento</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-accent" onClick={()=>duplicate(event)}><Copy className="size-4"/>Duplicar Evento</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-accent" onClick={()=>lifecycle(event,"ARCHIVE")}><Archive className="size-4"/>Archivar Evento</button><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-red-400 hover:bg-red-500/10" onClick={()=>lifecycle(event,"PERMANENT_DELETE")}><Trash2 className="size-4"/>Eliminar Evento</button></div></details></div></article>)}{filtered.length===0&&<p className="rounded-2xl border border-dashed p-10 text-center text-muted">No hay eventos para esta vista.</p>}</section>
    {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form action={submit} className="grid max-h-[90vh] w-full max-w-2xl gap-4 overflow-auto rounded-2xl border bg-card p-6 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">Editar Evento</h2>{[["date","Fecha",editing.date??"","date"],["time","Hora",editing.time?.slice(0,5)??"","time"],["type","Tipo",editing.type,"text"],["location","Lugar",editing.location??"","text"],["municipality","Comuna",editing.municipality??"","text"],["service","Servicio",editing.service,"text"],["duration","Duración",String(editing.duration??""),"number"],["transport","Transporte",String(editing.transport),"number"]].map(([name,label,value,type])=><label className="text-sm" key={name}><span className="mb-1.5 block text-muted">{label}</span><input className="h-11 w-full rounded-xl border bg-background px-3" defaultValue={value} name={name} type={type}/></label>)}<label className="text-sm sm:col-span-2"><span className="mb-1.5 block text-muted">Motivo obligatorio</span><input className="h-11 w-full rounded-xl border bg-background px-3" name="reason" required/></label><div className="flex justify-end gap-2 sm:col-span-2"><button className="rounded-xl border px-4 py-2" onClick={()=>setEditing(null)} type="button">Cancelar</button><button className="rounded-xl bg-primary px-4 py-2 text-primary-foreground" disabled={pending}>{pending?"Sincronizando…":"Guardar y sincronizar"}</button></div></form></div>}
  </div>;
}
