export type CertificationScope = "CORE" | "TENANT";
export type CertificationCheck = { module: string; flow: string; checkName: string; required: boolean };
export type CertificationTenantAdapter = { tenantSlug: string; scope: CertificationScope; modules: readonly string[]; requiredChecks: readonly CertificationCheck[]; optionalChecks: readonly CertificationCheck[]; integrationChecks: readonly CertificationCheck[]; certificationPolicy: "LIVE_REQUIRED" | "SAFE_MOCK" };
const common = ["AUTH", "RBAC", "MIDDLEWARE", "CUSTOMERS", "CRM", "QUOTATIONS", "RESERVATIONS", "PROJECTS", "DOCUMENTS", "STAFF", "PAYMENTS", "CALENDAR", "DRIVE", "TIMELINE", "MODALS", "MOBILE", "DESKTOP", "ERROR_HANDLING", "RESILIENT_SYNC", "BACKGROUND_JOBS", "AUDIT_TRAIL"];
const checks = (modules: readonly string[]): CertificationCheck[] => modules.map(module => ({ module, flow: "SAFE_MODE", checkName: `${module}_CONTRACT`, required: true }));
export const CoreCertificationAdapter: CertificationTenantAdapter = { tenantSlug: "core", scope: "CORE", modules: common, requiredChecks: checks(common), optionalChecks: [], integrationChecks: [], certificationPolicy: "LIVE_REQUIRED" };
export const BoomboxCertificationAdapter: CertificationTenantAdapter = { tenantSlug: "boombox", scope: "TENANT", modules: ["STAFF_CALL", "OPERATIONS", "STAFF_ASSIGNMENTS", "PORTAL_STAFF", "PORTAL_CLIENT", "SERVICES", "EXTRAS", "TRANSPORT", "RESOURCES", "VEHICLES", "SETTLEMENTS", "AGREEMENTS", "CALENDAR", "DRIVE", "PUBLICATION_GATE"], requiredChecks: checks(["STAFF_CALL", "OPERATIONS", "STAFF_ASSIGNMENTS", "PORTAL_STAFF", "PORTAL_CLIENT", "SERVICES", "EXTRAS", "TRANSPORT", "RESOURCES", "VEHICLES", "SETTLEMENTS", "AGREEMENTS", "CALENDAR", "DRIVE", "PUBLICATION_GATE"]), optionalChecks: [], integrationChecks: [], certificationPolicy: "LIVE_REQUIRED" };
export const PixmediaCertificationAdapter: CertificationTenantAdapter = { tenantSlug: "pixmedia", scope: "TENANT", modules: ["CUSTOMERS", "QUOTATIONS", "RESERVATIONS", "INVENTORY", "ASSIGNMENTS", "OPERATIONS", "CALENDAR", "DRIVE", "DOCUMENTS", "PAYMENTS", "MOBILE", "DESKTOP"], requiredChecks: checks(["CUSTOMERS", "QUOTATIONS", "RESERVATIONS", "INVENTORY", "ASSIGNMENTS", "OPERATIONS", "CALENDAR", "DRIVE", "DOCUMENTS", "PAYMENTS", "MOBILE", "DESKTOP"]), optionalChecks: [], integrationChecks: [], certificationPolicy: "LIVE_REQUIRED" };
export function getCertificationAdapter(slug: string): CertificationTenantAdapter { return slug === "boombox" ? BoomboxCertificationAdapter : slug === "pixmedia" ? PixmediaCertificationAdapter : CoreCertificationAdapter; }
