import "server-only";
import { connect } from "node:tls";
import { createAdminClient } from "@/lib/supabase/admin";
import { loadGoogleWorkspaceConnection } from "@/features/connectors/google-workspace/application/google-workspace.repository";
import type { HealthAlert, HealthSignal, HealthStatus, SystemHealthSnapshot } from "./types";

const ok=(condition:boolean)=>condition?"HEALTHY" as const:"CRITICAL" as const;
const score=(signals:readonly HealthSignal[])=>signals.length?Math.round(signals.reduce((sum,item)=>sum+(item.status==="HEALTHY"?100:item.status==="WARNING"?60:item.status==="UNAVAILABLE"?40:0),0)/signals.length):0;
const latest=(values:(string|null|undefined)[])=>values.filter((value):value is string=>Boolean(value)).sort().at(-1);
const since=(value?:string)=>value?new Intl.RelativeTimeFormat("es-CL",{numeric:"auto"}).format(-Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000)),"minute"):"Sin registros";

async function routeSignal(base:string,path:string,label:string):Promise<HealthSignal>{const started=performance.now();try{const response=await fetch(`${base}${path}`,{method:"HEAD",redirect:"manual",cache:"no-store",signal:AbortSignal.timeout(6000)});return{label,status:response.status<500?"HEALTHY":"CRITICAL",value:response.status<500?"Disponible":"No disponible",detail:`HTTP ${response.status} · ${Math.round(performance.now()-started)} ms`}}catch{return{label,status:"CRITICAL",value:"No disponible",detail:"La ruta no respondió dentro del tiempo esperado."}}}
async function sslExpiry(host:string){return new Promise<string|null>(resolve=>{const socket=connect({host,port:443,servername:host,timeout:5000,rejectUnauthorized:true},()=>{const cert=socket.getPeerCertificate();socket.end();resolve(cert.valid_to?new Date(cert.valid_to).toISOString():null)});socket.on("error",()=>resolve(null));socket.on("timeout",()=>{socket.destroy();resolve(null)})})}

export async function loadSystemHealth(actorId:string):Promise<SystemHealthSnapshot>{
  const admin=createAdminClient();const checkedAt=new Date().toISOString();const configuredDomain=process.env.NEXT_PUBLIC_APP_URL||"https://orbit-platform-v1.vercel.app";const base=configuredDomain.replace(/\/$/,"");const host=new URL(base).hostname;const started=performance.now();let platformOnline=false;try{const response=await fetch(base,{method:"HEAD",redirect:"manual",cache:"no-store",signal:AbortSignal.timeout(6000)});platformOnline=response.status<500}catch{}const responseTimeMs=platformOnline?Math.round(performance.now()-started):null;
  const [{error:dbError},{data:storageUsage,error:storageError},{data:calendar},{data:drive},{data:gmail},{data:jobs},{data:deadLetters},{data:failedAttempts},{data:portalSessions},{data:audit},{data:timeline},{data:healthAlerts},{data:previousChecks},authUsers,ssl,google,routeSignals]=await Promise.all([
    admin.from("projects").select("id").limit(1),admin.rpc("orbit_storage_usage"),admin.from("calendar_sync").select("status,last_synced_at,last_error").order("last_synced_at",{ascending:false}).limit(50),admin.from("drive_sync").select("status,last_synced_at,last_error,external_folder_id").order("last_synced_at",{ascending:false}).limit(50),admin.from("communications").select("status,occurred_at,external_message_id,communication_type").eq("channel","GMAIL").order("occurred_at",{ascending:false}).limit(50),admin.from("connector_jobs").select("connector,operation,status,attempt_count,max_attempts,updated_at,last_error").order("updated_at",{ascending:false}).limit(100),admin.from("dead_letter_jobs").select("id,connector,operation,failed_at,resolved_at").is("resolved_at",null),admin.from("portal_access_attempts").select("succeeded,attempted_at,device").eq("succeeded",false).gte("attempted_at",new Date(Date.now()-86400000).toISOString()),admin.from("portal_access_sessions").select("expires_at,revoked_at,last_accessed_at,device").gt("expires_at",checkedAt).is("revoked_at",null),admin.from("audit_events").select("id,occurred_at").order("occurred_at",{ascending:false}).limit(1),admin.from("timeline_events").select("id,occurred_at").order("occurred_at",{ascending:false}).limit(1),admin.from("system_health_alerts").select("id,alert_key,severity,message,status,last_seen_at").in("status",["OPEN","ACKNOWLEDGED"]).order("last_seen_at",{ascending:false}),admin.from("system_health_checks").select("services,deployment_ref").order("checked_at",{ascending:false}).limit(1),admin.auth.admin.listUsers({page:1,perPage:1000}),sslExpiry(host),loadGoogleWorkspaceConnection().catch(()=>undefined),Promise.all([["/portal/login","Customer Portal"],["/staff/login","Staff Portal"],["/login","Administración"],["/tasks","Task Center"],["/reports","Business Intelligence"],["/operations","Command Center"]].map(([path,label])=>routeSignal(base,path,label)))
  ]);
  const dbHealthy=!dbError;const authHealthy=!authUsers.error;const sslDays=ssl?Math.ceil((new Date(ssl).getTime()-Date.now())/86400000):null;const totalBytes=(storageUsage??[]).reduce((sum:number,item:{total_bytes:number})=>sum+Number(item.total_bytes),0);const totalObjects=(storageUsage??[]).reduce((sum:number,item:{object_count:number})=>sum+Number(item.object_count),0);
  const lastCalendar=latest((calendar??[]).map(item=>item.last_synced_at));const lastDrive=latest((drive??[]).map(item=>item.last_synced_at));const lastGmail=latest((gmail??[]).map(item=>item.occurred_at));const googleGranted=new Set(google?.grantedServices.filter(item=>item.granted).map(item=>item.id)??[]);const googleConnected=google?.connectionStatus==="CONNECTED";
  const vercel:HealthSignal[]=[{label:"Deployment",status:ok(platformOnline),value:platformOnline?"En línea":"No disponible",detail:process.env.VERCEL_ENV?`Entorno ${process.env.VERCEL_ENV}`:"Verificación HTTP"},{label:"Producción",status:ok(platformOnline),value:process.env.VERCEL_URL??host},{label:"Certificado SSL",status:sslDays===null?"UNAVAILABLE":sslDays>30?"HEALTHY":sslDays>7?"WARNING":"CRITICAL",value:sslDays===null?"No disponible":`${sslDays} días restantes`,detail:ssl?`Vence ${new Date(ssl).toLocaleDateString("es-CL")}`:undefined},{label:"Dominio",status:ok(platformOnline),value:host},{label:"Tiempo de respuesta",status:responseTimeMs===null?"CRITICAL":responseTimeMs<1000?"HEALTHY":responseTimeMs<2500?"WARNING":"CRITICAL",value:responseTimeMs===null?"Sin respuesta":`${responseTimeMs} ms`},{label:"Último deployment",status:process.env.VERCEL_GIT_COMMIT_SHA?"HEALTHY":"UNAVAILABLE",value:process.env.VERCEL_GIT_COMMIT_SHA?.slice(0,8)??"No disponible"}];
  const supabase:HealthSignal[]=[{label:"Database",status:ok(dbHealthy),value:dbHealthy?"Conectada":"No disponible"},{label:"Authentication",status:ok(authHealthy),value:authHealthy?"Operacional":"No disponible"},{label:"Storage",status:storageError?"CRITICAL":"HEALTHY",value:storageError?"No disponible":`${totalObjects} archivos`},{label:"Realtime",status:dbHealthy?"WARNING":"CRITICAL",value:dbHealthy?"Configurado · no sondeado":"No disponible"},{label:"Migraciones",status:dbHealthy?"HEALTHY":"CRITICAL",value:dbHealthy?"Esquema accesible":"No verificable"},{label:"Último backup",status:"UNAVAILABLE",value:"Requiere Management API"},{label:"Uso de Storage",status:"HEALTHY",value:formatBytes(totalBytes)}];
  const googleSignals:HealthSignal[]=[{label:"OAuth",status:ok(Boolean(googleConnected)),value:googleConnected?"Conectado":"Desconectado"},{label:"Refresh Token",status:googleConnected?"HEALTHY":"CRITICAL",value:googleConnected?"Persistido en servidor":"No disponible"},{label:"Gmail",status:googleGranted.has("GMAIL")?"HEALTHY":"CRITICAL",value:googleGranted.has("GMAIL")?"Autorizado":"Sin autorización"},{label:"Calendar",status:googleGranted.has("CALENDAR")?"HEALTHY":"CRITICAL",value:googleGranted.has("CALENDAR")?"Autorizado":"Sin autorización",detail:`Última sincronización ${since(lastCalendar)}`},{label:"Drive",status:googleGranted.has("DRIVE")?"HEALTHY":"CRITICAL",value:googleGranted.has("DRIVE")?"Autorizado":"Sin autorización",detail:`Última sincronización ${since(lastDrive)}`},{label:"Borradores Gmail",status:(gmail??[]).some(item=>item.external_message_id)?"HEALTHY":"WARNING",value:(gmail??[]).some(item=>item.external_message_id)?"Creación confirmada":"Sin borradores recientes"},{label:"Última actividad",status:latest([lastCalendar,lastDrive,lastGmail])?"HEALTHY":"WARNING",value:since(latest([lastCalendar,lastDrive,lastGmail]))}];
  const serviceSignals:HealthSignal[]=[...routeSignals,{label:"Timeline",status:timeline?.length?"HEALTHY":"WARNING",value:timeline?.length?`Última actividad ${since(timeline[0].occurred_at)}`:"Sin registros"},{label:"Auditoría",status:audit?.length?"HEALTHY":"WARNING",value:audit?.length?`Última actividad ${since(audit[0].occurred_at)}`:"Sin registros"},{label:"Experience Review",status:dbHealthy?"HEALTHY":"CRITICAL",value:dbHealthy?"Repositorio disponible":"No disponible"},{label:"Payroll",status:dbHealthy?"HEALTHY":"CRITICAL",value:dbHealthy?"Repositorio disponible":"No disponible"},{label:"Equipment",status:dbHealthy?"HEALTHY":"CRITICAL",value:dbHealthy?"Repositorio disponible":"No disponible"},{label:"Event 360°",status:dbHealthy?"HEALTHY":"CRITICAL",value:dbHealthy?"Repositorio disponible":"No disponible"}];
  const unknownDevices=(portalSessions??[]).filter(item=>!item.device||item.device==="UNKNOWN").length;const activeAuth=(authUsers.data?.users??[]).filter(user=>user.last_sign_in_at&&Date.now()-new Date(user.last_sign_in_at).getTime()<3600000).length;const security:HealthSignal[]=[{label:"Intentos fallidos",status:(failedAttempts??[]).length>5?"WARNING":"HEALTHY",value:`${failedAttempts?.length??0} en 24 h`,detail:"Accesos de Portal registrados"},{label:"Sesiones activas",status:"HEALTHY",value:String((portalSessions?.length??0)+activeAuth),detail:"Portales vigentes y accesos administrativos recientes"},{label:"Último login",status:"HEALTHY",value:latest([...(portalSessions??[]).map(item=>item.last_accessed_at),...(authUsers.data?.users??[]).map(user=>user.last_sign_in_at)])?since(latest([...(portalSessions??[]).map(item=>item.last_accessed_at),...(authUsers.data?.users??[]).map(user=>user.last_sign_in_at)])):"Sin registros"},{label:"Dispositivos desconocidos",status:unknownDevices?"WARNING":"HEALTHY",value:String(unknownDevices)},{label:"Expiración de sesión",status:"HEALTHY",value:"Políticas activas"}];
  const storage:HealthSignal[]=(storageUsage??[]).map((item:{bucket_id:string;object_count:number;total_bytes:number})=>({label:item.bucket_id,status:"HEALTHY",value:formatBytes(Number(item.total_bytes)),detail:`${item.object_count} archivos`}));storage.push({label:"Capacidad disponible",status:"UNAVAILABLE",value:"Requiere Management API"},{label:"Tendencia",status:"UNAVAILABLE",value:"Disponible después de múltiples mediciones"});
  const jobGroups=["AGREEMENT","PDF","DRIVE","CALENDAR","PORTAL","TIMELINE","AUDIT","PAYROLL","PROFIT"].map(key=>{const matches=(jobs??[]).filter(item=>`${item.connector} ${item.operation}`.toUpperCase().includes(key));const failed=matches.filter(item=>["FAILED","DEAD_LETTER"].includes(item.status)).length;return{label:key,status:(failed?"CRITICAL":matches.some(item=>["PENDING","RETRY"].includes(item.status))?"WARNING":"HEALTHY") as HealthStatus,value:failed?`${failed} fallidos`:matches.length?`${matches.length} registrados`:"Sin trabajos pendientes"}});if(deadLetters?.length)jobGroups.push({label:"RECUPERACIÓN",status:"CRITICAL",value:`${deadLetters.length} trabajos requieren atención`});
  const allSignals=[...vercel,...supabase,...googleSignals,...serviceSignals,...security,...storage,...jobGroups];const generatedAlerts=allSignals.filter(item=>item.status==="CRITICAL"||item.status==="WARNING").map(item=>({key:`health:${item.label.toLowerCase().replaceAll(" ","-")}`,severity:(item.status==="CRITICAL"?"CRITICAL":"WARNING") as "CRITICAL"|"WARNING",message:operationalMessage(item)}));
  for(const alert of generatedAlerts)await admin.from("system_health_alerts").upsert({alert_key:alert.key,severity:alert.severity,message:alert.message,status:"OPEN",last_seen_at:checkedAt},{onConflict:"alert_key"});
  const activeKeys=new Set(generatedAlerts.map(item=>item.key));for(const item of healthAlerts??[]){if(!activeKeys.has(item.alert_key))await admin.from("system_health_alerts").update({status:"RESOLVED",resolved_at:checkedAt}).eq("id",item.id)}
  const scores=[{label:"Infraestructura",value:score(vercel)},{label:"Google",value:score(googleSignals)},{label:"Database",value:score(supabase)},{label:"Portal",value:score(serviceSignals.filter(item=>item.label.includes("Portal")))},{label:"Seguridad",value:score(security)},{label:"Performance",value:responseTimeMs===null?0:responseTimeMs<1000?100:responseTimeMs<2500?60:20}];const overallScore=Math.round(scores.reduce((sum,item)=>sum+item.value,0)/scores.length);scores.push({label:"Overall ORBIT",value:overallScore});const overallStatus=overallScore>=85?"HEALTHY":overallScore>=60?"WARNING":"CRITICAL";
  const deploymentRef=process.env.VERCEL_GIT_COMMIT_SHA??process.env.VERCEL_URL;
  await appendHealthTransitions(admin,previousChecks?.[0],allSignals,deploymentRef,actorId);
  await admin.from("system_health_checks").insert({overall_status:overallStatus,overall_score:overallScore,scores,services:allSignals,deployment_ref:deploymentRef,created_by:actorId});
  const {data:alerts}=await admin.from("system_health_alerts").select("id,severity,message,status,last_seen_at").in("status",["OPEN","ACKNOWLEDGED"]).order("last_seen_at",{ascending:false}).limit(20);
  const recommendations=(alerts??[]).filter(item=>item.status==="OPEN").map(item=>item.message.includes("Google")?"Reconectar Google Workspace.":item.message.includes("Storage")?"Revisar el uso de almacenamiento.":item.message.includes("sincron")?"Revisar la sincronización fallida.":`Revisar: ${item.message}`).slice(0,4);if(!recommendations.length)recommendations.push("Mantener la revisión periódica del estado de ORBIT.");
  const projectRef=(process.env.SUPABASE_URL??"").match(/https:\/\/([^.]+)/)?.[1]??"";const driveId=(drive??[]).find(item=>item.external_folder_id)?.external_folder_id;
  return{checkedAt,overallStatus,overallScore,version:process.env.npm_package_version??"ORBIT v1.0",deployment:process.env.VERCEL_GIT_COMMIT_SHA?.slice(0,8)??process.env.VERCEL_URL??"Local",domain:host,responseTimeMs,scores,vercel,supabase,google:googleSignals,services:serviceSignals,security,storage,jobs:jobGroups,alerts:(alerts??[]).map(item=>({id:item.id,severity:item.severity as "WARNING"|"CRITICAL",message:item.message,status:item.status,lastSeenAt:item.last_seen_at})) as HealthAlert[],recommendations,links:{supabase:`https://supabase.com/dashboard/project/${projectRef}`,vercel:"https://vercel.com/dashboard",drive:driveId?`https://drive.google.com/drive/folders/${driveId}`:undefined}};
}

function operationalMessage(signal:HealthSignal){if(signal.label==="Calendar")return `Google Calendar requiere atención. ${signal.detail??"Revisa la sincronización."}`;if(signal.label==="Customer Portal")return"Customer Portal no está disponible.";if(signal.label==="Authentication")return"Supabase Authentication no está disponible.";if(signal.label==="Certificado SSL")return`El certificado SSL requiere revisión: ${signal.value}.`;return`${signal.label} requiere atención: ${signal.value}.`}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1048576)return`${(value/1024).toFixed(1)} KB`;if(value<1073741824)return`${(value/1048576).toFixed(1)} MB`;return`${(value/1073741824).toFixed(2)} GB`}
async function appendHealthTransitions(admin:ReturnType<typeof createAdminClient>,previous:{services:unknown;deployment_ref:string|null}|undefined,current:readonly HealthSignal[],deployment:string|undefined,actorId:string){
  if(!previous)return;
  const oldSignals=Array.isArray(previous.services)?previous.services as HealthSignal[]:[];const oldByLabel=new Map(oldSignals.map(item=>[item.label,item.status]));const events:{action:string;message:string;entity:string}[]=[];
  for(const item of current){const before=oldByLabel.get(item.label);if(!before||before===item.status)continue;if(item.status==="CRITICAL")events.push({action:"SERVICE_OFFLINE",message:`${item.label} dejó de estar disponible.`,entity:item.label});else if(before==="CRITICAL"&&item.status==="HEALTHY")events.push({action:"SERVICE_RESTORED",message:`${item.label} volvió a estar operativo.`,entity:item.label})}
  if(deployment&&previous.deployment_ref&&deployment!==previous.deployment_ref)events.push({action:"DEPLOYMENT_UPDATED",message:"ORBIT recibió un nuevo deployment productivo.",entity:deployment});
  for(const event of events){const correlation=crypto.randomUUID();await admin.from("timeline_events").insert({event_type:event.action,title:event.message,description:event.message,orbit_event_id:"ORB-SYSTEM-HEALTH",actor_id:actorId,actor_label:"Sistema",source:"System",action:event.action,entity_type:"SystemHealth",entity_id:event.entity,human_message:event.message,correlation_id:correlation,created_by:actorId})}
}
