"use client";

import { useEffect, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Activity, AlertTriangle, Check, CheckCircle2, Cloud, Database, ExternalLink, Gauge, Globe2, HardDrive, History, LockKeyhole, RefreshCw, Server, ShieldCheck, Sparkles } from "lucide-react";
import { acknowledgeHealthAlertAction } from "./actions";
import type { HealthSignal, HealthStatus, SystemHealthSnapshot } from "./types";

const statusCopy:Record<HealthStatus,string>={HEALTHY:"Operacional",WARNING:"Atención",CRITICAL:"Crítico",UNAVAILABLE:"No disponible"};
const statusClass:Record<HealthStatus,string>={HEALTHY:"border-success/25 bg-success/10 text-success",WARNING:"border-warning/25 bg-warning/10 text-warning",CRITICAL:"border-danger/25 bg-danger/10 text-danger",UNAVAILABLE:"border-border bg-background/55 text-muted"};

export function SystemHealthCenter({snapshot}:{snapshot:SystemHealthSnapshot}){
  const router=useRouter();const[pending,startTransition]=useTransition();const[updated,setUpdated]=useState(snapshot.checkedAt);
  useEffect(()=>{const timer=window.setInterval(()=>startTransition(()=>{router.refresh();setUpdated(new Date().toISOString())}),60000);return()=>window.clearInterval(timer)},[router]);
  const tone=snapshot.overallStatus==="HEALTHY"?"text-success":snapshot.overallStatus==="WARNING"?"text-warning":"text-danger";
  return <div className="space-y-6 pb-12 lg:space-y-8">
    <header className="relative overflow-hidden rounded-[2rem] border bg-card p-6 sm:p-8 lg:p-10">
      <div className="absolute right-0 top-0 h-56 w-56 rounded-full bg-brand/10 blur-3xl"/>
      <div className="relative flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between">
        <div className="max-w-3xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-brand"><Activity className="size-4"/>System Health Center</div><h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">ORBIT está {snapshot.overallStatus==="HEALTHY"?"operacional":snapshot.overallStatus==="WARNING"?"requiriendo atención":"en estado crítico"}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted sm:text-base">Una vista ejecutiva del estado real de la plataforma y sus integraciones productivas.</p></div>
        <div className="grid min-w-full grid-cols-2 gap-3 sm:min-w-[430px] sm:grid-cols-4"><Metric label="Estado" value={statusCopy[snapshot.overallStatus]} tone={tone}/><Metric label="Score" value={`${snapshot.overallScore}%`} tone={tone}/><Metric label="Versión" value={snapshot.version}/><Metric label="Deployment" value={snapshot.deployment}/></div>
      </div><div className="relative mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 border-t pt-5 text-xs text-muted"><span>Última revisión {new Date(snapshot.checkedAt).toLocaleString("es-CL")}</span><span>{snapshot.domain}</span><span>{snapshot.responseTimeMs===null?"Sin respuesta":`${snapshot.responseTimeMs} ms`}</span><button className="inline-flex min-h-9 items-center gap-2 rounded-xl border px-3 hover:bg-background disabled:opacity-60" disabled={pending} onClick={()=>startTransition(()=>{router.refresh();setUpdated(new Date().toISOString())})}><RefreshCw className={`size-3.5 ${pending?"animate-spin":""}`}/>Actualizar</button><span className="sr-only">{updated}</span></div>
    </header>

    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{snapshot.scores.map(item=><article className="rounded-2xl border bg-card p-4" key={item.label}><div className="flex items-center justify-between"><span className="text-xs font-medium text-muted">{item.label}</span><Gauge className="size-4 text-brand"/></div><p className={`mt-4 text-2xl font-semibold ${item.value>=85?"text-success":item.value>=60?"text-warning":"text-danger"}`}>{item.value}%</p></article>)}</section>

    {snapshot.alerts.length>0&&<section className="rounded-[1.75rem] border border-warning/20 bg-warning/[.04] p-5 sm:p-7"><SectionTitle icon={AlertTriangle} title="Centro de alertas" subtitle="Situaciones productivas que requieren revisión operativa."/><div className="mt-5 space-y-3">{snapshot.alerts.map(alert=><article className="flex flex-col gap-4 rounded-2xl border bg-card p-4 sm:flex-row sm:items-center sm:justify-between" key={alert.id}><div><div className="flex items-center gap-2"><Status status={alert.severity}/><span className="text-xs text-muted">{new Date(alert.lastSeenAt).toLocaleString("es-CL")}</span></div><p className="mt-2 text-sm font-medium">{alert.message}</p></div>{alert.status==="OPEN"?<button className="min-h-11 shrink-0 rounded-xl border px-4 text-sm font-semibold transition hover:bg-background disabled:opacity-50" disabled={pending} onClick={()=>startTransition(async()=>{await acknowledgeHealthAlertAction(alert.id);router.refresh()})}>Reconocer alerta</button>:<span className="inline-flex items-center gap-2 text-xs font-semibold text-muted"><Check className="size-4"/>Reconocida</span>}</article>)}</div></section>}

    <div className="grid gap-6 xl:grid-cols-2"><SignalSection icon={Cloud} title="Vercel" subtitle="Disponibilidad, dominio y deployment" signals={snapshot.vercel}/><SignalSection icon={Database} title="Supabase" subtitle="Database, Auth, Storage y plataforma" signals={snapshot.supabase}/><SignalSection icon={Globe2} title="Google Workspace" subtitle="OAuth y servicios autorizados" signals={snapshot.google}/><SignalSection icon={Server} title="Servicios ORBIT" subtitle="Disponibilidad de superficies productivas" signals={snapshot.services}/><SignalSection icon={ShieldCheck} title="Seguridad" subtitle="Accesos y sesiones observables" signals={snapshot.security}/><SignalSection icon={HardDrive} title="Storage" subtitle="Uso real por bucket productivo" signals={snapshot.storage}/><SignalSection icon={Activity} title="Procesos en segundo plano" subtitle="Colas, sincronizaciones y recuperación" signals={snapshot.jobs}/><Recommendations recommendations={snapshot.recommendations}/></div>

    <section className="rounded-[1.75rem] border bg-card p-5 sm:p-7"><SectionTitle icon={Sparkles} title="Acciones rápidas" subtitle="Accesos operativos; las acciones externas mantienen sus propias autorizaciones."/><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Quick href="/api/integrations/google/connect" label="Reconectar Google" icon={RefreshCw}/><Quick href={snapshot.links.supabase} label="Abrir Supabase" icon={Database} external/><Quick href={snapshot.links.vercel} label="Abrir Vercel" icon={Cloud} external/>{snapshot.links.drive&&<Quick href={snapshot.links.drive} label="Abrir Google Drive" icon={HardDrive} external/>}<Quick href="/settings#connections" label="Connection Center" icon={LockKeyhole}/><Quick href="/operations" label="Command Center" icon={Activity}/><Quick href="/projects" label="Revisar Timeline" icon={History}/></div></section>
  </div>
}

function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className="rounded-2xl border bg-background/45 p-3"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-muted">{label}</p><p className={`mt-2 truncate text-sm font-semibold ${tone}`}>{value}</p></div>}
function SectionTitle({icon:Icon,title,subtitle}:{icon:typeof Activity;title:string;subtitle:string}){return <div className="flex items-start gap-3"><div className="rounded-xl border bg-background p-2.5 text-brand"><Icon className="size-5"/></div><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted">{subtitle}</p></div></div>}
function SignalSection({icon,title,subtitle,signals}:{icon:typeof Activity;title:string;subtitle:string;signals:readonly HealthSignal[]}){return <section className="min-w-0 overflow-hidden rounded-[1.75rem] border bg-card p-5 sm:p-7"><SectionTitle icon={icon} title={title} subtitle={subtitle}/><div className="mt-5 min-w-0 divide-y">{signals.map(signal=><div className="flex min-h-16 min-w-0 items-center justify-between gap-3 py-3 first:pt-0 last:pb-0 sm:gap-4" key={`${title}-${signal.label}`}><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{signal.label}</p><p className="mt-1 truncate text-xs text-muted">{signal.detail??signal.value}</p></div><div className="max-w-[48%] shrink-0 text-right"><Status status={signal.status}/>{signal.detail&&<p className="mt-1.5 truncate text-xs text-muted">{signal.value}</p>}</div></div>)}</div></section>}
function Status({status}:{status:HealthStatus|"WARNING"|"CRITICAL"}){return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] ${statusClass[status]}`}><span className="size-1.5 rounded-full bg-current"/>{statusCopy[status]}</span>}
function Recommendations({recommendations}:{recommendations:readonly string[]}){return <section className="min-w-0 overflow-hidden rounded-[1.75rem] border bg-card p-5 sm:p-7"><SectionTitle icon={Sparkles} title="Recomendaciones" subtitle="Acciones sugeridas según el estado observado."/><div className="mt-5 space-y-3">{recommendations.map((item,index)=><div className="flex min-w-0 gap-3 rounded-2xl border bg-background/35 p-4" key={item}><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-brand/10 text-xs font-semibold text-brand">{index+1}</span><p className="min-w-0 break-words text-sm leading-6">{item}</p></div>)}</div></section>}
function Quick({href,label,icon:Icon,external=false}:{href:string;label:string;icon:typeof Activity;external?:boolean}){return <Link className="group flex min-h-12 items-center justify-between rounded-2xl border bg-background/35 px-4 text-sm font-semibold transition hover:border-brand/35 hover:bg-brand/[.04]" href={href} target={external?"_blank":undefined}><span className="flex items-center gap-3"><Icon className="size-4 text-brand"/>{label}</span>{external?<ExternalLink className="size-3.5 text-muted"/>:<CheckCircle2 className="size-3.5 text-muted transition group-hover:text-brand"/>}</Link>}
