"use client";

import { useEffect, useState, useTransition } from "react";
import { loadStaffConsumablesAction, recordStaffConsumableReturnAction, type StaffConsumable } from "./staff-consumables.actions";

export function StaffConsumablesPanel({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<StaffConsumable[]>([]);
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const [values, setValues] = useState<Record<string, string>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [incidents, setIncidents] = useState<Record<string, boolean>>({});
  const reload = () => startTransition(async () => { const result = await loadStaffConsumablesAction(projectId); if (result.ok) setItems(result.items); else setMessage(result.message ?? "No fue posible cargar los consumibles."); });
  useEffect(() => { reload(); }, [projectId]);
  if (!items.length && !message) return null;
  return <section className="rounded-2xl border p-4 sm:col-span-2"><h3 className="font-semibold">Consumibles de caja</h3><p className="mt-1 text-sm text-muted">Saldo de salida de solo lectura. Al retorno, informa el saldo restante; el sistema calcula el uso.</p>{message ? <p className="mt-3 text-sm text-red-600">{message}</p> : null}<div className="mt-4 grid gap-3 md:grid-cols-2">{items.map((item) => { const low = item.remaining <= item.threshold; return <div className="rounded-xl border p-3" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.boxCode}{item.printerCode ? ` · ${item.printerCode}` : ""}</p><p className="text-sm text-muted">{item.formatKey.replace("PHOTO_", "")} · lote {item.lot}</p><p className="text-sm text-muted">Cargado {new Date(item.loadedAt).toLocaleDateString("es-CL")}</p></div><span className={`rounded-full px-2 py-1 text-xs ${item.remaining === 0 ? "bg-slate-100 text-slate-700" : low ? "bg-amber-100 text-amber-900" : "bg-emerald-100 text-emerald-900"}`}>{item.remaining === 0 ? "EMPTY" : low ? "LOW STOCK" : "STOCK OK"}</span></div><p className="mt-3 text-2xl font-semibold">{item.remaining} fotos disponibles</p><div className="mt-3 grid gap-2"><label className="text-sm font-medium">Retorno<input className="mt-1 min-h-11 w-full rounded-lg border bg-background px-3" type="number" min="0" value={values[item.id] ?? ""} onChange={(event) => setValues((current) => ({ ...current, [item.id]: event.target.value }))} placeholder={`Salida: ${item.remaining}`} /></label><textarea className="min-h-16 rounded-lg border bg-background p-2 text-sm" value={notes[item.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Nota de retorno (opcional)" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={incidents[item.id] ?? false} onChange={(event) => setIncidents((current) => ({ ...current, [item.id]: event.target.checked }))} /> Reportar problema de papel/impresora</label><button type="button" disabled={pending || values[item.id] === undefined || values[item.id] === ""} onClick={() => startTransition(async () => { const result = await recordStaffConsumableReturnAction({ projectId, mediaLotId: item.id, remaining: Number(values[item.id]), note: notes[item.id] ?? "", incident: incidents[item.id] ?? false }); setMessage(result.ok ? "Retorno registrado correctamente." : ("message" in result ? (result.message ?? "No fue posible registrar el retorno.") : "No fue posible registrar el retorno.")); if (result.ok) reload(); })} className="min-h-11 rounded-lg bg-foreground px-3 py-2 text-sm text-background disabled:opacity-50">{pending ? "Guardando…" : "Registrar retorno"}</button></div></div>; })}</div></section>;
}
