import "server-only";
import {createAdminClient} from "@/lib/supabase/admin";
import {portalLogoutAction} from "./actions";
import {StaffPortalDashboard,type StaffPortalEvent} from "./staff-portal-dashboard";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago"}).format(new Date());
const addDays=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)};
const finish=(time:string,hours:number)=>{const[h,m]=time.slice(0,5).split(":").map(Number);const total=h*60+m+hours*60;return`${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`};

export async function StaffPortal({staffId}:{staffId:string}){const admin=createAdminClient(),start=today(),end=addDays(start,15),month=start.slice(0,7);const[staffResult,assignmentsResult,paymentsResult,documentsResult,checkinsResult,notificationsResult]=await Promise.all([
  admin.from("staff").select("first_name,last_name").eq("id",staffId).single(),
  admin.from("assignments").select("project_id,assignment_type,status,projects!inner(id,name,project_type,event_date,event_time,location,city,operations,customers(full_name),project_services(service_code,duration_hours))").eq("staff_id",staffId).is("deleted_at",null).not("status","in",'(CANCELLED,REJECTED)').gte("projects.event_date",start).lte("projects.event_date",end).order("created_at",{ascending:false}),
  admin.from("event_staff_payments").select("project_id,total_internal_payment,paid_amount,sii_receipt_status,projects!inner(event_date)").eq("staff_id",staffId).is("deleted_at",null).gte("projects.event_date",`${month}-01`).lt("projects.event_date",addDays(`${month}-01`,32).slice(0,7)+"-01"),
  admin.from("documents").select("id,project_id,document_type").is("deleted_at",null),
  admin.from("staff_event_checkins").select("project_id,status").eq("staff_id",staffId),
  admin.from("internal_notifications").select("id,title,message,created_at").eq("staff_id",staffId).in("category",["OPERATIONS","STAFF"]).order("created_at",{ascending:false}).limit(12),
]);const error=staffResult.error??assignmentsResult.error??paymentsResult.error??documentsResult.error??checkinsResult.error??notificationsResult.error;if(error)throw error;
  const grouped=new Map<string,{project:NonNullable<(typeof assignmentsResult.data)>[number]["projects"];roles:string[];status:string}>();for(const row of assignmentsResult.data??[]){const current=grouped.get(row.project_id);if(current){if(!current.roles.includes(row.assignment_type))current.roles.push(row.assignment_type);}else grouped.set(row.project_id,{project:row.projects,roles:[row.assignment_type],status:row.status});}
  const events:StaffPortalEvent[]=[...grouped.entries()].map(([projectId,item])=>{const project=Array.isArray(item.project)?item.project[0]:item.project;const services=Array.isArray(project.project_services)?project.project_services:[];const customer=Array.isArray(project.customers)?project.customers[0]:project.customers;const ops=(project.operations??{})as Record<string,unknown>;const hours=Number(services[0]?.duration_hours??4);const payment=(paymentsResult.data??[]).find(row=>row.project_id===projectId);return{id:projectId,customer:customer?.full_name??project.name,eventType:project.project_type,service:services.map(row=>row.service_code).filter(Boolean).join(" + ")||"Servicio BOOMBOX",date:project.event_date,start:project.event_time?.slice(0,5)??"00:00",finish:finish(project.event_time??"00:00",hours),address:project.location??"Dirección por confirmar",district:project.city??"Comuna por confirmar",venue:String(ops.venue??ops.venueName??project.location??"Lugar por confirmar"),roles:item.roles,net:Number(payment?.total_internal_payment??0),status:item.status,notes:String(ops.staffNotes??ops.operationalNotes??ops.notes??""),documents:(documentsResult.data??[]).filter(row=>row.project_id===projectId).map(row=>({id:row.id,type:row.document_type})),checkins:(checkinsResult.data??[]).filter(row=>row.project_id===projectId).map(row=>row.status)}}).sort((a,b)=>a.date.localeCompare(b.date));
  const generated=(paymentsResult.data??[]).reduce((sum,row)=>sum+Number(row.total_internal_payment),0),paid=(paymentsResult.data??[]).reduce((sum,row)=>sum+Number(row.paid_amount),0),receipts=(paymentsResult.data??[]);const payment={generated,paid,pending:Math.max(0,generated-paid),receiptStatus:receipts.length&&receipts.every(row=>row.sii_receipt_status==="RECEIVED")?"Recibida":"Pendiente"};const notifications=(notificationsResult.data??[]).map(row=>({id:row.id,title:row.title,message:row.message,date:new Date(row.created_at).toLocaleString("es-CL")}));const staffName=staffResult.data?`${staffResult.data.first_name} ${staffResult.data.last_name}`:"Colaborador";return <main className="min-h-screen bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-7xl"><div className="mb-4 flex justify-end"><form action={portalLogoutAction.bind(null,"STAFF")}><button className="min-h-11 rounded-xl border px-4 text-sm font-medium">Cerrar sesión</button></form></div><StaffPortalDashboard events={events} name={staffName} notifications={notifications} payment={payment}/></div></main>}
