import "server-only";
import {createAdminClient} from "@/lib/supabase/admin";
import {portalLogoutAction} from "./actions";
import {StaffPortalDashboard,type AvailableStaffEvent,type StaffPortalEvent,type StaffRequest,type StaffExpenseSubmission} from "./staff-portal-dashboard";
import {mapStaffMonthlyAccount,STAFF_MONTHLY_ACCOUNT_SELECT,type StaffMonthlyAccount} from "@/features/staff-monthly-account/model";
import {chileDateTime as operationalDateTime} from "@/features/operations/event-operational-window";
import {getCanonicalOrbitEventStates} from "@/features/operations/canonical-event-state";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago"}).format(new Date());
const addDays=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)};
const finish=(time:string,hours:number)=>{if(!/^\d{2}:\d{2}$/.test(time)||!Number.isFinite(hours))return"";const[h,m]=time.split(":").map(Number);const total=h*60+m+hours*60;return`${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`};
const OPERATIONAL_ROLES = ["OPERATOR", "ASSEMBLY", "DISASSEMBLY"] as const;

export async function StaffPortal({staffId}:{staffId:string}){const admin=createAdminClient(),start=today(),expenseStart=addDays(start,-30),end=addDays(start,15),month=start.slice(0,7);const[staffResult,assignmentsResult,paymentsResult,documentsResult,checkinsResult,notificationsResult,publicationsResult,allAssignmentsResult,requestsResult,checklistResult,vehiclesResult,costMasterResult,operationalContractsResult,physicalResourcesResult,staffRequirementsResult,logisticsTripsResult,expenseSubmissionsResult,monthlyAccountsResult]=await Promise.all([
  admin.from("staff").select("first_name,last_name,capabilities,portal_password_change_required").eq("id",staffId).single(),
  admin.from("assignments").select("project_id,assignment_type,status,resources,assigned_vehicle,projects!inner(id,name,orbit_event_id,project_type,event_date,event_time,event_time_mode,location,city,operations,customers(full_name,phone),project_services(service_code,duration_hours,extras))").eq("staff_id",staffId).is("deleted_at",null).not("status","in",'(CANCELLED,REJECTED)').gte("projects.event_date",expenseStart).lte("projects.event_date",end).order("created_at",{ascending:false}),
  admin.from("staff_settlement_financials").select("project_id,final_amount,paid_amount,sii_receipt_status,accounting_month").eq("staff_id",staffId).eq("accounting_month",`${month}-01`),
  admin.from("documents").select("id,project_id,document_type,operational_for_staff").eq("operational_for_staff",true).is("deleted_at",null),
  admin.from("staff_event_checkins").select("project_id,status").eq("staff_id",staffId),
  admin.from("internal_notifications").select("id,title,message,created_at").eq("staff_id",staffId).in("category",["OPERATIONS","STAFF"]).order("created_at",{ascending:false}).limit(12),
  admin.from("staff_available_event_projection").select("project_id,orbit_event_id,project_type,event_date,event_time,event_time_mode,city,access_instructions,services").gte("event_date",start).lte("event_date",end),
  admin.from("assignments").select("project_id,assignment_type,status").is("deleted_at",null).not("status","in",'(CANCELLED,REJECTED)'),
  admin.from("staff_assignment_requests").select("id,project_id,responsibility,status,requested_at,projects(name,customers(full_name))").eq("staff_id",staffId).order("requested_at",{ascending:false}).limit(30),
  admin.from("timeline_events").select("project_id,description").eq("staff_id",staffId).eq("action","STAFF_CHECKLIST_ITEM_COMPLETED"),
  admin.from("event_vehicle_assignments").select("project_id,operational_assets(asset_code,metadata)").eq("status","ASSIGNED").is("deleted_at",null),
  admin.from("cost_master_entries").select("code,amount").eq("enabled",true).is("deleted_at",null),
  admin.from("project_operational_contracts").select("project_id,contact_status,contact_first_name,contact_last_name,contact_phone,contact_role,service_start_at,service_end_at,staff_arrival_at,operational_notes,special_instructions,equipment_notes,setup_notes,emergency_notes"),
  admin.from("asset_assignments").select("project_id,operational_assets(asset_code)").eq("assignment_status","ASSIGNED").is("deleted_at",null),
  admin.from("event_staff_requirements").select("project_id,role,required_quantity,published").eq("published",true),
  admin.from("vehicle_trips").select("id,project_id,driver_staff_id,driver_name,trip_type,sequence,origin,destination,planned_start_at,planned_end_at,meeting_point,instructions,status,operational_assets(asset_code,vehicle_profiles(model)),staff(first_name,last_name)").eq("driver_staff_id",staffId).is("deleted_at",null).neq("status","CANCELLED").order("sequence"),
  admin.from("staff_expense_submissions").select("id,project_id,category,amount,occurred_on,description,status,rejection_reason").eq("staff_id",staffId).order("submitted_at",{ascending:false}).limit(30),
  admin.from("staff_monthly_accounts").select(STAFF_MONTHLY_ACCOUNT_SELECT).eq("staff_id",staffId).order("accounting_month",{ascending:false}),
]);const error=staffResult.error??assignmentsResult.error??paymentsResult.error??documentsResult.error??checkinsResult.error??notificationsResult.error??publicationsResult.error??allAssignmentsResult.error??requestsResult.error??checklistResult.error??vehiclesResult.error??costMasterResult.error??operationalContractsResult.error??physicalResourcesResult.error??staffRequirementsResult.error??logisticsTripsResult.error??expenseSubmissionsResult.error??monthlyAccountsResult.error;if(error)throw error;const monthlyMonths=[...new Set((monthlyAccountsResult.data??[]).map(row=>String(row.accounting_month)))];if(monthlyMonths.length){const refreshResults=await Promise.all(monthlyMonths.map(accountingMonth=>admin.rpc("ensure_staff_monthly_account",{p_staff_id:staffId,p_month:accountingMonth})));const refreshError=refreshResults.find(result=>result.error)?.error;if(refreshError)throw refreshError;}const canonicalMonthlyAccounts=monthlyMonths.length?((await admin.from("staff_monthly_accounts").select(STAFF_MONTHLY_ACCOUNT_SELECT).eq("staff_id",staffId).order("accounting_month",{ascending:false})).data??[]):[];
  const canonicalEvents=await getCanonicalOrbitEventStates(admin,[...(assignmentsResult.data??[]).map(row=>row.project_id)]);const grouped=new Map<string,{project:NonNullable<(typeof assignmentsResult.data)>[number]["projects"];roles:string[];status:string;resources:Record<string,unknown>}>();for(const row of assignmentsResult.data??[]){const current=grouped.get(row.project_id);if(current){if(!current.roles.includes(row.assignment_type))current.roles.push(row.assignment_type);if(["CONFIRMED","ACCEPTED","COMPLETED"].includes(row.status))current.status=row.status;}else grouped.set(row.project_id,{project:row.projects,roles:[row.assignment_type],status:row.status,resources:(row.resources??{})as Record<string,unknown>});}
  const events:StaffPortalEvent[]=[...grouped.entries()].map(([projectId,item])=>{const project=Array.isArray(item.project)?item.project[0]:item.project;const services=Array.isArray(project.project_services)?project.project_services:[];const customer=Array.isArray(project.customers)?project.customers[0]:project.customers;const contract=(operationalContractsResult.data??[]).find(row=>row.project_id===projectId);const canonical=canonicalEvents.get(projectId);const canonicalStart=canonical?operationalDateTime(canonical.serviceStartAt):{date:project.event_date,time:project.event_time?.slice(0,5)??""};const canonicalEnd=canonical?operationalDateTime(canonical.serviceEndAt):{date:canonicalStart.date,time:finish(canonicalStart.time,Number(services[0]?.duration_hours??4))};return{id:projectId,orbitEventId:project.orbit_event_id,customer:customer?.full_name??project.name,clientPhone:"Por confirmar",productionContact:"BOOMBOX Producción",productionPhone:"Por confirmar",eventType:project.project_type,service:services.map(row=>row.service_code).filter(Boolean).join(" + ")||"Servicio BOOMBOX",duration:Number(services[0]?.duration_hours??4),extras:[],date:canonicalStart.date,staffCallAt:canonical?.staffCallAt??null,start:canonicalStart.time,finish:canonicalEnd.time,timeMode:project.event_time_mode??"ESTIMATED",address:String(project.location??"Dirección por confirmar"),district:project.city??"Comuna por confirmar",venue:project.location??"Lugar por confirmar",roles:item.roles,net:Number((paymentsResult.data??[]).find(row=>row.project_id===projectId)?.final_amount??0),status:item.status,vehicle:"No asignado",logistics:[],equipment:[],operationalInformation:{observations:contract?.operational_notes??"",specialInstructions:contract?.special_instructions??"",equipmentNotes:contract?.equipment_notes??"",setupNotes:contract?.setup_notes??"",emergencyNotes:contract?.emergency_notes??""},documents:(documentsResult.data??[]).filter(row=>row.project_id===projectId).map(row=>({id:row.id,type:row.document_type})),checkins:(checkinsResult.data??[]).filter(row=>row.project_id===projectId).map(row=>row.status),checklist:(checklistResult.data??[]).filter(row=>row.project_id===projectId).map(row=>row.description)};});
  const skills=staffResult.data?.capabilities??[],officialRates=new Map((costMasterResult.data??[]).map(item=>[item.code,Number(item.amount)]));const occupied=new Map<string,Map<string,number>>();for(const row of allAssignmentsResult.data??[]){const counts=occupied.get(row.project_id)??new Map<string,number>();counts.set(row.assignment_type,(counts.get(row.assignment_type)??0)+1);occupied.set(row.project_id,counts)}const availableEvents:AvailableStaffEvent[]=(publicationsResult.data??[]).flatMap(row=>{const services=(Array.isArray(row.services)?row.services:[])as {code?:string;durationHours?:number;quantity?:number}[],taken=occupied.get(row.project_id)??new Map<string,number>(),requirements=(staffRequirementsResult.data??[]).filter(item=>item.project_id===row.project_id&&OPERATIONAL_ROLES.includes(item.role as (typeof OPERATIONAL_ROLES)[number])),available=requirements.filter(item=>skills.includes(item.role)&&(taken.get(item.role)??0)<item.required_quantity).map(item=>item.role);if(skills.includes("ASSEMBLY")&&skills.includes("DISASSEMBLY")&&available.includes("ASSEMBLY")&&available.includes("DISASSEMBLY"))available.push("ASSEMBLY_DISASSEMBLY");if(!available.length)return[];const hours=Number(services[0]?.durationHours??0),startTime=row.event_time?.slice(0,5)??"";return[{id:row.project_id,orbitEventId:row.orbit_event_id,eventType:row.project_type,customer:"Evento BOOMBOX",clientPhone:"Disponible después de confirmación",productionContact:"Disponible después de confirmación",productionPhone:"Disponible después de confirmación",service:services.map(value=>`${Number(value.quantity??1)} × ${value.code??"Servicio"}`).join(" + ")||"Servicio BOOMBOX",duration:hours,date:row.event_date,staffCallAt:null,start:startTime,finish:finish(startTime,hours),timeMode:row.event_time_mode??"ESTIMATED",address:"Disponible después de confirmación",district:row.city??"Zona por confirmar",venue:row.city??"Zona por confirmar",vehicle:"Disponible después de confirmación",equipment:[],available,payments:{operator:officialRates.get(`OPERATOR_${hours}_HOURS`)??0,assembly:officialRates.get("ASSEMBLY")??0,disassembly:officialRates.get("DISASSEMBLY")??0,combined:officialRates.get("ASSEMBLY_DISASSEMBLY")??0,transportationBonus:0}}]}).sort((a,b)=>a.date.localeCompare(b.date));
  const requests:StaffRequest[]=(requestsResult.data??[]).map(row=>{const project=Array.isArray(row.projects)?row.projects[0]:row.projects;const customer=project?(Array.isArray(project.customers)?project.customers[0]:project.customers):null;return{id:row.id,projectId:row.project_id,customer:customer?.full_name??project?.name??"Evento",responsibility:row.responsibility,status:row.status,requestedAt:row.requested_at}});
  const generated=(paymentsResult.data??[]).reduce((sum,row)=>sum+Number(row.final_amount),0),paid=(paymentsResult.data??[]).reduce((sum,row)=>sum+Number(row.paid_amount),0),receipts=(paymentsResult.data??[]);const payment={generated,paid,pending:Math.max(0,generated-paid),receiptStatus:receipts.length&&receipts.every(row=>row.sii_receipt_status==="RECEIVED")?"Recibida":"Pendiente"};const notifications=(notificationsResult.data??[]).map(row=>({id:row.id,title:row.title,message:row.message,date:new Date(row.created_at).toLocaleString("es-CL")}));const expenseSubmissions:StaffExpenseSubmission[]=(expenseSubmissionsResult.data??[]).map(row=>({id:row.id,projectId:row.project_id,category:row.category,amount:Number(row.amount),occurredOn:row.occurred_on,description:row.description??"",status:row.status,rejectionReason:row.rejection_reason??""}));const monthlyAccounts:StaffMonthlyAccount[]=(canonicalMonthlyAccounts.length?canonicalMonthlyAccounts:monthlyAccountsResult.data??[]).map(row=>mapStaffMonthlyAccount(row));const staffName=staffResult.data?`${staffResult.data.first_name} ${staffResult.data.last_name}`:"Colaborador";return <main className="min-h-screen bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-7xl"><div className="mb-4 flex justify-end"><form action={portalLogoutAction.bind(null,"STAFF")}><button className="min-h-11 rounded-xl border px-4 text-sm font-medium">Cerrar sesión</button></form></div><StaffPortalDashboard expenseSubmissions={expenseSubmissions} availableEvents={availableEvents} events={events} monthlyAccounts={monthlyAccounts} mustChangePassword={Boolean(staffResult.data?.portal_password_change_required)} name={staffName} notifications={notifications} payment={payment} requests={requests}/></div></main>}
