"use client";

import {useState,useTransition} from "react";
import {CalendarDays,Clock3,MapPin} from "lucide-react";
import {claimResponsibilityAction} from "./staff-portal.actions";

export type PortalEvent={id:string;customer:string;eventType:string;service:string;address:string;district:string;venue:string;date:string;start:string;finish:string;slots:Array<{role:"OPERATOR"|"ASSEMBLY"|"DISASSEMBLY";label:string;pay:number;owner:string|null;mine:boolean;eligible:boolean}>};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);

export function StaffEventBoard({events}:{events:PortalEvent[]}){
  const[pending,start]=useTransition();const[notice,setNotice]=useState("");
  const take=(eventId:string,role:string)=>start(async()=>{const result=await claimResponsibilityAction(eventId,role);setNotice(result.message);if(result.ok)location.reload();});
  return <section className="rounded-3xl border bg-card p-5 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Próximos 15 días</p><h2 className="mt-2 text-xl font-semibold">Mis próximos eventos</h2><p className="mt-1 text-sm text-muted">Toma únicamente las responsabilidades habilitadas en tu perfil.</p></div>{notice&&<p className="mt-4 rounded-xl border border-brand/20 bg-brand/10 p-3 text-sm" role="status">{notice}</p>}<div className="mt-5 grid gap-4">{events.length?events.map(event=><article className="rounded-2xl border p-4 sm:p-5" key={event.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold">{event.customer}</h3><p className="mt-1 text-sm text-muted">{event.eventType} · {event.service}</p></div><a className="text-sm font-semibold text-brand" href={`#event-${event.id}`}>Ver evento</a></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><p><CalendarDays className="mr-2 inline size-4 text-brand"/>{event.date}</p><p><Clock3 className="mr-2 inline size-4 text-brand"/>{event.start}–{event.finish}</p><p><MapPin className="mr-2 inline size-4 text-brand"/>{event.venue} · {event.district}</p></div><p className="mt-2 text-sm text-muted">{event.address}</p><div className="mt-4 grid gap-3 md:grid-cols-3">{event.slots.map(slot=><div className="rounded-xl border bg-background/40 p-3" key={slot.role}><div className="flex justify-between gap-2"><span className="text-sm font-medium">{slot.label}</span><span className="text-sm font-semibold">{money(slot.pay)}</span></div>{slot.mine?<p className="mt-3 text-sm font-semibold text-emerald-500">Asignado a ti</p>:slot.owner?<p className="mt-3 text-sm text-muted">Tomado · {slot.owner}</p>:slot.eligible?<button className="mt-3 min-h-10 w-full rounded-lg bg-brand px-3 text-sm font-semibold text-brand-foreground disabled:opacity-50" disabled={pending} onClick={()=>take(event.id,slot.role)}>Tomar {slot.label}</button>:<p className="mt-3 text-sm text-muted">No habilitado</p>}</div>)}</div></article>):<p className="py-8 text-center text-sm text-muted">No hay eventos disponibles durante los próximos 15 días.</p>}</div></section>;
}
