import "server-only";
import {CalendarDays,ReceiptText,WalletCards} from "lucide-react";
import {createAdminClient} from "@/lib/supabase/admin";
import {portalLogoutAction} from "./actions";
import {StaffEventBoard,type PortalEvent} from "./staff-event-board";

const ROLES=[{code:"OPERATOR" as const,label:"Operador"},{code:"ASSEMBLY" as const,label:"Montaje"},{code:"DISASSEMBLY" as const,label:"Desmontaje"}];
const todayKey=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago"}).format(new Date());
const plusDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
const finishTime=(time:string,hours:number)=>{const[h,m]=time.slice(0,5).split(":").map(Number);const total=h*60+m+hours*60;return`${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);

export async function StaffPortal({staffId}:{staffId:string}){
  const admin=createAdminClient(),today=todayKey(),end=plusDays(today,15);
  const[staffResult,projectsResult,assignmentsResult,paymentsResult,costsResult]=await Promise.all([
    admin.from("staff").select("first_name,last_name,capabilities,status").eq("id",staffId).single(),
    admin.from("projects").select("id,name,project_type,event_date,event_time,location,city,operations,customers(full_name),project_services(service_code,duration_hours,extras)").gte("event_date",today).lte("event_date",end).is("deleted_at",null).not("status","in",'(Archived,Cancelled,CANCELLED)').order("event_date"),
    admin.from("assignments").select("project_id,staff_id,assignment_type,status,staff(first_name,last_name)").is("deleted_at",null).not("status","in",'(CANCELLED,REJECTED)'),
    admin.from("event_staff_payments").select("id,project_id,total_internal_payment,settlement_status,paid_amount,sii_receipt_status,projects(name,event_date)").eq("staff_id",staffId).is("deleted_at",null).order("created_at",{ascending:false}),
    admin.from("cost_master_entries").select("code,amount").eq("enabled",true).is("deleted_at",null),
  ]);
  const error=staffResult.error??projectsResult.error??assignmentsResult.error??paymentsResult.error??costsResult.error;if(error)throw error;
  const staff=staffResult.data,projects=projectsResult.data??[],assignments=assignmentsResult.data??[],payments=paymentsResult.data??[];
  const capabilities=new Set<string>(staff?.capabilities??[]),costMap=new Map((costsResult.data??[]).map(x=>[x.code,Number(x.amount)]));
  const events:PortalEvent[]=projects.map(row=>{const services=Array.isArray(row.project_services)?row.project_services:[];const hours=Math.max(2,Math.min(10,Number(services[0]?.duration_hours??4)));const ops=(row.operations??{}) as Record<string,unknown>;const customer=Array.isArray(row.customers)?row.customers[0]:row.customers;return{id:row.id,customer:customer?.full_name??row.name,eventType:row.project_type,service:services.map(x=>x.service_code).filter(Boolean).join(" + ")||"Servicio BOOMBOX",address:row.location??"Dirección por confirmar",district:row.city??"Comuna por confirmar",venue:String(ops.venue??ops.venueName??row.location??"Lugar por confirmar"),date:row.event_date,start:row.event_time?.slice(0,5)??"00:00",finish:finishTime(row.event_time??"00:00",hours),slots:ROLES.map(role=>{const occupied=assignments.find(a=>a.project_id===row.id&&a.assignment_type===role.code);const owner=occupied?.staff?(Array.isArray(occupied.staff)?occupied.staff[0]:occupied.staff):null;return{role:role.code,label:role.label,pay:costMap.get(role.code==="OPERATOR"?`OPERATOR_${hours}_HOURS`:role.code)??0,owner:owner?`${owner.first_name} ${owner.last_name}`:null,mine:occupied?.staff_id===staffId,eligible:capabilities.has(role.code)}})}});
  const net=payments.reduce((sum,p)=>sum+Number(p.total_internal_payment),0),paid=payments.reduce((sum,p)=>sum+Number(p.paid_amount),0),receiptPending=payments.filter(p=>p.sii_receipt_status!=="RECEIVED").length;
  return <main className="min-h-screen bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 rounded-3xl border bg-card p-6 sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Portal Staff</p><h1 className="mt-2 text-3xl font-semibold">Hola, {staff?.first_name}.</h1><p className="mt-2 text-muted">Eventos, responsabilidades y pagos BOOMBOX.</p></div><form action={portalLogoutAction.bind(null,"STAFF")}><button className="min-h-11 rounded-xl border px-4 text-sm font-medium">Cerrar sesión</button></form></header><section className="grid gap-4 md:grid-cols-3"><Card icon={CalendarDays} title="Eventos próximos" value={String(events.length)}/><Card icon={WalletCards} title="Pago neto acumulado" value={money(net)}/><Card icon={ReceiptText} title="Boletas SII pendientes" value={String(receiptPending)}/></section><StaffEventBoard events={events}/><section className="rounded-3xl border bg-card p-5 sm:p-7"><h2 className="text-xl font-semibold">Historial y liquidación mensual</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-muted"><tr><th className="pb-3">Evento</th><th className="pb-3">Fecha</th><th className="pb-3">Neto</th><th className="pb-3">Pago</th><th className="pb-3">Boleta SII</th></tr></thead><tbody>{payments.map(item=>{const project=Array.isArray(item.projects)?item.projects[0]:item.projects;return <tr className="border-t" key={item.id}><td className="py-3">{project?.name}</td><td>{project?.event_date}</td><td>{money(Number(item.total_internal_payment))}</td><td>{item.settlement_status==="PAID"?"Pagado":item.settlement_status==="ADVANCE"?"Anticipo":"Pendiente"}</td><td>{item.sii_receipt_status==="RECEIVED"?"Recibida":"Pendiente"}</td></tr>})}</tbody></table></div><div className="mt-5 flex flex-wrap gap-5 border-t pt-4 text-sm"><p>Neto: <strong>{money(net)}</strong></p><p>Pagado: <strong>{money(paid)}</strong></p><p>Saldo: <strong>{money(net-paid)}</strong></p><p>Retención SII: <strong>15,25%</strong></p></div></section></div></main>;
}
function Card({icon:Icon,title,value}:{icon:typeof CalendarDays;title:string;value:string}){return <article className="rounded-2xl border bg-card p-5"><Icon className="size-5 text-brand"/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-muted">{title}</p></article>}
