"use server";
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { createSupabaseServerActionClient } from "@/lib/supabase/server";
import { extractBankReceipt } from "./receipt-extractor";

type Result={ok:true;id:string}|{ok:false;error:string};
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export async function importBankReceiptAction(formData:FormData):Promise<Result>{
 try{
  const client=await createSupabaseServerActionClient();const{data:auth}=await client.auth.getUser();if(!auth.user)throw new Error("Sesión requerida.");
  const file=formData.get("receipt");const accountId=String(formData.get("bankAccountId")??"");if(!(file instanceof File)||!file.size)throw new Error("Selecciona un comprobante.");if(file.size>15*1024*1024)throw new Error("El archivo no puede superar 15 MB.");if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("Formato no compatible.");
  const bytes=Buffer.from(await file.arrayBuffer());const checksum=createHash("sha256").update(bytes).digest("hex");const ext=file.name.split(".").pop()?.toLowerCase()||"bin";const path=`bank-reconciliation/${auth.user.id}/${crypto.randomUUID()}.${ext}`;
  const{error:uploadError}=await client.storage.from("orbit-documents").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;
  let extraction;let extractionError="";try{extraction=await extractBankReceipt(file);}catch(error){extractionError=error instanceof Error?error.message:"Extracción no disponible";extraction={transferDate:null,transferTime:null,amount:null,originBank:null,transferHolder:null,reference:null,destinationAccount:null,confidence:0};}
  const{data:created,error:createError}=await client.from("bank_reconciliation_imports").insert({bank_account_id:accountId,original_document_path:path,original_document_name:file.name,mime_type:file.type,checksum,transfer_date:extraction.transferDate,transfer_time:extraction.transferTime,amount:extraction.amount,origin_bank:extraction.originBank,transfer_holder:extraction.transferHolder,reference:extraction.reference,destination_account:extraction.destinationAccount,extraction_confidence:extraction.confidence,extraction_payload:{...extraction,extractionError},status:extraction.amount?"SUGGESTED":"REVIEW_REQUIRED",uploaded_by:auth.user.id}).select("id").single();if(createError)throw createError;
  const{data:invoices,error:invoiceError}=await client.from("accounts_receivable_projection").select("id,project_id,customer_id,invoice_number,amount,paid_amount,due_date,status,customers(full_name,company),projects(name,event_date)").not("status","in",'(CANCELLED,ARCHIVED)').gt("outstanding_balance",0);if(invoiceError)throw invoiceError;
  // Supabase relation inference is dynamic for this security-invoker view.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const holder=normalize(extraction.transferHolder??"");const ref=normalize(extraction.reference??"");const ranked=(invoices??[]).map((inv:any)=>{let score=0;const reasons:string[]=[];const outstanding=Number(inv.amount)-Number(inv.paid_amount);if(extraction.amount===outstanding){score+=65;reasons.push("Monto exacto");}else if(extraction.amount&&Math.abs(extraction.amount-outstanding)/Math.max(outstanding,1)<=.05){score+=35;reasons.push("Monto cercano");}const customer=Array.isArray(inv.customers)?inv.customers[0]:inv.customers;const project=Array.isArray(inv.projects)?inv.projects[0]:inv.projects;const names=normalize(`${customer?.full_name??""} ${customer?.company??""}`);if(holder&&names.split(" ").some((part:string)=>part.length>3&&holder.includes(part))){score+=20;reasons.push("Titular coincide");}if(ref&&normalize(`${inv.invoice_number} ${project?.name??""}`).split(" ").some((part:string)=>part.length>3&&ref.includes(part))){score+=15;reasons.push("Referencia coincide");}return{inv,score,reasons};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,5);
  if(ranked.length){const{error}=await client.from("bank_reconciliation_candidates").insert(ranked.map((x,index)=>({import_id:created.id,invoice_id:x.inv.id,customer_id:x.inv.customer_id,project_id:x.inv.project_id,score:x.score,reasons:x.reasons,candidate_rank:index+1})));if(error)throw error;}
  await client.from("bank_reconciliation_audit").insert({import_id:created.id,action:"DOCUMENT_IMPORTED",actor_id:auth.user.id,new_state:{path,fileName:file.name,extraction,candidates:ranked.length}});
  revalidatePath("/finance/banking");return{ok:true,id:created.id};
 }catch(error){return{ok:false,error:error instanceof Error?error.message:"No fue posible importar el comprobante."};}
}

export async function saveRecurringExpenseRuleAction(formData:FormData):Promise<{ok:boolean;error?:string}>{try{const client=await createSupabaseServerActionClient();const{data:auth}=await client.auth.getUser();if(!auth.user)throw new Error("Sesión requerida.");const id=String(formData.get("id")??"");const payload={bank_account_id:String(formData.get("bankAccountId")||"")||null,name:String(formData.get("name")||""),category:String(formData.get("category")||"ADMINISTRATION"),amount:Number(formData.get("amount")),frequency:String(formData.get("frequency")||"MONTHLY"),due_day:Number(formData.get("dueDay")||1),next_due_date:String(formData.get("nextDueDate")),active:formData.get("active")==="on",updated_by:auth.user.id};const query=id?client.from("finance_recurring_expense_rules").update(payload).eq("id",id):client.from("finance_recurring_expense_rules").insert({...payload,created_by:auth.user.id});const{error}=await query;if(error)throw error;revalidatePath("/finance/banking");revalidatePath("/settings");return{ok:true};}catch(error){return{ok:false,error:error instanceof Error?error.message:"No fue posible guardar."};}}
