import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { BankingReadModel,ReconciliationCandidate } from "./types";

type Row=Record<string,unknown>;
const n=(v:unknown)=>Number(v??0);
export async function loadBankingReadModel(client:SupabaseClient):Promise<BankingReadModel>{
  await client.rpc("generate_recurring_finance_expenses",{p_as_of:new Date().toISOString().slice(0,10)});
  const [accounts,imports,rules,mp]=await Promise.all([
    client.from("finance_bank_accounts").select("id,code,name,account_kind,account_type,bank_name,is_primary,active").order("is_primary",{ascending:false}),
    client.from("bank_reconciliation_imports").select("id,original_document_name,status,transfer_date,transfer_time,amount,origin_bank,transfer_holder,reference,destination_account,extraction_confidence,created_at,bank_reconciliation_candidates(invoice_id,project_id,customer_id,score,reasons,candidate_rank,invoices(invoice_number,amount,paid_amount),customers(full_name),projects(name))").order("created_at",{ascending:false}).limit(20),
    client.from("finance_recurring_expense_rules").select("id,bank_account_id,name,provider,category,amount,currency,frequency,due_day,next_due_date,active").order("name"),
    client.from("mercado_pago_transactions").select("gross_amount,fee_amount,net_amount,settlement_status,transfer_status,project_id")
  ]);
  for(const result of [accounts,imports,rules,mp])if(result.error)throw result.error;
  const mappedImports=(imports.data??[]).map((raw:Row)=>{const candidates=((raw.bank_reconciliation_candidates??[]) as Row[]).sort((a,b)=>n(a.candidate_rank)-n(b.candidate_rank));const c=candidates[0];const invoice=(Array.isArray(c?.invoices)?c?.invoices[0]:c?.invoices) as Row|undefined;const customer=(Array.isArray(c?.customers)?c?.customers[0]:c?.customers) as Row|undefined;const project=(Array.isArray(c?.projects)?c?.projects[0]:c?.projects) as Row|undefined;const candidate:ReconciliationCandidate|null=c?{invoiceId:String(c.invoice_id),projectId:String(c.project_id),customerId:String(c.customer_id),customer:String(customer?.full_name??"Cliente"),event:String(project?.name??"Evento"),invoiceNumber:String(invoice?.invoice_number??""),outstanding:Math.max(0,n(invoice?.amount)-n(invoice?.paid_amount)),score:n(c.score),reasons:(c.reasons as string[])??[]}:null;return{id:String(raw.id),fileName:String(raw.original_document_name),status:String(raw.status),transferDate:raw.transfer_date?String(raw.transfer_date):null,transferTime:raw.transfer_time?String(raw.transfer_time):null,amount:raw.amount==null?null:n(raw.amount),originBank:raw.origin_bank?String(raw.origin_bank):null,holder:raw.transfer_holder?String(raw.transfer_holder):null,reference:raw.reference?String(raw.reference):null,destination:raw.destination_account?String(raw.destination_account):null,confidence:raw.extraction_confidence==null?null:n(raw.extraction_confidence),candidate,createdAt:String(raw.created_at)}});
  const mpRows=(mp.data??[]) as Row[];
  return {accounts:(accounts.data??[]).map((r:Row)=>({id:String(r.id),code:String(r.code),name:String(r.name),accountKind:String(r.account_kind),accountType:r.account_type?String(r.account_type):null,bankName:r.bank_name?String(r.bank_name):null,primary:Boolean(r.is_primary),active:Boolean(r.active)})),imports:mappedImports,recurringRules:(rules.data??[]).map((r:Row)=>({id:String(r.id),name:String(r.name),provider:r.provider?String(r.provider):null,category:String(r.category),amount:n(r.amount),currency:String(r.currency??"CLP") as "CLP"|"USD",frequency:String(r.frequency),dueDay:n(r.due_day),nextDueDate:String(r.next_due_date),active:Boolean(r.active),bankAccountId:r.bank_account_id?String(r.bank_account_id):null})),mercadoPago:{currentBalance:mpRows.filter(r=>String(r.transfer_status)!=="TRANSFERRED").reduce((s,r)=>s+n(r.net_amount),0),pendingTransfers:mpRows.filter(r=>String(r.transfer_status)==="PENDING").reduce((s,r)=>s+n(r.net_amount),0),transferredAmount:mpRows.filter(r=>String(r.transfer_status)==="TRANSFERRED").reduce((s,r)=>s+n(r.net_amount),0),fees:mpRows.reduce((s,r)=>s+n(r.fee_amount),0),netAmount:mpRows.reduce((s,r)=>s+n(r.net_amount),0),associatedEvents:new Set(mpRows.map(r=>r.project_id).filter(Boolean)).size}};
}
