"use client";

import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Check, ChevronLeft, ChevronRight, LoaderCircle, Sparkles } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { Button } from "@/components/ui/button";

type Service = { code: string; name: string; configuration: Record<string, unknown> };
type Price = { category: string; code: string; duration_hours: number | null; unit_price: number; rules: Record<string, unknown> };
type Venue = { name: string; municipality: string; province: string };
const money = (value: number) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value);
const terms = ["La fecha queda reservada una vez firmado el contrato y recibido el pago de reserva.", "El saldo restante debe pagarse durante la semana previa al evento.", "El horario contratado no se extiende por atrasos propios del evento.", "El cliente debe asegurar acceso, espacio y conexión eléctrica adecuados.", "El traslado se calcula según la ubicación seleccionada.", "BOOMBOX puede suspender el servicio ante riesgos para personas o equipos.", "El material digital se entrega según los plazos informados por BOOMBOX."];

export function AutomaticBookingExperience({ email, prices, services, token, venues }: { email: string; prices: Price[]; services: Service[]; token: string; venues: Venue[] }) {
  const [step, setStep] = useState(0); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{ portalUrl: string; total: number } | null>(null);
  const [customer, setCustomer] = useState({ name: "", rut: "", phone: "+569", email, address: "" });
  const [event, setEvent] = useState({ type: "Wedding", date: "", time: "18:00", venue: "", address: "", municipality: "", operationalContact: "", operationalPhone: "+569" });
  const [service, setService] = useState({ code: "", hours: 2, extras: [] as string[], brandingQuantity: 2 });
  const [termsAccepted, setTermsAccepted] = useState(false); const [signature, setSignature] = useState("");
  const [payment, setPayment] = useState({ method: "TRANSFER" as "TRANSFER" | "MERCADO_PAGO", receiptName: "", receiptType: "", receiptBase64: "" });
  const selectedService = services.find((item) => item.code === service.code); const compatible = Array.isArray(selectedService?.configuration.compatibleExtras) ? selectedService.configuration.compatibleExtras as string[] : [];
  const quote = useMemo(() => { const rows = prices.filter((item) => item.category === "SERVICE" && item.code === service.code); const base = rows.find((item) => item.duration_hours === service.hours)?.unit_price ?? rows[0]?.unit_price ?? 0; const extraMap: Record<string,string>={QR:"QR",Branding:"BRANDING",Imanes:"UNLIMITED_MAGNETS",Scrapbook:"SCRAPBOOK"}; const extras=service.extras.reduce((sum,item)=>sum+(prices.find(price=>price.category==="EXTRA"&&price.code===extraMap[item])?.unit_price??(item==="Scrapbook"?50000:0))*(item==="Branding"?service.brandingQuantity:1),0);const transport=prices.find(price=>price.category==="TRANSPORT"&&Array.isArray(price.rules.municipalities)&&(price.rules.municipalities as string[]).includes(event.municipality))?.unit_price??0;const subtotal=base+extras+transport;const total=Math.round(subtotal*(payment.method==="MERCADO_PAGO"?1.05:1));return{base,extras,transport,total,reservation:Math.round(total/2)};},[event.municipality,payment.method,prices,service]);
  const valid = step===0?Boolean(customer.name&&/^[0-9]{7,8}-[0-9K]$/i.test(customer.rut)&&/^\+569\d{8}$/.test(customer.phone)):step===1?Boolean(event.date&&event.time&&event.venue&&event.address&&event.municipality&&event.operationalContact&&/^\+569\d{8}$/.test(event.operationalPhone)):step===2?Boolean(service.code&&quote.total>0):step===3?termsAccepted&&Boolean(signature):step===4?Boolean(payment.receiptBase64):false;
  const chooseVenue=(name:string)=>{const venue=venues.find(item=>item.name===name);setEvent(current=>({...current,venue:name,municipality:venue?.municipality??current.municipality}));};
  const toggleExtra=(extra:string)=>setService(current=>({...current,extras:current.extras.includes(extra)?current.extras.filter(item=>item!==extra):[...current.extras,extra]}));
  const confirm=async()=>{setPending(true);setError("");try{const response=await fetch(`/api/booking/${encodeURIComponent(token)}/confirm`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,event,service,payment,signatureDataUrl:signature})});const body=await response.json() as {ok:boolean;message?:string;portalUrl?:string;total?:number};if(!response.ok||!body.ok||!body.portalUrl)throw new Error(body.message);setResult({portalUrl:body.portalUrl,total:Number(body.total??quote.total)});setStep(5);}catch(cause){setError(cause instanceof Error&&cause.message?cause.message:"No pudimos completar tu reserva.");}finally{setPending(false)}};
  return <main className="min-h-screen bg-background px-4 py-6 text-foreground sm:py-10"><div className="mx-auto max-w-5xl"><BrandLogo className="mx-auto h-16 w-52" priority surface="dark"/><header className="mt-8 text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Reserva Automática BOOMBOX</p><h1 className="mt-3 text-3xl font-semibold sm:text-5xl">Tu evento, paso a paso.</h1><p className="mt-3 text-muted">Una sola acción clara en cada etapa.</p></header><div className="mt-8 flex gap-2">{["Tus datos","Evento","Servicio","Contrato","Pago","Listo"].map((label,index)=><div className="flex-1" key={label}><div className={`h-1.5 rounded-full ${index<=step?"bg-brand":"bg-border"}`}/><p className="mt-2 hidden text-center text-xs text-muted sm:block">{label}</p></div>)}</div><section className="mt-7 rounded-3xl border bg-card p-5 sm:p-8">
  {step===0&&<Step title="Cuéntanos quién eres"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre y Apellido" value={customer.name} onChange={value=>setCustomer({...customer,name:value})}/><Field label="RUT" value={customer.rut} onChange={value=>{const raw=value.replace(/[^0-9K]/gi,"").toUpperCase().slice(0,9);setCustomer({...customer,rut:raw.length>1?`${raw.slice(0,-1)}-${raw.slice(-1)}`:raw})}}/><Field label="Teléfono" value={customer.phone} onChange={value=>setCustomer({...customer,phone:`+569${value.replace(/\D/g,"").replace(/^569/,"").slice(0,8)}`})}/><Field disabled label="Correo" value={customer.email} onChange={()=>{}}/><Field label="Dirección" value={customer.address} onChange={value=>setCustomer({...customer,address:value})}/></div></Step>}
  {step===1&&<Step title="Información de tu evento"><div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo de Evento" value={event.type} onChange={value=>setEvent({...event,type:value})} options={["Wedding","Corporate","Birthday","Graduation","Private","Other"]}/><Field label="Fecha" type="date" value={event.date} onChange={value=>setEvent({...event,date:value})}/><Field label="Hora de inicio" type="time" value={event.time} onChange={value=>setEvent({...event,time:value})}/><div><Field label="Venue" list="booking-venues" value={event.venue} onChange={chooseVenue}/><datalist id="booking-venues">{venues.map(item=><option key={item.name} value={item.name}/>)}</datalist></div><Field label="Dirección del evento" value={event.address} onChange={value=>setEvent({...event,address:value})}/><Field label="Municipalidad" value={event.municipality} onChange={value=>setEvent({...event,municipality:value})}/><Field label="Contacto operacional" value={event.operationalContact} onChange={value=>setEvent({...event,operationalContact:value})}/><Field label="Teléfono operacional" value={event.operationalPhone} onChange={value=>setEvent({...event,operationalPhone:`+569${value.replace(/\D/g,"").replace(/^569/,"").slice(0,8)}`})}/></div></Step>}
  {step===2&&<Step title="Elige tu experiencia"><div className="grid gap-6 lg:grid-cols-[1fr_20rem]"><div><div className="grid gap-3 sm:grid-cols-2">{services.map(item=><button className={`rounded-2xl border p-4 text-left ${service.code===item.code?"border-brand bg-brand/5":""}`} key={item.code} onClick={()=>setService(current=>({...current,code:item.code,hours:Number(item.configuration.minimumHours??2),extras:[]}))} type="button"><strong>{item.name}</strong></button>)}</div>{service.code&&<><Select label="Horas" value={String(service.hours)} onChange={value=>setService({...service,hours:Number(value)})} options={Array.from({length:Math.max(1,Number(selectedService?.configuration.maximumHours??service.hours)-Number(selectedService?.configuration.minimumHours??service.hours)+1)},(_,index)=>String(Number(selectedService?.configuration.minimumHours??service.hours)+index))}/><div className="mt-4 grid gap-2 sm:grid-cols-2">{[["QR","QR"],["BRANDING","Branding"],["UNLIMITED_MAGNETS","Imanes"],["SCRAPBOOK","Scrapbook"]].filter(([code])=>compatible.includes(code)).map(([,label])=><label className="flex items-center gap-3 rounded-xl border p-4" key={label}><input checked={service.extras.includes(label)} onChange={()=>toggleExtra(label)} type="checkbox"/>{label}</label>)}</div></>}</div><Summary quote={quote} service={selectedService?.name}/></div></Step>}
  {step===3&&<Step title="Revisa y firma tu contrato"><Summary quote={quote} service={selectedService?.name}/><div className="mt-6 max-h-56 space-y-4 overflow-y-auto rounded-xl border p-5" tabIndex={0}>{terms.map((item,index)=><p className="text-sm leading-6 text-muted" key={item}><strong>{index+1}.</strong> {item}</p>)}</div><label className="mt-5 flex gap-3 rounded-xl border p-4"><input checked={termsAccepted} onChange={event=>setTermsAccepted(event.target.checked)} type="checkbox"/>He leído y acepto los Términos y Condiciones.</label>{termsAccepted&&<Signature onChange={setSignature}/>}</Step>}
  {step===4&&<Step title="Confirma el pago"><Summary quote={quote} service={selectedService?.name}/><div className="mt-6 grid grid-cols-2 gap-3"><Button onClick={()=>setPayment({...payment,method:"TRANSFER"})} variant={payment.method==="TRANSFER"?"default":"outline"}>Transferencia</Button><Button onClick={()=>setPayment({...payment,method:"MERCADO_PAGO"})} variant={payment.method==="MERCADO_PAGO"?"default":"outline"}>Mercado Pago +5%</Button></div>{payment.method==="TRANSFER"&&<div className="mt-5 rounded-xl border p-4 text-sm"><strong>PRODUCCIONES BOOMBOX COMPANY SPA</strong><p className="mt-2 text-muted">RUT 76.565.272-3 · Banco BCI · Cuenta Corriente 52093409 · contabilidad@boom-box.cl</p></div>}<label className="mt-5 block font-medium">Comprobante<input accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-2 block w-full rounded-xl border p-3" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const base64=await fileBase64(file);setPayment({...payment,receiptName:file.name,receiptType:file.type,receiptBase64:base64})}} type="file"/></label></Step>}
  {step===5&&result&&<div className="py-8 text-center"><div className="text-5xl">🎉</div><h2 className="mt-5 text-3xl font-semibold">¡Reserva Confirmada!</h2><div className="mx-auto mt-6 grid max-w-xl gap-3 text-left sm:grid-cols-2">{["Contrato Firmado","Reserva Confirmada","Portal Disponible","Correo Enviado"].map(item=><div className="flex gap-3 rounded-xl border p-4" key={item}><Check className="size-5 text-success"/>{item}</div>)}</div><p className="mt-6 text-xl font-semibold">TOTAL {money(result.total)}</p><a className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-brand px-6 font-semibold text-brand-foreground" href={result.portalUrl}>Abrir mi Portal BOOMBOX</a></div>}
  {error&&<p className="mt-5 rounded-xl border border-danger/30 bg-danger/5 p-4 text-sm text-danger" role="alert">{error}</p>}</section>{step<5&&<footer className="mt-5 flex justify-between"><Button disabled={step===0||pending} onClick={()=>setStep(current=>current-1)} variant="outline"><ChevronLeft className="size-4"/>Atrás</Button>{step<4?<Button disabled={!valid} onClick={()=>setStep(current=>current+1)}>Continuar<ChevronRight className="size-4"/></Button>:<Button disabled={!valid||pending} onClick={()=>void confirm()}>{pending?<LoaderCircle className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}{pending?"Confirmando reserva…":"Confirmar Reserva"}</Button>}</footer>}</div></main>;
}

function Step({title,children}:{title:string;children:React.ReactNode}){return <div><h2 className="mb-6 text-2xl font-semibold">{title}</h2>{children}</div>}
function Field({label,value,onChange,type="text",...props}:{label:string;value:string;onChange:(value:string)=>void;type?:string}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"value"|"onChange"|"type">){return <label className="block text-sm font-medium">{label}<input className="mt-2 h-12 w-full rounded-xl border bg-background px-4" onChange={event=>onChange(event.target.value)} type={type} value={value} {...props}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label className="mt-4 block text-sm font-medium">{label}<select className="mt-2 h-12 w-full rounded-xl border bg-background px-4" onChange={event=>onChange(event.target.value)} value={value}>{options.map(item=><option key={item} value={item}>{item}</option>)}</select></label>}
function Summary({quote,service}:{quote:{base:number;extras:number;transport:number;total:number;reservation:number};service?:string}){return <aside className="rounded-2xl border bg-background/40 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-brand">Resumen Comercial</p><dl className="mt-4 space-y-3 text-sm"><Row label={service??"Servicio"} value={money(quote.base)}/><Row label="Extras" value={money(quote.extras)}/><Row label="Transporte" value={money(quote.transport)}/><Row label="Reserva" value={money(quote.reservation)}/><Row label="Saldo" value={money(quote.total-quote.reservation)}/><Row label="TOTAL" value={money(quote.total)}/></dl></aside>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3 border-b border-border/60 pb-2 last:border-0"><dt>{label}</dt><dd className="font-semibold">{value}</dd></div>}
function Signature({onChange}:{onChange:(value:string)=>void}){const ref=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);const point=(event:ReactPointerEvent<HTMLCanvasElement>)=>{const canvas=event.currentTarget;const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*(canvas.width/rect.width),y:(event.clientY-rect.top)*(canvas.height/rect.height)}};return <div className="mt-5"><p className="mb-2 text-sm font-medium">Firma</p><canvas className="h-44 w-full touch-none rounded-xl border bg-white" height={352} onPointerDown={event=>{drawing.current=true;event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);const context=event.currentTarget.getContext("2d");context?.beginPath();context?.moveTo(p.x,p.y)}} onPointerMove={event=>{if(!drawing.current)return;const p=point(event);const context=event.currentTarget.getContext("2d");if(context){context.lineWidth=4;context.lineCap="round";context.strokeStyle="#111";context.lineTo(p.x,p.y);context.stroke()}}} onPointerUp={()=>{drawing.current=false;if(ref.current)onChange(ref.current.toDataURL("image/png"))}} ref={ref} width={1200}/><Button className="mt-2" onClick={()=>{const canvas=ref.current;canvas?.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);onChange("")}} variant="outline">Limpiar firma</Button></div>}
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
