"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import Link from "next/link";
import { ChevronLeft, ChevronRight, LoaderCircle, Sparkles } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { Button } from "@/components/ui/button";

type Service = { code: string; name: string; configuration: Record<string, unknown>; availableHours: number[] };
type Price = { category: string; code: string; duration_hours: number | null; unit_price: number; rules: Record<string, unknown> };
type Venue = { name: string; municipality: string; province: string; surcharge: number };
type Municipality = { name: string; province: string; transport: number };
const money = (value: number) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value);
const terms = [
  ["Reserva y pago", "La fecha quedará reservada una vez firmado el contrato y abonado el 50% del valor total. El saldo restante deberá pagarse durante la semana previa al evento. La reserva no es reembolsable, pues bloquea exclusivamente la fecha y horario seleccionados."],
  ["Reprogramación", "El cliente podrá solicitar un cambio de fecha, sujeto a disponibilidad de BOOMBOX. Los valores podrán actualizarse si la nueva fecha corresponde a otra temporada, ubicación o condición de servicio. La reserva podrá cederse a otra persona previa autorización escrita."],
  ["Horario contratado", "El servicio comenzará y finalizará en el horario acordado. Los atrasos propios del evento no extenderán automáticamente el servicio. Toda hora adicional deberá ser solicitada y pagada, quedando sujeta a disponibilidad."],
  ["Acceso e instalación", "El cliente deberá asegurar acceso oportuno al recinto, un espacio adecuado y conexión eléctrica independiente de 220 V. Los costos generados por esperas, restricciones o una segunda visita podrán cobrarse adicionalmente."],
  ["Traslado", "El valor del traslado se calculará automáticamente según la ubicación seleccionada y se incorporará al total del servicio. Cualquier cambio posterior de dirección podrá modificar dicho valor."],
  ["Uso y daños", "El cliente será responsable por daños, pérdidas o roturas ocasionados por él o sus invitados al equipamiento, accesorios o elementos de BOOMBOX."],
  ["Seguridad", "BOOMBOX podrá suspender el servicio si existe mal uso, riesgo para las personas, agresiones al operador o peligro para los equipos."],
  ["Contingencias técnicas", "Ante una falla atribuible a BOOMBOX, la empresa dispondrá de hasta 45 minutos para intentar solucionarla. Si no fuera posible, se devolverá proporcionalmente el valor correspondiente al tiempo no prestado."],
  ["Entrega digital", "El respaldo digital será enviado dentro de los 7 días hábiles posteriores al evento mediante un enlace disponible durante 10 días."],
  ["Fuerza mayor", "Si el servicio no puede realizarse por hechos imprevisibles o ajenos a las partes, estas procurarán reprogramarlo de común acuerdo."],
] as const;
const eventTypeOptions = [{ value: "Wedding", label: "Matrimonio" }, { value: "Corporate", label: "Corporativo" }, { value: "Birthday", label: "Cumpleaños" }, { value: "Graduation", label: "Graduación" }, { value: "Private", label: "Evento privado" }, { value: "Other", label: "Otro" }];

export function AutomaticBookingExperience({ email, municipalities, prices, services, token, venues }: { email: string; municipalities: Municipality[]; prices: Price[]; services: Service[]; token: string; venues: Venue[] }) {
  const [step, setStep] = useState(0); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{ portalUrl: string; contractUrl: string; reservationNumber: string; eventDate: string; service: string; reservation: number; balance: number; total: number } | null>(null);
  const [progressIndex, setProgressIndex] = useState(0);
  const [customer, setCustomer] = useState({ name: "", rut: "", phone: "+569", email, address: "" });
  const [event, setEvent] = useState({ type: "Wedding", date: "", time: "18:00", venue: "", address: "", municipality: "", operationalContact: "", operationalPhone: "+569" });
  const [service, setService] = useState({ code: "", hours: 2, extras: [] as string[], brandingQuantity: 2 });
  const [magnetsMode, setMagnetsMode] = useState<"NONE" | "PAID" | "BENEFIT">("NONE");
  const [termsRead, setTermsRead] = useState(false); const [termsAccepted, setTermsAccepted] = useState(false); const [signature, setSignature] = useState("");
  const termsContainerRef = useRef<HTMLDivElement>(null); const termsEndRef = useRef<HTMLDivElement>(null);
  const [payment, setPayment] = useState({ method: "TRANSFER" as "TRANSFER" | "MERCADO_PAGO", receiptName: "", receiptType: "", receiptBase64: "" });
  const selectedService = services.find((item) => item.code === service.code); const compatible = Array.isArray(selectedService?.configuration.compatibleExtras) ? selectedService.configuration.compatibleExtras as string[] : [];
  const effectiveExtras = useMemo(() => {
    const included = event.type === "Wedding" ? ["QR incluido", "Scrapbook incluido"] : ["Birthday", "Graduation"].includes(event.type) ? ["QR incluido"] : [];
    return [...included, ...service.extras, ...(magnetsMode === "PAID" ? ["Imanes"] : magnetsMode === "BENEFIT" ? ["Imanes · Beneficio BOOMBOX"] : [])];
  }, [event.type, magnetsMode, service.extras]);
  const selectedVenue = venues.find((item) => item.name.localeCompare(event.venue, "es", { sensitivity: "base" }) === 0);
  const selectedMunicipality = municipalities.find((item) => item.name === event.municipality);
  const quote = useMemo(() => { const rows = prices.filter((item) => item.category === "SERVICE" && item.code === service.code); const base = rows.find((item) => item.duration_hours === service.hours)?.unit_price ?? rows[0]?.unit_price ?? 0; const extraMap: Record<string,string>={QR:"QR",Branding:"BRANDING",Imanes:"UNLIMITED_MAGNETS",Scrapbook:"SCRAPBOOK"}; const extras=effectiveExtras.reduce((sum,item)=>sum+(prices.find(price=>price.category==="EXTRA"&&price.code===extraMap[item])?.unit_price??0)*(item==="Branding"?service.brandingQuantity:1),0);const transport=selectedMunicipality?.transport??0;const venueSurcharge=selectedVenue?.surcharge??0;const subtotal=base+extras+transport+venueSurcharge;const total=Math.round(subtotal*(payment.method==="MERCADO_PAGO"?1.05:1));return{base,extras,transport,venueSurcharge,total,reservation:Math.round(total/2)};},[effectiveExtras,payment.method,prices,selectedMunicipality?.transport,selectedVenue?.surcharge,service]);
  const validMunicipality = municipalities.some((item) => item.name === event.municipality);
  const valid = step===0?Boolean(customer.name&&/^[0-9]{7,8}-[0-9K]$/i.test(customer.rut)&&/^\+569\d{8}$/.test(customer.phone)):step===1?Boolean(event.date&&event.time&&event.venue&&event.address&&validMunicipality&&event.operationalContact&&/^\+569\d{8}$/.test(event.operationalPhone)):step===2?Boolean(service.code&&quote.total>0):step===3?termsAccepted&&Boolean(signature):step===4?Boolean(payment.receiptBase64):false;
  useEffect(()=>{if(step!==3||termsRead)return;const root=termsContainerRef.current;const target=termsEndRef.current;if(!root||!target)return;const reachedEnd=()=>{if(root.scrollHeight-root.scrollTop-root.clientHeight<=40)setTermsRead(true)};reachedEnd();const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)setTermsRead(true)},{root,threshold:.5});observer.observe(target);root.addEventListener("scroll",reachedEnd,{passive:true});return()=>{observer.disconnect();root.removeEventListener("scroll",reachedEnd)}},[step,termsRead]);
  useEffect(()=>{if(!pending)return;setProgressIndex(0);const timer=window.setInterval(()=>setProgressIndex(current=>Math.min(current+1,4)),3200);return()=>window.clearInterval(timer)},[pending]);
  const chooseVenue=(name:string)=>{const venue=venues.find(item=>item.name===name);setEvent(current=>({...current,venue:name,municipality:venue?.municipality??current.municipality}));};
  const toggleExtra=(extra:string)=>setService(current=>({...current,extras:current.extras.includes(extra)?current.extras.filter(item=>item!==extra):[...current.extras,extra]}));
  const confirm=async()=>{setPending(true);setError("");try{const response=await fetch(`/api/booking/${encodeURIComponent(token)}/confirm`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,event,service:{...service,extras:effectiveExtras},payment,signatureDataUrl:signature})});const body=await response.json() as {ok:boolean;message?:string;portalUrl?:string;contractUrl?:string;reservationNumber?:string;eventDate?:string;service?:string;reservation?:number;balance?:number;total?:number};if(!response.ok||!body.ok||!body.portalUrl||!body.contractUrl||!body.reservationNumber)throw new Error(body.message||"No fue posible confirmar la reserva. Inténtalo nuevamente.");setResult({portalUrl:body.portalUrl,contractUrl:body.contractUrl,reservationNumber:body.reservationNumber,eventDate:body.eventDate??event.date,service:body.service??selectedService?.name??service.code,reservation:Number(body.reservation??quote.reservation),balance:Number(body.balance??quote.total-quote.reservation),total:Number(body.total??quote.total)});setStep(5);}catch(cause){setError(cause instanceof Error&&cause.message?cause.message:"No fue posible confirmar la reserva. Inténtalo nuevamente.");}finally{setPending(false)}};
  return <main className="min-h-screen bg-background px-4 py-6 text-foreground sm:py-10"><div className="mx-auto max-w-5xl"><BrandLogo className="mx-auto h-16 w-52" priority surface="dark"/><header className="mt-8 text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Reserva Automática BOOMBOX</p><h1 className="mt-3 text-3xl font-semibold sm:text-5xl">Tu evento, paso a paso.</h1><p className="mt-3 text-muted">Una sola acción clara en cada etapa.</p></header><div className="mt-8 flex gap-2">{["Tus datos","Evento","Servicio","Contrato","Pago","Listo"].map((label,index)=><div className="flex-1" key={label}><div className={`h-1.5 rounded-full ${index<=step?"bg-brand":"bg-border"}`}/><p className="mt-2 hidden text-center text-xs text-muted sm:block">{label}</p></div>)}</div><section className="mt-7 rounded-3xl border bg-card p-5 sm:p-8">
  {step===0&&<Step title="Cuéntanos quién eres"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre y Apellido" value={customer.name} onChange={value=>setCustomer({...customer,name:value})}/><Field label="RUT" value={customer.rut} onChange={value=>{const raw=value.replace(/[^0-9K]/gi,"").toUpperCase().slice(0,9);setCustomer({...customer,rut:raw.length>1?`${raw.slice(0,-1)}-${raw.slice(-1)}`:raw})}}/><Field label="Teléfono" value={customer.phone} onChange={value=>setCustomer({...customer,phone:`+569${value.replace(/\D/g,"").replace(/^569/,"").slice(0,8)}`})}/><Field disabled label="Correo" value={customer.email} onChange={()=>{}}/><Field label="Dirección" value={customer.address} onChange={value=>setCustomer({...customer,address:value})}/></div></Step>}
  {step===1&&<Step title="Información de tu evento"><div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo de evento" value={event.type} onChange={value=>{setEvent({...event,type:value});setService(current=>({...current,extras:[]}));setMagnetsMode("NONE")}} options={eventTypeOptions}/><Field label="Fecha" type="date" value={event.date} onChange={value=>setEvent({...event,date:value})}/><Field label="Hora de inicio" type="time" value={event.time} onChange={value=>setEvent({...event,time:value})}/><div><Field label="Lugar del Evento" list="booking-venues" value={event.venue} onChange={chooseVenue}/><datalist id="booking-venues">{venues.map(item=><option key={item.name} value={item.name}/>)}</datalist></div><Field label="Dirección del Evento" value={event.address} onChange={value=>setEvent({...event,address:value})}/><MunicipalityCombobox items={municipalities} onChange={value=>setEvent({...event,municipality:value})} value={event.municipality}/><Field label="Contacto operacional" value={event.operationalContact} onChange={value=>setEvent({...event,operationalContact:value})}/><Field label="Teléfono operacional" value={event.operationalPhone} onChange={value=>setEvent({...event,operationalPhone:`+569${value.replace(/\D/g,"").replace(/^569/,"").slice(0,8)}`})}/></div></Step>}
  {step===2&&<Step title="Elige tu experiencia"><div className="grid gap-6 lg:grid-cols-[1fr_20rem]"><div><div className="grid gap-3 sm:grid-cols-2">{services.map(item=><button className={`rounded-2xl border p-4 text-left ${service.code===item.code?"border-brand bg-brand/5":""}`} key={item.code} onClick={()=>{setService(current=>({...current,code:item.code,hours:item.availableHours[0]??2,extras:[]}));setMagnetsMode("NONE")}} type="button"><strong>{item.name}</strong></button>)}</div>{service.code&&<><Select label="Horas" value={String(service.hours)} onChange={value=>setService({...service,hours:Number(value)})} options={(selectedService?.availableHours??[]).map(String)}/><SmartExtras compatible={compatible} eventType={event.type} magnetsMode={magnetsMode} onMagnetsMode={setMagnetsMode} prices={prices} selected={service.extras} toggle={toggleExtra}/></>}</div><Summary quote={quote} service={selectedService?.name}/></div></Step>}
  {step===3&&<Step title="Revisa y firma tu contrato"><Summary quote={quote} service={selectedService?.name}/><p className="mt-6 text-sm text-muted">Lee el contrato completo y desplázate hasta el final para aceptar.</p><div className="mt-3 max-h-72 space-y-5 overflow-y-auto overscroll-contain rounded-xl border p-5" ref={termsContainerRef} tabIndex={0}>{terms.map(([title,content],index)=><section key={title}><h3 className="font-semibold">{index+1}. {title}</h3><p className="mt-2 text-sm leading-6 text-muted">{content}</p></section>)}<div aria-hidden="true" className="h-px" ref={termsEndRef}/></div><div className={`mt-5 flex min-h-16 touch-manipulation items-start gap-3 rounded-xl border p-4 ${termsRead?"cursor-pointer":"cursor-not-allowed opacity-60"}`}><input aria-describedby="booking-terms-status" aria-disabled={!termsRead} checked={termsAccepted} className="mt-0.5 size-6 shrink-0 accent-[var(--brand)]" id="booking-terms-accepted" onChange={event=>{if(termsRead)setTermsAccepted(event.target.checked)}} onClick={event=>{if(!termsRead)event.preventDefault()}} type="checkbox"/><label className="flex min-h-11 flex-1 cursor-inherit items-start" htmlFor="booking-terms-accepted">He leído y acepto los Términos y Condiciones.</label></div><p aria-live="polite" className="mt-2 text-xs text-muted" id="booking-terms-status">{termsRead?"Puedes aceptar y continuar con la firma.":"Desplázate hasta el final del documento para habilitar la aceptación."}</p>{termsAccepted&&<Signature onChange={setSignature} value={signature}/>} {termsAccepted&&!signature&&<p className="mt-3 text-sm text-warning">Firma dentro del recuadro para continuar.</p>}</Step>}
  {step===4&&<Step title="Confirma el pago"><Summary quote={quote} service={selectedService?.name}/><div className="mt-6 grid grid-cols-2 gap-3"><Button onClick={()=>setPayment({...payment,method:"TRANSFER"})} variant={payment.method==="TRANSFER"?"default":"outline"}>Transferencia</Button><Button onClick={()=>setPayment({...payment,method:"MERCADO_PAGO"})} variant={payment.method==="MERCADO_PAGO"?"default":"outline"}>Mercado Pago +5%</Button></div>{payment.method==="TRANSFER"&&<div className="mt-5 rounded-xl border p-4 text-sm"><strong>PRODUCCIONES BOOMBOX COMPANY SPA</strong><p className="mt-2 text-muted">RUT 76.565.272-3 · Banco BCI · Cuenta Corriente 52093409 · contabilidad@boom-box.cl</p></div>}<label className="mt-5 block font-medium">Comprobante<input accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-2 block w-full rounded-xl border p-3" disabled={pending} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const base64=await fileBase64(file);setPayment({...payment,receiptName:file.name,receiptType:file.type,receiptBase64:base64})}} type="file"/></label>{pending&&<BookingProgress activeIndex={progressIndex}/>}</Step>}
  {step===5&&result&&<div className="py-8 text-center"><div className="text-5xl">🎉</div><h2 className="mt-5 text-3xl font-semibold">¡Tu reserva fue recibida correctamente!</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted">Gracias por elegir BOOMBOX. Hemos recibido tu reserva. Nuestro equipo revisará el pago y, una vez validado, recibirás la confirmación por correo electrónico.</p><dl className="mx-auto mt-7 max-w-2xl space-y-3 rounded-2xl border bg-background/40 p-5 text-left"><Row label="Número de reserva" value={result.reservationNumber}/><Row label="Fecha del evento" value={result.eventDate}/><Row label="Servicio" value={result.service}/><Row label="Monto de reserva" value={money(result.reservation)}/><Row label="Saldo restante" value={money(result.balance)}/><Row label="TOTAL" value={money(result.total)}/></dl><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a className="inline-flex min-h-12 items-center justify-center rounded-xl bg-brand px-6 font-semibold text-brand-foreground" href={result.portalUrl}>Ir al Portal del Cliente</a><a className="inline-flex min-h-12 items-center justify-center rounded-xl border px-6 font-semibold" href={result.contractUrl}>Descargar contrato</a><Link className="inline-flex min-h-12 items-center justify-center rounded-xl border px-6 font-semibold" href="/">Volver al inicio</Link></div></div>}
  {error&&<p className="mt-5 rounded-xl border border-danger/30 bg-danger/5 p-4 text-sm text-danger" role="alert">{error}</p>}</section>{step<5&&<footer className="mt-5 flex justify-between"><Button disabled={step===0||pending} onClick={()=>setStep(current=>current-1)} variant="outline"><ChevronLeft className="size-4"/>Atrás</Button>{step<4?<Button disabled={!valid} onClick={()=>setStep(current=>current+1)}>Continuar<ChevronRight className="size-4"/></Button>:<Button disabled={!valid||pending} onClick={()=>void confirm()}>{pending?<LoaderCircle className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}{pending?"Confirmando reserva…":"Confirmar Reserva"}</Button>}</footer>}</div></main>;
}

function Step({title,children}:{title:string;children:React.ReactNode}){return <div><h2 className="mb-6 text-2xl font-semibold">{title}</h2>{children}</div>}
function Field({label,value,onChange,type="text",...props}:{label:string;value:string;onChange:(value:string)=>void;type?:string}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"value"|"onChange"|"type">){return <label className="block text-sm font-medium">{label}<input className="mt-2 h-12 w-full rounded-xl border bg-background px-4" onChange={event=>onChange(event.target.value)} type={type} value={value} {...props}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<string|{value:string;label:string}>}){return <label className="mt-4 block text-sm font-medium">{label}<select className="mt-2 h-12 w-full rounded-xl border bg-background px-4" onChange={event=>onChange(event.target.value)} value={value}>{options.map(item=>{const option=typeof item==="string"?{value:item,label:item}:item;return <option key={option.value} value={option.value}>{option.label}</option>})}</select></label>}
function MunicipalityCombobox({items,onChange,value}:{items:Municipality[];onChange:(value:string)=>void;value:string}){
  const [query,setQuery]=useState(value);const [open,setOpen]=useState(false);
  useEffect(()=>setQuery(value),[value]);
  const filtered=useMemo(()=>{const normalized=query.trim().toLocaleLowerCase("es-CL");return items.filter((item)=>!normalized||item.name.toLocaleLowerCase("es-CL").includes(normalized)).sort((a,b)=>a.name.localeCompare(b.name,"es")).slice(0,50)},[items,query]);
  const selected=items.find((item)=>item.name===value);
  return <div className="relative"><label className="block text-sm font-medium" htmlFor="booking-municipality">Comuna</label><input aria-autocomplete="list" aria-controls="booking-municipality-options" aria-expanded={open} autoComplete="off" className="mt-2 h-12 w-full rounded-xl border bg-background px-4" id="booking-municipality" onBlur={()=>setTimeout(()=>setOpen(false),100)} onChange={event=>{setQuery(event.target.value);onChange("");setOpen(true)}} onFocus={()=>setOpen(true)} placeholder="Busca y selecciona una comuna" role="combobox" value={query}/>{open&&<div className="absolute z-30 mt-2 max-h-64 w-full overflow-y-auto rounded-xl border bg-card p-1 shadow-xl" id="booking-municipality-options" role="listbox">{filtered.map((item)=><button aria-selected={item.name===value} className="flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-sm hover:bg-accent focus:bg-accent" key={`${item.province}-${item.name}`} onMouseDown={event=>event.preventDefault()} onClick={()=>{setQuery(item.name);onChange(item.name);setOpen(false)}} role="option" type="button"><span className="font-medium">{item.name}</span><span className="text-xs text-muted">{item.province}</span></button>)}{!filtered.length&&<p className="px-3 py-4 text-sm text-muted">No hay comunas activas que coincidan.</p>}</div>}{query&&!selected&&<p className="mt-2 text-xs text-danger">Selecciona una comuna de la lista.</p>}{selected&&<p className="mt-2 text-xs text-muted">Provincia {selected.province} · Transporte {selected.transport?money(selected.transport):"incluido"}</p>}</div>
}
function SmartExtras({compatible,eventType,magnetsMode,onMagnetsMode,prices,selected,toggle}:{compatible:string[];eventType:string;magnetsMode:"NONE"|"PAID"|"BENEFIT";onMagnetsMode:(value:"NONE"|"PAID"|"BENEFIT")=>void;prices:Price[];selected:string[];toggle:(extra:string)=>void}){
  const extraPrice=(code:string)=>prices.find((item)=>item.category==="EXTRA"&&item.code===code)?.unit_price??0;
  const qrIncluded=["Wedding","Birthday","Graduation"].includes(eventType);
  const scrapbookIncluded=eventType==="Wedding";
  const scrapbookOptional=["Birthday","Graduation","Corporate"].includes(eventType);
  return <div className="mt-5 grid gap-3 sm:grid-cols-2">
    {compatible.includes("QR")&&(qrIncluded?<LockedExtra label="QR"/>:<OptionalExtra checked={selected.includes("QR")} label="QR" onChange={()=>toggle("QR")} price={extraPrice("QR")}/>) }
    {compatible.includes("SCRAPBOOK")&&(scrapbookIncluded?<LockedExtra label="Scrapbook"/>:scrapbookOptional?<OptionalExtra checked={selected.includes("Scrapbook")} label="Scrapbook" onChange={()=>toggle("Scrapbook")} price={extraPrice("SCRAPBOOK")}/>:null)}
    {compatible.includes("UNLIMITED_MAGNETS")&&<label className="rounded-xl border p-4 text-sm font-medium">Imanes<select className="mt-2 h-11 w-full rounded-lg border bg-background px-3" onChange={event=>onMagnetsMode(event.target.value as "NONE"|"PAID"|"BENEFIT")} value={magnetsMode}><option value="NONE">No incluidos</option><option value="PAID">+{money(extraPrice("UNLIMITED_MAGNETS"))}</option><option value="BENEFIT">Beneficio BOOMBOX · $0</option></select></label>}
    {compatible.includes("BRANDING")&&<OptionalExtra checked={selected.includes("Branding")} label="Branding" onChange={()=>toggle("Branding")} price={extraPrice("BRANDING")}/>}
  </div>
}
function LockedExtra({label}:{label:string}){return <div className="flex items-center gap-3 rounded-xl border p-4"><input checked disabled readOnly type="checkbox"/><span className="text-sm font-medium">{label}<span className="mt-1 block text-xs text-success">Incluido · $0 · Fijo</span></span></div>}
function OptionalExtra({checked,label,onChange,price}:{checked:boolean;label:string;onChange:()=>void;price:number}){return <label className="flex items-center gap-3 rounded-xl border p-4"><input checked={checked} onChange={onChange} type="checkbox"/><span className="text-sm font-medium">{label}<span className="mt-1 block text-xs text-muted">Opcional · +{money(price)}</span></span></label>}
function Summary({quote,service}:{quote:{base:number;extras:number;transport:number;venueSurcharge:number;total:number;reservation:number};service?:string}){return <aside className="rounded-2xl border bg-background/40 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-brand">Resumen Comercial</p><dl className="mt-4 space-y-3 text-sm"><Row label={service??"Servicio"} value={money(quote.base)}/><Row label="Extras" value={money(quote.extras)}/><Row label="Transporte" value={money(quote.transport)}/>{quote.venueSurcharge>0&&<Row label="Recargo lugar" value={money(quote.venueSurcharge)}/>}<Row label="Reserva" value={money(quote.reservation)}/><Row label="Saldo" value={money(quote.total-quote.reservation)}/><Row label="TOTAL" value={money(quote.total)}/></dl></aside>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3 border-b border-border/60 pb-2 last:border-0"><dt>{label}</dt><dd className="font-semibold">{value}</dd></div>}
function Signature({onChange,value}:{onChange:(value:string)=>void;value:string}){const ref=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);const moved=useRef(false);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const render=()=>{const rect=canvas.getBoundingClientRect();const ratio=window.devicePixelRatio||1;const width=Math.max(1,Math.round(rect.width*ratio));const height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const context=canvas.getContext("2d");context?.clearRect(0,0,width,height);if(value){const image=new Image();image.onload=()=>context?.drawImage(image,0,0,width,height);image.src=value}};render();const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect()},[value]);const point=(event:ReactPointerEvent<HTMLCanvasElement>)=>{const canvas=event.currentTarget;const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*(canvas.width/rect.width),y:(event.clientY-rect.top)*(canvas.height/rect.height)}};const finish=(canvas:HTMLCanvasElement)=>{if(!drawing.current)return;drawing.current=false;if(moved.current)onChange(canvas.toDataURL("image/png"));moved.current=false};return <div className="mt-5"><p className="mb-2 text-sm font-medium">Firma</p><canvas aria-label="Área de firma" className="h-44 w-full touch-none rounded-xl border bg-white" onPointerCancel={event=>finish(event.currentTarget)} onPointerDown={event=>{drawing.current=true;moved.current=false;event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);const context=event.currentTarget.getContext("2d");context?.beginPath();context?.moveTo(p.x,p.y)}} onPointerMove={event=>{if(!drawing.current)return;const p=point(event);const context=event.currentTarget.getContext("2d");if(context){moved.current=true;context.lineWidth=Math.max(4,2.5*(window.devicePixelRatio||1));context.lineCap="round";context.lineJoin="round";context.strokeStyle="#F78900";context.lineTo(p.x,p.y);context.stroke()}}} onPointerUp={event=>finish(event.currentTarget)} ref={ref}/><Button className="mt-2" onClick={()=>{const canvas=ref.current;canvas?.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);onChange("")}} variant="outline">Limpiar firma</Button></div>}

const bookingProgressSteps=["Creando reserva…","Generando contrato…","Preparando tu portal…","Enviando confirmación…","Casi listo…"];
function BookingProgress({activeIndex}:{activeIndex:number}){return <div aria-live="polite" className="mt-5 rounded-2xl border border-brand/30 bg-brand/5 p-5" role="status"><div className="flex items-center gap-3"><LoaderCircle className="size-5 animate-spin text-brand"/><strong>{bookingProgressSteps[activeIndex]}</strong></div><ol className="mt-4 space-y-2 text-sm">{bookingProgressSteps.map((label,index)=><li className={index<=activeIndex?"text-foreground":"text-muted"} key={label}>{index<activeIndex?"✓":index===activeIndex?"●":"○"} {label}</li>)}</ol></div>}
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
