"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, CircleDollarSign, ReceiptText, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MobileDialog } from "@/components/ui/mobile-dialog";

const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const dateLabel=(value:string)=>new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`));
export type CashFlowKind="INCOMING"|"OUTGOING"|"PENDING_COLLECTION"|"PENDING_PAYMENT";
export interface CashFlowTransaction{id:string;kind:CashFlowKind;date:string;amount:number;title:string;detail:string;href:string;source:string;overdue?:boolean}
export interface CashFlowData{generatedAt:string;transactions:readonly CashFlowTransaction[]}
type Range="TODAY"|"WEEK"|"MONTH"|"CUSTOM";

export function CashFlowCenter({data}:{data:CashFlowData}){
  const today=new Date(data.generatedAt).toLocaleDateString("en-CA",{timeZone:"America/Santiago"});
  const[range,setRange]=useState<Range>("MONTH");const[from,setFrom]=useState(today.slice(0,8)+"01");const[to,setTo]=useState(today);const[detail,setDetail]=useState<{title:string;items:CashFlowTransaction[]}|null>(null);
  const actual=data.transactions.filter(item=>item.kind==="INCOMING"||item.kind==="OUTGOING");const currentCash=actual.reduce((sum,item)=>sum+(item.kind==="INCOMING"?item.amount:-item.amount),0);
  const endFor=(days:number)=>{const end=new Date(`${today}T12:00:00Z`);end.setUTCDate(end.getUTCDate()+days);return end.toISOString().slice(0,10)};
  const within=(date:string,start:string,end:string)=>date.slice(0,10)>=start&&date.slice(0,10)<=end;
  const rangeBounds=useMemo(()=>{if(range==="CUSTOM")return{start:from,end:to};if(range==="TODAY")return{start:today,end:today};if(range==="WEEK"){const start=new Date(`${today}T12:00:00Z`);start.setUTCDate(start.getUTCDate()-6);return{start:start.toISOString().slice(0,10),end:today}}return{start:today.slice(0,8)+"01",end:today};},[from,range,to,today]);
  const filtered=data.transactions.filter(item=>within(item.date,rangeBounds.start,rangeBounds.end));
  const incoming=filtered.filter(item=>item.kind==="INCOMING");const outgoing=filtered.filter(item=>item.kind==="OUTGOING");const pendingCollections=data.transactions.filter(item=>item.kind==="PENDING_COLLECTION");const pendingPayments=data.transactions.filter(item=>item.kind==="PENDING_PAYMENT");
  const sum=(items:readonly CashFlowTransaction[])=>items.reduce((total,item)=>total+item.amount,0);
  const projection=(days:number)=>{const end=endFor(days);return currentCash+sum(pendingCollections.filter(item=>item.date<=end))-sum(pendingPayments.filter(item=>item.date<=end))};
  const projectedCash=projection(30);const forecasts=[{label:"Hoy",days:0},{label:"7 días",days:7},{label:"15 días",days:15},{label:"30 días",days:30}];
  const largePayments=[...pendingPayments].sort((a,b)=>b.amount-a.amount).slice(0,3);const largeCollections=[...pendingCollections].sort((a,b)=>b.amount-a.amount).slice(0,3);const overdue=pendingCollections.filter(item=>item.overdue);
  const open=(title:string,items:CashFlowTransaction[])=>setDetail({title,items:[...items].sort((a,b)=>a.date.localeCompare(b.date))});
  return <section className="space-y-6">
    <header className="rounded-3xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Finanzas · Caja en tiempo real</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Cash Flow Center</h1><p className="mt-3 max-w-2xl text-sm text-muted sm:text-base">Entradas, salidas y compromisos proyectados desde los registros productivos de ORBIT.</p><p className="mt-4 text-xs text-muted">Actualizado {new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Santiago"}).format(new Date(data.generatedAt))}</p></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Kpi icon={CircleDollarSign} label="Caja actual" value={currentCash} detail="Saldo neto registrado" onClick={()=>open("Movimientos de caja actual",actual)}/><Kpi icon={WalletCards} label="Caja proyectada" value={projectedCash} detail="Proyección a 30 días" onClick={()=>open("Movimientos de la proyección",[...pendingCollections,...pendingPayments])}/><Kpi icon={ArrowUpRight} label="Pagos recibidos" value={sum(incoming)} detail="Entradas del período" onClick={()=>open("Pagos recibidos",incoming)}/><Kpi icon={ArrowDownRight} label="Pagos realizados" value={sum(outgoing)} detail="Salidas del período" onClick={()=>open("Pagos realizados",outgoing)}/><Kpi icon={ReceiptText} label="Cobros pendientes" value={sum(pendingCollections)} detail="Facturas por cobrar" onClick={()=>open("Cobros pendientes",pendingCollections)}/><Kpi icon={CalendarDays} label="Pagos a proveedores" value={sum(pendingPayments)} detail="Obligaciones pendientes" onClick={()=>open("Pagos pendientes",pendingPayments)}/></div>
    <section className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Período</p><h2 className="mt-1 text-xl font-semibold">Movimientos registrados</h2></div><div className="flex flex-wrap gap-2">{([['TODAY','Hoy'],['WEEK','Esta semana'],['MONTH','Este mes'],['CUSTOM','Rango personalizado']]as const).map(([id,label])=><Button className="min-h-9 px-3" key={id} onClick={()=>setRange(id)} variant={range===id?"default":"outline"}>{label}</Button>)}</div></div>{range==="CUSTOM"&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Desde<input className="mt-2 block w-full rounded-xl border bg-background p-3" max={to} onChange={event=>setFrom(event.target.value)} type="date" value={from}/></label><label className="text-sm font-medium">Hasta<input className="mt-2 block w-full rounded-xl border bg-background p-3" min={from} onChange={event=>setTo(event.target.value)} type="date" value={to}/></label></div>}</section>
    <section className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Forecast</p><h2 className="mt-1 text-2xl font-semibold">Saldo esperado</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{forecasts.map(item=>{const value=projection(item.days);const end=endFor(item.days);const items=[...pendingCollections.filter(row=>row.date<=end),...pendingPayments.filter(row=>row.date<=end)];return <button className="rounded-2xl border bg-card p-5 text-left transition hover:border-brand" key={item.label} onClick={()=>open(`Proyección · ${item.label}`,items)}><span className="flex items-center justify-between"><CalendarDays className="size-5 text-brand"/><ArrowRight className="size-4 text-muted"/></span><strong className={"mt-5 block text-2xl "+(value<0?"text-red-500":"")}>{money.format(value)}</strong><span className="mt-1 block font-semibold">{item.label}</span><span className="mt-1 block text-xs text-muted">Caja esperada al {dateLabel(end)}</span></button>})}</div></section>
    <section className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">Atención financiera</p><h2 className="mt-1 text-2xl font-semibold">Alertas de caja</h2></div><div className="grid gap-3 lg:grid-cols-2"><Alert title="Proyección negativa" active={forecasts.some(item=>projection(item.days)<0)} detail={forecasts.some(item=>projection(item.days)<0)?"Existe al menos un horizonte con saldo esperado negativo.":"La caja proyectada permanece positiva en todos los horizontes."} onClick={()=>open("Compromisos de caja",[...pendingCollections,...pendingPayments])}/><Alert title="Cobros vencidos" active={overdue.length>0} detail={overdue.length?`${overdue.length} cobros vencidos por ${money.format(sum(overdue))}.`:"No existen cobros vencidos."} onClick={()=>open("Cobros vencidos",overdue)}/><Alert title="Próximos pagos relevantes" active={largePayments.length>0} detail={largePayments.length?`${largePayments.length} mayores compromisos suman ${money.format(sum(largePayments))}.`:"No existen pagos pendientes."} onClick={()=>open("Próximos pagos relevantes",largePayments)}/><Alert title="Próximas cobranzas relevantes" active={largeCollections.length>0} detail={largeCollections.length?`${largeCollections.length} mayores cobros suman ${money.format(sum(largeCollections))}.`:"No existen cobranzas pendientes."} onClick={()=>open("Próximas cobranzas relevantes",largeCollections)}/></div></section>
    {detail&&<MobileDialog eyebrow="Detalle de transacciones" onClose={()=>setDetail(null)} size="xl" title={detail.title} variant="fullscreen-mobile"><div className="divide-y">{detail.items.map(item=><a className="grid gap-2 py-4 transition hover:text-brand sm:grid-cols-[130px_1fr_auto] sm:items-center" href={item.href} key={`${item.kind}-${item.id}`}><span className="text-xs text-muted">{dateLabel(item.date)}</span><span><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs text-muted">{item.detail} · {item.source}</span></span><strong className={item.kind==="INCOMING"||item.kind==="PENDING_COLLECTION"?"text-emerald-500":"text-red-500"}>{item.kind==="INCOMING"||item.kind==="PENDING_COLLECTION"?"+":"−"}{money.format(item.amount)}</strong></a>)}{!detail.items.length&&<p className="py-10 text-center text-sm text-muted">No existen transacciones para este indicador.</p>}</div></MobileDialog>}
  </section>;
}

function Kpi({detail,icon:Icon,label,onClick,value}:{detail:string;icon:typeof CircleDollarSign;label:string;onClick:()=>void;value:number}){return <button className="group rounded-2xl border bg-card p-5 text-left transition hover:border-brand/50" onClick={onClick}><span className="flex items-center justify-between"><Icon className="size-5 text-brand"/><ArrowRight className="size-4 text-muted transition group-hover:translate-x-1"/></span><strong className={"mt-5 block text-2xl "+(value<0?"text-red-500":"")}>{money.format(value)}</strong><span className="mt-1 block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted">{detail}</span></button>}
function Alert({active,detail,onClick,title}:{active:boolean;detail:string;onClick:()=>void;title:string}){return <button className="rounded-2xl border bg-card p-5 text-left transition hover:border-brand" onClick={onClick}><span className="flex items-center gap-2"><AlertTriangle className={"size-4 "+(active?"text-amber-500":"text-emerald-500")}/><strong>{title}</strong></span><p className="mt-2 text-sm text-muted">{detail}</p></button>}
