export type OperationalStartSource="STAFF_CALL"|"STAFF_ARRIVAL"|"SERVICE_START";
export type OperationalWindow={operationalStartAt:string;serviceStartAt:string;serviceEndAt:string;source:OperationalStartSource};
export type StaffCallSource="DEFAULT_60_MIN"|"FOUNDER_OVERRIDE"|"LEGACY";
const valid=(value:string|null|undefined):value is string=>typeof value==="string"&&!Number.isNaN(new Date(value).getTime());
export function chileLocalToIso(local:string):string{const normalized=local.length===16?`${local}:00`:local;const naive=new Date(`${normalized}Z`);if(Number.isNaN(naive.getTime()))throw new Error("Fecha operacional inválida.");const formatter=new Intl.DateTimeFormat("en-US",{timeZone:"America/Santiago",timeZoneName:"longOffset",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});const offset=formatter.formatToParts(naive).find(part=>part.type==="timeZoneName")?.value??"GMT-04:00";const match=offset.match(/GMT([+-])(\d{2}):?(\d{2})?/);const minutes=match?((Number(match[2])*60)+(Number(match[3]??0)))*(match[1]==="-"?-1:1):-240;return new Date(naive.getTime()-minutes*60*1000).toISOString();}
/** Canonical operational rule: staff arrives exactly one hour before service start. */
export function calculateStaffCallAt(serviceStartAt:string|Date):string{const start=serviceStartAt instanceof Date?serviceStartAt:new Date(serviceStartAt);if(Number.isNaN(start.getTime()))throw new Error("Inicio de servicio inválido.");return new Date(start.getTime()-60*60*1000).toISOString();}
export function resolveCanonicalStaffCallAt(input:{serviceStartAt:string;overrides?:readonly {value:string|null|undefined;source?:string|null}[]}):{staffCallAt:string;source:StaffCallSource}{const override=input.overrides?.find(item=>["FOUNDER_OVERRIDE","MANUAL_OVERRIDE"].includes(String(item.source))&&valid(item.value)&&new Date(item.value as string).getTime()<=new Date(input.serviceStartAt).getTime());if(override?.value)return{staffCallAt:override.value,source:"FOUNDER_OVERRIDE"};return{staffCallAt:calculateStaffCallAt(input.serviceStartAt),source:"DEFAULT_60_MIN"};}
export function isValidOperationalCall(value:string|null|undefined,serviceStartAt:string){if(typeof value!=="string"||!valid(value)||!valid(serviceStartAt))return false;const call=new Date(value).getTime(),start=new Date(serviceStartAt).getTime();return call<=start&&call>=start-86_400_000;}
export const chileDateTime=(value:string)=>{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value??"";return{date:`${part("year")}-${part("month")}-${part("day")}`,time:`${part("hour")}:${part("minute")}`}};
export function resolveEventOperationalWindow(input:{assignmentStaffCalls:readonly(string|null|undefined)[];staffArrivalAt?:string|null;serviceStartAt:string;serviceEndAt:string}):OperationalWindow{const earliestCall=input.assignmentStaffCalls.filter((value):value is string=>isValidOperationalCall(value,input.serviceStartAt)).sort((left,right)=>new Date(left).getTime()-new Date(right).getTime())[0];const arrival=isValidOperationalCall(input.staffArrivalAt,input.serviceStartAt)?input.staffArrivalAt:null;return{operationalStartAt:earliestCall??arrival??input.serviceStartAt,serviceStartAt:input.serviceStartAt,serviceEndAt:input.serviceEndAt,source:earliestCall?"STAFF_CALL":arrival?"STAFF_ARRIVAL":"SERVICE_START"};}
