"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { calculateAndPersistRealEventCost } from "@/features/profit-engine";

type Result={ok:true;message:string}|{ok:false;error:string};
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const optional=(data:FormData,key:string)=>value(data,key)||null;
async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión expiró.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar logística.");return{client,userId:data.user.id};}
const friendly=(error:unknown)=>{const candidate=error&&typeof error==="object"&&"message"in error?String(error.message):error instanceof Error?error.message:"";if(candidate.includes("VEHÍCULO NO DISPONIBLE"))return candidate;if(candidate&&!["violates","schema cache","column"].some(token=>candidate.includes(token)))return candidate;return"No fue posible guardar la logística.";};
const refresh=(projectId:string)=>{for(const path of [`/projects/${projectId}`,"/operations","/resources","/finance","/reports"])revalidatePath(path);};

export async function setEventLogisticsModeAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),mode=value(data,"mode");const{error}=await client.rpc("set_event_logistics_mode",{p_project_id:projectId,p_mode:mode});if(error)throw error;refresh(projectId);return{ok:true,message:"Necesidad logística actualizada."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function saveEventLogisticsTripAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId");const{error}=await client.rpc("save_event_logistics_trip",{p_project_id:projectId,p_trip_id:optional(data,"tripId"),p_asset_id:optional(data,"assetId"),p_driver_staff_id:optional(data,"driverStaffId"),p_driver_name:optional(data,"driverName"),p_trip_type:value(data,"tripType"),p_sequence:Number(value(data,"sequence")||1),p_origin:value(data,"origin"),p_destination:value(data,"destination"),p_planned_start_at:value(data,"plannedStartAt"),p_planned_end_at:value(data,"plannedEndAt"),p_meeting_point:optional(data,"meetingPoint"),p_instructions:optional(data,"instructions")});if(error)throw error;refresh(projectId);return{ok:true,message:"Viaje guardado y disponibilidad confirmada."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function updateVehicleTripStatusAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId");const{error}=await client.rpc("update_vehicle_trip_status",{p_trip_id:value(data,"tripId"),p_status:value(data,"status"),p_odometer:value(data,"odometer")?Number(value(data,"odometer")):null});if(error)throw error;refresh(projectId);return{ok:true,message:"Estado del viaje actualizado."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function addEventLogisticsExpenseAction(data:FormData):Promise<Result>{let uploadedPath="";try{const{client,userId}=await context(),projectId=value(data,"projectId"),tripId=value(data,"tripId"),category=value(data,"category"),total=Number(value(data,"total"));if(!["FUEL","TOLLS","PARKING","TRANSPORT","OTHER_OPERATIONAL"].includes(category)||!projectId||!tripId||total<0)throw new Error("Completa tipo, viaje y monto.");const file=data.get("receipt");if(file instanceof File&&file.size>0){if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("El comprobante debe ser una foto o PDF.");uploadedPath=`logistics/${projectId}/${crypto.randomUUID()}.${file.name.split(".").pop()?.toLowerCase()||"bin"}`;const{error:uploadError}=await client.storage.from("orbit-expenses").upload(uploadedPath,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(uploadError)throw uploadError;}const{data:trip,error:tripError}=await client.from("vehicle_trips").select("asset_id").eq("id",tripId).eq("project_id",projectId).single();if(tripError)throw tripError;const metadata={associationType:"EVENT",associationId:projectId,vehicleTripId:tripId,expenseType:category,description:value(data,"description")};const{error}=await client.from("expenses").insert({project_id:projectId,vehicle_trip_id:tripId,category,supplier:optional(data,"supplier"),occurred_on:value(data,"date"),subtotal:total,vat:0,total,status:"PENDING",receipt_path:uploadedPath||null,vehicle_id:trip.asset_id,approval_reason:JSON.stringify(metadata),created_by:userId,updated_by:userId});if(error)throw error;await calculateAndPersistRealEventCost(client,projectId);refresh(projectId);return{ok:true,message:"Gasto logístico registrado como pendiente de revisión."};}catch(error){if(uploadedPath)try{const client=await createSupabaseServerClient();await client.storage.from("orbit-expenses").remove([uploadedPath]);}catch{}return{ok:false,error:friendly(error)};}}
