"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { calculateAndPersistRealEventCost } from "@/features/profit-engine";

type Result={ok:true;message:string}|{ok:false;error:string};
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const optional=(data:FormData,key:string)=>value(data,key)||null;
async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión expiró.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar logística.");return{client,userId:data.user.id};}
const friendly=(error:unknown)=>{const candidate=error&&typeof error==="object"&&"message"in error?String(error.message):error instanceof Error?error.message:"";if(candidate.includes("VEHÍCULO NO DISPONIBLE"))return candidate;if(candidate&&!["violates","schema cache","column"].some(token=>candidate.includes(token)))return candidate;return"No fue posible guardar la logística.";};
const refresh=(projectId:string)=>{for(const path of [`/projects/${projectId}`,"/operations","/resources","/finance","/reports"])revalidatePath(path);};
async function timeline(client:Awaited<ReturnType<typeof createSupabaseServerClient>>,projectId:string,action:string,title:string,description:string,entityType:string,entityId:string,correlation:string){try{const{data:project}=await client.from("projects").select("customer_id,orbit_event_id").eq("id",projectId).single();if(!project)return;const{error}=await client.from("timeline_events").upsert({customer_id:project.customer_id,project_id:projectId,orbit_event_id:project.orbit_event_id,event_type:action,title,description,actor_label:"Operations",source:"Operations",action,entity_type:entityType,entity_id:entityId,human_message:description,correlation_id:correlation},{onConflict:"correlation_id",ignoreDuplicates:true});if(error)throw error;}catch(error){console.error("[ORBIT][LOGISTICS_TIMELINE_BOUNDARY]",{projectId,action,error:error instanceof Error?error.message:String(error)});}}

export async function setEventLogisticsModeAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),mode=value(data,"mode");const{error}=await client.rpc("set_event_logistics_mode",{p_project_id:projectId,p_mode:mode});if(error)throw error;await timeline(client,projectId,"LOGISTICS_MODE_UPDATED","Necesidad logística actualizada",`Modo logístico: ${mode}.`,"Project",projectId,`logistics-mode:${projectId}:${mode}`);refresh(projectId);return{ok:true,message:"Necesidad logística actualizada."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function saveEventLogisticsSettingsAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId");const{error}=await client.rpc("save_event_logistics_settings",{p_project_id:projectId,p_changes:{reason:optional(data,"reason"),parkingStatus:optional(data,"parkingStatus"),maxAccessHeight:optional(data,"maxAccessHeight"),loadingAccess:optional(data,"loadingAccess"),notes:optional(data,"notes")}});if(error)throw error;refresh(projectId);return{ok:true,message:"Acceso e instrucciones logísticas actualizados."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function saveEventLogisticsTripAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),existing=optional(data,"tripId");const{data:tripId,error}=await client.rpc("save_event_logistics_trip",{p_project_id:projectId,p_trip_id:existing,p_asset_id:optional(data,"assetId"),p_driver_staff_id:optional(data,"driverStaffId"),p_driver_name:optional(data,"driverName"),p_trip_type:value(data,"tripType"),p_sequence:Number(value(data,"sequence")||1),p_origin:value(data,"origin"),p_destination:value(data,"destination"),p_planned_start_at:value(data,"plannedStartAt"),p_planned_end_at:value(data,"plannedEndAt"),p_meeting_point:optional(data,"meetingPoint"),p_instructions:optional(data,"instructions")});if(error)throw error;await timeline(client,projectId,existing?"LOGISTICS_TRIP_UPDATED":"LOGISTICS_TRIP_CREATED",existing?"Viaje logístico actualizado":"Viaje logístico creado",`${value(data,"origin")} → ${value(data,"destination")}.`,"VehicleTrip",String(tripId),`logistics-trip:${tripId}:${existing?"updated":"created"}`);refresh(projectId);return{ok:true,message:"Viaje guardado y disponibilidad confirmada."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function updateVehicleTripStatusAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),tripId=value(data,"tripId"),status=value(data,"status");const{error}=await client.rpc("update_vehicle_trip_status",{p_trip_id:tripId,p_status:status,p_odometer:value(data,"odometer")?Number(value(data,"odometer")):null});if(error)throw error;await timeline(client,projectId,`LOGISTICS_TRIP_${status}`,"Estado del viaje actualizado",`Viaje logístico: ${status}.`,"VehicleTrip",tripId,`logistics-trip-status:${tripId}:${status}`);refresh(projectId);return{ok:true,message:"Estado del viaje actualizado."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function addEventLogisticsExpenseAction(data:FormData):Promise<Result>{let uploadedPath="";try{const{client,userId}=await context(),projectId=value(data,"projectId"),tripId=value(data,"tripId"),category=value(data,"category"),total=Number(value(data,"total")),description=value(data,"description");if(!["FUEL","TOLLS","PARKING","TRANSPORT","OTHER_OPERATIONAL"].includes(category)||!projectId||!tripId||total<0)throw new Error("Completa tipo, viaje y monto.");if(category==="OTHER_OPERATIONAL"&&!description)throw new Error("Describe el otro gasto logístico.");const file=data.get("receipt");const fingerprintSource=[projectId,tripId,category,value(data,"date"),total,description,optional(data,"supplier"),file instanceof File?`${file.name}:${file.size}`:""].join("|");const idempotencyKey=Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(fingerprintSource))).toString("hex");const{count}=await client.from("expenses").select("id",{count:"exact",head:true}).eq("idempotency_key",idempotencyKey).is("deleted_at",null);if(count)throw new Error("Este gasto ya fue registrado. Revisa la lista antes de intentar nuevamente.");if(file instanceof File&&file.size>0){if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("El comprobante debe ser una foto o PDF.");uploadedPath=`logistics/${projectId}/${crypto.randomUUID()}.${file.name.split(".").pop()?.toLowerCase()||"bin"}`;const{error:uploadError}=await client.storage.from("orbit-expenses").upload(uploadedPath,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(uploadError)throw uploadError;}const{data:trip,error:tripError}=await client.from("vehicle_trips").select("asset_id").eq("id",tripId).eq("project_id",projectId).single();if(tripError)throw tripError;const metadata={associationType:"EVENT",associationId:projectId,vehicleTripId:tripId,expenseType:category,description,litres:optional(data,"litres")};const{data:created,error}=await client.from("expenses").insert({project_id:projectId,vehicle_trip_id:tripId,category,supplier:optional(data,"supplier"),occurred_on:value(data,"date"),subtotal:total,vat:0,total,status:"PENDING",receipt_path:uploadedPath||null,vehicle_id:trip.asset_id,idempotency_key:idempotencyKey,approval_reason:JSON.stringify(metadata),created_by:userId,updated_by:userId}).select("id").single();if(error)throw error;await calculateAndPersistRealEventCost(client,projectId);await timeline(client,projectId,"LOGISTICS_EXPENSE_ADDED","Gasto logístico agregado",`${category} · ${total}.`,"Expense",created.id,`logistics-expense:${created.id}`);refresh(projectId);return{ok:true,message:"Gasto logístico registrado como pendiente de revisión."};}catch(error){if(uploadedPath)try{const client=await createSupabaseServerClient();await client.storage.from("orbit-expenses").remove([uploadedPath]);}catch{}return{ok:false,error:friendly(error)};}}

export async function reviewEventLogisticsExpenseAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),expenseId=value(data,"expenseId"),status=value(data,"status");const{error}=await client.rpc("review_event_logistics_expense",{p_expense_id:expenseId,p_status:status});if(error)throw error;await calculateAndPersistRealEventCost(client,projectId);await timeline(client,projectId,"LOGISTICS_EXPENSE_REVIEWED","Gasto logístico revisado",`Resultado de revisión: ${status}.`,"Expense",expenseId,`logistics-expense-review:${expenseId}:${status}`);refresh(projectId);return{ok:true,message:"Gasto logístico revisado."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function closeEventLogisticsAction(data:FormData):Promise<Result>{try{const{client}=await context(),projectId=value(data,"projectId"),reason=optional(data,"overrideReason");const{error}=await client.rpc("close_event_logistics",{p_project_id:projectId,p_override_reason:reason});if(error)throw error;await timeline(client,projectId,"LOGISTICS_CLOSED","Logística cerrada",reason?`Cierre Founder con razón: ${reason}.`:"Todos los viajes y gastos quedaron resueltos.","Project",projectId,`logistics-closed:${projectId}`);refresh(projectId);return{ok:true,message:"Logística cerrada. El Evento permanece abierto para Phase F."};}catch(error){return{ok:false,error:friendly(error)};}}

export async function logisticsReceiptUrlAction(path:string):Promise<{ok:true;url:string}|{ok:false;error:string}>{try{const{client}=await context();const{data,error}=await client.storage.from("orbit-expenses").createSignedUrl(path,300);if(error)throw error;return{ok:true,url:data.signedUrl};}catch(error){return{ok:false,error:friendly(error)};}}
