"use client";

import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Car,ChevronDown,MapPinned,Plus,ReceiptText} from "lucide-react";
import {addEventLogisticsExpenseAction,closeEventLogisticsAction,reviewEventLogisticsExpenseAction,saveEventLogisticsSettingsAction,saveEventLogisticsTripAction,setEventLogisticsModeAction,updateVehicleTripStatusAction} from "./event-logistics.actions";

export type EventLogisticsData={projectId:string;mode:"NOT_REQUIRED"|"COMPANY_VEHICLE"|"STAFF_OWN"|"EXTERNAL";status:"NOT_REQUIRED"|"PENDING"|"PLANNED"|"IN_PROGRESS"|"COMPLETED";access:{reason:string;parkingStatus:string;maxHeight:number|null;loadingAccess:string;notes:string;contactName:string;contactPhone:string};summary:{tripCount:number;vehicleCount:number;fuel:number;tolls:number;parking:number;other:number;total:number};vehicles:readonly{id:string;label:string;available:boolean;height:number|null}[];drivers:readonly{id:string;label:string}[];trips:readonly{id:string;assetId:string|null;vehicle:string;driver:string;type:string;sequence:number;origin:string;destination:string;plannedStartAt:string;plannedEndAt:string;distance:number|null;status:string;meetingPoint:string;instructions:string}[];expenses:readonly{id:string;tripId:string;category:string;description:string;total:number;status:string;receipt:boolean}[]};
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const tripLabel:Record<string,string>={DELIVERY_ASSEMBLY:"Montaje / entrega",PICKUP_DISASSEMBLY:"Retiro / desmontaje",EVENT_OPERATION:"Operación / Evento",RETURN:"Regreso"};
const modeLabel:Record<string,string>={NOT_REQUIRED:"No requiere logística",COMPANY_VEHICLE:"Vehículo BOOMBOX",STAFF_OWN:"Staff va por su cuenta",EXTERNAL:"Transporte externo"};

export function EventLogisticsCenter({data}:{data:EventLogisticsData}){const router=useRouter();const[open,setOpen]=useState<"trip"|"expense"|null>(null);const[feedback,setFeedback]=useState("");const[pending,start]=useTransition();const run=(action:(form:FormData)=>Promise<{ok:boolean;message?:string;error?:string}>,form:FormData)=>start(async()=>{const result=await action(form);setFeedback(result.ok?result.message??"Guardado.":result.error??"No fue posible guardar.");if(result.ok){setOpen(null);router.refresh();}});return <section className="scroll-mt-24 rounded-2xl border bg-card p-4 sm:p-6" id="event-logistics">
  <header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-brand">Operations 1.0 · Phase E</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-semibold"><Car className="size-5"/>Logística</h2><p className="mt-2 text-sm text-muted">Vehículos, conductores, viajes y costo logístico real del Evento.</p></div><span className="w-fit rounded-full border px-3 py-1.5 text-xs font-semibold">{data.status.replaceAll("_"," ")}</span></header>
  <form action={form=>run(setEventLogisticsModeAction,form)} className="mt-5 flex flex-col gap-3 sm:flex-row"><input name="projectId" type="hidden" value={data.projectId}/><select className="min-h-11 flex-1 rounded-xl border bg-background px-3" defaultValue={data.mode} name="mode">{Object.entries(modeLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="min-h-11 rounded-xl border px-4 font-semibold" disabled={pending}>Guardar necesidad</button></form>
  <details className="mt-4 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Acceso, parking y contacto en terreno</summary><form action={form=>run(saveEventLogisticsSettingsAction,form)} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="projectId" type="hidden" value={data.projectId}/><Field label="Motivo / modalidad" name="reason" value={data.access.reason}/><Select label="Estacionamiento" name="parkingStatus" options={[["","Sin informar"],["AVAILABLE","Disponible"],["INCLUDED","Incluido"],["PAID","Pagado"],["UNAVAILABLE","No disponible"],["UNKNOWN","Desconocido"]]}/><Field label="Altura máxima de acceso (m)" name="maxAccessHeight" type="number" value={data.access.maxHeight?.toString()??""}/><Field label="Acceso carga / descarga" name="loadingAccess" value={data.access.loadingAccess}/><Field label="Instrucciones logísticas" name="notes" value={data.access.notes}/><div className="rounded-xl bg-accent/40 p-3 text-sm"><strong>Contacto en terreno</strong><p>{data.access.contactName||"Pendiente"}</p>{data.access.contactPhone?<a className="font-semibold text-brand" href={`tel:${data.access.contactPhone}`}>Llamar · {data.access.contactPhone}</a>:null}</div><button className="min-h-11 rounded-xl border px-4 font-semibold sm:col-span-2" disabled={pending}>Guardar información de acceso</button></form></details>
  <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Vehículos" value={String(data.summary.vehicleCount)}/><Metric label="Viajes" value={String(data.summary.tripCount)}/><Metric label="Combustible" value={money.format(data.summary.fuel)}/><Metric label="Peajes + parking" value={money.format(data.summary.tolls+data.summary.parking)}/><Metric featured label="Costo real" value={money.format(data.summary.total)}/></div>
  {data.mode!=="NOT_REQUIRED"?<div className="mt-5 flex flex-col gap-2 sm:flex-row"><button className="min-h-11 rounded-xl bg-brand px-4 font-semibold text-brand-foreground" onClick={()=>setOpen(open==="trip"?null:"trip")} type="button"><Plus className="mr-2 inline size-4"/>Crear viaje</button><button className="min-h-11 rounded-xl border px-4 font-semibold" disabled={!data.trips.length} onClick={()=>setOpen(open==="expense"?null:"expense")} type="button"><ReceiptText className="mr-2 inline size-4"/>Registrar gasto</button></div>:null}
  {open==="trip"?<TripForm data={data} disabled={pending} onSubmit={form=>run(saveEventLogisticsTripAction,form)}/>:null}
  {open==="expense"?<ExpenseForm data={data} disabled={pending} onSubmit={form=>run(addEventLogisticsExpenseAction,form)}/>:null}
  {feedback?<p className="mt-4 rounded-xl bg-accent/40 p-3 text-sm" role="status">{feedback}</p>:null}
  <div className="mt-6 space-y-3">{data.trips.map(trip=>{const vehicle=data.vehicles.find(item=>item.id===trip.assetId),heightConflict=Boolean(data.access.maxHeight&&vehicle?.height&&vehicle.height>data.access.maxHeight);return <article className="rounded-xl border p-4" key={trip.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{trip.sequence}. {tripLabel[trip.type]??trip.type}</p><p className="mt-1 text-sm text-muted">{trip.vehicle} · {trip.driver}</p><p className="mt-1 text-sm"><strong>Salida:</strong> {new Date(trip.plannedStartAt).toLocaleString("es-CL")} · <strong>Llegada:</strong> {new Date(trip.plannedEndAt).toLocaleString("es-CL")}</p></div><span className="w-fit rounded-full bg-accent px-2.5 py-1 text-xs font-semibold">{trip.status}</span></div>{heightConflict?<p className="mt-3 rounded-lg bg-warning/10 p-3 text-sm font-semibold text-warning">Advertencia: el vehículo ({vehicle?.height} m) supera la altura conocida del acceso ({data.access.maxHeight} m).</p>:null}<details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">Ver ruta y detalles</summary><div className="mt-2 space-y-1 text-muted"><p>{trip.origin} → {trip.destination}</p><p>Punto de encuentro: {trip.meetingPoint||"Pendiente"}</p><p>Kilómetros: {trip.distance??"Pendiente"}</p><p>{trip.instructions||"Sin instrucciones adicionales"}</p></div></details><div className="mt-4 flex flex-wrap gap-2">{trip.status==="PLANNED"?<TripStatus projectId={data.projectId} tripId={trip.id} status="IN_PROGRESS" label="Iniciar viaje" run={run}/>:null}{trip.status==="IN_PROGRESS"?<TripStatus projectId={data.projectId} tripId={trip.id} status="ARRIVED" label="Llegué" run={run}/>:null}{trip.status==="ARRIVED"?<TripStatus projectId={data.projectId} tripId={trip.id} status="COMPLETED" label="Finalizar viaje" run={run}/>:null}<a className="min-h-10 rounded-lg border px-3 py-2 text-sm font-semibold" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(trip.destination)}`} rel="noreferrer" target="_blank"><MapPinned className="mr-1 inline size-4"/>Abrir en Maps</a></div></article>})}{!data.trips.length&&data.mode!=="NOT_REQUIRED"?<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted">Logística pendiente: crea el primer viaje.</p>:null}</div>
  {data.expenses.length?<details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-semibold"><ChevronDown className="mr-2 inline size-4"/>Gastos logísticos ({data.expenses.length})</summary><div className="mt-3 divide-y">{data.expenses.map(expense=><div className="grid gap-3 py-3 text-sm sm:grid-cols-[1fr_auto]" key={expense.id}><div><p className="font-medium">{expense.description||expense.category}</p><p className="text-muted">{expense.status}{expense.receipt?" · Comprobante":""}</p></div><div className="flex flex-wrap items-center gap-2"><strong>{money.format(expense.total)}</strong>{expense.status==="PENDING"?<><ExpenseReview expenseId={expense.id} projectId={data.projectId} status="APPROVED" label="Aprobar" run={run}/><ExpenseReview expenseId={expense.id} projectId={data.projectId} status="REJECTED" label="Rechazar" run={run}/></>:null}</div></div>)}</div></details>:null}
  {data.mode!=="NOT_REQUIRED"&&data.status!=="COMPLETED"?<details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Cerrar logística</summary><p className="mt-2 text-sm text-muted">Completa viajes y revisa gastos. Para cerrar con pendientes, registra una razón Founder.</p><form action={form=>run(closeEventLogisticsAction,form)} className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto]"><input name="projectId" type="hidden" value={data.projectId}/><input className="min-h-11 rounded-xl border bg-background px-3" name="overrideReason" placeholder="Razón de override (solo si quedan pendientes)"/><button className="min-h-11 rounded-xl bg-brand px-4 font-semibold text-brand-foreground" disabled={pending}>Cerrar logística</button></form></details>:null}
 </section>}
function TripForm({data,disabled,onSubmit}:{data:EventLogisticsData;disabled:boolean;onSubmit:(form:FormData)=>void}){return <form action={onSubmit} className="mt-5 grid gap-3 rounded-xl border bg-background/30 p-4 sm:grid-cols-2"><input name="projectId" type="hidden" value={data.projectId}/><Select label="Tipo de viaje" name="tripType" options={Object.entries(tripLabel)}/><Field label="Secuencia" name="sequence" type="number" value={String(data.trips.length+1)}/><Select label="Vehículo" name="assetId" options={[["","Sin vehículo BOOMBOX"],...data.vehicles.map(v=>[v.id,`${v.label}${v.available?"":" · No disponible"}`])]}/><Select label="Conductor Staff" name="driverStaffId" options={[["","Founder / otro conductor"],...data.drivers.map(v=>[v.id,v.label])]}/><Field label="Founder / otro conductor" name="driverName"/><Field label="Origen" name="origin"/><Field label="Destino" name="destination"/><Field label="Salida planificada" name="plannedStartAt" type="datetime-local"/><Field label="Fin planificado" name="plannedEndAt" type="datetime-local"/><Field label="Punto de encuentro" name="meetingPoint"/><Field label="Instrucciones" name="instructions"/><button className="min-h-11 rounded-xl bg-brand px-4 font-semibold text-brand-foreground sm:col-span-2" disabled={disabled}>Confirmar viaje y disponibilidad</button></form>}
function ExpenseForm({data,disabled,onSubmit}:{data:EventLogisticsData;disabled:boolean;onSubmit:(form:FormData)=>void}){return <form action={onSubmit} className="mt-5 grid gap-3 rounded-xl border bg-background/30 p-4 sm:grid-cols-2"><input name="projectId" type="hidden" value={data.projectId}/><Select label="Viaje" name="tripId" options={data.trips.map(v=>[v.id,`${v.sequence}. ${tripLabel[v.type]??v.type}`])}/><Select label="Tipo" name="category" options={[["FUEL","Combustible"],["TOLLS","Peaje"],["PARKING","Estacionamiento"],["TRANSPORT","Transporte externo"],["OTHER_OPERATIONAL","Otro gasto de ruta"]]}/><Field label="Descripción" name="description"/><Field label="Proveedor / estación" name="supplier"/><Field label="Litros (opcional)" name="litres" type="number"/><Field label="Fecha" name="date" type="date"/><Field label="Monto" name="total" type="number"/><label className="text-sm sm:col-span-2">Comprobante opcional<input accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" className="mt-2 block w-full rounded-xl border bg-background p-2" name="receipt" type="file"/></label><button className="min-h-11 rounded-xl bg-brand px-4 font-semibold text-brand-foreground sm:col-span-2" disabled={disabled}>Guardar gasto pendiente</button></form>}
function TripStatus({projectId,tripId,status,label,run}:{projectId:string;tripId:string;status:string;label:string;run:(action:typeof updateVehicleTripStatusAction,form:FormData)=>void}){return <form action={form=>run(updateVehicleTripStatusAction,form)}><input name="projectId" type="hidden" value={projectId}/><input name="tripId" type="hidden" value={tripId}/><input name="status" type="hidden" value={status}/><button className="min-h-10 rounded-lg border px-3 text-sm font-semibold">{label}</button></form>}
function ExpenseReview({projectId,expenseId,status,label,run}:{projectId:string;expenseId:string;status:string;label:string;run:(action:typeof reviewEventLogisticsExpenseAction,form:FormData)=>void}){return <form action={form=>run(reviewEventLogisticsExpenseAction,form)}><input name="projectId" type="hidden" value={projectId}/><input name="expenseId" type="hidden" value={expenseId}/><input name="status" type="hidden" value={status}/><button className="min-h-9 rounded-lg border px-2 text-xs font-semibold">{label}</button></form>}
function Metric({label,value,featured=false}:{label:string;value:string;featured?:boolean}){return <div className={`rounded-xl border p-3 ${featured?"border-brand/40 bg-brand/5":""}`}><p className="text-xs text-muted">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
function Field({label,name,type="text",value=""}:{label:string;name:string;type?:string;value?:string}){return <label className="text-sm">{label}<input className="mt-2 min-h-11 w-full rounded-xl border bg-background px-3" defaultValue={value} name={name} required={!['driverName','meetingPoint','instructions','reason','maxAccessHeight','loadingAccess','notes','description','supplier','litres'].includes(name)} step={type==="number"?"any":undefined} type={type}/></label>}
function Select({label,name,options}:{label:string;name:string;options:(string[])[]}){return <label className="text-sm">{label}<select className="mt-2 min-h-11 w-full rounded-xl border bg-background px-3" name={name}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
