"use server";

import {revalidatePath} from "next/cache";
import {createSupabaseServerActionClient} from "@/lib/supabase/server";
import {deliverSmartAssignmentPackage} from "./smart-assignment-package.service";

type Result={ok:true;message:string}|{ok:false;message:string};
async function context(){const client=await createSupabaseServerActionClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Sesión requerida.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError||!["CEO","ADMINISTRATOR"].includes(profile?.role))throw new Error("Solo Administración puede asignar Staff.");return client;}
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();

export async function assignEventResponsibilityAction(data:FormData):Promise<Result>{try{const client=await context();const{error}=await client.rpc("assign_event_operational_responsibility",{p_project_id:value(data,"projectId"),p_staff_id:value(data,"staffId"),p_responsibility:value(data,"responsibility"),p_reason:"Asignación desde Centro de Operaciones"});if(error)throw error;revalidatePath("/operations");revalidatePath(`/projects/${value(data,"projectId")}`);return{ok:true,message:"Asignación guardada."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible guardar la asignación."};}}

export async function adjustEventRolePayAction(data:FormData):Promise<Result>{try{const client=await context();const paymentId=value(data,"paymentId"),role=value(data,"role"),amount=Number(data.get("amount")),reason=value(data,"reason");if(!paymentId||!Number.isFinite(amount)||amount<0||!reason)throw new Error("Ingresa un neto válido y el motivo del ajuste.");const{data:payment,error:readError}=await client.from("event_staff_payments").select("project_id,automatic_operator_payment,automatic_assembly_payment,automatic_disassembly_payment,operator_payment,assembly_payment,disassembly_payment").eq("id",paymentId).is("deleted_at",null).single();if(readError)throw readError;const original=role==="OPERATOR"?Number(payment.automatic_operator_payment||payment.operator_payment):role==="ASSEMBLY"?Number(payment.automatic_assembly_payment||payment.assembly_payment):Number(payment.automatic_disassembly_payment||payment.disassembly_payment),difference=amount-original;if(difference===0)throw new Error("El valor ingresado es igual al original; no requiere ajuste.");const{error}=await client.rpc("add_staff_settlement_adjustment",{p_settlement_id:paymentId,p_reason:"DIFFERENCE_CORRECTION",p_amount:difference,p_comment:reason});if(error)throw error;revalidatePath("/operations");revalidatePath(`/projects/${payment.project_id}`);revalidatePath("/resources/staff");revalidatePath("/finance");revalidatePath("/reports");return{ok:true,message:"Ajuste registrado sin alterar la liquidación original."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible ajustar el pago."};}}

export async function setStaffEventPublicationAction(data:FormData):Promise<Result>{try{const client=await context(),projectId=value(data,"projectId"),published=value(data,"published")==="true";const{data:project,error:projectError}=await client.from("projects").select("status,event_date,location,city,operations,customers(full_name),project_services(service_code,duration_hours)").eq("id",projectId).is("deleted_at",null).single();if(projectError)throw projectError;const closed=["COMPLETED","COMPLETED_EVENT","CLOSED","ARCHIVED","CANCELLED","Completed","Archived","Cancelled"].includes(project.status);if(published&&closed)throw new Error("Un Evento cerrado no puede recibir nuevas solicitudes de Staff.");const customer=Array.isArray(project.customers)?project.customers[0]:project.customers,services=Array.isArray(project.project_services)?project.project_services:[],operations=(project.operations??{})as Record<string,unknown>,address=String(operations.eventAddress??project.location??"");if(published&&(!project.event_date||!address||!project.city||!customer?.full_name||!services.some(item=>item.service_code&&Number(item.duration_hours)>0)))throw new Error("Completa fecha, ubicación, cliente, servicio y duración antes de activar el Evento para Staff.");const{error}=await client.rpc("set_staff_event_publication",{p_project_id:projectId,p_published:published});if(error)throw error;revalidatePath("/operations");revalidatePath("/resources/staff");revalidatePath(`/projects/${projectId}`);revalidatePath("/staff-portal");return{ok:true,message:published?"Evento activado y visible en Portal Staff.":"Evento desactivado. Las asignaciones confirmadas permanecen intactas."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible cambiar la publicación."};}}

export async function reviewStaffRequestAction(data:FormData):Promise<Result>{try{const client=await context(),approved=value(data,"decision")==="approve",requestId=value(data,"requestId");const{data:review,error}=await client.rpc("review_staff_assignment_request",{p_request_id:requestId,p_approved:approved,p_reason:approved?"Aprobada por Founder":"Rechazada por Founder"});if(error)throw error;if(approved&&(!review||String((review as Record<string,unknown>).status)!=="CONFIRMED"))throw new Error("La aprobación no confirmó la asignación y su liquidación.");let deliveryWarning="";if(approved){try{await deliverSmartAssignmentPackage(client,requestId);}catch(error){deliveryWarning=` La asignación y liquidación quedaron confirmadas, pero la entrega del paquete requiere atención: ${error instanceof Error?error.message:"error de comunicación"}.`;}}revalidatePath("/");revalidatePath("/operations");revalidatePath("/resources/staff");revalidatePath("/staff-portal");revalidatePath("/finance");revalidatePath("/finance/cash-flow");revalidatePath("/reports");return{ok:true,message:approved?`Aprobación completada: asignación y liquidación creadas; Portal, email, calendario y checklist preparados.${deliveryWarning}`:"Solicitud rechazada."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible revisar la solicitud."};}}
