"use client";

import Link from "next/link";
import {useState,useTransition} from "react";
import {adjustEventRolePayAction,assignEventResponsibilityAction,reviewStaffRequestAction,setStaffEventPublicationAction} from "./operations-planning.actions";

export type StaffOption={id:string;name:string;skills:string[]};
export type PlanningRole={code:"OPERATOR"|"ASSEMBLY"|"DISASSEMBLY";label:string;pay:number;paymentId:string|null;staffId:string|null;assignee:string|null;status:string};
export type PlanningEvent={id:string;date:string;customer:string;service:string;hours:number;address:string;district:string;venue:string;booths:number;roles:{operator:PlanningRole;assembly:PlanningRole;disassembly:PlanningRole};status:string;published:boolean};
export type PlanningRequest={id:string;staffName:string;customer:string;service:string;date:string;responsibility:string};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
const tax=(net:number)=>Math.round(net/(1-0.1525)-net);

export function OperationsPlanningBoard({events,staff,configuredPay}:{events:PlanningEvent[];staff:StaffOption[];configuredPay:{operator:number;assembly:number;disassembly:number;combined:number}}){
  const[pending,startTransition]=useTransition();const[message,setMessage]=useState("");
  const submit=(action:(data:FormData)=>Promise<{ok:boolean;message:string}>,data:FormData)=>startTransition(async()=>{const result=await action(data);setMessage(result.message);if(result.ok)location.reload();});
  return <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Centro de Operaciones</p><h1 className="mt-2 text-2xl font-semibold">Proyección · próximos 15 días</h1><p className="mt-2 text-sm text-muted">Una fila por evento. Asigna Operador, Montaje y Desmontaje sin usar Excel.</p></div><Link className="rounded-xl border px-4 py-2 text-sm font-semibold" href="/resources/staff">Administrar Staff</Link></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Rate label="Operador" value={configuredPay.operator}/><Rate label="Montaje" value={configuredPay.assembly}/><Rate label="Desmontaje" value={configuredPay.disassembly}/><Rate label="Montaje + Desmontaje" value={configuredPay.combined}/></div>{message?<p className="mt-4 rounded-xl border border-brand/20 bg-brand/10 p-3 text-sm" role="status">{message}</p>:null}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-xs"><thead className="text-muted"><tr>{["Fecha","Cliente","Servicio","Horas","Dirección","Comuna","Lugar","Cabinas","Operador","Montaje","Desmontaje","Estado"].map(label=><th className="whitespace-nowrap pb-3 pr-5 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{events.map(event=><tr className="border-t align-top" key={event.id}><td className="whitespace-nowrap py-4 pr-5"><Link className="font-semibold text-brand" href={`/projects/${event.id}`}>{event.date}</Link></td><td className="pr-5 font-medium">{event.customer}</td><td className="pr-5">{event.service}</td><td className="pr-5">{event.hours}</td><td className="max-w-52 pr-5">{event.address}</td><td className="pr-5">{event.district}</td><td className="max-w-44 pr-5">{event.venue}</td><td className="pr-5">{event.booths}</td><RoleCell eventId={event.id} role={event.roles.operator} staff={staff} pending={pending} submit={submit}/><RoleCell eventId={event.id} role={event.roles.assembly} staff={staff} pending={pending} submit={submit}/><RoleCell eventId={event.id} role={event.roles.disassembly} staff={staff} pending={pending} submit={submit}/><td><span className="rounded-full bg-brand/10 px-2 py-1 font-semibold text-brand">{event.status}</span></td></tr>)}</tbody></table>{events.length===0?<p className="py-10 text-center text-sm text-muted">No hay eventos durante los próximos 15 días.</p>:null}</div><div className="mt-5 rounded-2xl border p-4"><p className="text-sm font-semibold">Asignación combinada</p><p className="mt-1 text-xs text-muted">Montaje + Desmontaje utiliza siempre la tarifa combinada configurada, no la suma manual.</p><CombinedAssignment events={events} staff={staff} pending={pending} submit={submit}/></div></section>;
}
function Rate({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-background/40 p-3"><p className="text-xs text-muted">☐ {label}</p><p className="mt-1 font-semibold">Neto · {money(value)}</p></div>}
export function OperationsStaffPortalControl({events,requests}:{events:PlanningEvent[];requests:PlanningRequest[]}){const[pending,startTransition]=useTransition();const[message,setMessage]=useState("");const submit=(action:(data:FormData)=>Promise<{ok:boolean;message:string}>,data:FormData)=>startTransition(async()=>{const result=await action(data);setMessage(result.message);if(result.ok)location.reload()});return <section className="rounded-3xl border bg-card p-5 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Portal Staff</p><h2 className="mt-2 text-xl font-semibold">Publicación y solicitudes</h2><p className="mt-1 text-sm text-muted">Publica eventos y aprueba responsabilidades antes de convertirlas en asignaciones.</p></div>{message?<p className="mt-4 rounded-xl border border-brand/20 bg-brand/10 p-3 text-sm">{message}</p>:null}<div className="mt-5 grid gap-4 xl:grid-cols-2"><div><h3 className="font-semibold">Eventos próximos</h3><div className="mt-3 space-y-2">{events.map(event=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3" key={event.id}><div><p className="text-sm font-semibold">{event.date} · {event.customer}</p><p className="text-xs text-muted">{event.service}</p></div><form action={data=>submit(setStaffEventPublicationAction,data)}><input name="projectId" type="hidden" value={event.id}/><input name="published" type="hidden" value={String(!event.published)}/><button className={`rounded-lg px-3 py-2 text-xs font-semibold ${event.published?"border":"bg-brand text-brand-foreground"}`} disabled={pending}>{event.published?"Retirar del Portal":"Publicar para Staff"}</button></form></div>)}</div></div><div><h3 className="font-semibold">Solicitudes pendientes</h3><div className="mt-3 space-y-2">{requests.map(item=><div className="rounded-xl border p-3" key={item.id}><p className="text-sm font-semibold">{item.staffName} · {item.responsibility}</p><p className="mt-1 text-xs text-muted">{item.customer} · {item.service} · {item.date}</p><form action={data=>submit(reviewStaffRequestAction,data)} className="mt-3 flex gap-2"><input name="requestId" type="hidden" value={item.id}/><button className="rounded-lg bg-brand px-3 py-2 text-xs font-semibold text-brand-foreground" disabled={pending} name="decision" value="approve">Aprobar</button><button className="rounded-lg border px-3 py-2 text-xs font-semibold" disabled={pending} name="decision" value="reject">Rechazar</button></form></div>)}{requests.length===0?<p className="text-sm text-muted">No hay solicitudes pendientes.</p>:null}</div></div></div></section>}
function RoleCell({eventId,role,staff,pending,submit}:{eventId:string;role:PlanningRole;staff:StaffOption[];pending:boolean;submit:(action:(data:FormData)=>Promise<{ok:boolean;message:string}>,data:FormData)=>void}){const eligible=staff.filter(member=>member.skills.includes(role.code));if(!role.assignee)return <td className="min-w-56 pr-5"><form action={data=>submit(assignEventResponsibilityAction,data)} className="space-y-2"><input name="projectId" type="hidden" value={eventId}/><input name="responsibility" type="hidden" value={role.code}/><select aria-label={`Asignar ${role.label}`} className="h-9 w-full rounded-lg border bg-background px-2" name="staffId" required defaultValue=""><option value="">Sin asignar</option>{eligible.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select><button className="text-xs font-semibold text-brand disabled:opacity-50" disabled={pending}>Asignar · {money(role.pay)}</button></form></td>;const roleTax=tax(role.pay);return <td className="min-w-56 pr-5"><p className="font-semibold text-emerald-500">{role.assignee}</p><p className="mt-1">{role.label} · Neto {money(role.pay)}</p><p className="text-muted">Impuesto {money(roleTax)} · Empresa {money(role.pay+roleTax)}</p>{role.paymentId?<details className="mt-2"><summary className="cursor-pointer font-semibold text-brand">Ajustar este evento</summary><form action={data=>submit(adjustEventRolePayAction,data)} className="mt-2 space-y-2"><input name="paymentId" type="hidden" value={role.paymentId}/><input name="role" type="hidden" value={role.code}/><input className="h-8 w-full rounded border bg-background px-2" defaultValue={role.pay} min="0" name="amount" type="number"/><input className="h-8 w-full rounded border bg-background px-2" name="reason" placeholder="Motivo obligatorio" required/><button className="font-semibold text-brand" disabled={pending}>Guardar ajuste</button></form></details>:null}</td>}
function CombinedAssignment({events,staff,pending,submit}:{events:PlanningEvent[];staff:StaffOption[];pending:boolean;submit:(action:(data:FormData)=>Promise<{ok:boolean;message:string}>,data:FormData)=>void}){const eligible=staff.filter(member=>member.skills.includes("ASSEMBLY")&&member.skills.includes("DISASSEMBLY"));return <form action={data=>submit(assignEventResponsibilityAction,data)} className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input name="responsibility" type="hidden" value="ASSEMBLY_DISASSEMBLY"/><select className="h-10 rounded-lg border bg-background px-3" name="projectId" required defaultValue=""><option value="">Seleccionar evento</option>{events.map(event=><option key={event.id} value={event.id}>{event.date} · {event.customer}</option>)}</select><select className="h-10 rounded-lg border bg-background px-3" name="staffId" required defaultValue=""><option value="">Seleccionar Staff</option>{eligible.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select><button className="rounded-lg bg-brand px-4 text-sm font-semibold text-brand-foreground disabled:opacity-50" disabled={pending}>Asignar combinación</button></form>}
