"use server";

import {revalidatePath} from "next/cache";
import {createSupabaseServerClient} from "@/lib/supabase/server";

type Result={ok:true;message:string}|{ok:false;message:string};
async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Sesión requerida.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError||!["CEO","ADMINISTRATOR"].includes(profile?.role))throw new Error("Solo Administración puede asignar Staff.");return client;}
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();

export async function assignEventResponsibilityAction(data:FormData):Promise<Result>{try{const client=await context();const{error}=await client.rpc("assign_event_operational_responsibility",{p_project_id:value(data,"projectId"),p_staff_id:value(data,"staffId"),p_responsibility:value(data,"responsibility"),p_reason:"Asignación desde Centro de Operaciones"});if(error)throw error;revalidatePath("/operations");revalidatePath(`/projects/${value(data,"projectId")}`);return{ok:true,message:"Asignación guardada."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible guardar la asignación."};}}

export async function adjustEventRolePayAction(data:FormData):Promise<Result>{try{const client=await context();const paymentId=value(data,"paymentId"),role=value(data,"role"),amount=Number(data.get("amount")),reason=value(data,"reason");if(!paymentId||!Number.isFinite(amount)||amount<0||!reason)throw new Error("Ingresa un neto válido y el motivo del ajuste.");const{data:payment,error:readError}=await client.from("event_staff_payments").select("project_id,operator_payment,assembly_payment,disassembly_payment").eq("id",paymentId).is("deleted_at",null).single();if(readError)throw readError;const operator=role==="OPERATOR"?amount:Number(payment.operator_payment),assembly=role==="ASSEMBLY"?amount:Number(payment.assembly_payment),disassembly=role==="DISASSEMBLY"?amount:Number(payment.disassembly_payment);const{error}=await client.rpc("set_staff_payment_override",{p_payment_id:paymentId,p_operator:operator,p_assembly:assembly,p_disassembly:disassembly,p_reason:reason});if(error)throw error;revalidatePath("/operations");revalidatePath(`/projects/${payment.project_id}`);return{ok:true,message:"Neto actualizado solo para este evento."};}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible ajustar el pago."};}}
