import Link from "next/link";

export type PlanningRole={label:string;pay:number;assignee:string|null;status:string};
export type PlanningEvent={id:string;date:string;customer:string;eventType:string;service:string;hours:number;address:string;district:string;venue:string;booths:number;roles:{operator:PlanningRole;assembly:PlanningRole;disassembly:PlanningRole};status:string};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);

export function OperationsPlanningBoard({events}:{events:PlanningEvent[]}){
  return <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Centro de Operaciones</p><h1 className="mt-2 text-2xl font-semibold">Planificación · próximos 15 días</h1><p className="mt-2 text-sm text-muted">Una fila por evento. Los cupos se bloquean al ser tomados desde Portal Staff.</p></div><Link className="rounded-xl border px-4 py-2 text-sm font-semibold" href="/resources/staff">Administrar Staff</Link></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1700px] text-left text-xs"><thead className="text-muted"><tr>{["Fecha","Cliente","Tipo","Servicio","Horas","Dirección","Comuna","Lugar","Cabinas","Pago operador","Pago montaje","Pago desmontaje","Operador","Montaje","Desmontaje","Estado"].map(label=><th className="whitespace-nowrap pb-3 pr-5 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{events.map(event=><tr className="border-t align-top" key={event.id}><td className="whitespace-nowrap py-4 pr-5"><Link className="font-semibold text-brand" href={`/projects/${event.id}`}>{event.date}</Link></td><td className="pr-5 font-medium">{event.customer}</td><td className="pr-5">{event.eventType}</td><td className="pr-5">{event.service}</td><td className="pr-5">{event.hours}</td><td className="max-w-52 pr-5">{event.address}</td><td className="pr-5">{event.district}</td><td className="max-w-44 pr-5">{event.venue}</td><td className="pr-5">{event.booths}</td><td className="pr-5">{money(event.roles.operator.pay)}</td><td className="pr-5">{money(event.roles.assembly.pay)}</td><td className="pr-5">{money(event.roles.disassembly.pay)}</td><RoleCell role={event.roles.operator}/><RoleCell role={event.roles.assembly}/><RoleCell role={event.roles.disassembly}/><td><span className="rounded-full bg-brand/10 px-2 py-1 font-semibold text-brand">{event.status}</span></td></tr>)}</tbody></table>{!events.length&&<p className="py-10 text-center text-sm text-muted">No hay eventos durante los próximos 15 días.</p>}</div></section>;
}
function RoleCell({role}:{role:PlanningRole}){const label=role.assignee??"Sin asignar";const tone=role.assignee?"text-emerald-500":"text-amber-500";return <td className="pr-5"><p className={`whitespace-nowrap font-semibold ${tone}`}>{label}</p><p className="mt-1 text-[11px] text-muted">{role.assignee?role.status:"Disponible"}</p></td>}
