import "server-only";
import type {SupabaseClient} from "@supabase/supabase-js";
import {GoogleGmailApiProvider} from "@/features/connectors/google-gmail/provider/google-gmail-live.provider";
import {loadGoogleWorkspaceAccessToken} from "@/features/connectors/google-workspace/application/google-workspace.repository";

type Client=SupabaseClient;
type ServiceRow={service_code:string|null;duration_hours:number|null;extras:unknown};
const html=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]??char));
const role=(value:string)=>({OPERATOR:"Operador",ASSEMBLY:"Montaje",DISASSEMBLY:"Desmontaje",ASSEMBLY_DISASSEMBLY:"Montaje + Desmontaje"}[value]??value);
const appUrl=()=>process.env.NEXT_PUBLIC_APP_URL??"https://orbit.boom-box.cl";
const finish=(time:string,hours:number)=>{const[h,m]=time.slice(0,5).split(":").map(Number),total=h*60+m+hours*60;return`${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`};

export async function deliverSmartAssignmentPackage(client:Client,requestId:string){
  const{data:request,error}=await client.from("staff_assignment_requests").select("id,project_id,staff_id,responsibility,staff(first_name,last_name,email),projects(id,name,customer_id,orbit_event_id,project_type,event_date,event_time,location,city,operations,customers(full_name,phone),project_services(service_code,duration_hours,extras))").eq("id",requestId).single();
  if(error||!request)throw error??new Error("No fue posible preparar el paquete operacional.");
  const staff=Array.isArray(request.staff)?request.staff[0]:request.staff,project=Array.isArray(request.projects)?request.projects[0]:request.projects;
  if(!project||!staff)throw new Error("La asignación no contiene Staff o Evento válido.");
  const services=(Array.isArray(project.project_services)?project.project_services:[])as ServiceRow[],customer=Array.isArray(project.customers)?project.customers[0]:project.customers,ops=(project.operations??{})as Record<string,unknown>;
  const address=String(ops.eventAddress??project.location??"Dirección por confirmar"),start=project.event_time?.slice(0,5)??"00:00",hours=Number(services[0]?.duration_hours??0),end=finish(start,hours),maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${address}, ${project.city??""}`)}`,portal=`${appUrl()}/login?access=staff`,calendar=googleCalendarUrl({title:`BOOMBOX · ${customer?.full_name??project.name}`,date:project.event_date,start,end,address,description:`Servicio: ${services.map(item=>item.service_code).filter(Boolean).join(" + ")}\nCliente: ${customer?.full_name??project.name}\nTeléfono: ${customer?.phone??"Por confirmar"}\nORBIT Event ID: ${project.orbit_event_id}`});
  const correlation=`smart-assignment:${request.id}`;
  const audit=async(action:string,title:string,description:string)=>{const{error:auditError}=await client.from("timeline_events").upsert({customer_id:project.customer_id,project_id:project.id,staff_id:request.staff_id,orbit_event_id:project.orbit_event_id,event_type:action,title,description,actor_label:"ORBIT",source:"StaffAssignment",action,entity_type:"AssignmentRequest",entity_id:request.id,human_message:description,correlation_id:`${correlation}:${action.toLowerCase()}`},{onConflict:"correlation_id",ignoreDuplicates:true});if(auditError)throw auditError};
  const{error:notificationError}=await client.from("internal_notifications").upsert({project_id:project.id,customer_id:project.customer_id,staff_id:request.staff_id,notification_type:"SMART_ASSIGNMENT_PACKAGE",title:"Nuevo evento asignado",message:`${customer?.full_name??project.name} · ${project.event_date} · ${role(request.responsibility)}`,status:"UNREAD",correlation_id:correlation,category:"OPERATIONS",priority:"HIGH",action_required:true,entity_type:"AssignmentRequest",entity_id:request.id,related_href:"/staff-portal",metadata:{delivery_status:"PENDING",portal,calendar,maps}},{onConflict:"correlation_id",ignoreDuplicates:true});
  if(notificationError)throw notificationError;
  await audit("PORTAL_UPDATED","Portal Staff actualizado","El Evento confirmado quedó disponible en Portal Staff.");
  await audit("CHECKLIST_CREATED","Checklist preparado","ORBIT preparó el checklist operacional del Evento.");
  const{data:notification}=await client.from("internal_notifications").select("id,metadata").eq("correlation_id",correlation).single();
  if(!notification)return{emailSent:false,alreadyDelivered:false};
  const deliveryStatus=String((notification.metadata as Record<string,unknown>|null)?.delivery_status??"");if(deliveryStatus==="SENT")return{emailSent:false,alreadyDelivered:true};
  if(!staff.email){await client.from("internal_notifications").update({metadata:{delivery_status:"NO_EMAIL",portal,calendar,maps}}).eq("id",notification.id);return{emailSent:false,alreadyDelivered:false};}
  const service=services.map(item=>item.service_code).filter(Boolean).join(" + ")||"Servicio BOOMBOX",productionName=String(ops.productionContact??ops.productionName??"BOOMBOX Producción"),productionPhone=String(ops.productionPhone??ops.contactPhone??"Por confirmar");
  try{
    const sent=await new GoogleGmailApiProvider(await loadGoogleWorkspaceAccessToken()).send({to:staff.email,subject:"You have been assigned to a BOOMBOX event",textBody:`Hola ${staff.first_name}. Tu asignación BOOMBOX fue confirmada.\n\nServicio: ${service}\nCliente: ${customer?.full_name??project.name}\nFecha: ${project.event_date}\nHorario: ${start}–${end}\nUbicación: ${address}, ${project.city??""}\nGoogle Maps: ${maps}\nContacto cliente: ${customer?.phone??"Por confirmar"}\nProducción: ${productionName} · ${productionPhone}\nRol: ${role(request.responsibility)}\nORBIT Event ID: ${project.orbit_event_id}\n\nPortal Staff: ${portal}\nCalendario: ${calendar}`,htmlBody:`<main style="font-family:Arial,sans-serif;color:#171717;line-height:1.6"><h1>Nuevo Evento asignado</h1><p>Hola ${html(staff.first_name)}, tu asignación BOOMBOX fue confirmada por el Founder.</p><p><strong>Servicio:</strong> ${html(service)}<br><strong>Cliente:</strong> ${html(customer?.full_name??project.name)}<br><strong>Fecha:</strong> ${html(project.event_date)}<br><strong>Horario:</strong> ${html(start)}–${html(end)}<br><strong>Ubicación:</strong> ${html(address)}, ${html(project.city)}<br><strong>Contacto cliente:</strong> ${html(customer?.phone??"Por confirmar")}<br><strong>Producción:</strong> ${html(productionName)} · ${html(productionPhone)}<br><strong>Rol:</strong> ${html(role(request.responsibility))}<br><strong>ORBIT Event ID:</strong> ${html(project.orbit_event_id)}</p><p><a href="${portal}" style="display:inline-block;background:#F78900;color:#111;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:10px">Abrir Portal Staff</a> &nbsp; <a href="${calendar}">Agregar al calendario</a></p><p><a href="${maps}">Abrir ruta en Google Maps</a></p></main>`,driveFileIds:[]});
    await client.from("internal_notifications").update({metadata:{delivery_status:"SENT",message_id:sent.messageId,thread_id:sent.threadId,portal,calendar,maps,sent_at:new Date().toISOString()}}).eq("id",notification.id);
    await audit("STAFF_EMAIL_SENT","Email enviado","ORBIT envió el paquete operacional al colaborador.");
    await audit("STAFF_CALENDAR_CREATED","Calendario creado","ORBIT generó la invitación compatible con Google, Apple y Outlook.");
    const{data:assignmentRows}=await client.from("assignments").select("id,resources").eq("project_id",project.id).eq("staff_id",request.staff_id).is("deleted_at",null).not("status","in",'(CANCELLED,REJECTED)');
    for(const assignment of assignmentRows??[]){await client.from("assignments").update({resources:{...((assignment.resources??{})as Record<string,unknown>),smartAssignment:{portal:"ACCEPTED",email:"SENT",calendar:"SENT",checklist:"PENDING",requestId:request.id,updatedAt:new Date().toISOString()}}}).eq("id",assignment.id)}
    return{emailSent:true,alreadyDelivered:false};
  }catch(emailError){await client.from("internal_notifications").update({metadata:{delivery_status:"FAILED",error:emailError instanceof Error?emailError.message:"Unknown",portal,calendar,maps}}).eq("id",notification.id);await audit("STAFF_EMAIL_FAILED","Email pendiente","La asignación quedó confirmada, pero el email requiere revisión.");throw emailError;}
}

function googleCalendarUrl(input:{title:string;date:string;start:string;end:string;address:string;description:string}){const compact=(date:string,time:string)=>`${date.replaceAll("-","")}T${time.replace(":","")}00`;return`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(input.title)}&dates=${compact(input.date,input.start)}/${compact(input.date,input.end)}&details=${encodeURIComponent(input.description)}&location=${encodeURIComponent(input.address)}`;}
