import "server-only";
import type {SupabaseClient} from "@supabase/supabase-js";
import {GoogleGmailApiProvider} from "@/features/connectors/google-gmail/provider/google-gmail-live.provider";
import {loadGoogleWorkspaceAccessToken} from "@/features/connectors/google-workspace/application/google-workspace.repository";
import {assignmentNotificationFingerprint,assignmentRoleLabel as role,buildStaffAssignmentEmail,chileAssignmentDateTime as chile} from "./staff-assignment-notification.model";

type Mail={to:string;subject:string;textBody:string;htmlBody:string;driveFileIds:string[]};
type Sender={send(message:Mail):Promise<{messageId:string;threadId:string}>};
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]??char));

export async function deliverStaffAssignmentNotification(client:SupabaseClient,assignmentId:string,sender?:Sender){
  const{data:assignment,error}=await client.from("assignments").select("id,project_id,staff_id,assignment_type,status,staff_call_at,staff(first_name,last_name,email,status,deleted_at),projects(id,customer_id,name,orbit_event_id,event_date,event_time,location,city)").eq("id",assignmentId).is("deleted_at",null).single();
  if(error||!assignment)throw error??new Error("Asignación no encontrada.");
  const staff=Array.isArray(assignment.staff)?assignment.staff[0]:assignment.staff,project=Array.isArray(assignment.projects)?assignment.projects[0]:assignment.projects;
  if(!staff||staff.status!=="ACTIVE"||staff.deleted_at)throw new Error("El Staff no está activo.");
  if(!project)throw new Error("Evento no encontrado.");
  const{data:contract}=await client.from("project_operational_contracts").select("service_start_at,service_end_at,staff_arrival_at").eq("project_id",project.id).maybeSingle();
  const call=assignment.staff_call_at??contract?.staff_arrival_at??null,start=contract?.service_start_at??null,end=contract?.service_end_at??null,location=[project.location,project.city].filter(Boolean).join(" · ")||null;
  const fingerprint=assignmentNotificationFingerprint({assignmentId:assignment.id,staffId:assignment.staff_id,role:assignment.assignment_type,staffCallAt:call,serviceStartAt:start,serviceEndAt:end,location});
  const correlation=`staff-assignment-delivery:${assignment.id}:${fingerprint}`,portal=`${process.env.NEXT_PUBLIC_APP_URL??"https://orbit.boom-box.cl"}/login?access=staff`;
  const{data:notification,error:notificationError}=await client.from("internal_notifications").upsert({project_id:project.id,customer_id:project.customer_id,staff_id:assignment.staff_id,notification_type:"STAFF_ASSIGNMENT_NOTIFICATION",title:"Nueva asignación pendiente de confirmación",message:`${staff.first_name} ${staff.last_name} · ${role(assignment.assignment_type)} · ${project.orbit_event_id} · Citación ${chile(call)}`,status:"UNREAD",correlation_id:correlation,category:"STAFF",priority:"HIGH",action_required:true,entity_type:"Assignment",entity_id:assignment.id,related_href:`/projects/${project.id}#staff-assignment`,metadata:{delivery_status:"NOTIFICATION_CREATED",fingerprint,staff_call_at:call,service_start_at:start,service_end_at:end,portal}},{onConflict:"correlation_id",ignoreDuplicates:true}).select("id,metadata").maybeSingle();
  if(notificationError)throw notificationError;
  const existing=notification??(await client.from("internal_notifications").select("id,metadata").eq("correlation_id",correlation).single()).data;
  if(!existing)return{status:"FAILED" as const};
  const prior=String((existing.metadata as Record<string,unknown>|null)?.delivery_status??"");
  if(prior==="EMAIL_SENT")return{status:"SKIPPED" as const};
  if(!staff.email){await client.from("internal_notifications").update({metadata:{delivery_status:"EMAIL_FAILED",fingerprint,error_code:"STAFF_EMAIL_MISSING",staff_call_at:call,service_start_at:start,service_end_at:end,portal}}).eq("id",existing.id);return{status:"FAILED" as const};}
  const message=buildStaffAssignmentEmail({staffName:`${staff.first_name} ${staff.last_name}`.trim(),eventName:project.name,orbitEventId:project.orbit_event_id,role:assignment.assignment_type,staffCallAt:call,serviceStartAt:start,serviceEndAt:end,location,portalUrl:portal});
  try{const provider=sender??new GoogleGmailApiProvider(await loadGoogleWorkspaceAccessToken());const sent=await provider.send({...message,to:staff.email});await client.from("internal_notifications").update({metadata:{delivery_status:"EMAIL_SENT",fingerprint,message_id:sent.messageId,thread_id:sent.threadId,sent_at:new Date().toISOString(),staff_call_at:call,service_start_at:start,service_end_at:end,portal}}).eq("id",existing.id);return{status:"SENT" as const};}
  catch(mailError){const reason=mailError instanceof Error?mailError.message:"Provider error";await client.from("internal_notifications").update({metadata:{delivery_status:"EMAIL_FAILED",fingerprint,error_code:"EMAIL_PROVIDER",error:reason,staff_call_at:call,service_start_at:start,service_end_at:end,portal}}).eq("id",existing.id);await client.from("internal_notifications").upsert({project_id:project.id,customer_id:project.customer_id,staff_id:assignment.staff_id,notification_type:"STAFF_ASSIGNMENT_EMAIL_FAILED",title:"Falló email de asignación Staff",message:`${staff.first_name} ${staff.last_name} · ${project.orbit_event_id}`,status:"UNREAD",correlation_id:`${correlation}:failed`,category:"OPERATIONS",priority:"HIGH",action_required:true,entity_type:"Assignment",entity_id:assignment.id,related_href:`/projects/${project.id}#staff-assignment`,metadata:{delivery_status:"EMAIL_FAILED",reason,notification_id:existing.id}},{onConflict:"correlation_id"});return{status:"FAILED" as const};}
}

export async function notifyOperationsOfStaffRejection(client:SupabaseClient,input:{projectId:string;staffId:string;assignmentIds:string[];reason:string}){
  const[{data:settings},{data:staff},{data:project}]=await Promise.all([client.from("company_settings").select("operations_email").eq("settings_key","PRIMARY").single(),client.from("staff").select("first_name,last_name").eq("id",input.staffId).single(),client.from("projects").select("name,orbit_event_id").eq("id",input.projectId).single()]);
  if(!settings?.operations_email||!staff||!project)return{status:"NO_RECIPIENT" as const};
  const correlation=`staff-rejected-email:${input.assignmentIds.sort().join(":")}`;
  const{data:existing}=await client.from("internal_notifications").select("id,metadata").eq("correlation_id",correlation).maybeSingle();if(String((existing?.metadata as Record<string,unknown>|null)?.delivery_status??"")==="EMAIL_SENT")return{status:"SKIPPED" as const};
  const{data:row}=existing?{data:existing}:await client.from("internal_notifications").insert({project_id:input.projectId,staff_id:input.staffId,notification_type:"STAFF_REJECTION_OPERATIONS_EMAIL",title:"Staff rechazó una asignación",message:`${staff.first_name} ${staff.last_name} · ${project.orbit_event_id} · ${input.reason}`,status:"UNREAD",correlation_id:correlation,category:"OPERATIONS",priority:"HIGH",action_required:true,entity_type:"Assignment",entity_id:input.assignmentIds[0],related_href:`/projects/${input.projectId}#staff-assignment`,metadata:{delivery_status:"EMAIL_QUEUED"}}).select("id,metadata").single();
  try{const sent=await new GoogleGmailApiProvider(await loadGoogleWorkspaceAccessToken()).send({to:settings.operations_email,subject:`Staff rechazó asignación · ${project.orbit_event_id}`,textBody:`${staff.first_name} ${staff.last_name} rechazó ${project.name}. Motivo: ${input.reason}`,htmlBody:`<main><h1>Staff rechazó una asignación</h1><p>${escape(staff.first_name)} ${escape(staff.last_name)} rechazó ${escape(project.name)}.</p><p><strong>Motivo:</strong> ${escape(input.reason)}</p></main>`,driveFileIds:[]});await client.from("internal_notifications").update({metadata:{delivery_status:"EMAIL_SENT",message_id:sent.messageId,sent_at:new Date().toISOString()}}).eq("id",row!.id);return{status:"SENT" as const};}catch(error){await client.from("internal_notifications").update({metadata:{delivery_status:"EMAIL_FAILED",error:error instanceof Error?error.message:"Provider error"}}).eq("id",row!.id);return{status:"FAILED" as const};}
}
