import type{SupabaseClient}from"@supabase/supabase-js";
export interface RealEventCostSummary{projectId:string;calculatedAt:string;status:"CALCULATED"|"PENDING_REVENUE";revenue:{contractedService:number;extras:number;transport:number;discount:number;finalSaleValue:number};costs:{operator:number;setup:number;teardown:number;staffOther:number;allocatedFuel:number;paper:number;magnets:number;scrapbook:number;branding:number;vehicle:number;otherExpenses:number;totalOperationalCost:number};profit:{grossProfit:number;grossMarginPercent:number;netProfit:number;netMarginPercent:number};history:{originalRevenue:number;originalCost:number;finalRevenue:number;finalCost:number;calculationTimestamp:string}}
const n=(value:unknown)=>Number(value??0);
export async function calculateAndPersistRealEventCost(client:SupabaseClient,projectId:string):Promise<RealEventCostSummary>{
 const{data,error}=await client.from("financial_event_records").select("project_id,status,revenue,real_cost,gross_profit,gross_margin,net_profit,net_margin,cost_breakdown,traceability,calculated_at").eq("project_id",projectId).maybeSingle();if(error)throw error;
 const costs=(data?.cost_breakdown??{})as Record<string,unknown>;const trace=(data?.traceability??{})as Record<string,unknown>;const revenue=n(data?.revenue),real=n(data?.real_cost),operator=n(costs.operator),setup=n(costs.assembly),fuel=n(costs.fuel),paper=n(costs.paper),magnets=n(costs.magnets),scrapbook=n(costs.scrapbook),other=n(costs.configuredOther)+n(costs.registeredExpenses)+n(costs.inventory);
 return{projectId,calculatedAt:data?.calculated_at??new Date(0).toISOString(),status:data?.status==="CONFIRMED"?"CALCULATED":"PENDING_REVENUE",revenue:{contractedService:revenue,extras:0,transport:0,discount:0,finalSaleValue:revenue},costs:{operator,setup,teardown:0,staffOther:0,allocatedFuel:fuel,paper,magnets,scrapbook,branding:0,vehicle:0,otherExpenses:other,totalOperationalCost:real},profit:{grossProfit:n(data?.gross_profit),grossMarginPercent:n(data?.gross_margin),netProfit:n(data?.net_profit),netMarginPercent:n(data?.net_margin)},history:{originalRevenue:n(trace.originalRevenue??revenue),originalCost:n(trace.originalCost??real),finalRevenue:revenue,finalCost:real,calculationTimestamp:data?.calculated_at??new Date(0).toISOString()}};
}
export async function refreshRealEventCosts(client:SupabaseClient):Promise<readonly RealEventCostSummary[]>{const{data,error}=await client.from("financial_event_records").select("project_id");if(error)throw error;return Promise.all((data??[]).map(row=>calculateAndPersistRealEventCost(client,row.project_id)));}
