import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";

export interface RealEventCostSummary {
  projectId:string;calculatedAt:string;status:"CALCULATED"|"PENDING_REVENUE";
  revenue:{contractedService:number;extras:number;transport:number;discount:number;finalSaleValue:number};
  costs:{operator:number;setup:number;teardown:number;staffOther:number;allocatedFuel:number;paper:number;magnets:number;scrapbook:number;branding:number;vehicle:number;otherExpenses:number;totalOperationalCost:number};
  profit:{grossProfit:number;grossMarginPercent:number;netProfit:number;netMarginPercent:number};
  history:{originalRevenue:number;originalCost:number;finalRevenue:number;finalCost:number;calculationTimestamp:string};
}

type MoneyRow={total?:number|string|null};
const total=(rows:readonly MoneyRow[]|null|undefined,key:keyof MoneyRow="total")=>(rows??[]).reduce((sum,row)=>sum+Number(row[key]??0),0);
const asObject=(value:unknown):Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value)?value as Record<string,unknown>:{};

export async function calculateAndPersistRealEventCost(client:SupabaseClient,projectId:string):Promise<RealEventCostSummary>{
  const quotationResult=await client.from("quotations").select("id,subtotal,transport_total,discount_total,grand_total,final_customer_price,status,updated_at").eq("project_id",projectId).is("deleted_at",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(quotationResult.error)throw quotationResult.error;const quotation=quotationResult.data;
  const[itemsResult,payrollResult,fuelResult,movementsResult,expensesResult,snapshotsResult,authResult]=await Promise.all([
    quotation?.id?client.from("quotation_items").select("item_type,code,label,total").eq("quotation_id",quotation.id):Promise.resolve({data:[],error:null}),
    client.from("event_staff_payments").select("assembly_payment,operator_payment,disassembly_payment,transport_bonus,parking_payment,total_internal_payment,status,updated_at").eq("project_id",projectId).is("deleted_at",null).neq("status","CANCELLED"),
    client.from("vehicle_route_events").select("allocated_fuel_cost,created_at").eq("project_id",projectId),
    client.from("inventory_movements").select("total_cost,movement_type,occurred_at,supplies(name)").eq("project_id",projectId).is("deleted_at",null).in("movement_type",["CONSUMPTION","LOSS","REPLACEMENT"]),
    client.from("expenses").select("total,category,vehicle_id,supply_id,supplier,approval_reason,updated_at").eq("project_id",projectId).is("deleted_at",null),
    client.from("profit_snapshots").select("id,revenue,operational_cost,basis,created_at").eq("project_id",projectId).is("deleted_at",null).order("created_at",{ascending:true}),
    client.auth.getUser(),
  ]);
  const error=itemsResult.error??payrollResult.error??fuelResult.error??movementsResult.error??expensesResult.error??snapshotsResult.error;if(error)throw error;
  const items=itemsResult.data??[];const contractedService=items.filter(item=>item.item_type==="SERVICE").reduce((sum,item)=>sum+Number(item.total??0),0);const extras=items.filter(item=>item.item_type==="EXTRA").reduce((sum,item)=>sum+Number(item.total??0),0);const transport=Number(quotation?.transport_total??items.filter(item=>item.item_type==="TRANSPORT").reduce((sum,item)=>sum+Number(item.total??0),0));const discount=Number(quotation?.discount_total??0);const finalSaleValue=Number(quotation?.final_customer_price??quotation?.grand_total??0);
  const payroll=payrollResult.data??[];const operator=payroll.reduce((sum,item)=>sum+Number(item.operator_payment??0),0);const setup=payroll.reduce((sum,item)=>sum+Number(item.assembly_payment??0),0);const teardown=payroll.reduce((sum,item)=>sum+Number(item.disassembly_payment??0),0);const staffOther=payroll.reduce((sum,item)=>sum+Number(item.transport_bonus??0)+Number(item.parking_payment??0),0);
  const expenses=(expensesResult.data??[]).map(item=>{let metadata:Record<string,unknown>={};try{metadata=JSON.parse(item.approval_reason??"{}");}catch{}return{...item,label:`${item.supplier??""} ${String(metadata.description??"")}`.toLocaleLowerCase("es-CL")};});
  const routeFuel=total((fuelResult.data??[]).map(item=>({total:item.allocated_fuel_cost})));const registeredFuel=expenses.filter(item=>item.category==="FUEL").reduce((sum,item)=>sum+Number(item.total??0),0);const allocatedFuel=routeFuel||registeredFuel;
  const movementSupplies=(movementsResult.data??[]).map(item=>({label:String(Array.isArray(item.supplies)?item.supplies[0]?.name:(item.supplies as {name?:string}|null)?.name??"").toLocaleLowerCase("es-CL"),amount:Number(item.total_cost??0)}));const expenseSupplies=expenses.filter(item=>item.category==="SUPPLIES").map(item=>({label:item.label,amount:Number(item.total??0)}));const supplies=movementSupplies.length>0?movementSupplies:expenseSupplies;const bucket=(pattern:RegExp)=>supplies.filter(item=>pattern.test(item.label)).reduce((sum,item)=>sum+item.amount,0);const paper=bucket(/papel|paper|dnp|media|ribbon/);const magnets=bucket(/im[aá]n|magnet/);const scrapbook=bucket(/scrapbook/);const branding=bucket(/branding|gr[aá]fic|impresi[oó]n/);const identifiedSupplies=paper+magnets+scrapbook+branding;const remainingSupplies=Math.max(0,supplies.reduce((sum,item)=>sum+item.amount,0)-identifiedSupplies);
  const vehicle=expenses.filter(item=>item.category==="TRANSPORT"||(Boolean(item.vehicle_id)&&item.category!=="FUEL")).reduce((sum,item)=>sum+Number(item.total??0),0);const otherExpenses=remainingSupplies+expenses.filter(item=>!item.vehicle_id&&!['FUEL','TRANSPORT','SUPPLIES'].includes(item.category)).reduce((sum,item)=>sum+Number(item.total??0),0);
  const totalOperationalCost=operator+setup+teardown+staffOther+allocatedFuel+paper+magnets+scrapbook+branding+vehicle+otherExpenses;const grossProfit=finalSaleValue-totalOperationalCost;const grossMarginPercent=finalSaleValue?grossProfit/finalSaleValue*100:0;const netProfit=grossProfit;const netMarginPercent=grossMarginPercent;const snapshots=snapshotsResult.data??[];const first=snapshots[0];const signature=createHash("sha256").update(JSON.stringify({quotation:quotation?.updated_at??quotation?.id,payroll:payroll.map(item=>item.updated_at),fuel:fuelResult.data,inventory:movementsResult.data,expenses:expenses.map(item=>item.updated_at),values:{finalSaleValue,totalOperationalCost}})).digest("hex");const latest=snapshots.at(-1);const latestBasis=asObject(latest?.basis);const calculatedAt=new Date().toISOString();const originalRevenue=Number(latestBasis.originalRevenue??asObject(first?.basis).originalRevenue??first?.revenue??finalSaleValue);const originalCost=Number(latestBasis.originalCost??asObject(first?.basis).originalCost??first?.operational_cost??totalOperationalCost);
  const result:RealEventCostSummary={projectId,calculatedAt,status:finalSaleValue>0?"CALCULATED":"PENDING_REVENUE",revenue:{contractedService,extras,transport,discount,finalSaleValue},costs:{operator,setup,teardown,staffOther,allocatedFuel,paper,magnets,scrapbook,branding,vehicle,otherExpenses,totalOperationalCost},profit:{grossProfit,grossMarginPercent,netProfit,netMarginPercent},history:{originalRevenue,originalCost,finalRevenue:finalSaleValue,finalCost:totalOperationalCost,calculationTimestamp:calculatedAt}};
  let canPersist=false;
  if(authResult.data.user){const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",authResult.data.user.id).maybeSingle();if(profileError)throw profileError;canPersist=profile?.role==="CEO"||profile?.role==="ADMINISTRATOR";}
  if(finalSaleValue>0&&latestBasis.realCostSignature!==signature&&authResult.data.user&&canPersist){const{error:insertError}=await client.from("profit_snapshots").insert({project_id:projectId,revenue:finalSaleValue,crew_cost:operator+setup+teardown+staffOther,transport_cost:vehicle,fuel_cost:allocatedFuel,supplies_cost:paper+magnets+scrapbook+branding,expense_cost:otherExpenses,operational_cost:totalOperationalCost,gross_margin:grossProfit,gross_margin_percent:grossMarginPercent,basis:{realCostSignature:signature,originalRevenue,originalCost,finalRevenue:finalSaleValue,finalCost:totalOperationalCost,calculationTimestamp:calculatedAt,revenue:result.revenue,costs:result.costs,profit:result.profit},created_by:authResult.data.user.id,updated_by:authResult.data.user.id,approval_reason:"Costo real recalculado automáticamente"});if(insertError)throw insertError;}
  return result;
}

export async function refreshRealEventCosts(client:SupabaseClient):Promise<readonly RealEventCostSummary[]>{const{data,error}=await client.from("projects").select("id").is("deleted_at",null);if(error)throw error;const results:RealEventCostSummary[]=[];for(const project of data??[])results.push(await calculateAndPersistRealEventCost(client,project.id));return results;}
