begin;

alter table public.internal_notifications
  add column if not exists category text not null default 'SYSTEM' check(category in ('COMMERCIAL','CUSTOMER','OPERATIONS','STAFF','EQUIPMENT','GOOGLE','SYSTEM','SECURITY','PAYMENTS','PORTAL')),
  add column if not exists priority text not null default 'NORMAL' check(priority in ('CRITICAL','HIGH','NORMAL','INFORMATION')),
  add column if not exists action_required boolean not null default false,
  add column if not exists staff_id uuid references public.staff(id),
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists related_href text,
  add column if not exists metadata jsonb not null default '{}';

create table if not exists public.notification_user_states(
  id uuid primary key default gen_random_uuid(),
  notification_id uuid not null references public.internal_notifications(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz, archived_at timestamptz, dismissed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(notification_id,user_id)
);
create table if not exists public.notification_settings(singleton_key text primary key default 'PRIMARY' check(singleton_key='PRIMARY'),retention_days integer not null default 30 check(retention_days between 1 and 365),updated_by uuid references auth.users(id),updated_at timestamptz not null default now());
insert into public.notification_settings(singleton_key) values('PRIMARY') on conflict do nothing;
create index if not exists internal_notifications_inbox_idx on public.internal_notifications(created_at desc,priority,category) where status<>'RESOLVED';
create index if not exists notification_user_states_user_idx on public.notification_user_states(user_id,archived_at,read_at);
alter table public.notification_user_states enable row level security;alter table public.notification_settings enable row level security;
create policy notification_states_own on public.notification_user_states for all using(user_id=auth.uid() and public.is_internal_user()) with check(user_id=auth.uid() and public.is_internal_user());
create policy notification_settings_internal_read on public.notification_settings for select using(public.is_internal_user());create policy notification_settings_admin_write on public.notification_settings for all using(public.can_administer()) with check(public.can_administer());
drop trigger if exists notification_user_states_audit on public.notification_user_states;create trigger notification_user_states_audit after insert or update or delete on public.notification_user_states for each row execute function public.audit_row_change();
create or replace function public.notification_from_timeline() returns trigger language plpgsql security definer set search_path=public as $$ declare v_category text;v_priority text:='NORMAL';v_required boolean:=false;v_title text;begin v_category:=case when new.action in('QUOTATION_ACCEPTED','QUOTATION_REJECTED','QUOTATION_EXPIRING','NEGOTIATED_PRICE_APPROVED','AGREEMENT_GENERATED','AGREEMENT_SIGNED') then 'COMMERCIAL' when new.action in('CUSTOMER_PORTAL_ACCESS','CUSTOMER_PORTAL_ACCESSED','CUSTOMER_DESIGN_UPLOADED','CUSTOMER_MESSAGE','AGREEMENT_DOWNLOADED','CUSTOMER_REVIEWED') then 'CUSTOMER' when new.action in('STAFF_ASSIGNED','STAFF_ACCEPTED','STAFF_REJECTED','OPERATOR_ASSIGNED','OPERATOR_ACCEPTED','OPERATOR_DECLINED') then 'STAFF' when new.action in('TOTEM_ASSIGNED','CASE_ASSIGNED','EQUIPMENT_ASSIGNED','EQUIPMENT_RETURNED','MAINTENANCE_REQUIRED') then 'EQUIPMENT' when new.action like 'CALENDAR_%' or new.action like 'DRIVE_%' or new.action like 'GMAIL_%' or new.action like 'GOOGLE_%' then 'GOOGLE' when new.action in('PAYMENT_RECEIVED','PAYMENT_CONFIRMED','FINAL_PAYMENT_RECEIVED','INVOICE_GENERATED','PAYMENT_OVERDUE') then 'PAYMENTS' when new.action in('DEPLOYMENT_UPDATED','BACKUP_COMPLETED','SERVICE_OFFLINE','SERVICE_RESTORED','SSL_EXPIRING','HEALTH_WARNING') then 'SYSTEM' else null end;if v_category is null then return new;end if;v_priority:=case when new.action in('SERVICE_OFFLINE','SSL_EXPIRING','PAYMENT_OVERDUE','GOOGLE_AUTHORIZATION_EXPIRED') then 'CRITICAL' when new.action in('QUOTATION_REJECTED','STAFF_REJECTED','OPERATOR_DECLINED','MAINTENANCE_REQUIRED') then 'HIGH' when new.action in('SERVICE_RESTORED','BACKUP_COMPLETED','CALENDAR_SYNCHRONIZED','DRIVE_UPLOAD_COMPLETED') then 'INFORMATION' else 'NORMAL' end;v_required:=v_priority in('CRITICAL','HIGH') or new.action in('QUOTATION_ACCEPTED','AGREEMENT_SIGNED','CUSTOMER_MESSAGE');v_title:=coalesce(nullif(new.title,''),new.human_message,'Nueva actividad en ORBIT');insert into public.internal_notifications(project_id,customer_id,staff_id,notification_type,title,message,status,correlation_id,category,priority,action_required,entity_type,entity_id,related_href,metadata) values(new.project_id,new.customer_id,new.staff_id,new.action,v_title,new.human_message,'UNREAD','timeline:'||new.id,v_category,v_priority,v_required,new.entity_type,new.entity_id,case when new.project_id is not null then '/projects/'||new.project_id else null end,jsonb_build_object('timeline_id',new.id,'orbit_event_id',new.orbit_event_id)) on conflict(correlation_id) do nothing;return new;end $$;
drop trigger if exists timeline_notification_dispatch on public.timeline_events;create trigger timeline_notification_dispatch after insert on public.timeline_events for each row execute function public.notification_from_timeline();
create or replace function public.notification_from_health_alert() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status='OPEN' then insert into public.internal_notifications(notification_type,title,message,status,correlation_id,category,priority,action_required,entity_type,entity_id,related_href) values('HEALTH_WARNING','ORBIT requiere atención',new.message,'UNREAD','health-alert:'||new.id,'SYSTEM',case when new.severity='CRITICAL' then 'CRITICAL' else 'HIGH' end,true,'SystemHealthAlert',new.id::text,'/settings/health') on conflict(correlation_id) do nothing;end if;return new;end $$;
drop trigger if exists health_alert_notification_dispatch on public.system_health_alerts;create trigger health_alert_notification_dispatch after insert on public.system_health_alerts for each row execute function public.notification_from_health_alert();
create or replace function public.notification_from_failed_access() returns trigger language plpgsql security definer set search_path=public as $$ begin if not new.succeeded then insert into public.internal_notifications(project_id,customer_id,staff_id,notification_type,title,message,status,correlation_id,category,priority,action_required,entity_type,entity_id,related_href,metadata) values(new.project_id,new.customer_id,new.staff_id,'FAILED_LOGIN','Intento de acceso no validado','Se registró un intento de acceso que requiere seguimiento de seguridad.','UNREAD','failed-access:'||new.id,'SECURITY','HIGH',true,'PortalAccessAttempt',new.id::text,'/settings/health',jsonb_build_object('access_type',new.access_type,'device',new.device)) on conflict(correlation_id) do nothing;end if;return new;end $$;
drop trigger if exists failed_access_notification_dispatch on public.portal_access_attempts;create trigger failed_access_notification_dispatch after insert on public.portal_access_attempts for each row execute function public.notification_from_failed_access();
create or replace function public.archive_read_notifications() returns integer language plpgsql security definer set search_path=public as $$ declare affected integer;days integer;begin if not public.is_internal_user() then raise exception 'Acceso interno requerido.';end if;select retention_days into days from public.notification_settings where singleton_key='PRIMARY';update public.notification_user_states set archived_at=now(),updated_at=now() where user_id=auth.uid() and read_at<now()-make_interval(days=>coalesce(days,30)) and archived_at is null;get diagnostics affected=row_count;return affected;end $$;
revoke all on function public.archive_read_notifications() from public,anon;grant execute on function public.archive_read_notifications() to authenticated;
do $$ begin alter publication supabase_realtime add table public.internal_notifications;exception when duplicate_object then null;end $$;
commit;
