begin;
create table if not exists public.orbit_modules(
  id uuid primary key default gen_random_uuid(),module_key text not null unique,name text not null,description text not null,category text not null check(category in('FOUNDATION','OPERATIONS','BUSINESS','CUSTOMER_EXPERIENCE','AI','LAB')),enabled boolean not null default false,display_order integer not null default 100,
  version integer not null default 1,approval_reason text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_by uuid references auth.users(id),updated_at timestamptz not null default now()
);
drop trigger if exists orbit_modules_touch on public.orbit_modules;create trigger orbit_modules_touch before update on public.orbit_modules for each row execute function public.touch_versioned_row();
drop trigger if exists orbit_modules_audit on public.orbit_modules;create trigger orbit_modules_audit after insert or update or delete on public.orbit_modules for each row execute function public.audit_row_change();
alter table public.orbit_modules enable row level security;
drop policy if exists orbit_modules_authenticated_read on public.orbit_modules;create policy orbit_modules_authenticated_read on public.orbit_modules for select to authenticated using(true);
drop policy if exists orbit_modules_admin_write on public.orbit_modules;create policy orbit_modules_admin_write on public.orbit_modules for all to authenticated using(public.can_administer()) with check(public.can_administer());
insert into public.orbit_modules(module_key,name,description,category,enabled,display_order)
values
('DASHBOARD','Dashboard','Centro de control diario y accesos operacionales.','FOUNDATION',true,1),('COMMERCIAL','Commercial','Cotizaciones, acuerdos y negociación comercial.','FOUNDATION',true,2),('PROJECTS','Projects','Clientes, reservas y Event 360°.','FOUNDATION',true,3),('OPERATIONS','Operations','Preparación y ejecución de eventos.','FOUNDATION',true,4),('RESOURCES','Resources','Recursos operacionales configurables.','FOUNDATION',true,5),('FINANCE','Finance','Control financiero, gastos y cobranzas.','FOUNDATION',true,6),('REPORTS','Reports','Reportes operacionales y ejecutivos.','FOUNDATION',true,7),('CUSTOMER_PORTAL','Customer Portal','Experiencia privada de clientes.','FOUNDATION',true,8),
('STAFF','Staff','Equipo, capacidades, asignaciones y pagos.','OPERATIONS',true,20),('FLEET','Fleet','Vehículos y disponibilidad operacional.','OPERATIONS',true,21),('EQUIPMENT','Equipment','Equipamiento, estados e historial.','OPERATIONS',true,22),('ROUTE_COSTS','Route Costs','Rutas y distribución automática de combustible.','OPERATIONS',true,23),('COST_MASTER','Cost Master','Fuente editable de costos operacionales.','OPERATIONS',true,24),
('BUSINESS_INTELLIGENCE','Business Intelligence','Indicadores ejecutivos y tendencias.','BUSINESS',true,40),('EVENT_PROFITABILITY','Event Profitability','Costo y margen real por evento.','BUSINESS',true,41),('INVENTORY','Inventory','Disponibilidad e inventario operacional.','BUSINESS',true,42),('FUEL_CONTROL','Fuel Control','Cargas, comprobantes y costos de combustible.','BUSINESS',true,43),('PAPER_CONSUMPTION','Paper Consumption','Consumo y costo de papel fotográfico.','BUSINESS',true,44),('STRIP_CONTROL','Strip Control','Control de tiras y consumibles de producción.','BUSINESS',true,45),('EVENT_CHECKLIST','Event Checklist','Checklist antes, durante y después del evento.','BUSINESS',true,46),
('BOOKING_EXPERIENCE','Booking Experience','Reserva manual y automática guiada.','CUSTOMER_EXPERIENCE',true,60),('CUSTOMER_TIMELINE','Customer Timeline','Historial visible de la experiencia del cliente.','CUSTOMER_EXPERIENCE',true,61),('NOVA_CORE','NOVA CORE','Asistencia operacional y recomendaciones NOVA.','AI',true,80),('WHATSAPP_AI','WhatsApp IA','Automatización inteligente para WhatsApp.','AI',true,81),('INSTAGRAM_AI','Instagram IA','Automatización inteligente para Instagram.','AI',true,82),('EXPERIMENTAL_FEATURES','Experimental Features','Funciones en evaluación controlada.','LAB',true,100)
on conflict(module_key) do nothing;
commit;
