begin;

create table if not exists public.estimated_cost_sheets(
  id uuid primary key default gen_random_uuid(),project_id uuid not null unique references public.projects(id) on delete cascade,orbit_event_id text not null,status text not null check(status in('PENDING','CALCULATED','CANCELLED')),
  paper numeric(14,2) not null default 0,operator numeric(14,2) not null default 0,assembly numeric(14,2) not null default 0,disassembly numeric(14,2) not null default 0,fuel numeric(14,2) not null default 0,transport numeric(14,2) not null default 0,scrapbook numeric(14,2) not null default 0,magnets numeric(14,2) not null default 0,pens numeric(14,2) not null default 0,double_sided_tape numeric(14,2) not null default 0,other_configured numeric(14,2) not null default 0,total numeric(14,2) not null default 0,
  source_snapshot jsonb not null default '{}',calculated_at timestamptz not null default now(),version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);

create or replace function public.sync_estimated_cost_sheet(p_project_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare p public.projects%rowtype;q public.quotations%rowtype;hours numeric:=0;paper_value numeric:=0;operator_value numeric:=0;assembly_value numeric:=0;disassembly_value numeric:=0;fuel_value numeric:=0;transport_value numeric:=0;scrapbook_value numeric:=0;magnets_value numeric:=0;pens_value numeric:=0;tape_value numeric:=0;other_value numeric:=0;operator_count integer:=0;assembly_count integer:=0;disassembly_count integer:=0;cancelled boolean:=false;
begin
  select * into p from public.projects where id=p_project_id;if not found then return;end if;
  cancelled:=p.deleted_at is not null or upper(p.status) in('CANCELLED','CANCELED','ARCHIVED');
  select * into q from public.quotations where project_id=p_project_id and status='ACCEPTED' and deleted_at is null order by approved_at desc nulls last,created_at desc limit 1;
  select coalesce(max(duration_hours),0) into hours from public.project_services where project_id=p_project_id;
  select coalesce(sum(coalesce((m.configuration->>'estimatedPhotosPerHour')::numeric,0)*coalesce(ps.duration_hours,0)),0)*coalesce((select amount from public.cost_master_entries where code='COST_PER_PHOTO' and enabled and deleted_at is null limit 1),0) into paper_value from public.project_services ps left join public.master_data_entries m on m.domain='SERVICES' and m.code=ps.service_code and m.enabled where ps.project_id=p_project_id;
  select count(*) filter(where assignment_type='OPERATOR'),count(*) filter(where assignment_type='ASSEMBLY'),count(*) filter(where assignment_type='DISASSEMBLY') into operator_count,assembly_count,disassembly_count from public.assignments where project_id=p_project_id and deleted_at is null and status not in('CANCELLED','REJECTED');
  select coalesce(amount,0)*greatest(operator_count,1) into operator_value from public.cost_master_entries where code='OPERATOR_'||greatest(2,least(10,ceil(hours)::int))||'_HOURS' and enabled and deleted_at is null limit 1;
  select coalesce(amount,0)*greatest(assembly_count,1) into assembly_value from public.cost_master_entries where code='ASSEMBLY' and enabled and deleted_at is null limit 1;
  select coalesce(amount,0)*greatest(disassembly_count,1) into disassembly_value from public.cost_master_entries where code='DISASSEMBLY' and enabled and deleted_at is null limit 1;
  select coalesce(amount,0) into fuel_value from public.cost_master_entries where code='DEFAULT_FUEL_COST' and enabled and deleted_at is null limit 1;
  select coalesce(unit_price,0) into transport_value from public.commercial_prices where category='TRANSPORT' and enabled and deleted_at is null and coalesce(rules->'municipalities','[]'::jsonb)?p.city order by display_order limit 1;
  if q.id is not null and exists(select 1 from public.quotation_items where quotation_id=q.id and code ilike '%SCRAPBOOK%')then select coalesce(amount,0) into scrapbook_value from public.cost_master_entries where code='SCRAPBOOK_COST' and enabled and deleted_at is null limit 1;end if;
  if q.id is not null and exists(select 1 from public.quotation_items where quotation_id=q.id and code ilike '%MAGNET%')then select coalesce(amount,0) into magnets_value from public.cost_master_entries where code='MAGNETS_EVENT_COST' and enabled and deleted_at is null limit 1;end if;
  select coalesce(amount/nullif(quantity,0),0) into pens_value from public.cost_master_entries where code='PENCILS_COST' and enabled and deleted_at is null limit 1;
  select coalesce(amount/nullif(quantity,0),0) into tape_value from public.cost_master_entries where code='DOUBLE_SIDED_TAPE_COST' and enabled and deleted_at is null limit 1;
  select coalesce(sum(amount),0) into other_value from public.cost_master_entries where category='OTHER' and enabled and deleted_at is null and code not in('SCRAPBOOK_COST','MAGNETS_PURCHASE','MAGNETS_EVENT_COST','PENCILS_COST','DOUBLE_SIDED_TAPE_COST');
  paper_value:=coalesce(paper_value,0);operator_value:=coalesce(operator_value,0);assembly_value:=coalesce(assembly_value,0);disassembly_value:=coalesce(disassembly_value,0);fuel_value:=coalesce(fuel_value,0);transport_value:=coalesce(transport_value,0);scrapbook_value:=coalesce(scrapbook_value,0);magnets_value:=coalesce(magnets_value,0);pens_value:=coalesce(pens_value,0);tape_value:=coalesce(tape_value,0);other_value:=coalesce(other_value,0);
  insert into public.estimated_cost_sheets(project_id,orbit_event_id,status,paper,operator,assembly,disassembly,fuel,transport,scrapbook,magnets,pens,double_sided_tape,other_configured,total,source_snapshot,calculated_at)
  values(p.id,p.orbit_event_id,case when cancelled then 'CANCELLED' when q.id is null then 'PENDING' else 'CALCULATED' end,case when cancelled then 0 else paper_value end,case when cancelled then 0 else operator_value end,case when cancelled then 0 else assembly_value end,case when cancelled then 0 else disassembly_value end,case when cancelled then 0 else fuel_value end,case when cancelled then 0 else transport_value end,case when cancelled then 0 else scrapbook_value end,case when cancelled then 0 else magnets_value end,case when cancelled then 0 else pens_value end,case when cancelled then 0 else tape_value end,case when cancelled then 0 else other_value end,case when cancelled then 0 else paper_value+operator_value+assembly_value+disassembly_value+fuel_value+transport_value+scrapbook_value+magnets_value+pens_value+tape_value+other_value end,jsonb_build_object('quotationId',q.id,'serviceHours',hours,'municipality',p.city,'operatorAssignments',operator_count,'assemblyAssignments',assembly_count,'disassemblyAssignments',disassembly_count,'source','COST_MASTER_AND_MASTER_DATA'),now())
  on conflict(project_id)do update set orbit_event_id=excluded.orbit_event_id,status=excluded.status,paper=excluded.paper,operator=excluded.operator,assembly=excluded.assembly,disassembly=excluded.disassembly,fuel=excluded.fuel,transport=excluded.transport,scrapbook=excluded.scrapbook,magnets=excluded.magnets,pens=excluded.pens,double_sided_tape=excluded.double_sided_tape,other_configured=excluded.other_configured,total=excluded.total,source_snapshot=excluded.source_snapshot,calculated_at=now(),updated_at=now(),version=estimated_cost_sheets.version+1;
end$$;

create or replace function public.estimated_cost_project_source_changed()returns trigger language plpgsql security definer set search_path=public as $$declare target uuid;begin if tg_table_name='projects'then target:=case when tg_op='DELETE'then old.id else new.id end;else target:=case when tg_op='DELETE'then old.project_id else new.project_id end;end if;if target is not null then perform public.sync_estimated_cost_sheet(target);end if;return case when tg_op='DELETE'then old else new end;end$$;
do $$declare table_name text;begin foreach table_name in array array['projects','project_services','quotations','assignments']loop execute format('drop trigger if exists estimated_cost_sync on public.%I',table_name);execute format('create trigger estimated_cost_sync after insert or update or delete on public.%I for each row execute function public.estimated_cost_project_source_changed()',table_name);end loop;end$$;
create or replace function public.estimated_cost_quote_item_changed()returns trigger language plpgsql security definer set search_path=public as $$declare target uuid;begin select project_id into target from public.quotations where id=case when tg_op='DELETE'then old.quotation_id else new.quotation_id end;if target is not null then perform public.sync_estimated_cost_sheet(target);end if;return case when tg_op='DELETE'then old else new end;end$$;
drop trigger if exists estimated_cost_sync on public.quotation_items;create trigger estimated_cost_sync after insert or update or delete on public.quotation_items for each row execute function public.estimated_cost_quote_item_changed();
create or replace function public.estimated_cost_master_changed()returns trigger language plpgsql security definer set search_path=public as $$declare row record;begin for row in select id from public.projects loop perform public.sync_estimated_cost_sheet(row.id);end loop;return case when tg_op='DELETE'then old else new end;end$$;
drop trigger if exists estimated_cost_sync on public.cost_master_entries;create trigger estimated_cost_sync after insert or update or delete on public.cost_master_entries for each row execute function public.estimated_cost_master_changed();
drop trigger if exists estimated_cost_sync on public.master_data_entries;create trigger estimated_cost_sync after insert or update or delete on public.master_data_entries for each row execute function public.estimated_cost_master_changed();
drop trigger if exists estimated_cost_sync on public.commercial_prices;create trigger estimated_cost_sync after insert or update or delete on public.commercial_prices for each row execute function public.estimated_cost_master_changed();

alter table public.estimated_cost_sheets enable row level security;create policy estimated_cost_sheets_internal_read on public.estimated_cost_sheets for select using(public.is_internal_user());revoke insert,update,delete on public.estimated_cost_sheets from authenticated;
drop trigger if exists estimated_cost_sheets_audit on public.estimated_cost_sheets;create trigger estimated_cost_sheets_audit after insert or update or delete on public.estimated_cost_sheets for each row execute function public.audit_row_change();
select public.sync_estimated_cost_sheet(id)from public.projects;
commit;
