begin;
alter table public.expenses add column if not exists expense_scope text check(expense_scope is null or expense_scope in('EVENT_DIRECT','BUSINESS_OVERHEAD','ASSET_EQUIPMENT','VEHICLE','STAFF_REIMBURSEMENT','RECURRING_FIXED')),add column if not exists subcategory text,add column if not exists supplier_rut text,add column if not exists document_type text,add column if not exists payment_method text,add column if not exists bank_account_id uuid references public.finance_bank_accounts(id),add column if not exists extraction_status text not null default 'NOT_ANALYZED' check(extraction_status in('NOT_ANALYZED','EXTRACTED','REQUIRES_REVIEW','CONFIRMED')),add column if not exists suggested_category text,add column if not exists confirmed_category text;
alter table public.documents add column if not exists expense_id uuid references public.expenses(id);
create unique index if not exists documents_expense_uq on public.documents(expense_id) where expense_id is not null and deleted_at is null;
create index if not exists expenses_scope_date_idx on public.expenses(expense_scope,occurred_on desc) where deleted_at is null;
create or replace function public.validate_business_expense_scope() returns trigger language plpgsql set search_path=public as $$begin if new.expense_scope='EVENT_DIRECT' and new.project_id is null then raise exception 'EVENT_DIRECT requiere un Evento.';end if;if new.expense_scope in('BUSINESS_OVERHEAD','ASSET_EQUIPMENT','VEHICLE','RECURRING_FIXED') and new.project_id is not null then raise exception 'Este gasto general no puede cargarse al costo directo de un Evento.';end if;if new.expense_scope='VEHICLE' and nullif(new.vehicle_id,'') is null then raise exception 'VEHICLE requiere un vehículo.';end if;if new.suggested_category is not null and new.confirmed_category is null then raise exception 'La clasificación sugerida requiere confirmación Founder/Admin.';end if;return new;end $$;
drop trigger if exists business_expense_scope_guard on public.expenses;
create trigger business_expense_scope_guard before insert or update of expense_scope,project_id,vehicle_id,suggested_category,confirmed_category on public.expenses for each row execute function public.validate_business_expense_scope();
-- DDL-only: no extraction, expense, document, backfill or historical repair runs on installation.
commit;
