create or replace function public.resolve_event_operational_window(p_project_id uuid)
returns table(operational_start_at timestamptz,service_start_at timestamptz,service_end_at timestamptz,source text)
language sql stable security invoker set search_path=public as $$
with event_source as(select p.id,coalesce(c.service_start_at,(p.event_date+p.event_time)::timestamp at time zone 'America/Santiago') service_start_at,coalesce(c.service_end_at,(p.event_date+p.event_time)::timestamp at time zone 'America/Santiago'+make_interval(hours=>greatest(1,coalesce((select max(ps.duration_hours) from public.project_services ps where ps.project_id=p.id),1)))) service_end_at,c.staff_arrival_at,(select min(a.staff_call_at) from public.assignments a where a.project_id=p.id and a.deleted_at is null and a.status not in('REJECTED','CANCELLED') and a.staff_call_at is not null) staff_call_at from public.projects p left join public.project_operational_contracts c on c.project_id=p.id where p.id=p_project_id and p.deleted_at is null)
select coalesce(staff_call_at,staff_arrival_at,service_start_at),service_start_at,service_end_at,case when staff_call_at is not null then 'STAFF_CALL' when staff_arrival_at is not null then 'STAFF_ARRIVAL' else 'SERVICE_START' end from event_source;
$$;
create or replace function public.preview_calendar_operational_resync()
returns table(event_id uuid,project_id uuid,calendar_start_before timestamptz,calendar_start_after timestamptz,calendar_end timestamptz,source text,requires_update boolean,google_event_linked boolean)
language sql stable security invoker set search_path=public as $$
select e.id,e.project_id,(e.event_date+p.event_time)::timestamp at time zone 'America/Santiago',w.operational_start_at,w.service_end_at,w.source,(e.event_date+p.event_time)::timestamp at time zone 'America/Santiago' is distinct from w.operational_start_at,cs.external_event_id is not null from public.crm_events e join public.projects p on p.id=e.project_id cross join lateral public.resolve_event_operational_window(e.project_id) w left join public.calendar_sync cs on cs.project_id=e.project_id where p.deleted_at is null and e.status not in('CANCELLED','CANCELED','ARCHIVED','DELETED');
$$;
create or replace function public.execute_calendar_operational_resync(p_dry_run boolean default true)
returns table(project_id uuid,queued boolean) language plpgsql security definer set search_path=public as $$
declare actor uuid:=auth.uid();is_service boolean:=coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' or auth.role()='service_role';begin if not(is_service or(actor is not null and public.can_administer()))then raise exception 'Acceso administrativo requerido.';end if;if p_dry_run then return query select p.project_id,false from public.preview_calendar_operational_resync() p where p.requires_update;return;end if;return query update public.calendar_sync cs set status='UPDATE_REQUIRED' from public.preview_calendar_operational_resync() p where p.project_id=cs.project_id and p.requires_update and p.google_event_linked and cs.status is distinct from 'UPDATE_REQUIRED' returning cs.project_id,true;end$$;
revoke all on function public.resolve_event_operational_window(uuid),public.preview_calendar_operational_resync(),public.execute_calendar_operational_resync(boolean) from public,anon;
grant execute on function public.resolve_event_operational_window(uuid),public.preview_calendar_operational_resync() to authenticated,service_role;
grant execute on function public.execute_calendar_operational_resync(boolean) to authenticated,service_role;
