begin;

-- 0198 reached Production before its first safe draft generation exposed that
-- PostgreSQL does not accept the compact interval literal `1 month-1 day`.
-- Replace only the canonical calculator; no accounts, payments or documents
-- are generated by this migration.
create or replace function public.calculate_staff_monthly_settlement(p_staff_id uuid,p_month date)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare
  month_start date:=date_trunc('month',p_month)::date;
  month_end date:=(date_trunc('month',p_month)+interval '1 month'-interval '1 day')::date;
  rate numeric:=public.staff_withholding_rate_for_period(month_start);
  work_total numeric:=0; reimbursement_total numeric:=0; advances numeric:=0;
  gross_amount numeric:=0; retention numeric:=0; cash_obligation numeric:=0;
  final_transfer numeric:=0; excess numeric:=0; missing_count integer:=0; ineligible_count integer:=0; event_total integer:=0;
  details jsonb:='[]'::jsonb;
begin
  select coalesce(sum(financial.payroll_net),0),coalesce(sum(financial.reimbursement_total),0),count(*),
    coalesce(jsonb_agg(jsonb_build_object(
      'settlementId',financial.settlement_id,'projectId',project.id,'eventDate',project.event_date,
      'event',project.name,'customer',customer.full_name,
      'service',coalesce((select string_agg(service.service_code,' + ' order by service.service_code) from public.project_services service where service.project_id=project.id),project.project_type),
      'location',concat_ws(' · ',nullif(project.location,''),nullif(project.city,'')),
      'roles',settlement.tasks,
      'hours',coalesce((select max(service.duration_hours) from public.project_services service where service.project_id=project.id),(project.operations->>'durationHours')::numeric,0),
      'workNet',financial.payroll_net,'reimbursements',financial.reimbursement_total,
      'advances',coalesce((select sum(case when movement.movement_type='ADVANCE' then movement.amount when movement.movement_type='REVERSAL' then -movement.amount else 0 end)
        from public.event_staff_settlement_movements movement where movement.settlement_id=settlement.id and movement.deleted_at is null),0)
    ) order by project.event_date,project.event_time,financial.settlement_id),'[]'::jsonb)
  into work_total,reimbursement_total,event_total,details
  from public.staff_settlement_financials financial
  join public.event_staff_payments settlement on settlement.id=financial.settlement_id
  join public.projects project on project.id=financial.project_id
  join public.customers customer on customer.id=project.customer_id
  where financial.staff_id=p_staff_id and project.event_date between month_start and month_end
    and project.deleted_at is null and upper(coalesce(project.status,'')) not in('CANCELLED','CANCELED','ARCHIVED','DELETED','QA')
    and settlement.deleted_at is null and settlement.status='CONFIRMED'
    and (exists(select 1 from public.event_operational_closures closure where closure.project_id=project.id and closure.status='CLOSED')
      or exists(select 1 from public.staff_monthly_close_eligibility_overrides override_record where override_record.settlement_id=settlement.id));

  select coalesce(sum(case when movement.movement_type='ADVANCE' then movement.amount when movement.movement_type='REVERSAL' then -movement.amount else 0 end),0)
  into advances
  from public.event_staff_settlement_movements movement
  join public.event_staff_payments settlement on settlement.id=movement.settlement_id
  join public.projects project on project.id=settlement.project_id
  where settlement.staff_id=p_staff_id and project.event_date between month_start and month_end
    and movement.deleted_at is null and settlement.deleted_at is null and settlement.status='CONFIRMED'
    and project.deleted_at is null and upper(coalesce(project.status,'')) not in('CANCELLED','CANCELED','ARCHIVED','DELETED','QA')
    and (exists(select 1 from public.event_operational_closures closure where closure.project_id=project.id and closure.status='CLOSED')
      or exists(select 1 from public.staff_monthly_close_eligibility_overrides override_record where override_record.settlement_id=settlement.id));
  advances:=greatest(advances,0);

  select count(*) into missing_count from (
    select distinct assignment.project_id
    from public.assignments assignment join public.projects project on project.id=assignment.project_id
    where assignment.staff_id=p_staff_id and assignment.deleted_at is null
      and assignment.status in('CONFIRMED','ACCEPTED','COMPLETED')
      and project.event_date between month_start and month_end and project.deleted_at is null
      and upper(coalesce(project.status,'')) not in('CANCELLED','CANCELED','ARCHIVED','DELETED','QA')
      and not exists(select 1 from public.event_staff_payments payment where payment.project_id=assignment.project_id and payment.staff_id=p_staff_id and payment.deleted_at is null and payment.status='CONFIRMED' and payment.total_internal_payment>0)
  ) missing;

  select count(*) into ineligible_count from public.event_staff_payments payment join public.projects project on project.id=payment.project_id
  where payment.staff_id=p_staff_id and payment.deleted_at is null and payment.status='CONFIRMED' and payment.total_internal_payment>0
    and project.event_date between month_start and month_end and project.deleted_at is null
    and not exists(select 1 from public.event_operational_closures closure where closure.project_id=project.id and closure.status='CLOSED')
    and not exists(select 1 from public.staff_monthly_close_eligibility_overrides override_record where override_record.settlement_id=payment.id);

  if rate is not null and work_total>0 then gross_amount:=round(work_total/(1-rate),0);end if;
  retention:=greatest(gross_amount-work_total,0);
  cash_obligation:=work_total+reimbursement_total;
  final_transfer:=greatest(cash_obligation-advances,0);
  excess:=greatest(advances-cash_obligation,0);
  return jsonb_build_object(
    'source','CANONICAL_STAFF_MONTHLY_SETTLEMENT_V1','rateSemantics','NET','periodSource','EVENT_DATE','rounding','ROUND_CLP_HALF_AWAY_FROM_ZERO',
    'staffId',p_staff_id,'month',month_start,'eventCount',event_total,'details',details,
    'workNet',work_total,'boletaGross',gross_amount,'withholdingRate',coalesce(rate,0)*100,
    'withholdingAmount',retention,'boletaNet',work_total,'reimbursementsTotal',reimbursement_total,
    'advancesTotal',advances,'cashObligation',cash_obligation,'finalTransferAmount',final_transfer,'excessAdvance',excess,
    'reviewRequired',(rate is null or missing_count>0 or ineligible_count>0 or excess>0),
    'reviewReason',concat_ws(' · ',case when rate is null then 'Falta tasa de retención efectiva para el período' end,case when missing_count>0 then missing_count||' Evento(s) con asignación sin compensación confirmada' end,case when ineligible_count>0 then ineligible_count||' Evento(s) aún no cerrados operacionalmente' end,case when excess>0 then 'Adelantos exceden la obligación mensual' end)
  );
end $$;

commit;
