-- Read-only draft quotation preflight. It never creates a project, reservation,
-- hold, assignment or payment. It mirrors the canonical pools and overlap rules.
create or replace function public.preflight_draft_capacity(
  p_service_codes text[], p_event_type text, p_event_date date,
  p_service_start timestamptz, p_service_end timestamptz,
  p_address text default '', p_city text default '', p_shell text default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare case_required numeric:=0; bbox_required numeric:=0; case_pool integer:=0; bbox_pool integer:=0; case_committed numeric:=0; bbox_committed numeric:=0; shell text:=nullif(upper(trim(p_shell)),''); same_day boolean:=false;
begin
  if auth.uid() is null or public.current_orbit_role() not in ('CEO','ADMINISTRATOR','SALES') then raise exception 'Permiso Founder/Admin requerido.'; end if;
  if p_event_date is null or p_service_start is null or p_service_end is null or p_service_end<=p_service_start then
    return jsonb_build_object('status','REVIEW_REQUIRED','reasonCode','OPERATIONAL_WINDOW_UNVERIFIABLE','humanSafeReason','Necesitamos validar el horario operacional.');
  end if;
  select coalesce(sum(m.units_per_service) filter(where m.asset_type='CASE'),0),coalesce(sum(m.units_per_service) filter(where m.asset_type='BBOX360'),0) into case_required,bbox_required from public.service_asset_type_mappings m where m.enabled and m.service_code=any(p_service_codes) and m.asset_type in ('CASE','BBOX360');
  select count(*) filter(where asset_type='CASE' and status not in ('MAINTENANCE','OUT_OF_SERVICE')),count(*) filter(where asset_type='BBOX360' and status not in ('MAINTENANCE','OUT_OF_SERVICE')) into case_pool,bbox_pool from public.operational_assets where deleted_at is null;
  select coalesce(sum(x.case_qty),0),coalesce(sum(x.bbox_qty),0) into case_committed,bbox_committed from (select p.id,coalesce(sum(ps.quantity*m.units_per_service) filter(where m.asset_type='CASE'),0) case_qty,coalesce(sum(ps.quantity*m.units_per_service) filter(where m.asset_type='BBOX360'),0) bbox_qty from public.crm_reservations r join public.projects p on p.id=r.project_id cross join lateral public.event_operational_window(p.id) w left join public.project_services ps on ps.project_id=p.id left join public.service_asset_type_mappings m on m.service_code=ps.service_code and m.enabled and m.asset_type in ('CASE','BBOX360') where r.status='CONFIRMED' and p.deleted_at is null and w.window_start<p_service_end and p_service_start<w.window_end group by p.id) x;
  select exists(select 1 from public.crm_reservations r join public.projects p on p.id=r.project_id cross join lateral public.event_operational_window(p.id) w where r.status='CONFIRMED' and p.deleted_at is null and w.window_start::date=p_event_date) into same_day;
  if case_required+case_committed>case_pool then return jsonb_build_object('status','UNAVAILABLE','reasonCode','CASE_CAPACITY_EXHAUSTED','humanSafeReason','Sin disponibilidad para este horario.','caseCapacity',jsonb_build_object('total',case_pool,'committed',case_committed,'available',greatest(case_pool-case_committed,0))); end if;
  if bbox_required+bbox_committed>bbox_pool then return jsonb_build_object('status','UNAVAILABLE','reasonCode','BBOX360_CAPACITY_EXHAUSTED','humanSafeReason','Sin disponibilidad para este horario.','bboxCapacity',jsonb_build_object('total',bbox_pool,'committed',bbox_committed,'available',greatest(bbox_pool-bbox_committed,0))); end if;
  if case_required>0 and upper(coalesce(p_event_type,'')) in ('MATRIMONIO','WEDDING','MARRIAGE') and shell is null then shell:='WHITE'; end if;
  if case_required>0 and same_day and (nullif(trim(coalesce(p_address,'')),'') is null or nullif(trim(coalesce(p_city,'')),'') is null) then return jsonb_build_object('status','REVIEW_REQUIRED','reasonCode','LOGISTICS_DATA_INCOMPLETE','humanSafeReason','Falta validar ubicación y logística para reutilizar el equipo.','caseCapacity',jsonb_build_object('total',case_pool,'committed',case_committed,'available',greatest(case_pool-case_committed,0))); end if;
  if case_required>0 and same_day then return jsonb_build_object('status','REVIEW_REQUIRED','reasonCode','TRAVEL_TIME_UNVERIFIABLE','humanSafeReason','El tiempo de traslado entre eventos requiere revisión de Founder.','caseCapacity',jsonb_build_object('total',case_pool,'committed',case_committed,'available',greatest(case_pool-case_committed,0))); end if;
  return jsonb_build_object('status','AVAILABLE','reasonCode','CAPACITY_CONFIRMED','humanSafeReason','Disponibilidad confirmada para este horario.','caseCapacity',jsonb_build_object('total',case_pool,'committed',case_committed,'available',greatest(case_pool-case_committed,0)),'bboxCapacity',jsonb_build_object('total',bbox_pool,'committed',bbox_committed,'available',greatest(bbox_pool-bbox_committed,0)),'shell',jsonb_build_object('preferred',shell,'status',case when shell is null then 'NOT_REQUIRED' else 'PLANNED' end));
end $$;
revoke all on function public.preflight_draft_capacity(text[],text,date,timestamptz,timestamptz,text,text,text) from public,anon;
grant execute on function public.preflight_draft_capacity(text[],text,date,timestamptz,timestamptz,text,text,text) to authenticated,service_role;
