"use server";import{revalidatePath}from"next/cache";import{createSupabaseServerActionClient}from"@/lib/supabase/server";import type{OperationalMilestone}from"./types";
type Result={ok:true;message:string}|{ok:false;error:string};const failed=(e:unknown):Result=>({ok:false,error:e instanceof Error?e.message:"No fue posible actualizar el checklist."});
export type EventCloseGate={status:string;ready:boolean;blockers:{code:string;label:string}[];serviceFinished:boolean;assets:{assigned:number;returned:number};incidentsOpen:number;staffFinalized:boolean;expensesFinalized:boolean;financialInvariant:boolean};
type GateResult={ok:boolean;data?:EventCloseGate;message?:string;error?:string};
export async function setChecklistItemAction(projectId:string,itemId:string,completed:boolean):Promise<Result>{try{const client=await createSupabaseServerActionClient();const{error}=await client.rpc("set_event_checklist_item",{p_item_id:itemId,p_completed:completed});if(error)throw error;refresh(projectId);return{ok:true,message:completed?"Control confirmado.":"Control marcado como pendiente."}}catch(e){return failed(e)}}
export async function recordOperationalMilestoneAction(projectId:string,milestone:OperationalMilestone,notes?:string):Promise<Result>{try{const client=await createSupabaseServerActionClient();const{error}=await client.rpc("record_event_milestone",{p_project_id:projectId,p_milestone:milestone,p_notes:notes??null});if(error){if(error.code==="23505")throw new Error("Este hito ya fue registrado.");throw error}refresh(projectId);return{ok:true,message:"Hito operacional registrado."}}catch(e){return failed(e)}}
export async function previewEventCloseAction(projectId:string):Promise<GateResult>{try{const client=await createSupabaseServerActionClient();const{data,error}=await client.rpc("preview_event_operational_close",{p_project_id:projectId});if(error)throw error;return{ok:true,data,message:"Gate de cierre actualizado."}}catch(e){return{ok:false,error:e instanceof Error?e.message:"No fue posible revisar el cierre."}}}
export async function closeEventOperationAction(projectId:string):Promise<GateResult>{try{const client=await createSupabaseServerActionClient();const{data,error}=await client.rpc("close_event_operation",{p_project_id:projectId});if(error)throw error;refresh(projectId);return{ok:true,data,message:"Evento cerrado operacionalmente."}}catch(e){return{ok:false,error:e instanceof Error?e.message:"No fue posible cerrar el Evento."}}}
export async function reopenEventOperationAction(projectId:string,reason:string):Promise<GateResult>{try{const client=await createSupabaseServerActionClient();const{data,error}=await client.rpc("reopen_event_operation",{p_project_id:projectId,p_reason:reason});if(error)throw error;refresh(projectId);return{ok:true,data,message:"Evento reabierto con trazabilidad."}}catch(e){return{ok:false,error:e instanceof Error?e.message:"No fue posible reabrir el Evento."}}}
export async function createEventIncidentAction(projectId:string,type:string,severity:string,description:string):Promise<GateResult>{try{const client=await createSupabaseServerActionClient();const{error}=await client.rpc("create_event_incident",{p_project_id:projectId,p_type:type,p_severity:severity,p_description:description,p_responsible:null});if(error)throw error;const result=await previewEventCloseAction(projectId);refresh(projectId);return{...result,message:"Incidencia registrada."}}catch(e){return{ok:false,error:e instanceof Error?e.message:"No fue posible registrar la incidencia."}}}
function refresh(projectId:string){revalidatePath(`/projects/${projectId}`);revalidatePath("/operations");revalidatePath("/tasks");revalidatePath("/notifications")}
