"use server";

import { createSupabaseServerClient } from "@/lib/supabase/server";

export type FuelType="GASOLINE_93"|"DIESEL";
export type VehicleOperationalStatus="OPERATIONAL"|"MAINTENANCE"|"DISABLED";
export interface FleetVehicle{id:string;code:string;nickname:string;model:string;plate:string;fuelType:FuelType;currentMileage:number|null;insuranceExpiration:string;technicalInspectionExpiration:string;operationalStatus:VehicleOperationalStatus;notes:string;enabled:boolean;version:number;fuelTotal:number;}
export interface FuelLog{id:string;assetId:string;date:string;fuelType:FuelType;litres:number;totalAmount:number;gasStation:string;receiptPath:string;}
type VehicleResult={ok:true;vehicle:FleetVehicle}|{ok:false;error:string};
const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const optional=(value:string)=>value||null;

async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión no está disponible.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar la flota.");return{client,userId:data.user.id};}
function friendly(error:unknown,fallback:string){const message=error instanceof Error?error.message:"";if(message.includes("unique")||message.includes("duplicate"))return"La patente o el código ya están registrados.";return message&&!["violates","column","schema","JSON"].some((part)=>message.includes(part))?message:fallback;}
function vehicle(row:{asset_id:string;nickname:string|null;model:string;plate:string|null;fuel_type:string;current_mileage:number|null;insurance_expiration:string|null;technical_inspection_expiration:string|null;operational_status:string;notes:string|null;version:number;operational_assets:{asset_code:string;status:string}|{asset_code:string;status:string}[]},fuelTotal=0):FleetVehicle{const linked=Array.isArray(row.operational_assets)?row.operational_assets[0]:row.operational_assets;return{id:row.asset_id,code:linked.asset_code,nickname:row.nickname??"",model:row.model,plate:row.plate??"",fuelType:row.fuel_type as FuelType,currentMileage:row.current_mileage,insuranceExpiration:row.insurance_expiration??"",technicalInspectionExpiration:row.technical_inspection_expiration??"",operationalStatus:row.operational_status as VehicleOperationalStatus,notes:row.notes??"",enabled:linked.status!=="OUT_OF_SERVICE",version:row.version,fuelTotal};}
const fields=(data:FormData)=>({nickname:optional(text(data,"nickname")),model:text(data,"model"),plate:optional(text(data,"plate").toUpperCase()),fuel_type:text(data,"fuelType")as FuelType,current_mileage:optional(text(data,"currentMileage"))===null?null:Number(text(data,"currentMileage")),insurance_expiration:optional(text(data,"insuranceExpiration")),technical_inspection_expiration:optional(text(data,"technicalInspectionExpiration")),operational_status:text(data,"operationalStatus")as VehicleOperationalStatus,notes:optional(text(data,"notes"))});
const select="asset_id,nickname,model,plate,fuel_type,current_mileage,insurance_expiration,technical_inspection_expiration,operational_status,notes,version,operational_assets!inner(asset_code,status)";

export async function createVehicleAction(data:FormData):Promise<VehicleResult>{try{const{client,userId}=await context();const input=fields(data);if(!input.model||!["GASOLINE_93","DIESEL"].includes(input.fuel_type))throw new Error("Completa modelo y combustible.");const code=`VEH-${input.model.toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,"")}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;const{data:asset,error:assetError}=await client.from("operational_assets").insert({asset_code:code,asset_type:"VEHICLE",status:"AVAILABLE",qr_key:`orbit:asset:${code}`,metadata:{name:input.model,resourceCategory:"VEHICLES"},created_by:userId,updated_by:userId}).select("id").single();if(assetError)throw assetError;const{data:created,error}=await client.from("vehicle_profiles").insert({asset_id:asset.id,...input,created_by:userId,updated_by:userId}).select(select).single();if(error)throw error;return{ok:true,vehicle:vehicle(created)};}catch(error){return{ok:false,error:friendly(error,"No fue posible agregar el vehículo.")};}}
export async function updateVehicleAction(data:FormData):Promise<VehicleResult>{try{const{client,userId}=await context();const id=text(data,"id");const version=Number(data.get("version"));const input=fields(data);const{data:updated,error}=await client.from("vehicle_profiles").update({...input,updated_by:userId}).eq("asset_id",id).eq("version",version).select(select).maybeSingle();if(error)throw error;if(!updated)throw new Error("El vehículo cambió en otra sesión.");await client.from("operational_assets").update({metadata:{name:input.model,resourceCategory:"VEHICLES"},updated_by:userId}).eq("id",id);return{ok:true,vehicle:vehicle(updated)};}catch(error){return{ok:false,error:friendly(error,"No fue posible editar el vehículo.")};}}
export async function setVehicleEnabledAction(item:FleetVehicle,enabled:boolean):Promise<VehicleResult>{try{const{client,userId}=await context();const{error:assetError}=await client.from("operational_assets").update({status:enabled?"AVAILABLE":"OUT_OF_SERVICE",updated_by:userId}).eq("id",item.id).is("deleted_at",null);if(assetError)throw assetError;const{data,error}=await client.from("vehicle_profiles").update({operational_status:enabled?"OPERATIONAL":"DISABLED",updated_by:userId}).eq("asset_id",item.id).eq("version",item.version).select(select).maybeSingle();if(error)throw error;if(!data)throw new Error("El vehículo cambió en otra sesión.");return{ok:true,vehicle:vehicle(data,item.fuelTotal)};}catch(error){return{ok:false,error:friendly(error,"No fue posible cambiar el estado del vehículo.")};}}
export async function deleteVehicleAction(item:FleetVehicle):Promise<{ok:true}|{ok:false;error:string}>{try{const{client,userId}=await context();const{data,error}=await client.from("operational_assets").update({status:"OUT_OF_SERVICE",deleted_at:new Date().toISOString(),deleted_by:userId,updated_by:userId}).eq("id",item.id).is("deleted_at",null).select("id").maybeSingle();if(error)throw error;if(!data)throw new Error("El vehículo ya no está disponible.");await client.from("vehicle_profiles").update({operational_status:"DISABLED",updated_by:userId}).eq("asset_id",item.id);return{ok:true};}catch(error){return{ok:false,error:friendly(error,"No fue posible eliminar el vehículo.")};}}

export async function addFuelLogAction(data:FormData):Promise<{ok:true;log:FuelLog}|{ok:false;error:string}>{try{const{client,userId}=await context();const assetId=text(data,"assetId");const file=data.get("receipt");if(!(file instanceof File)||file.size===0)throw new Error("Adjunta la fotografía o PDF del comprobante.");if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("El comprobante debe ser JPG, PNG, WEBP o PDF.");const extension=file.name.split(".").pop()?.toLowerCase()||"bin";const path=`fleet/${assetId}/${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await client.storage.from("orbit-expenses").upload(path,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const payload={asset_id:assetId,fuel_date:text(data,"date"),fuel_type:text(data,"fuelType"),litres:Number(data.get("litres")),total_amount:Number(data.get("totalAmount")),receipt_path:path,gas_station:text(data,"gasStation"),created_by:userId};if(!payload.fuel_date||!payload.gas_station||payload.litres<=0||payload.total_amount<0)throw new Error("Completa todos los datos de la carga.");const{data:created,error}=await client.from("vehicle_fuel_logs").insert(payload).select("id,asset_id,fuel_date,fuel_type,litres,total_amount,gas_station,receipt_path").single();if(error)throw error;return{ok:true,log:{id:created.id,assetId:created.asset_id,date:created.fuel_date,fuelType:created.fuel_type as FuelType,litres:Number(created.litres),totalAmount:Number(created.total_amount),gasStation:created.gas_station,receiptPath:created.receipt_path}};}catch(error){return{ok:false,error:friendly(error,"No fue posible registrar la carga de combustible.")};}}

export async function assignVehicleToEventAction(data:FormData):Promise<{ok:true}|{ok:false;error:string}>{try{const{client,userId}=await context();const payload={project_id:text(data,"projectId"),asset_id:text(data,"assetId"),driver_staff_id:optional(text(data,"driverId")),route:text(data,"route"),fuel_cost:Number(data.get("fuelCost")??0),distance:Number(data.get("distance")??0),status:"ASSIGNED",created_by:userId,updated_by:userId};if(!payload.project_id||!payload.asset_id||!payload.route)throw new Error("Selecciona evento y registra la ruta.");const{error}=await client.from("event_vehicle_assignments").insert(payload);if(error)throw error;return{ok:true};}catch(error){return{ok:false,error:friendly(error,"No fue posible asociar el vehículo al evento.")};}}
