"use client";

import { useState, useTransition } from "react";
import { Fuel, Pencil, Plus, Power, Route, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { addFuelLogAction, assignVehicleToEventAction, createVehicleAction, deleteVehicleAction, setVehicleEnabledAction, updateVehicleAction, type FleetVehicle, type FuelLog } from "./fleet-center.actions";

export interface FleetProjectOption{id:string;label:string;}
export interface FleetDriverOption{id:string;label:string;}
type Panel={kind:"create"}|{kind:"edit"|"fuel"|"assign";vehicle:FleetVehicle}|null;
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const fuelLabel=(value:string)=>value==="GASOLINE_93"?"Gasolina · 93 octanos":"Diésel";

export function FleetCenter({initialVehicles,initialFuelLogs,projects,drivers}:{initialVehicles:FleetVehicle[];initialFuelLogs:FuelLog[];projects:FleetProjectOption[];drivers:FleetDriverOption[]}){
  const[vehicles,setVehicles]=useState(initialVehicles);const[logs,setLogs]=useState(initialFuelLogs);const[panel,setPanel]=useState<Panel>(null);const[error,setError]=useState("");const[pending,startTransition]=useTransition();
  const save=(data:FormData,editing:boolean)=>{setError("");startTransition(async()=>{const result=editing?await updateVehicleAction(data):await createVehicleAction(data);if(!result.ok)return setError(result.error);setVehicles((current)=>editing?current.map((item)=>item.id===result.vehicle.id?result.vehicle:item):[result.vehicle,...current]);setPanel(null);});};
  const toggle=(vehicle:FleetVehicle)=>{setError("");startTransition(async()=>{const result=await setVehicleEnabledAction(vehicle,!vehicle.enabled);if(!result.ok)return setError(result.error);setVehicles((current)=>current.map((item)=>item.id===vehicle.id?result.vehicle:item));});};
  const remove=(vehicle:FleetVehicle)=>{if(!window.confirm(`¿Eliminar ${vehicle.model} de la flota activa?`))return;setError("");startTransition(async()=>{const result=await deleteVehicleAction(vehicle);if(!result.ok)return setError(result.error);setVehicles((current)=>current.filter((item)=>item.id!==vehicle.id));});};
  const addFuel=(data:FormData)=>{setError("");startTransition(async()=>{const result=await addFuelLogAction(data);if(!result.ok)return setError(result.error);setLogs((current)=>[result.log,...current]);setVehicles((current)=>current.map((item)=>item.id===result.log.assetId?{...item,fuelTotal:item.fuelTotal+result.log.totalAmount}:item));setPanel(null);});};
  const assign=(data:FormData)=>{setError("");startTransition(async()=>{const result=await assignVehicleToEventAction(data);if(!result.ok)return setError(result.error);setPanel(null);});};
  return <section className="space-y-5" aria-labelledby="fleet-title"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-brand">FLOTA BOOMBOX</p><h2 id="fleet-title" className="mt-2 text-2xl font-semibold sm:text-3xl">Vehículos operacionales</h2><p className="mt-2 text-sm text-muted">Flota, combustible y asignaciones vinculadas a costos operacionales.</p></div><Button onClick={()=>setPanel({kind:"create"})}><Plus className="size-4"/>Agregar vehículo</Button></div>{error&&<p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}<div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{vehicles.map((vehicle)=>{const vehicleLogs=logs.filter((log)=>log.assetId===vehicle.id);return <article key={vehicle.id} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">{vehicle.model}</p><p className="mt-1 text-sm text-muted">{vehicle.nickname||"Sin apodo"} · {vehicle.plate||"Patente pendiente"}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${vehicle.enabled?"border-emerald-500/30 bg-emerald-500/10 text-emerald-600":"border-red-500/30 bg-red-500/10 text-red-600"}`}>{vehicle.enabled?"Operacional":"Deshabilitado"}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><Detail label="Combustible" value={fuelLabel(vehicle.fuelType)}/><Detail label="Kilometraje" value={vehicle.currentMileage===null?"Pendiente":`${vehicle.currentMileage.toLocaleString("es-CL")} km`}/><Detail label="Seguro" value={vehicle.insuranceExpiration||"Pendiente"}/><Detail label="Revisión técnica" value={vehicle.technicalInspectionExpiration||"Pendiente"}/><Detail label="Costo combustible" value={money.format(vehicle.fuelTotal)}/><Detail label="Cargas" value={String(vehicleLogs.length)}/></dl><div className="mt-5 grid grid-cols-2 gap-2 border-t pt-4 sm:grid-cols-3"><Action icon={<Pencil/>} label="Editar" onClick={()=>setPanel({kind:"edit",vehicle})}/><Action icon={<Fuel/>} label="Agregar combustible" onClick={()=>setPanel({kind:"fuel",vehicle})}/><Action icon={<Route/>} label="Asignar a evento" onClick={()=>setPanel({kind:"assign",vehicle})}/><Action icon={<Power/>} label={vehicle.enabled?"Deshabilitar":"Habilitar"} onClick={()=>toggle(vehicle)} disabled={pending}/><Action icon={<Trash2/>} label="Eliminar" onClick={()=>remove(vehicle)} danger/></div></article>;})}</div>{panel&&<FleetPanel panel={panel} error={error} pending={pending} projects={projects} drivers={drivers} onClose={()=>{setPanel(null);setError("");}} onSave={save} onFuel={addFuel} onAssign={assign}/>}</section>;
}

function FleetPanel({panel,error,pending,projects,drivers,onClose,onSave,onFuel,onAssign}:{panel:Exclude<Panel,null>;error:string;pending:boolean;projects:FleetProjectOption[];drivers:FleetDriverOption[];onClose:()=>void;onSave:(data:FormData,editing:boolean)=>void;onFuel:(data:FormData)=>void;onAssign:(data:FormData)=>void}){const vehicle=panel.kind==="create"?null:panel.vehicle;return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 sm:max-w-2xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-brand">FLOTA</p><h3 className="mt-1 text-2xl font-semibold">{panel.kind==="create"?"Agregar vehículo":panel.kind==="edit"?"Editar vehículo":panel.kind==="fuel"?"Agregar combustible":"Asignar a evento"}</h3></div><button onClick={onClose} aria-label="Cerrar" className="rounded-lg border p-2"><X className="size-4"/></button></div>{panel.kind==="fuel"&&vehicle?<FuelForm vehicle={vehicle} pending={pending} error={error} onSubmit={onFuel}/>:panel.kind==="assign"&&vehicle?<AssignmentForm vehicle={vehicle} projects={projects} drivers={drivers} pending={pending} error={error} onSubmit={onAssign}/>:<VehicleForm vehicle={vehicle} pending={pending} error={error} onSubmit={onSave}/>}</div></div>;}
function VehicleForm({vehicle,pending,error,onSubmit}:{vehicle:FleetVehicle|null;pending:boolean;error:string;onSubmit:(data:FormData,editing:boolean)=>void}){return <form action={(data)=>onSubmit(data,!!vehicle)} className="mt-6 grid gap-4 sm:grid-cols-2">{vehicle&&<><input type="hidden" name="id" value={vehicle.id}/><input type="hidden" name="version" value={vehicle.version}/></>}<Field label="Modelo" name="model" defaultValue={vehicle?.model} required/><Field label="Apodo" name="nickname" defaultValue={vehicle?.nickname}/><Field label="Patente" name="plate" defaultValue={vehicle?.plate}/><Select label="Combustible" name="fuelType" defaultValue={vehicle?.fuelType??"GASOLINE_93"} options={[{value:"GASOLINE_93",label:"Gasolina · 93 octanos"},{value:"DIESEL",label:"Diésel"}]}/><Field label="Kilometraje actual" name="currentMileage" type="number" defaultValue={vehicle?.currentMileage?.toString()}/><Field label="Vencimiento seguro" name="insuranceExpiration" type="date" defaultValue={vehicle?.insuranceExpiration}/><Field label="Vencimiento revisión técnica" name="technicalInspectionExpiration" type="date" defaultValue={vehicle?.technicalInspectionExpiration}/><Select label="Estado operacional" name="operationalStatus" defaultValue={vehicle?.operationalStatus??"OPERATIONAL"} options={[{value:"OPERATIONAL",label:"Operacional"},{value:"MAINTENANCE",label:"Mantenimiento"},{value:"DISABLED",label:"Deshabilitado"}]}/><label className="sm:col-span-2 text-sm font-medium">Notas<textarea name="notes" defaultValue={vehicle?.notes} className="mt-2 min-h-24 w-full rounded-xl border bg-background p-3"/></label>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<Button className="sm:col-span-2" disabled={pending}>{pending?"Guardando...":vehicle?"Guardar cambios":"Agregar vehículo"}</Button></form>;}
function FuelForm({vehicle,pending,error,onSubmit}:{vehicle:FleetVehicle;pending:boolean;error:string;onSubmit:(data:FormData)=>void}){return <form action={onSubmit} className="mt-6 grid gap-4 sm:grid-cols-2"><input type="hidden" name="assetId" value={vehicle.id}/><Field label="Fecha" name="date" type="date" required/><Select label="Combustible" name="fuelType" defaultValue={vehicle.fuelType} options={[{value:"GASOLINE_93",label:"Gasolina · 93 octanos"},{value:"DIESEL",label:"Diésel"}]}/><Field label="Litros" name="litres" type="number" step="0.001" required/><Field label="Monto total" name="totalAmount" type="number" required/><Field label="Estación de servicio" name="gasStation" required/><label className="text-sm font-medium">Foto o PDF del comprobante<input required type="file" name="receipt" accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-2 block w-full rounded-xl border bg-background p-2 text-sm"/></label>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<Button className="sm:col-span-2" disabled={pending}>{pending?"Registrando...":"Registrar combustible"}</Button></form>;}
function AssignmentForm({vehicle,projects,drivers,pending,error,onSubmit}:{vehicle:FleetVehicle;projects:FleetProjectOption[];drivers:FleetDriverOption[];pending:boolean;error:string;onSubmit:(data:FormData)=>void}){return <form action={onSubmit} className="mt-6 grid gap-4 sm:grid-cols-2"><input type="hidden" name="assetId" value={vehicle.id}/><Select label="Evento" name="projectId" defaultValue="" options={[{value:"",label:"Seleccionar evento"},...projects.map((item)=>({value:item.id,label:item.label}))]}/><Select label="Conductor" name="driverId" defaultValue="" options={[{value:"",label:"Sin asignar"},...drivers.map((item)=>({value:item.id,label:item.label}))]}/><Field label="Ruta" name="route" required/><Field label="Distancia (km)" name="distance" type="number" defaultValue="0" required/><Field label="Costo de combustible" name="fuelCost" type="number" defaultValue="0" required/>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<Button className="sm:col-span-2" disabled={pending}>{pending?"Asignando...":"Asignar vehículo"}</Button></form>;}
function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>;}
function Action({icon,label,onClick,disabled,danger}:{icon:React.ReactElement;label:string;onClick:()=>void;disabled?:boolean;danger?:boolean}){return <button disabled={disabled} onClick={onClick} className={`rounded-lg border px-2 py-2 text-xs font-semibold hover:bg-accent disabled:opacity-40 ${danger?"text-red-600":""}`}>{<span className="mx-auto mb-1 block w-fit [&>svg]:size-4">{icon}</span>}{label}</button>;}
function Field({label,name,type="text",defaultValue,required,step}:{label:string;name:string;type?:string;defaultValue?:string;required?:boolean;step?:string}){return <label className="text-sm font-medium">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} step={step} min={type==="number"?"0":undefined} className="mt-2 h-11 w-full rounded-xl border bg-background px-3"/></label>;}
function Select({label,name,defaultValue,options}:{label:string;name:string;defaultValue:string;options:{value:string;label:string}[]}){return <label className="text-sm font-medium">{label}<select name={name} defaultValue={defaultValue} className="mt-2 h-11 w-full rounded-xl border bg-background px-3">{options.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;}
