"use client";

import { useMemo, useState, useTransition } from "react";
import { Pencil, Plus, Power, Search, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createResourceAction, deleteResourceAction, setResourceEnabledAction, updateResourceAction, type OperationalResource, type ResourceCategory } from "./resource-center.actions";

const categories:readonly{value:ResourceCategory;label:string}[]=[
  {value:"EQUIPMENT",label:"Equipamiento"},{value:"CONSUMABLES",label:"Consumibles"},{value:"OPERATORS",label:"Operadores"},{value:"ASSISTANTS",label:"Asistentes"},{value:"ACCESSORIES",label:"Accesorios"},
];
const label=(category:ResourceCategory)=>categories.find((item)=>item.value===category)?.label??category;
type Panel={mode:"create"}|{mode:"edit";item:OperationalResource}|null;

export function ResourceCenter({initialItems}:{initialItems:OperationalResource[]}){
  const[items,setItems]=useState(initialItems);const[query,setQuery]=useState("");const[category,setCategory]=useState<ResourceCategory|"ALL">("ALL");const[panel,setPanel]=useState<Panel>(null);const[error,setError]=useState("");const[pending,startTransition]=useTransition();
  const visible=useMemo(()=>items.filter((item)=>(category==="ALL"||item.category===category)&&`${item.name} ${item.code} ${label(item.category)} ${item.status}`.toLocaleLowerCase("es").includes(query.trim().toLocaleLowerCase("es"))),[category,items,query]);
  const save=(data:FormData,editing:boolean)=>{setError("");startTransition(async()=>{const result=editing?await updateResourceAction(data):await createResourceAction(data);if(!result.ok)return setError(result.error);setItems((current)=>editing?current.map((item)=>item.id===result.item.id&&item.source===result.item.source?result.item:item):[result.item,...current]);setPanel(null);});};
  const toggle=(item:OperationalResource)=>{setError("");startTransition(async()=>{const result=await setResourceEnabledAction(item,!item.enabled);if(!result.ok)return setError(result.error);setItems((current)=>current.map((entry)=>entry.id===item.id&&entry.source===item.source?result.item:entry));});};
  const remove=(item:OperationalResource)=>{if(!window.confirm(`¿Eliminar ${item.name}? Esta acción conservará su auditoría.`))return;setError("");startTransition(async()=>{const result=await deleteResourceAction(item);if(!result.ok)return setError(result.error);setItems((current)=>current.filter((entry)=>entry.id!==item.id||entry.source!==item.source));});};
  return <section className="space-y-6" aria-labelledby="resources-title">
    <header className="rounded-2xl border bg-card px-5 py-7 sm:px-8 sm:py-9 lg:px-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-brand">RECURSOS OPERACIONALES</p><h1 id="resources-title" className="mt-3 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Centro de Recursos</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted sm:text-base">Administra equipamiento, vehículos, consumibles y equipo humano desde un solo lugar.</p></div><Button onClick={()=>{setError("");setPanel({mode:"create"});}}><Plus className="size-4"/>Agregar recurso</Button></div></header>
    <div className="rounded-2xl border bg-card p-4 sm:p-5"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><span className="sr-only">Buscar recursos</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar por nombre, código, categoría o estado" className="h-11 w-full rounded-xl border bg-background pl-10 pr-4 text-sm outline-none focus:border-brand"/></label><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{[{value:"ALL" as const,label:"Todos"},...categories].map((option)=><button key={option.value} onClick={()=>setCategory(option.value)} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-semibold ${category===option.value?"border-brand bg-brand text-white":"bg-background hover:bg-accent"}`}>{option.label}</button>)}</div></div>
    {error&&<p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((item)=><article key={`${item.source}-${item.id}`} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-lg font-semibold">{item.name}</p><p className="mt-1 text-sm text-muted">{item.code} · {label(item.category)}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${item.enabled?"border-emerald-500/30 bg-emerald-500/10 text-emerald-600":"border-red-500/30 bg-red-500/10 text-red-600"}`}>{item.enabled?"Habilitado":"Deshabilitado"}</span></div><p className="mt-5 text-xs text-muted">Estado operacional</p><p className="mt-1 font-medium">{item.status.replaceAll("_"," ")}</p><div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4"><button onClick={()=>setPanel({mode:"edit",item})} className="rounded-lg border px-2 py-2 text-xs font-semibold hover:bg-accent"><Pencil className="mx-auto mb-1 size-4"/>Editar</button><button disabled={pending} onClick={()=>toggle(item)} className="rounded-lg border px-2 py-2 text-xs font-semibold hover:bg-accent"><Power className="mx-auto mb-1 size-4"/>{item.enabled?"Deshabilitar":"Habilitar"}</button><button onClick={()=>remove(item)} className="rounded-lg border px-2 py-2 text-xs font-semibold text-red-600 hover:bg-red-500/10"><Trash2 className="mx-auto mb-1 size-4"/>Eliminar</button></div></article>)}</div>
    {!visible.length&&<div className="rounded-2xl border border-dashed p-10 text-center"><p className="font-semibold">No encontramos recursos</p><p className="mt-1 text-sm text-muted">Ajusta la búsqueda o agrega un recurso operacional.</p></div>}
    {panel&&<ResourcePanel panel={panel} pending={pending} error={error} onClose={()=>{setPanel(null);setError("");}} onSave={save}/>} 
  </section>;
}

function ResourcePanel({panel,pending,error,onClose,onSave}:{panel:Exclude<Panel,null>;pending:boolean;error:string;onClose:()=>void;onSave:(data:FormData,editing:boolean)=>void}){const item=panel.mode==="edit"?panel.item:null;const allowedCategories=item?.source==="ASSET"?categories.filter((option)=>["EQUIPMENT","VEHICLES","ACCESSORIES"].includes(option.value)):item?[categories.find((option)=>option.value===item.category)!]:categories;return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 shadow-2xl sm:max-w-xl sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-brand">RECURSOS</p><h2 className="mt-1 text-2xl font-semibold">{item?"Editar recurso":"Agregar recurso"}</h2></div><button onClick={onClose} aria-label="Cerrar" className="rounded-lg border p-2"><X className="size-4"/></button></div><form className="mt-6 space-y-4" action={(data)=>onSave(data,!!item)}>{item&&<><input type="hidden" name="id" value={item.id}/><input type="hidden" name="source" value={item.source}/><input type="hidden" name="version" value={item.version}/></>}<Field label="Nombre" name="name" defaultValue={item?.name}/><Field label={item?.source==="STAFF"||(!item)?"Código / RUT":"Código"} name="code" defaultValue={item?.code}/><label className="block text-sm font-medium">Categoría<select name="category" defaultValue={item?.category??"EQUIPMENT"} className="mt-2 h-11 w-full rounded-xl border bg-background px-3">{allowedCategories.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{error&&<p className="text-sm text-red-600">{error}</p>}<Button disabled={pending} className="w-full" type="submit">{pending?"Guardando...":item?"Guardar cambios":"Agregar recurso"}</Button></form></div></div>;}
function Field({label,name,defaultValue}:{label:string;name:string;defaultValue?:string}){return <label className="block text-sm font-medium">{label}<input required name={name} defaultValue={defaultValue} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 outline-none focus:border-brand"/></label>;}
