"use server";

import { createSupabaseServerClient } from "@/lib/supabase/server";

export interface OperationalRoute{id:string;vehicleId:string;date:string;driverId:string;eventIds:string[];fuelAmount:number;distance:number|null;notes:string;receiptPath:string;version:number;allocatedPerEvent:number;}
const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
async function admin(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión no está disponible.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar rutas.");return client;}
function friendly(error:unknown,fallback:string){const message=error instanceof Error?error.message:"";return message&&!message.includes("violates")&&!message.includes("schema")?message:fallback;}
export async function saveRouteAction(data:FormData):Promise<{ok:true;routeId:string}|{ok:false;error:string}>{let uploadedPath="";try{const client=await admin();const routeId=text(data,"routeId")||null;const projectIds=data.getAll("eventIds").map(String).filter(Boolean);const receipt=data.get("receipt");if(receipt instanceof File&&receipt.size>0){if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(receipt.type))throw new Error("El comprobante debe ser JPG, PNG, WEBP o PDF.");const extension=receipt.name.split(".").pop()?.toLowerCase()||"bin";uploadedPath=`routes/${text(data,"vehicleId")}/${crypto.randomUUID()}.${extension}`;const{error}=await client.storage.from("orbit-expenses").upload(uploadedPath,await receipt.arrayBuffer(),{contentType:receipt.type,upsert:false});if(error)throw error;}if(!routeId&&!uploadedPath)throw new Error("Adjunta el comprobante de combustible.");const{data:saved,error}=await client.rpc("save_vehicle_route",{p_route_id:routeId,p_asset_id:text(data,"vehicleId"),p_route_date:text(data,"date"),p_driver_staff_id:text(data,"driverId")||null,p_project_ids:projectIds,p_receipt_path:uploadedPath,p_fuel_amount:Number(data.get("fuelAmount")),p_distance:text(data,"distance")?Number(data.get("distance")):null,p_notes:text(data,"notes")||null});if(error)throw error;return{ok:true,routeId:String(saved)};}catch(error){if(uploadedPath){try{const client=await createSupabaseServerClient();await client.storage.from("orbit-expenses").remove([uploadedPath]);}catch{}}return{ok:false,error:friendly(error,"No fue posible guardar la ruta.")};}}
export async function deleteRouteAction(routeId:string):Promise<{ok:true}|{ok:false;error:string}>{try{const client=await admin();const{error}=await client.rpc("delete_vehicle_route",{p_route_id:routeId});if(error)throw error;return{ok:true};}catch(error){return{ok:false,error:friendly(error,"No fue posible eliminar la ruta.")};}}
