"use server";

import { createSupabaseServerClient } from "@/lib/supabase/server";

export type StaffOperationalRole="OPERATOR"|"SETUP_TEARDOWN"|"PHOTOGRAPHER"|"DRIVER"|"SUPERVISOR"|"ASSISTANT"|"ADMINISTRATOR";
export type StaffStoredStatus="ACTIVE"|"VACATION"|"MEDICAL_LEAVE"|"INACTIVE"|"DISABLED";
export type StaffSkill="OPERATOR"|"ASSEMBLY"|"DISASSEMBLY"|"DRIVER"|"PHOTOGRAPHER"|"COORDINATOR"|"TECHNICIAN";
export interface StaffAssignmentView{id:string;projectId:string;eventName:string;service:string;date:string;vehicle:string;role:string;status:string;arrivalTime:string;startTime:string;finishTime:string;}
export interface StaffHistoryView{id:string;message:string;occurredAt:string;}
export interface StaffOperationalRecord{id:string;version:number;firstName:string;lastName:string;rut:string;phone:string;email:string;role:StaffOperationalRole;skills:StaffSkill[];status:StaffStoredStatus;bank:string;accountType:string;accountNumber:string;emergencyName:string;emergencyPhone:string;assignments:StaffAssignmentView[];history:StaffHistoryView[];}
type Result={ok:true;staff:StaffOperationalRecord}|{ok:false;error:string};
const statuses:readonly StaffStoredStatus[]=["ACTIVE","VACATION","MEDICAL_LEAVE","INACTIVE","DISABLED"];
const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión no está disponible.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar Staff.");return{client,userId:data.user.id};}
function friendly(error:unknown,fallback:string){const message=error instanceof Error?error.message:"";if(message.includes("unique")||message.includes("duplicate"))return"Ya existe Staff con ese RUT o correo.";return message&&!message.includes("violates")&&!message.includes("schema")?message:fallback;}
const skills:readonly StaffSkill[]=["OPERATOR","ASSEMBLY","DISASSEMBLY","DRIVER","PHOTOGRAPHER","COORDINATOR","TECHNICIAN"];
function empty(row:{id:string;version:number;first_name:string;last_name:string;rut:string|null;phone:string|null;email:string|null;role:string;capabilities:string[]|null;status:string;bank:string|null;account_type:string|null;account_number:string|null;emergency_contact:unknown}):StaffOperationalRecord{const emergency=(row.emergency_contact??{})as Record<string,unknown>;return{id:row.id,version:row.version,firstName:row.first_name,lastName:row.last_name,rut:row.rut??"",phone:row.phone??"",email:row.email??"",role:row.role as StaffOperationalRole,skills:(row.capabilities??[]).filter((item):item is StaffSkill=>skills.includes(item as StaffSkill)),status:row.status as StaffStoredStatus,bank:row.bank??"",accountType:row.account_type??"",accountNumber:row.account_number??"",emergencyName:typeof emergency.name==="string"?emergency.name:"",emergencyPhone:typeof emergency.phone==="string"?emergency.phone:"",assignments:[],history:[]};}
const select="id,version,first_name,last_name,rut,phone,email,role,capabilities,status,bank,account_type,account_number,emergency_contact";
function fields(data:FormData){const selected=data.getAll("skills").map(String).filter((item):item is StaffSkill=>skills.includes(item as StaffSkill));const status=text(data,"status")as StaffStoredStatus;const required=["firstName","lastName","rut","phone","email","bank","accountType","accountNumber","emergencyName","emergencyPhone"].map((key)=>text(data,key));if(required.some((value)=>!value)||!selected.length||!statuses.includes(status))throw new Error("Completa los campos obligatorios y selecciona al menos una habilidad.");const role:StaffOperationalRole=selected.includes("OPERATOR")?"OPERATOR":selected.some(x=>["ASSEMBLY","DISASSEMBLY"].includes(x))?"SETUP_TEARDOWN":selected.includes("DRIVER")?"DRIVER":selected.includes("PHOTOGRAPHER")?"PHOTOGRAPHER":"ASSISTANT";return{first_name:text(data,"firstName"),last_name:text(data,"lastName"),rut:text(data,"rut").toUpperCase(),phone:text(data,"phone"),email:text(data,"email").toLowerCase(),role,status,bank:text(data,"bank"),account_type:text(data,"accountType"),account_number:text(data,"accountNumber"),emergency_contact:{name:text(data,"emergencyName"),phone:text(data,"emergencyPhone")},operational_group:selected.includes("OPERATOR")&&selected.includes("ASSEMBLY")?"CALYPSO":selected.includes("OPERATOR")?"GREEN":null,capabilities:selected,specializations:[] as string[]};}
export async function createOperationalStaffAction(data:FormData):Promise<Result>{try{const{client,userId}=await context();const payload=fields(data);const{data:created,error}=await client.from("staff").insert({...payload,rates:{},availability:{label:"Disponible"},created_by:userId,updated_by:userId}).select(select).single();if(error)throw error;return{ok:true,staff:empty(created)};}catch(error){return{ok:false,error:friendly(error,"No fue posible agregar Staff.")};}}
export async function updateOperationalStaffAction(data:FormData):Promise<Result>{try{const{client,userId}=await context();const id=text(data,"id");const version=Number(data.get("version"));const payload=fields(data);const{data:updated,error}=await client.from("staff").update({...payload,updated_by:userId,approval_reason:"Perfil actualizado desde Staff Center"}).eq("id",id).eq("version",version).is("deleted_at",null).select(select).maybeSingle();if(error)throw error;if(!updated)throw new Error("El perfil cambió en otra sesión.");return{ok:true,staff:empty(updated)};}catch(error){return{ok:false,error:friendly(error,"No fue posible editar Staff.")};}}
export async function disableOperationalStaffAction(item:StaffOperationalRecord):Promise<Result>{try{const{client,userId}=await context();const{data,error}=await client.from("staff").update({status:"DISABLED",updated_by:userId,approval_reason:"Staff deshabilitado"}).eq("id",item.id).eq("version",item.version).is("deleted_at",null).select(select).maybeSingle();if(error)throw error;if(!data)throw new Error("El perfil cambió en otra sesión.");return{ok:true,staff:{...empty(data),assignments:item.assignments,history:item.history}};}catch(error){return{ok:false,error:friendly(error,"No fue posible deshabilitar Staff.")};}}
export async function deleteOperationalStaffAction(item:StaffOperationalRecord):Promise<{ok:true}|{ok:false;error:string}>{try{const{client,userId}=await context();const{data,error}=await client.from("staff").update({status:"DISABLED",deleted_at:new Date().toISOString(),deleted_by:userId,updated_by:userId,approval_reason:"Staff eliminado del registro activo"}).eq("id",item.id).eq("version",item.version).is("deleted_at",null).select("id").maybeSingle();if(error)throw error;if(!data)throw new Error("El perfil cambió en otra sesión.");return{ok:true};}catch(error){return{ok:false,error:friendly(error,"No fue posible eliminar Staff.")};}}
export async function assignOperationalStaffAction(data:FormData):Promise<{ok:true;assignmentIds:string[]}|{ok:false;error:string}>{try{const{client}=await context();const staffIds=data.getAll("staffIds").map(String);const role=text(data,"assignmentRole");const assignmentType=role==="SETUP"?"ASSEMBLY":role==="TEARDOWN"?"DISASSEMBLY":role;const{data:ids,error}=await client.rpc("assign_staff_group",{p_staff_ids:staffIds,p_project_id:text(data,"projectId"),p_assignment_type:assignmentType,p_vehicle:text(data,"vehicle"),p_reason:text(data,"reason")});if(error)throw error;return{ok:true,assignmentIds:(ids??[]).map(String)};}catch(error){return{ok:false,error:friendly(error,"No fue posible asignar Staff.")};}}
