"use client";

import Link from "next/link";
import{useTransition}from"react";
import{useRouter}from"next/navigation";
import{setStaffEventPublicationAction}from"@/features/operations/operations-planning.actions";

export type StaffOperationsEvent={id:string;date:string;customer:string;service:string;published:boolean;assignments:string[];settlements?:Array<{id:string;staff:string;net:number;paid:number;status:string}>;eventStatus?:string;requestCount?:number};
export type StaffOperationsRequest={id:string;projectId:string;staff:string;responsibility:string;event:string;date:string};

export function StaffOperationsView({events,requests}:{events:StaffOperationsEvent[];requests:StaffOperationsRequest[]}){
  const router=useRouter();const[pending,start]=useTransition();const publish=(event:StaffOperationsEvent)=>start(async()=>{const data=new FormData();data.set("projectId",event.id);data.set("published","true");const result=await setStaffEventPublicationAction(data);if(!result.ok)window.alert(result.message);else router.refresh();});
  const stage=(event:StaffOperationsEvent)=>["COMPLETED","Completed"].includes(event.eventStatus??"")?"Completado":["IN_PROGRESS","Running"].includes(event.eventStatus??"")?"En ejecución":event.assignments.length?"Confirmado":(event.requestCount??0)>0?"Solicitudes":event.published?"Publicado":"Borrador";
  return <section className="space-y-5 rounded-2xl border bg-card p-5 sm:p-7"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Operaciones · próximos 15 días</p><h2 className="mt-2 text-2xl font-semibold">Consola de publicación</h2><p className="mt-2 text-sm text-muted">Publica el Evento para el Portal Staff. Los montos visibles son la liquidación del Evento, sin cálculos alternativos.</p></header><div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section><h3 className="font-semibold">Próximos Eventos</h3><div className="mt-3 space-y-3">{events.map(event=><article className="rounded-xl border p-4" key={event.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{event.date} · {event.customer}</p><p className="mt-1 text-sm text-muted">{event.service}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${event.published?"bg-emerald-500/10 text-emerald-500":"bg-amber-500/10 text-amber-500"}`}>{stage(event)}</span></div><p className="mt-3 text-sm">{event.assignments.length?event.assignments.join(" · "):"Sin asignaciones confirmadas"}</p>{event.settlements?.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{event.settlements.map(item=><div className="rounded-lg bg-background/60 p-3 text-xs" key={item.id}><p className="font-semibold">{item.staff}</p><p className="mt-1 text-muted">Neto Evento: {money(item.net)} · Pagado: {money(item.paid)} · Saldo: {money(Math.max(0,item.net-item.paid))}</p></div>)}</div>:null}<div className="mt-3 flex flex-wrap gap-4">{!event.published?<button className="rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground" disabled={pending} onClick={()=>publish(event)}>{pending?"Publicando…":"Publicar para Staff"}</button>:<span className="py-2 text-sm font-semibold text-emerald-500">Publicado en Portal Staff</span>}<Link className="py-2 text-sm font-semibold text-brand" href={`/projects/${event.id}#staff-assignment`}>Abrir Evento</Link></div></article>)}{!events.length?<p className="rounded-xl border border-dashed p-6 text-sm text-muted">No hay eventos durante los próximos 15 días.</p>:null}</div></section><section><h3 className="font-semibold">Solicitudes pendientes</h3><div className="mt-3 space-y-3">{requests.map(request=><article className="rounded-xl border p-4" key={request.id}><p className="font-semibold">{request.staff} · {request.responsibility}</p><p className="mt-1 text-sm text-muted">{request.event} · {request.date}</p><Link className="mt-3 inline-block text-sm font-semibold text-brand" href={`/projects/${request.projectId}#staff-assignment`}>Aprobar o rechazar en el Evento</Link></article>)}{!requests.length?<p className="rounded-xl border border-dashed p-6 text-sm text-muted">No hay solicitudes pendientes.</p>:null}</div></section></div></section>;
}
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
