"use server";

import { createSupabaseServerClient } from "@/lib/supabase/server";
import { formatChileanPhone, formatChileanRut, normalizeChileanPhone, requireValidChileanRut } from "@/lib/chile/rut";

export type StaffOperationalRole="OPERATOR"|"SETUP_TEARDOWN"|"PHOTOGRAPHER"|"DRIVER"|"SUPERVISOR"|"ASSISTANT"|"ADMINISTRATOR";
export type StaffStoredStatus="ACTIVE"|"VACATION"|"MEDICAL_LEAVE"|"INACTIVE"|"DISABLED";
export type StaffSkill="OPERATOR"|"ASSEMBLY"|"DISASSEMBLY";
export interface StaffAssignmentView{id:string;projectId:string;eventName:string;service:string;date:string;vehicle:string;role:string;status:string;arrivalTime:string;startTime:string;finishTime:string;}
export interface StaffHistoryView{id:string;message:string;occurredAt:string;}
export interface StaffOperationalRecord{id:string;version:number;firstName:string;lastName:string;rut:string;phone:string;email:string;role:StaffOperationalRole;skills:StaffSkill[];status:StaffStoredStatus;bank:string;accountType:string;accountNumber:string;emergencyName:string;emergencyPhone:string;assignments:StaffAssignmentView[];history:StaffHistoryView[];associatedExpenses?:{id:string;projectId:string;eventName:string;date:string;category:string;description:string;amount:number;status:string}[];financial:{upcomingEvents:number;pendingPayments:number;completedEvents:number;revenueGenerated:number;totalCost:number};}
type Result={ok:true;staff:StaffOperationalRecord}|{ok:false;error:string};
const statuses:readonly StaffStoredStatus[]=["ACTIVE","VACATION","MEDICAL_LEAVE","INACTIVE","DISABLED"];
const text=(data:FormData,key:string)=>String(data.get(key)??"").trim();
async function context(){const client=await createSupabaseServerClient();const{data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("Tu sesión no está disponible.");const{data:profile,error:profileError}=await client.from("profiles").select("role").eq("id",data.user.id).single();if(profileError)throw profileError;if(!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Administración puede gestionar Staff.");return{client,userId:data.user.id};}
function friendly(error:unknown,fallback:string){const message=error instanceof Error?error.message:"";if(message.includes("unique")||message.includes("duplicate"))return"Ya existe Staff con ese RUT o correo.";return message&&!/violates|schema|coerce|json object|pgrst|constraint|column/i.test(message)?message:fallback;}
const skills:readonly StaffSkill[]=["OPERATOR","ASSEMBLY","DISASSEMBLY"];
function empty(row:{id:string;version:number;first_name:string;last_name:string;rut:string|null;phone:string|null;email:string|null;role:string;capabilities:string[]|null;status:string;bank:string|null;account_type:string|null;account_number:string|null;emergency_contact:unknown}):StaffOperationalRecord{const emergency=(row.emergency_contact??{})as Record<string,unknown>;return{id:row.id,version:row.version,firstName:row.first_name,lastName:row.last_name,rut:formatChileanRut(row.rut??""),phone:formatChileanPhone(row.phone??""),email:row.email??"",role:row.role as StaffOperationalRole,skills:(row.capabilities??[]).filter((item):item is StaffSkill=>skills.includes(item as StaffSkill)),status:row.status as StaffStoredStatus,bank:row.bank??"",accountType:row.account_type??"",accountNumber:row.account_number??"",emergencyName:typeof emergency.name==="string"?emergency.name:"",emergencyPhone:typeof emergency.phone==="string"?formatChileanPhone(emergency.phone):"",assignments:[],history:[],associatedExpenses:[],financial:{upcomingEvents:0,pendingPayments:0,completedEvents:0,revenueGenerated:0,totalCost:0}};}
const select="id,version,first_name,last_name,rut,phone,email,role,capabilities,status,bank,account_type,account_number,emergency_contact";
function fields(data:FormData){const selected=data.getAll("skills").map(String).filter((item):item is StaffSkill=>skills.includes(item as StaffSkill));const status=text(data,"status")as StaffStoredStatus;const required=["firstName","lastName","rut","phone","email","bank","accountType","accountNumber","emergencyName","emergencyPhone"].map((key)=>text(data,key));if(required.some((value)=>!value)||!selected.length||!statuses.includes(status))throw new Error("Completa los campos obligatorios y selecciona al menos una responsabilidad.");const role:StaffOperationalRole=selected.includes("OPERATOR")?"OPERATOR":"SETUP_TEARDOWN";return{first_name:text(data,"firstName"),last_name:text(data,"lastName"),rut:requireValidChileanRut(text(data,"rut")),phone:normalizeChileanPhone(text(data,"phone")),email:text(data,"email").toLowerCase(),role,status,bank:text(data,"bank"),account_type:text(data,"accountType"),account_number:text(data,"accountNumber"),emergency_contact:{name:text(data,"emergencyName"),phone:normalizeChileanPhone(text(data,"emergencyPhone"))},operational_group:selected.includes("OPERATOR")&&selected.some(item=>item!=="OPERATOR")?"CALYPSO":selected.includes("OPERATOR")?"GREEN":null,capabilities:selected,specializations:[] as string[]};}
export async function createOperationalStaffAction(data:FormData):Promise<Result>{try{const{client,userId}=await context();const payload=fields(data);const{data:created,error}=await client.from("staff").insert({...payload,rates:{},availability:{label:"Disponible"},created_by:userId,updated_by:userId}).select(select).single();if(error)throw error;return{ok:true,staff:empty(created)};}catch(error){return{ok:false,error:friendly(error,"No fue posible agregar Staff.")};}}
export async function updateOperationalStaffAction(data:FormData):Promise<Result>{try{const{client,userId}=await context();const id=text(data,"id");const version=Number(data.get("version"));const payload=fields(data);const{data:updated,error}=await client.from("staff").update({...payload,updated_by:userId,approval_reason:"Perfil actualizado desde Staff Center"}).eq("id",id).eq("version",version).is("deleted_at",null).select(select).maybeSingle();if(error)throw error;if(!updated)throw new Error("El perfil cambió en otra sesión.");return{ok:true,staff:empty(updated)};}catch(error){return{ok:false,error:friendly(error,"No fue posible editar Staff.")};}}
export async function disableOperationalStaffAction(item:StaffOperationalRecord):Promise<Result>{try{const{client,userId}=await context();const{data,error}=await client.from("staff").update({status:"DISABLED",updated_by:userId,approval_reason:"Staff deshabilitado"}).eq("id",item.id).eq("version",item.version).is("deleted_at",null).select(select).maybeSingle();if(error)throw error;if(!data)throw new Error("El perfil cambió en otra sesión.");return{ok:true,staff:{...empty(data),assignments:item.assignments,history:item.history,financial:item.financial}};}catch(error){return{ok:false,error:friendly(error,"No fue posible deshabilitar Staff.")};}}
export async function deleteOperationalStaffAction(item:StaffOperationalRecord):Promise<{ok:true}|{ok:false;error:string}>{try{const{client}=await context();const{data:approved,error}=await client.from("staff_onboarding_invitations").select("id").eq("staff_id",item.id).eq("status","APPROVED").limit(1);if(error)throw error;if(approved?.length)throw new Error("Un colaborador aprobado no puede eliminarse. Usa Deshabilitar para conservar su historial operacional.");throw new Error("Los perfiles Staff se conservan para proteger el historial. Usa Deshabilitar.");}catch(error){return{ok:false,error:friendly(error,"No fue posible eliminar Staff.")};}}
export async function assignOperationalStaffAction(data:FormData):Promise<{ok:true;assignmentIds:string[]}|{ok:false;error:string}>{try{const{client}=await context();const staffId=text(data,"staffId");const responsibilities=data.getAll("responsibilities").map(String).filter(item=>skills.includes(item as StaffSkill));if(!staffId||!responsibilities.length)throw new Error("Selecciona un colaborador y al menos una responsabilidad.");const{data:ids,error}=await client.rpc("assign_staff_responsibilities",{p_staff_id:staffId,p_project_id:text(data,"projectId"),p_responsibilities:responsibilities,p_vehicle:text(data,"vehicle"),p_reason:text(data,"reason")});if(error)throw error;return{ok:true,assignmentIds:(ids??[]).map(String)};}catch(error){return{ok:false,error:friendly(error,"No fue posible asignar Staff.")};}}
