import "server-only";
import type { GoogleWorkspaceProvider, GoogleWorkspaceProviderResult, GoogleWorkspaceProviderSession, GoogleWorkspaceVerificationResult } from "./google-workspace.provider";
import type { GoogleWorkspaceAuthorizationRequest, GoogleWorkspaceService } from "../types/google-workspace.types";

export interface GoogleWorkspaceOAuthConfig { clientId: string; clientSecret: string; redirectUri: string; }
interface TokenResponse { access_token: string; refresh_token?: string; expires_in: number; scope: string; }

export class GoogleWorkspaceOAuthProvider implements GoogleWorkspaceProvider {
  constructor(private readonly config: GoogleWorkspaceOAuthConfig) {}
  private async token(body: URLSearchParams): Promise<TokenResponse> { const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); if (!response.ok) throw new Error(`Google OAuth failed (${response.status}): ${await response.text()}`); return response.json() as Promise<TokenResponse>; }
  private services(scopes: readonly string[]): GoogleWorkspaceService[] { const result: GoogleWorkspaceService[] = []; if (scopes.some((s) => s.includes("calendar"))) result.push("CALENDAR"); if (scopes.some((s) => s.includes("drive"))) result.push("DRIVE"); if (scopes.some((s) => s.includes("gmail"))) result.push("GMAIL"); return result; }
  private async session(tokens: TokenResponse, fallbackRefresh?: string): Promise<GoogleWorkspaceProviderSession> { const response = await fetch("https://openidconnect.googleapis.com/v1/userinfo", { headers: { Authorization: `Bearer ${tokens.access_token}` } }); if (!response.ok) throw new Error(`Google profile failed (${response.status})`); const user = await response.json() as { email: string }; const scopes = tokens.scope.split(" "); return { account: user.email, domain: user.email.split("@")[1] ?? "", connectedSince: new Date().toISOString(), grantedServices: this.services(scopes), tokens: { accessToken: tokens.access_token, refreshToken: tokens.refresh_token ?? fallbackRefresh, expiresAt: new Date(Date.now() + tokens.expires_in * 1000).toISOString(), scopes } }; }
  async connect(request: GoogleWorkspaceAuthorizationRequest): Promise<GoogleWorkspaceProviderResult> { try { const body = new URLSearchParams({ code: request.authorizationCode, client_id: this.config.clientId, client_secret: this.config.clientSecret, redirect_uri: request.redirectUri, grant_type: "authorization_code" }); if (request.codeVerifier) body.set("code_verifier", request.codeVerifier); const tokens = await this.token(body); return { ok: true, session: await this.session(tokens) }; } catch (error) { return { ok: false, error: { code: "AUTHENTICATION_FAILED", message: error instanceof Error ? error.message : "Google authentication failed.", retryable: true } }; } }
  async refresh(refreshToken: string): Promise<GoogleWorkspaceProviderResult> { try { const tokens = await this.token(new URLSearchParams({ refresh_token: refreshToken, client_id: this.config.clientId, client_secret: this.config.clientSecret, grant_type: "refresh_token" })); return { ok: true, session: await this.session(tokens, refreshToken) }; } catch (error) { return { ok: false, error: { code: "TOKEN_EXPIRED", message: error instanceof Error ? error.message : "Google token refresh failed.", retryable: false } }; } }
  reconnect(refreshToken: string) { return this.refresh(refreshToken); }
  async disconnect(account: string): Promise<void> { void account; return; }
  async verify(session: GoogleWorkspaceProviderSession): Promise<GoogleWorkspaceVerificationResult> { const response = await fetch("https://www.googleapis.com/oauth2/v3/tokeninfo", { headers: { Authorization: `Bearer ${session.tokens.accessToken}` } }); return response.ok ? { healthy: true, verifiedAt: new Date().toISOString() } : { healthy: false, verifiedAt: new Date().toISOString(), error: { code: "AUTHENTICATION_FAILED", message: `Google verification failed (${response.status}).`, retryable: true } }; }
}
