"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerActionClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { validateSignatureUpload } from "@/features/commercial-hub/catalogs";
import { parseQuoteOperationalConditions } from "@/features/commercial-hub/operational-conditions";

type Result={ok:true;message:string}|{ok:false;error:string};
const json=(value:string,label:string)=>{try{return JSON.parse(value||"{}")}catch{throw new Error(`${label} debe contener JSON válido.`)}};
export async function updateCompanySettingsAction(formData:FormData):Promise<Result>{
  try{
    const client=await createSupabaseServerActionClient();const {data:auth,error:authError}=await client.auth.getUser();if(authError||!auth.user)throw authError??new Error("Sesión requerida.");
    const reason=String(formData.get("reason")??"").trim();if(!reason)throw new Error("La razón del cambio es obligatoria.");
    const id=String(formData.get("id"));const expectedVersion=Number(formData.get("version"));
    const value=(name:string)=>String(formData.get(name)??"").trim();
    const pdfConfiguration=json(value("pdfConfiguration"),"PDF") as Record<string,unknown>;
    pdfConfiguration.commercialOperationalConditions=parseQuoteOperationalConditions(value("quoteOperationalConditions"));
    const payload={company_name:value("companyName"),legal_name:value("legalName"),brand_name:value("brandName"),product_name:value("productName"),product_version:value("productVersion"),developed_by:value("developedBy"),powered_by:value("poweredBy"),tax_id:value("taxId")||null,tax_name:value("taxName"),tax_rate:Number(value("taxRate")),support_email:value("supportEmail")||null,sales_email:value("salesEmail")||null,operations_email:value("operationsEmail")||null,phone:value("phone")||null,website:value("website")||null,address:value("address")||null,city:value("city")||null,country:value("country"),locale:value("locale"),currency:value("currency"),timezone:value("timezone"),google_workspace_domain:value("googleWorkspaceDomain")||null,logo_url:value("logoUrl"),isotype_url:value("isotypeUrl"),document_logo_url:value("documentLogoUrl"),portal_logo_url:value("portalLogoUrl"),dashboard_logo_url:value("dashboardLogoUrl"),email_logo_url:value("emailLogoUrl"),primary_color:value("primaryColor"),accent_color:value("accentColor"),login_tagline:value("loginTagline"),portal_kicker:value("portalKicker"),portal_welcome:value("portalWelcome"),email_signature:value("emailSignature"),contract_footer:value("contractFooter"),quotation_footer:value("quotationFooter"),drive_root_folder:value("driveRootFolder"),contract_configuration:json(value("contractConfiguration"),"Contratos"),pdf_configuration:pdfConfiguration,email_configuration:json(value("emailConfiguration"),"Emails"),portal_configuration:json(value("portalConfiguration"),"Portal"),dashboard_configuration:json(value("dashboardConfiguration"),"Dashboard"),approval_reason:reason,updated_by:auth.user.id};
    const {data,error}=await client.from("company_settings").update(payload).eq("id",id).eq("version",expectedVersion).select("id").maybeSingle();if(error)throw error;if(!data)throw new Error("La configuración cambió en otra sesión. Recarga la página.");
    revalidatePath("/", "layout");return{ok:true,message:"Configuración guardada y auditada."};
  }catch(error){return{ok:false,error:error instanceof Error?error.message:"No fue posible guardar la empresa."}}
}

export async function uploadCompanyLogoAction(formData:FormData):Promise<Result>{
  try{const client=await createSupabaseServerActionClient();const {data:auth,error:authError}=await client.auth.getUser();if(authError||!auth.user)throw authError??new Error("Sesión requerida.");const file=formData.get("file");if(!(file instanceof File)||!file.size)throw new Error("Selecciona una imagen.");if(file.size>10_485_760)throw new Error("La imagen supera 10 MB.");const allowed=["image/png","image/jpeg","image/webp","image/svg+xml"];if(!allowed.includes(file.type))throw new Error("Usa PNG, JPG, WEBP o SVG.");const field=String(formData.get("field"));const allowedFields=["logo_url","isotype_url","document_logo_url","portal_logo_url","dashboard_logo_url","email_logo_url"];if(!allowedFields.includes(field))throw new Error("Destino de marca inválido.");const ext=file.name.split(".").pop()?.toLowerCase()||"png";const path=`primary/${field}-${Date.now()}.${ext}`;const {error:uploadError}=await client.storage.from("orbit-branding").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data:url}=client.storage.from("orbit-branding").getPublicUrl(path);const {error}=await client.from("company_settings").update({[field]:url.publicUrl,approval_reason:`Actualización de ${field}`,updated_by:auth.user.id}).eq("settings_key","PRIMARY");if(error)throw error;revalidatePath("/","layout");return{ok:true,message:"Logo actualizado y auditado."};}catch(error){return{ok:false,error:error instanceof Error?error.message:"No fue posible cargar el logo."}}
}

async function signatureAccess(){const client=await createSupabaseServerActionClient();const{data:auth,error}=await client.auth.getUser();if(error||!auth.user)throw error??new Error("Sesión requerida.");const{data:profile}=await client.from("profiles").select("role").eq("id",auth.user.id).single();if(!profile||!["CEO","ADMINISTRATOR"].includes(profile.role))throw new Error("Solo Founder o Administración puede configurar la firma.");return{client,user:auth.user}}

export async function prepareEmailSignatureUploadAction(input:{filename:string;mimeType:string;size:number}){
  try{await signatureAccess();const validation=validateSignatureUpload(input);if(validation)throw new Error(validation);const ext=input.filename.split(".").pop()?.toLowerCase()||({"image/gif":"gif","image/png":"png","image/jpeg":"jpg","image/webp":"webp"}[input.mimeType]??"img");const path=`email/signature-${crypto.randomUUID()}.${ext.replace(/[^a-z0-9]/g,"")}`;const admin=createAdminClient();const signed=await admin.storage.from("orbit-branding").createSignedUploadUrl(path);if(signed.error)throw signed.error;return{ok:true as const,path,signedUrl:signed.data.signedUrl}}catch(error){console.error("Email signature upload preparation failed",error);return{ok:false as const,error:error instanceof Error?error.message:"No fue posible preparar la firma."}}
}

export async function finalizeEmailSignatureUploadAction(input:{path:string;filename:string;mimeType:string;size:number}):Promise<Result>{
  try{const{client,user}=await signatureAccess();const validation=validateSignatureUpload(input);if(validation)throw new Error(validation);if(!input.path.startsWith("email/signature-"))throw new Error("La referencia de la firma no es válida.");const admin=createAdminClient();const info=await admin.storage.from("orbit-branding").info(input.path);if(info.error)throw new Error("Storage no confirmó la firma cargada.");const{data:url}=admin.storage.from("orbit-branding").getPublicUrl(input.path);const{data:current,error:readError}=await client.from("company_settings").select("email_configuration").eq("settings_key","PRIMARY").single();if(readError)throw readError;const configuration={...((current.email_configuration??{}) as Record<string,unknown>),signatureGifUrl:url.publicUrl,signatureAssetUrl:url.publicUrl,signatureMimeType:input.mimeType,signatureFilename:input.filename,signatureFileSize:input.size};const{error}=await client.from("company_settings").update({email_configuration:configuration,approval_reason:"Carga de firma gráfica oficial",updated_by:user.id}).eq("settings_key","PRIMARY");if(error)throw error;revalidatePath("/","layout");revalidatePath("/settings");return{ok:true,message:"Firma gráfica oficial configurada."}}catch(error){console.error("Email signature upload finalization failed",error);return{ok:false,error:error instanceof Error?error.message:"No fue posible cargar la firma."}}
}
